// build.rs — link the VERIFIED executor closure (rebuilt against the seL4 musl)
// + the C one-turn driver into the Rust root task.
//
// The executor's C side — the verified Lean closure (`libdregg_lean_elf.a`), the
// ELF Lean runtime bottom-half (leanrt/Init/Std/Lean/mathlib/deps/leancpp), real
// GMP, and the small stub TUs — is provisioned as seL4-musl-linked archives in
// `out/exec-sel4/` by `scripts/relink-roottask.sh` (which recompiles the
// executor-pd closure against the seL4/musllibc headers so every libc call routes
// through `__sysinfo`, not a direct `svc`). This build script:
//   1. compiles the seL4-PD driver (scripts/driver-sel4.c) against the seL4 musl
//      + Lean headers, and
//   2. emits the `cargo:rustc-link-*` lines to pull the driver + the executor
//      archives + the seL4 musl libc into the final root-task ELF.
//
// If the archives are not yet provisioned, the build still type-checks the Rust
// (the link step is what needs them) and prints a clear note — so the Rust PD
// shell is reviewable before the (heavy) closure relink completes.

use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out = crate_dir.join("out");
    let exec_sel4 = out.join("exec-sel4"); // seL4-musl-linked executor archives
    let musl_sel4 = out.join("musl-sel4"); // seL4/musllibc: include + lib/libc.a
    let lean_inc = lean_sysroot_include();

    println!("cargo:rerun-if-changed=scripts/driver-sel4.c");
    println!("cargo:rerun-if-changed=build.rs");

    // (1) Compile the seL4-PD driver against the seL4 musl + Lean headers, IF the
    //     seL4 musl headers are provisioned. (Stock host libc headers would pull
    //     the wrong syscall surface, so we require the seL4 musl include here.)
    let cc = env::var("DREGG_SEL4_MUSL_CC")
        .unwrap_or_else(|_| "aarch64-linux-musl-gcc".to_string());
    let driver_o = out.join("driver-sel4.o");
    if musl_sel4.join("include").is_dir() && lean_inc.is_some() {
        let lean_inc = lean_inc.unwrap();
        // The demo wire is compiled in via out/exec-sel4/demo-wire.o (generated by
        // relink-roottask.sh), not a -D macro (it's large JSON with quotes/colons).
        let status = Command::new(&cc)
            .args(["-O2", "-ffreestanding", "-fno-stack-protector", "-c"])
            .arg("-isystem").arg(musl_sel4.join("include"))
            .arg("-I").arg(&lean_inc)
            .arg("scripts/driver-sel4.c")
            .arg("-o").arg(&driver_o)
            .status();
        match status {
            Ok(s) if s.success() => {
                println!("cargo:rustc-link-arg={}", driver_o.display());
            }
            other => {
                println!("cargo:warning=driver-sel4.c compile failed/absent ({other:?}); link will be incomplete");
            }
        }
    } else {
        println!(
            "cargo:warning=seL4 musl headers ({}) or Lean sysroot include not provisioned — \
             run scripts/provision-sel4.sh + scripts/relink-roottask.sh. Building the Rust PD \
             shell only (no executor link).",
            musl_sel4.join("include").display()
        );
    }

    // (2) Link the executor archives (seL4-musl-linked) under a group (they are
    //     mutually recursive), then the seL4 musl libc. Same archive set + order
    //     as executor-pd/scripts/link-probe.sh, but the seL4-musl variants.
    if exec_sel4.is_dir() {
        println!("cargo:rustc-link-search=native={}", exec_sel4.display());
        // OVERRIDE objects FIRST (before the closure archive), exactly as
        // executor-pd/scripts/link-probe.sh orders them: init-stubs.o + aux-defs.o
        // define symbols (the no-op elaborator inits, the recovered auxiliary)
        // that ALSO exist in the closure archive; placing the .o ahead means the
        // linker takes these definitions and never pulls the archive members
        // (avoids `duplicate symbol initialize_Dregg2_Dregg2_Tactics`).
        for o in OVERRIDE_OBJS {
            let p = exec_sel4.join(o);
            if p.exists() {
                println!("cargo:rustc-link-arg={}", p.display());
            }
        }
        // --start-group over the recursive Lean archives. rustc invokes rust-lld
        // DIRECTLY (gnu-lld flavor), so these are passed straight to the linker —
        // bare `--start-group`, NOT `-Wl,--start-group` (which lld rejects).
        println!("cargo:rustc-link-arg=--start-group");
        for a in GROUP_ARCHIVES {
            let p = exec_sel4.join(a);
            if p.exists() {
                println!("cargo:rustc-link-arg={}", p.display());
            }
        }
        println!("cargo:rustc-link-arg=--end-group");
        // GMP after the group.
        let gmp = exec_sel4.join("libgmp.a");
        if gmp.exists() {
            println!("cargo:rustc-link-arg={}", gmp.display());
        }
        // The C++ runtime (libstdc++/libsupc++) + libgcc exception/atomic helpers.
        // The Lean runtime is hosted C++ (the executor turn doesn't elaborate, but
        // the runtime uses std::string/std::chrono/operator new + __cxa_*/_Unwind_*
        // + __aarch64_* atomics). These statics from the aarch64-linux-musl GCC have
        // ZERO `svc` (verified) — every syscall they make routes through the seL4
        // musl libc. Grouped (libstdc++ <-> libgcc_eh <-> libsupc++ are recursive).
        // The seL4 musl libc.a (which also carries libm) is linked via `-lc` from
        // the target's link args (its -L is provisioned above).
        for lib in cxx_runtime_archives() {
            let s = lib.to_string_lossy();
            if s.starts_with("--") {
                // group markers (--start-group/--end-group), passed straight through
                println!("cargo:rustc-link-arg={s}");
            } else if lib.exists() {
                println!("cargo:rustc-link-arg={s}");
            } else {
                println!("cargo:warning=C++ runtime archive missing: {s}");
            }
        }
        println!("cargo:rustc-link-search=native={}", musl_sel4.join("lib").display());
    } else {
        println!(
            "cargo:warning=executor seL4 archives ({}) not provisioned — run \
             scripts/relink-roottask.sh. The PD will not link the verified turn yet.",
            exec_sel4.display()
        );
    }
}

/// Objects placed BEFORE the closure archive (they define symbols also present in
/// the archive; first-definition-wins overrides the archive member). Mirrors
/// link-probe.sh's `driver.o init-stubs.o aux-defs.o` lead. (driver-sel4.o is
/// emitted as a plain rustc-link-arg above; demo-wire.o supplies the wire string.)
const OVERRIDE_OBJS: &[&str] = &["init-stubs.o", "aux-defs.o", "demo-wire.o", "libc-compat.o"];

/// The recursive-group archives + the panic-if-reached stubs, in link-probe.sh's
/// order (the seL4-musl rebuilds live in out/exec-sel4/). libgmp.a is appended
/// after the group by the caller.
const GROUP_ARCHIVES: &[&str] = &[
    "libdregg_lean_elf.a",
    "libleanrt_elf.a",
    "libInit_elf.a",
    "libStd_elf.a",
    "libLean_elf.a",
    "libmathlib_elf.a",
    "libBatteries_elf.a",
    "libAesop_elf.a",
    "libQq_elf.a",
    "libProofWidgets_elf.a",
    "libPlausible_elf.a",
    "libImportGraph_elf.a",
    "libLeanSearchClient_elf.a",
    "libMetatheory_elf.a",
    "libleancpp_kernel_elf.a",
    "crypto-stub.o",
    "kernel-stub.o",
    "dead-stub.o",
];

/// The static C++ runtime + libgcc archives from the aarch64-linux-musl GCC,
/// wrapped in a group (libstdc++ <-> libgcc_eh <-> libsupc++ are mutually
/// recursive). Overridable via DREGG_MUSL_TOOLCHAIN (the GCC install root).
fn cxx_runtime_archives() -> Vec<PathBuf> {
    let base = env::var("DREGG_MUSL_TOOLCHAIN").unwrap_or_else(|_| {
        "/opt/homebrew/Cellar/aarch64-unknown-linux-musl/15.2.0/toolchain".to_string()
    });
    let base = PathBuf::from(base);
    let stdcpp = base.join("aarch64-unknown-linux-musl/lib64");
    let gcc = base.join("lib/gcc/aarch64-unknown-linux-musl/15.2.0");
    // group { libstdc++ libsupc++ libgcc libgcc_eh }
    let mut v = vec![PathBuf::from("--start-group")];
    v.push(stdcpp.join("libstdc++.a"));
    v.push(stdcpp.join("libsupc++.a"));
    v.push(gcc.join("libgcc.a"));
    v.push(gcc.join("libgcc_eh.a"));
    v.push(PathBuf::from("--end-group"));
    v
}

/// Locate the Lean sysroot's `include` (for `lean/lean.h` when compiling the
/// driver). `lean --print-prefix` if `lean` is on PATH; else None.
fn lean_sysroot_include() -> Option<PathBuf> {
    let prefix = Command::new("lean")
        .arg("--print-prefix")
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())?;
    let inc = Path::new(&prefix).join("include");
    if inc.is_dir() { Some(inc) } else { None }
}
