val _ = load "wordsLib"; val _ = load "backend_x64Theory"; val _ = load "backend_x64_cvTheory";
val _ = load "cv_transLib"; val _ = load "cv_typeTheory"; val _ = load "reg_allocComputeLib";
val _ = load "stringLib"; val _ = load "panPtreeConversionTheory"; val _ = load "pan_to_wordTheory";
val _ = load "word_to_wordTheory"; val _ = load "backendTheory"; val _ = load "backend_asmTheory";
val _ = load "x64_configTheory";
open HolKernel boolLib bossLib Parse;
open panPtreeConversionTheory panLangTheory;
fun say s = (print s; TextIO.flushOut TextIO.stdOut);
val _ = Globals.max_print_depth := 8;
val rconc = rhs o concl;
val src = let val is = TextIO.openIn "tiny.pnk" val s = TextIO.inputAll is val _ = TextIO.closeIn is in s end;
val prog_tm = inst [alpha |-> ``:64``] (rand (rconc (EVAL (Term [QUOTE "parse_topdecs_to_ast ", ANTIQUOTE (stringSyntax.fromMLstring src)]))));
val tinyProg_def = new_definition("tinyProg_def", mk_eq(mk_var("tinyProg", type_of prog_tm), prog_tm));
val _ = computeLib.add_funs [tinyProg_def];
val tinyC_tm = rconc (EVAL ``x64_backend_config with word_to_word_conf := (x64_backend_config.word_to_word_conf with reg_alg := 0)``);
val pw = rconc (EVAL ``pan_to_word$compile_prog x64_config.ISA tinyProg``);
val TINY_PW_def = new_definition("TINY_PW_def", mk_eq(mk_var("TINY_PW", type_of pw), pw));
val _ = cv_transLib.cv_trans_deep_embedding EVAL TINY_PW_def;
say "=== STEP1: graphs via cv_eval_raw (inline config) ===\n";
val input_tm = ``FST (to_livesets_0_x64 (^tinyC_tm, TINY_PW, LN))``;
val graphs = cv_transLib.cv_eval_raw input_tm |> rconc;
say ("graphs termsize=" ^ Int.toString (term_size graphs) ^ "\n");
val oracle_tm = reg_allocComputeLib.get_oracle_raw reg_alloc.Irc graphs;
say ("oracle termsize=" ^ Int.toString (term_size oracle_tm) ^ "\n");
val _ = Globals.max_print_depth := 60; print_term oracle_tm; say "\n"; Globals.max_print_depth := 8;
val oracle_def = new_definition("tiny_oracle_def", mk_eq(mk_var("tiny_oracle", type_of oracle_tm), oracle_tm));
val _ = computeLib.add_funs [oracle_def];
val _ = cv_transLib.cv_trans_deep_embedding EVAL oracle_def;
say "=== STEP2: word_to_word_inlogic_x64 with col_oracle ===\n";
val wc = ``<| reg_alg := 0; col_oracle := tiny_oracle |>``;
val ww_input = ``word_to_word_inlogic_x64 ^wc TINY_PW``;
val ww = (cv_transLib.cv_eval ww_input) handle e =>
  (say ("cv_eval EXN "^General.exnMessage e^"; try raw\n"); cv_transLib.cv_eval_raw ww_input);
val ww_r = rconc ww;
val is_some = optionSyntax.is_some ww_r handle _ => false;
val has_ra = can (find_term (fn t => (same_const (fst (strip_comb t)) ``reg_alloc_aux`` handle _ => false))) ww_r;
val has_oc = can (find_term (fn t => (same_const (fst (strip_comb t)) ``oracle_colour_ok`` handle _ => false))) ww_r;
say ("ww is SOME: " ^ Bool.toString is_some ^ "  reg_alloc_aux: " ^ Bool.toString has_ra ^ "  oracle_colour_ok: " ^ Bool.toString has_oc ^ "  termsize=" ^ Int.toString (term_size ww_r) ^ "\n");
val _ = Globals.max_print_depth := 40; print_term ww_r; say "\n";
say "=== PHASE B DONE ===\n";
