val _ = load "wordsLib"; val _ = load "backend_x64Theory"; val _ = load "backend_x64_cvTheory";
val _ = load "cv_transLib"; val _ = load "cv_typeTheory"; val _ = load "reg_allocComputeLib";
val _ = load "stringLib"; val _ = load "panPtreeConversionTheory"; val _ = load "pan_to_wordTheory";
val _ = load "word_to_wordTheory"; val _ = load "word_to_stackTheory"; val _ = load "backendTheory";
val _ = load "backend_asmTheory"; val _ = load "x64_configTheory";
open HolKernel boolLib bossLib Parse;
open panPtreeConversionTheory panLangTheory;
fun say s = (print s; TextIO.flushOut TextIO.stdOut);
val _ = Globals.max_print_depth := 6;
val rconc = rhs o concl;
val src = let val is = TextIO.openIn "tiny.pnk" val s = TextIO.inputAll is val _ = TextIO.closeIn is in s end;
val prog_tm = inst [alpha |-> ``:64``] (rand (rconc (EVAL (Term [QUOTE "parse_topdecs_to_ast ", ANTIQUOTE (stringSyntax.fromMLstring src)]))));
val tinyProg_def = new_definition("tinyProg_def", mk_eq(mk_var("tinyProg", type_of prog_tm), prog_tm));
val _ = computeLib.add_funs [tinyProg_def];
val tinyC_tm = rconc (EVAL ``x64_backend_config with word_to_word_conf := (x64_backend_config.word_to_word_conf with reg_alg := 0)``);
val pw = rconc (EVAL ``pan_to_word$compile_prog x64_config.ISA tinyProg``);
val TINY_PW_def = new_definition("TINY_PW_def", mk_eq(mk_var("TINY_PW", type_of pw), pw));
val _ = cv_transLib.cv_trans_deep_embedding EVAL TINY_PW_def;
val graphs = cv_transLib.cv_eval_raw ``FST (to_livesets_0_x64 (^tinyC_tm, TINY_PW, LN))`` |> rconc;
val oracle_tm = reg_allocComputeLib.get_oracle_raw reg_alloc.Irc graphs;
val oracle_def = new_definition("tiny_oracle_def", mk_eq(mk_var("tiny_oracle", type_of oracle_tm), oracle_tm));
val _ = computeLib.add_funs [oracle_def];
val _ = cv_transLib.cv_trans_deep_embedding EVAL oracle_def;
val wc = ``<| reg_alg := 0; col_oracle := tiny_oracle |>``;
val ww = cv_transLib.cv_eval ``word_to_word_inlogic_x64 ^wc TINY_PW`` |> rconc;
val (col_tm, wprog_tm) = pairSyntax.dest_pair (optionSyntax.dest_some ww);
say ("=== PHASE A OK: wprog termsize=" ^ Int.toString (term_size wprog_tm) ^ " ===\n");
(* word_to_stack via EVAL *)
val wprog_def = new_definition("tiny_wprog_def", mk_eq(mk_var("tiny_wprog", type_of wprog_tm), wprog_tm));
val _ = computeLib.add_funs [wprog_def];
val ws_th = EVAL ``word_to_stack$compile x64_config F tiny_wprog``;
val ws_r = rconc ws_th;
val ws_abs = length (find_terms is_abs ws_r);
say ("word_to_stack termsize=" ^ Int.toString (term_size ws_r) ^ " residual_abs=" ^ Int.toString ws_abs ^ "\n");
val bm_tm = rconc (EVAL ``FST (word_to_stack$compile x64_config F tiny_wprog)``);
val cprime_tm = rconc (EVAL ``FST (SND (word_to_stack$compile x64_config F tiny_wprog))``);
val p_tm = rconc (EVAL ``SND (SND (SND (word_to_stack$compile x64_config F tiny_wprog)))``);
say ("stackprog termsize=" ^ Int.toString (term_size p_tm) ^ " bm termsize=" ^ Int.toString (term_size bm_tm) ^ "\n");
val stackprog_def = new_definition("tiny_stackprog_def", mk_eq(mk_var("tiny_stackprog", type_of p_tm), p_tm));
val bm_def = new_definition("tiny_bm_def", mk_eq(mk_var("tiny_bm", type_of bm_tm), bm_tm));
val _ = cv_transLib.cv_trans_deep_embedding EVAL stackprog_def;
val _ = cv_transLib.cv_trans_deep_embedding EVAL bm_def;
say "=== deep-embedded stackprog+bm; run encoder from_stack_x64 via cv_eval_raw ===\n";
val enc_input = ``from_stack_x64 ^tinyC_tm LN tiny_stackprog tiny_bm``;
val enc = cv_transLib.cv_eval_raw enc_input;
val enc_r = rconc enc;
say ("=== ENCODER DONE termsize=" ^ Int.toString (term_size enc_r) ^ " ===\n");
val _ = Globals.max_print_depth := 10; print_term enc_r; say "\n";
say "=== PHASE C DONE ===\n";
(* convert cv result to HOL via to_option/to_pair EVAL *)
val _ = say "=== converting encoder cv result to HOL ===\n";
val enc_hol = CONV_RULE (RAND_CONV EVAL) enc;
val enc_hr = rconc enc_hol;
val is_some = optionSyntax.is_some enc_hr;
say ("encoder result is SOME: " ^ Bool.toString is_some ^ "\n");
val payload = optionSyntax.dest_some enc_hr;
(* payload = (bytes, bytes_len, bm1, bm1_len, ffi_names, shmem_len, syms, conf_str) *)
val bytes_tm = fst (pairSyntax.dest_pair payload);
val (byte_els, _) = listSyntax.dest_list bytes_tm;
val nbytes = length byte_els;
fun byteval t = numSyntax.int_of_term (rand t) handle _ => (numSyntax.int_of_term t handle _ => ~1);
val nums = map byteval byte_els;
val allconc = List.all (fn n => n >= 0 andalso n < 256) nums;
say ("BYTE COUNT = " ^ Int.toString nbytes ^ "  all_concrete_0_255 = " ^ Bool.toString allconc ^ "\n");
val f8 = List.take(nums, Int.min(8,nbytes));
val l8 = List.drop(nums, Int.max(0,nbytes-8));
say ("first8 = [" ^ String.concatWith "," (map Int.toString f8) ^ "]\n");
say ("last8  = [" ^ String.concatWith "," (map Int.toString l8) ^ "]\n");
say ("byte sum = " ^ Int.toString (foldl op+ 0 nums) ^ "\n");
(* write bytes to file as hex *)
val f = TextIO.openOut "tiny_bytes.hex";
val _ = TextIO.output(f, String.concatWith " " (map (fn n => StringCvt.padLeft #"0" 2 (Int.fmt StringCvt.HEX n)) nums));
val _ = TextIO.closeOut f;
say "wrote tiny_bytes.hex\n";
(* check no reg_alloc_aux / no n2w symbolic in bytes *)
val has_ra = can (find_term (fn t => (same_const (fst (strip_comb t)) ``reg_alloc_aux`` handle _ => false))) enc_hr;
say ("encoder result has reg_alloc_aux: " ^ Bool.toString has_ra ^ "\n");
say "=== PHASE D DONE ===\n";
