/-
# Dregg2.Circuit.FinBindsKernel — DEBT-B lane R4: collapse the apex's carried set to
`Poseidon2SpongeCR` ALONE, on the finite/reachable (`denote`-image) subclass.

`StateCommit.recStateCommit_binds_kernel` (equal full-state roots for the same turn ⇒ equal whole
`RecordKernelState`) currently carries FIVE crypto/structural carriers — `compressInjective cmb`,
`compressInjective compress`, `compressNInjective compressN`, `cellLeafInjective CH`, `RestHashIffFrame
RH` — plus the `AccountsWF` structural side-condition on both states. This lane RE-SEATS that keystone
on the two REACHABLE (`denote`-image) states `denote f`, `denote f'`, with the SINGLE crypto residual
`Poseidon2SpongeCR sponge`. All FIVE carriers are DERIVED, not assumed:

  * `cmb`, `compress` := `Freshness.spongeCompress sponge`     ⇒ `compressInjective` from `spongeCompress_inj`.
  * `compressN`       := `sponge`                              ⇒ `compressNInjective` = `Poseidon2SpongeCR` (defeq).
  * `CH`              := `CH_fin sponge` (`sponge ∘ refEncodeLeaf`) ⇒ `cellLeafInjective` from a REALIZED
                         `LeafRealization` built HERE (no `LeafRealization` hypothesis — realized off
                         `encV_injective` + `Poseidon2SpongeCR`).
  * `RH`              := `RH_fin sponge`                       ⇒ the `RestHashIffFrame` BODY holds ON THE
                         IMAGE from `restHashIffFrame_of_fin` (the `rest_body_matches` `Iff.rfl` tripwire
                         welds that body to `StateCommit.RestHashIffFrame`). We do NOT and cannot claim
                         the ∀-`RecordKernelState` version — it is unsatisfiable for infinite-support
                         states. This is why R4 is scoped to `denote`-images.

HONEST SCOPE: the result is over `(f f' : FinKernelState)` (reachable states — every real
`RecordKernelState` is a `denote` image, `FinKernelState.denote_surjective_on_reachable`), NOT all
`RecordKernelState`. The SOLE crypto residual is `Poseidon2SpongeCR sponge`; the four hash carriers are
discharged. `RestHashIffFrame` is no longer carried (it is realized on the image).

⚠ `AccountsWF` STATUS (a real finding, reported honestly): `AccountsWF` (the non-crypto structural
side-condition "cells outside `accounts` hold the kernel `default = Value.int 0`") is STILL needed by the
dead-cell case of the cell-map recovery. But `AccountsWF (denote f)` is UNSATISFIABLE for every `f`:
`FinKernelState.cell` is a `CanonMap … (Value.record [])`, so `denote` reads an absent cell as
`Value.record []`, which is NOT the kernel `default (Value.int 0)`. So the exact-target-shape theorem
`recStateCommit_binds_kernel_fin` (below) — faithful, and PROVED with the hypotheses genuinely consumed —
cannot be instantiated on a concrete state. The INSTANTIABLE companion `recStateCommit_binds_kernel_fin_canon`
replaces `AccountsWF` with the SATISFIABLE, faithful fin-level canonicality condition ("`cell` stores no
key outside `accounts`" — the exact sparse invariant the deployed `BTreeMap` maintains). Aligning the
`FinKernelState.cell` default to `Value.int 0` (a committed-file change, NOT done here) would make the
two coincide; flagged as a sibling issue.

NO carrier laundering: every `def` here is a concrete realization or a step function; the only `Prop`
hypotheses are `Poseidon2SpongeCR sponge` (crypto) and the structural side-condition. No `def …Sound`,
no assumed `class`.
-/
import Dregg2.Circuit.FinFrameHash
import Dregg2.Circuit.Freshness
-- `RecordKernelState.ext` is generated by `attribute [ext] RecordKernelState` here (the structure
-- itself carries no `@[ext]`); imported for the field-wise assembly of `denote f = denote f'`.
import Dregg2.Exec.ConcreteKernel

namespace Dregg2.Circuit.FinBindsKernel

open Dregg2.Exec (CellId Value Turn RecordKernelState)
open Dregg2.Circuit.StateCommit
open Dregg2.Circuit.Poseidon2Binding
open Dregg2.Circuit.Freshness (spongeCompress spongeCompress_inj)
open Dregg2.Circuit.FinKernelState
open Dregg2.Circuit.FinFrameHash

set_option autoImplicit false

/-! ## §1 — the concrete Poseidon2 leaf encoder + its REALIZED `LeafRealization` (no hypothesis). -/

/-- **`CH_fin sponge c v`** — the concrete Poseidon2 leaf hash: the sponge of the injective canonical
serialization `refEncodeLeaf c v = [c, encV v]` (`Poseidon2Binding.Reference`). This is a genuine
`sponge ∘ encode` leaf hash, realized at the SAME `sponge` the frame/root use. -/
def CH_fin (sponge : List ℤ → ℤ) (c : CellId) (v : Value) : ℤ :=
  sponge (Reference.refEncodeLeaf c v)

/-- **`finLeafRealization`** — the REALIZATION of `CH_fin sponge` on `Poseidon2SpongeCR sponge`: encoder
`refEncodeLeaf` (INJECTIVE in the `Value` by `refEncodeLeaf_inj`, itself off `encV_injective`), factoring
`CH c v = sponge (refEncodeLeaf c v)` by `rfl`, with the crypto carrier the given `Poseidon2SpongeCR`.
`LeafRealization` is CONSTRUCTED, never taken as a hypothesis. -/
def finLeafRealization (sponge : List ℤ → ℤ) (hCR : Poseidon2SpongeCR sponge) :
    LeafRealization (CH_fin sponge) where
  sponge := sponge
  encodeLeaf := Reference.refEncodeLeaf
  encodeLeaf_inj := Reference.refEncodeLeaf_inj
  factor := fun _ _ => rfl
  spongeCR := hCR

/-- **`CH_fin_injective`** — `cellLeafInjective (CH_fin sponge)` DISCHARGED from `Poseidon2SpongeCR`
alone (via the realized bundle). No `cellLeafInjective`/`LeafRealization` hypothesis. -/
theorem CH_fin_injective (sponge : List ℤ → ℤ) (hCR : Poseidon2SpongeCR sponge) :
    cellLeafInjective (CH_fin sponge) :=
  cellLeafInjective_of_realization (finLeafRealization sponge hCR)

/-! ## §2 — the Poseidon2 commitment primitives (all off the SINGLE `sponge`). -/

/-- The full-state root at the Poseidon2 primitives: `cmb`/`compress` are 2-element sponges over
`sponge`, `compressN` IS `sponge`, `CH` is `CH_fin sponge`, `RH` is `RH_fin sponge`. -/
noncomputable def p2Commit (sponge : List ℤ → ℤ) (k : RecordKernelState) (t : Turn) : ℤ :=
  recStateCommit (CH_fin sponge) (RH_fin sponge)
    (spongeCompress sponge) (spongeCompress sponge) sponge k t

/-! ## §3 — the cell-map recovery on the image (the four hash carriers → `Poseidon2SpongeCR`).

This mirrors `StateCommit.cellDigest_binds_cells`, but (a) instantiates the four hash carriers at the
Poseidon2 primitives — all off `Poseidon2SpongeCR sponge` — and (b) discharges the DEAD-CELL case from
the SATISFIABLE fin-level canonicality condition (no stored cell outside `accounts`) instead of the
kernel-default `AccountsWF`, since `AccountsWF (denote f)` is unsatisfiable. -/

/-- **`cellDigest_binds_cells_fin`** — equal cell-digests (same turn) force `(denote f).cell =
(denote f').cell`, with the SOLE crypto residual `Poseidon2SpongeCR sponge`. Dead cells agree because
neither `f` nor `f'` stores a cell outside its `accounts` (`hCanon`/`hCanon'`), so both denote to the
`CanonMap` default there. -/
theorem cellDigest_binds_cells_fin
    (sponge : List ℤ → ℤ) (hCR : Poseidon2SpongeCR sponge)
    (f f' : FinKernelState) (t : Turn)
    (hCanon  : ∀ c, c ∉ f.accounts  → f.cell.toMap.lookup c = none)
    (hCanon' : ∀ c, c ∉ f'.accounts → f'.cell.toMap.lookup c = none)
    (hAcc : (denote f).accounts = (denote f').accounts)
    (hcd : cellDigest (CH_fin sponge) (spongeCompress sponge) sponge (denote f) t
         = cellDigest (CH_fin sponge) (spongeCompress sponge) sponge (denote f') t) :
    (denote f).cell = (denote f').cell := by
  have hCompress : compressInjective (spongeCompress sponge) := spongeCompress_inj sponge hCR
  have hLeaf : cellLeafInjective (CH_fin sponge) := CH_fin_injective sponge hCR
  have hCompressN : compressNInjective sponge := compressNInjective_of_poseidon2CR hCR
  unfold cellDigest at hcd
  rw [← hAcc] at hcd
  obtain ⟨hframeEq, hmovedEq⟩ := hCompress _ _ _ _ hcd
  have hcellframe : ∀ c ∈ ((denote f).accounts \ {t.src, t.dst}),
      (denote f).cell c = (denote f').cell c :=
    FrameDigestBindsCells (CH_fin sponge) sponge hCompressN hLeaf (denote f) (denote f')
      ((denote f).accounts \ {t.src, t.dst}) hframeEq
  obtain ⟨hmsrc, hmdst⟩ :=
    MovedDigestBindsCells (CH_fin sponge) (spongeCompress sponge) hCompress hLeaf
      (denote f).cell (denote f').cell t.src t.dst hmovedEq
  funext c
  by_cases hcsrc : c = t.src
  · subst hcsrc; exact hmsrc
  · by_cases hcdst : c = t.dst
    · subst hcdst; exact hmdst
    · by_cases hcacc : c ∈ (denote f).accounts
      · have hmem : c ∈ (denote f).accounts \ {t.src, t.dst} := by
          simp only [Finset.mem_sdiff, Finset.mem_insert, Finset.mem_singleton, not_or]
          exact ⟨hcacc, hcsrc, hcdst⟩
        exact hcellframe c hmem
      · -- DEAD cell: canonicality on both states ⇒ absent ⇒ both denote to the `CanonMap` default.
        have hf  : c ∉ f.accounts  := hcacc
        have hf' : c ∉ f'.accounts := by
          have : c ∉ (denote f').accounts := by rw [← hAcc]; exact hcacc
          exact this
        show f.cell.get c = f'.cell.get c
        simp only [CanonMap.get, SortedMap.get, hCanon c hf, hCanon' c hf', Option.getD_none]

/-! ## §4 — THE HEADLINE (target shape) + the INSTANTIABLE companion. -/

/-- **`recStateCommit_binds_kernel_fin` — THE TARGET (exact shape, `AccountsWF` carried).** Equal
full-state Poseidon2 roots (same turn) on two `denote`-image states force `denote f = denote f'`. The
FIVE carriers of `StateCommit.recStateCommit_binds_kernel` are all DERIVED from the SOLE crypto residual
`Poseidon2SpongeCR sponge`; `RestHashIffFrame` is realized on the image by `restHashIffFrame_of_fin`.
`AccountsWF` remains as the non-crypto structural side-condition — see the module header: it is genuinely
consumed by the proof, though `AccountsWF (denote f)` is unsatisfiable under the committed
`FinKernelState.cell` default (use `recStateCommit_binds_kernel_fin_canon` to instantiate). -/
theorem recStateCommit_binds_kernel_fin
    (sponge : List ℤ → ℤ) (hCR : Poseidon2SpongeCR sponge)
    (f f' : FinKernelState) (t : Turn)
    (hwf : AccountsWF (denote f)) (hwf' : AccountsWF (denote f'))
    (hroot : p2Commit sponge (denote f) t = p2Commit sponge (denote f') t) :
    denote f = denote f' := by
  unfold p2Commit at hroot
  -- root injectivity: split into cell-digest + rest-hash (via `compressInjective (spongeCompress …)`).
  obtain ⟨hcd, hRHeq⟩ :=
    recStateCommit_binds (CH_fin sponge) (RH_fin sponge) (spongeCompress sponge)
      (spongeCompress sponge) sponge (spongeCompress_inj sponge hCR) (denote f) (denote f') t hroot
  -- the 17 non-cell fields from `RH_fin` ON THE IMAGE (residual `Poseidon2SpongeCR`).
  obtain ⟨hAcc, hCaps, hBal, hNul, hRev, hCom, hSC, hFac, hLif, hDC, hDel, hDgs, hDE, hDEA,
    hHeaps, hNR, hRR⟩ := (restHashIffFrame_of_fin sponge hCR f f').mp hRHeq
  -- the cell map from the cell-digest (reuse the committed `cellDigest_binds_cells` with `AccountsWF`).
  have hcell : (denote f).cell = (denote f').cell :=
    cellDigest_binds_cells (CH_fin sponge) (spongeCompress sponge) sponge
      (spongeCompress_inj sponge hCR) (compressNInjective_of_poseidon2CR hCR)
      (CH_fin_injective sponge hCR) (denote f) (denote f') t hwf hwf' hAcc.symm hcd
  -- assemble every field (order-robust): `restHashIffFrame_of_fin` gives `denote f'.X = denote f.X`.
  apply RecordKernelState.ext <;>
    first
      | exact hcell
      | exact hAcc.symm | exact hCaps.symm | exact hBal.symm | exact hNul.symm
      | exact hRev.symm | exact hCom.symm | exact hSC.symm | exact hFac.symm
      | exact hLif.symm | exact hDC.symm | exact hDel.symm | exact hDgs.symm
      | exact hDE.symm | exact hDEA.symm | exact hHeaps.symm | exact hNR.symm | exact hRR.symm

/-- **`recStateCommit_binds_kernel_fin_canon` — THE INSTANTIABLE companion.** Same conclusion and same
SOLE crypto residual `Poseidon2SpongeCR sponge`, but the dead-cell frame is closed by the SATISFIABLE
fin-level canonicality condition (`cell` stores no key outside `accounts`) rather than the
kernel-default `AccountsWF` (which is unsatisfiable on the image). THIS is the form that fires on
concrete states. -/
theorem recStateCommit_binds_kernel_fin_canon
    (sponge : List ℤ → ℤ) (hCR : Poseidon2SpongeCR sponge)
    (f f' : FinKernelState) (t : Turn)
    (hCanon  : ∀ c, c ∉ f.accounts  → f.cell.toMap.lookup c = none)
    (hCanon' : ∀ c, c ∉ f'.accounts → f'.cell.toMap.lookup c = none)
    (hroot : p2Commit sponge (denote f) t = p2Commit sponge (denote f') t) :
    denote f = denote f' := by
  unfold p2Commit at hroot
  obtain ⟨hcd, hRHeq⟩ :=
    recStateCommit_binds (CH_fin sponge) (RH_fin sponge) (spongeCompress sponge)
      (spongeCompress sponge) sponge (spongeCompress_inj sponge hCR) (denote f) (denote f') t hroot
  obtain ⟨hAcc, hCaps, hBal, hNul, hRev, hCom, hSC, hFac, hLif, hDC, hDel, hDgs, hDE, hDEA,
    hHeaps, hNR, hRR⟩ := (restHashIffFrame_of_fin sponge hCR f f').mp hRHeq
  have hcell : (denote f).cell = (denote f').cell :=
    cellDigest_binds_cells_fin sponge hCR f f' t hCanon hCanon' hAcc.symm hcd
  apply RecordKernelState.ext <;>
    first
      | exact hcell
      | exact hAcc.symm | exact hCaps.symm | exact hBal.symm | exact hNul.symm
      | exact hRev.symm | exact hCom.symm | exact hSC.symm | exact hFac.symm
      | exact hLif.symm | exact hDC.symm | exact hDel.symm | exact hDgs.symm
      | exact hDE.symm | exact hDEA.symm | exact hHeaps.symm | exact hNR.symm | exact hRR.symm

/-! ## §5 — TEETH (both polarities). -/

/-- The empty finite state stores no cell anywhere, so it satisfies the canonicality side-condition. -/
theorem finInit_cell_canon : ∀ c, c ∉ finInit.accounts → finInit.cell.toMap.lookup c = none :=
  fun _ _ => rfl

/-- **POSITIVE TOOTH — the binding FIRES on two concrete states that agree.** At `f = f' = finInit`
(canonicality discharged by `finInit_cell_canon`, equal roots by `rfl`) the instantiable companion
yields `denote finInit = denote finInit`. So the hypotheses are simultaneously satisfiable and the
conclusion follows — the theorem is non-vacuously applicable. -/
example (t : Turn) : denote finInit = denote finInit :=
  recStateCommit_binds_kernel_fin_canon Reference.refSponge Reference.refSponge_CR
    finInit finInit t finInit_cell_canon finInit_cell_canon rfl

/-- **POSITIVE TOOTH — the leaf carrier is realized (fires on a concrete sponge).** -/
example : cellLeafInjective (CH_fin Reference.refSponge) :=
  CH_fin_injective Reference.refSponge Reference.refSponge_CR

/-- `rootedInit` and `finInit` differ in `nullifierRoot` (limb-0 = 7 vs 0), so they denote distinctly. -/
theorem denote_rootedInit_ne_finInit : denote rootedInit ≠ denote finInit := by
  intro h
  have h0 : (denote rootedInit).nullifierRoot 0 = (denote finInit).nullifierRoot 0 :=
    congrFun (congrArg RecordKernelState.nullifierRoot h) 0
  rw [denote_carries_nullifierRoot] at h0            -- h0 : (7 : ℤ) = (denote finInit).nullifierRoot 0
  rw [show (denote finInit).nullifierRoot 0 = 0 from rfl] at h0
  exact absurd h0 (by decide)

/-- **POSITIVE TOOTH — the rest carrier BINDS a root.** `RH_fin` (residual `Poseidon2SpongeCR`)
distinguishes two states that differ ONLY in `nullifierRoot` (`rootedInit` has limb-0 = 7,
`finInit` = 0): equal `RH_fin` would force the roots to agree by `restHashIffFrame_of_fin.mp`, but they
do not. So the rest hash genuinely binds the accumulator root — not vacuous. -/
theorem RH_fin_separates_root :
    RH_fin Reference.refSponge (denote rootedInit) ≠ RH_fin Reference.refSponge (denote finInit) := by
  intro h
  have hbody := (restHashIffFrame_of_fin Reference.refSponge Reference.refSponge_CR rootedInit finInit).mp h
  -- the 16th of the 17 clauses: `(denote finInit).nullifierRoot = (denote rootedInit).nullifierRoot`.
  have hroot := hbody.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1
  have h0 := congrFun hroot 0                         -- (denote finInit).nR 0 = (denote rootedInit).nR 0
  rw [denote_carries_nullifierRoot] at h0             -- ... = 7
  rw [show (denote finInit).nullifierRoot 0 = 0 from rfl] at h0
  exact absurd h0 (by decide)

/-- **NEGATIVE TOOTH — a collapsing sponge BREAKS the binding, so `Poseidon2SpongeCR` is load-bearing.**
The collapsing sponge `fun _ => 0` is NOT collision-resistant (`collapsing_not_CR`), and under it the
Poseidon2 root collapses to the constant `0` — so two DISTINCT `denote`-image states (`rootedInit` vs
`finInit`, differing in `nullifierRoot`) share a root while `denote rootedInit ≠ denote finInit`. Hence
the conclusion FAILS without the CR hypothesis: `Poseidon2SpongeCR` is genuinely required. -/
theorem collapse_breaks_binding_fin (t : Turn) :
    ¬ Poseidon2SpongeCR (fun _ : List ℤ => (0 : ℤ))
      ∧ denote rootedInit ≠ denote finInit
      ∧ p2Commit (fun _ => 0) (denote rootedInit) t = p2Commit (fun _ => 0) (denote finInit) t := by
  refine ⟨collapsing_not_CR, denote_rootedInit_ne_finInit, ?_⟩
  -- every primitive collapses to `0`, so both roots are the constant `0`.
  simp only [p2Commit, recStateCommit, spongeCompress]

/-! ## §6 — axiom-hygiene tripwires (the standard whitelist; `Classical.choice` from `RH_fin`). -/

#assert_axioms CH_fin_injective
#assert_axioms cellDigest_binds_cells_fin
#assert_axioms recStateCommit_binds_kernel_fin
#assert_axioms recStateCommit_binds_kernel_fin_canon
#assert_axioms collapse_breaks_binding_fin

end Dregg2.Circuit.FinBindsKernel
