open HolKernel boolLib bossLib Parse;
val _ = load "boundScanInstallTheory";
open boundScanInstallTheory;
val th = boundScanInstallTheory.boundScan_rung3_installed;
val (orc,ax) = Tag.dest_tag (Thm.tag th);
val () = print ("\nAUDIT boundScan_rung3_installed\n");
val () = print ("oracles = [" ^ String.concatWith "," orc ^ "]\n");
val () = print ("axioms  = [" ^ String.concatWith "," ax ^ "]\n");
val () = print ("theory axioms (boundScanInstall) = " ^ Int.toString (length (axioms "boundScanInstall")) ^ "\n");
val c = concl th;
fun antes t = let val (a,b)=dest_imp t in strip_conj a end;
val body = #2 (dest_imp c);
val resid = antes body;
val s = String.concatWith "\n" (map term_to_string resid);
fun has sub = String.isSubstring sub s;
val () = print ("residual conjuncts = " ^ Int.toString (length resid) ^ "\n");
val () = print ("contains backend_config_ok? " ^ Bool.toString (has "backend_config_ok") ^ " (want false)\n");
val () = print ("contains mc_conf_ok? "        ^ Bool.toString (has "mc_conf_ok") ^ " (want false)\n");
val () = print ("contains mc_init_ok? "        ^ Bool.toString (has "mc_init_ok") ^ " (want false)\n");
val () = print ("contains Ag32? "              ^ Bool.toString (has "Ag32") ^ " (want false)\n");
val () = print ("contains pan_installed? "     ^ Bool.toString (has "pan_installed") ^ " (want true)\n");
val () = print ("contains boundScanBytes? "    ^ Bool.toString (has "boundScanBytes") ^ " (want true)\n");
val piconj = valOf (List.find (fn t => String.isSubstring "pan_installed" (term_to_string t)) resid);
val pic = fst (strip_comb piconj);
val d = dest_thy_const pic;
val () = print ("pan_installed const = " ^ #Thy d ^ "$" ^ #Name d ^ "\n");
