val _ = load "cachefreshRung3Theory"; val _ = load "cachefreshBytesBridgeTheory";
open cachefreshRung3Theory cachefreshBytesBridgeTheory;
fun tag th = let val (o_,a)=Tag.dest_tag (Thm.tag th) in "[oracles: "^String.concatWith "," o_^"] [axioms: "^String.concatWith "," a^"]" end;
val _ = print ("AAA backbone cachefresh_rung3_native = "^tag cachefresh_rung3_native^"\n");
val _ = print ("AAA linkA cachefresh_decisioncore_refines_spec = "^tag cachefresh_decisioncore_refines_spec^"\n");
val _ = print ("AAA faithful cachefreshIf_faithful = "^tag cachefreshIf_faithful^"\n");
val _ = print ("AAA L2 cachefresh_compile_prog_native = "^tag cachefresh_compile_prog_native^"\n");
val _ = print ("AAA theory-axioms cachefreshRung3 = "^Int.toString(length(axioms "cachefreshRung3"))^"\n");
val _ = print ("AAA theory-axioms cachefreshBytesBridge = "^Int.toString(length(axioms "cachefreshBytesBridge"))^"\n");
val c = concl cachefreshIf_faithful; val (lhs,rhs)=dest_eq c;
fun qn t = let val {Thy,Name,...}=dest_thy_const t in Thy^"$"^Name end;
val progn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="cachefreshProg") lhs);
val ifn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="cachefreshIf") rhs);
val _ = print ("AAA faithful-distinct prog="^progn^" if="^ifn^" DISTINCT="^Bool.toString(progn<>ifn)^"\n");
val bc = concl cachefresh_rung3_native; val (ante,conc)=dest_imp bc;
val _ = print ("AAA backbone antecedent-conjuncts = "^Int.toString(length(strip_conj ante))^"\n");
val _ = print ("AAA backbone concl-mentions-cachefreshProg = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="cachefreshProg")) conc)^"\n");
val _ = print ("AAA backbone ante-mentions-cachefreshBytes = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="cachefreshBytes")) ante)^"\n");
