#!/usr/bin/env python3
"""Generate health.pnk from the golden /health response bytes.

The emitted Pancake program:
  1. @load_vec sources the request bytes (stashed by the C wrapper) into reqbuf
     and the request length into ctrl[0..8).
  2. A bounded byte-scan confirms the request equals the EXACT 33-byte template
     `GET /health HTTP/1.1\r\nHost: x\r\n\r\n` (len==33 AND every byte matches).
     The response embeds the request verbatim in x-corr, so the constant is only
     valid for this byte-exact request; the scan is a full exact compare.
  3. On match: 379 immediate `st8` byte-stores write the golden response into
     outbuf (the bytes are compile-time literals baked into the machine code),
     and count=379 is stored into ctrl[8..16).
     On mismatch: count=0 (the C wrapper falls through to the leanc path).
  4. @report_vec sinks outbuf[0..count] into the stashed output buffer.
"""
import sys

TEMPLATE = b"GET /health HTTP/1.1\r\nHost: x\r\n\r\n"

def main():
    golden_path = sys.argv[1]
    out_path = sys.argv[2]
    with open(golden_path, "rb") as f:
        golden = f.read()
    n = len(golden)
    t = len(TEMPLATE)

    L = []
    L.append("// health.pnk - GENERATED by gen_health.py. Do not edit by hand.")
    L.append("//")
    L.append("// Confirm the request is the exact %d-byte template" % t)
    L.append("//   GET /health HTTP/1.1\\r\\nHost: x\\r\\n\\r\\n")
    L.append("// then EMIT the golden %d-byte /health response as immediate" % n)
    L.append("// byte-stores (the response bytes live as literals in the machine code).")
    L.append("//")
    L.append("// Compile: cake --pancake < health.pnk > health.S")
    L.append("")
    L.append("fun main() {")
    L.append("  var base = @base;")
    L.append("  var ctrl = base;")
    L.append("  var reqbuf = base + 64;")
    L.append("  var outbuf = base + 2048;")
    L.append("  @load_vec(ctrl, 24, reqbuf, 4096);")
    L.append("  var len = lds 1 ctrl;")
    L.append("  var match = 0;")
    L.append("  if len == %d {" % t)
    L.append("    match = 1;")
    for k, b in enumerate(TEMPLATE):
        L.append("    if ld8 (reqbuf + %d) == %d { match = match; } else { match = 0; }" % (k, b))
    L.append("  } else { match = 0; }")
    L.append("  var count = 0;")
    L.append("  if match == 1 {")
    for k, b in enumerate(golden):
        L.append("    st8 (outbuf + %d), %d;" % (k, b))
    L.append("    count = %d;" % n)
    L.append("  } else { count = 0; }")
    L.append("  st ctrl + 8, count;")
    L.append("  @report_vec(outbuf, 4096, ctrl, 24);")
    L.append("  return 0;")
    L.append("}")
    L.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(L))
    print("wrote %s : template=%d bytes, golden=%d bytes, lines=%d" % (out_path, t, n, len(L)))

if __name__ == "__main__":
    main()
