//! # `cap_reshape_descriptor` — the OPENABLE `capability_root` descriptor loader (the ARGUS linchpin).
//!
//! The cap-reshape crown (#103): the Lean-verified `EffectVmDescriptor` that checks, IN-CIRCUIT, the
//! two capability-security openings a light client must trust WITHOUT re-running history:
//!
//!   * **non-amplification** — a granted cap is `≤` a held cap (the in-row submask gates
//!     `granted_bit ≤ held_bit` per bit, over the opened held leaf);
//!   * **production-authority** — a mint is gated on OPENING the issuer cap from the producer's held-set
//!     root (the held `target` binds the minted-asset PI + the control/mint bit is set).
//!
//! ## Provenance (anti-drift, the LAW#1 way)
//!
//! `dregg-effectvm-capreshape-v1.json` is the output of the verified Lean emit
//! `Dregg2.Circuit.Emit.EffectVmEmitCapReshape.capReshapeJson` (`emitVmJson capReshapeVmDescriptor`),
//! a CACHE of that emission (Lean is the source of truth). The Rust prover INTERPRETS this descriptor
//! via `parse_vm_descriptor` (it AUTHORS NO CONSTRAINT — the constraints are emitted from the proved
//! Lean module). The test below re-parses the JSON into the prover's structure; the Lean↔JSON drift
//! gate is generate-fresh `scripts/check-descriptor-drift.sh` (`CAPRESHAPE_V1_FP` is a cache-freshness
//! pin, NOT a faithfulness check).
//!
//! This is a STANDALONE loader (its own module + test), NOT registered in the locked
//! `effect_vm_descriptors` registry (whose count assertions would otherwise break). The descriptor is
//! the openable-`capability_root` check the sdk authority-binding (the Phase-D payoff) routes to; this
//! module proves it parses + carries the anti-amplify + anti-unauthorized-mint teeth.
//!
//! ## The carried hypothesis (honest seam)
//!
//! The descriptor checks the SUBMASK shadow of non-amplification (`granted_bit ≤ held_bit`, bit by bit)
//! and binds the rights digest into the opened held leaf; the bridge to the genuine `Finset Auth`
//! lattice is the Lean `entryEncodes` correspondence (`EffectVmEmitCapReshape` §2′). The turn-level
//! binding of the opened `cap_root` to the producer's authenticated cell-root is the sdk
//! authority-binding (`full_turn_proof.rs`), cited not duplicated here.

use crate::lean_descriptor_air::{EffectVmDescriptor, parse_vm_descriptor};

/// The verified-Lean JSON cache for the openable-`capability_root` descriptor (Lean is the
/// source of truth; regenerated by `scripts/emit-descriptors.sh`).
pub const CAPRESHAPE_V1_JSON: &str =
    include_str!("../descriptors/dregg-effectvm-capreshape-v1.json");

/// SHA-256 cache-freshness pin for the committed bytes (re-pinned by the emit script; NOT a
/// faithfulness check — the Lean↔JSON gate is generate-fresh `scripts/check-descriptor-drift.sh`).
pub const CAPRESHAPE_V1_FP: &str =
    "7d2db99b03d3f71c20001bc878a21ffa3498783465b8b144e23a040b52c8b58b";

/// The descriptor name (the canonical wire identity).
pub const CAPRESHAPE_V1_NAME: &str = "dregg-effectvm-capreshape-v1";

/// The `Auth` rights-mask bit width (8 atoms ⇒ 8 bits): mirrors Lean `EffectVmEmitCapReshape.MASK_BITS`.
pub const MASK_BITS: usize = 8;

/// The held-mask bit columns (aux block, `[104, 112)` on the 186-col layout). Mirrors Lean
/// `col.heldBit i = 104 + i`.
pub const HELD_BIT_BASE: usize = 104;

/// The granted-mask bit columns (`[112, 120)`). Mirrors Lean `col.grantedBit i = 112 + i`.
pub const GRANTED_BIT_BASE: usize = 112;

/// The control-bit position (`authBit control = 64 = 2^6`). Mirrors Lean `CONTROL_BIT_POS`.
pub const CONTROL_BIT_POS: usize = 6;

/// Parse the openable-`capability_root` descriptor through the running EffectVM interpreter.
/// (The same `parse_vm_descriptor` the cutover dispatcher uses; the descriptor drives the verified
/// circuit for the cap-reshape row.)
pub fn cap_reshape_descriptor() -> Result<EffectVmDescriptor, String> {
    parse_vm_descriptor(CAPRESHAPE_V1_JSON)
}

#[cfg(test)]
mod tests {
    use super::*;
    // The constraint AST forms inspected by the anti-amplify / production-authority teeth.
    // These live in `lean_descriptor_air` (plonky3-gated, same as this module's descriptor
    // types) and are not part of this module's runtime surface, so they're imported here.
    use crate::lean_descriptor_air::{LeanExpr, VmConstraint};

    /// The committed JSON re-parses through the interpreter into the structure the prover
    /// consumes (name, width, PI count, constraint count, hash site). The Lean↔JSON drift gate
    /// is generate-fresh `scripts/check-descriptor-drift.sh`, not a self-consistent FP rehash.
    #[test]
    fn capreshape_parses() {
        let d =
            cap_reshape_descriptor().expect("cap-reshape descriptor must parse via interpreter");
        assert_eq!(d.name, CAPRESHAPE_V1_NAME, "parsed name != wire identity");
        assert_eq!(
            d.trace_width, 187,
            "cap-reshape shares the 187-col EffectVM base trace (P0-2 record-digest)"
        );
        assert_eq!(d.public_input_count, 1, "the minted-asset PI");
        // 8 held-bool + 8 granted-bool + 8 submask + 2 recon + 1 PI binding + 1 control gate = 28.
        assert_eq!(d.constraints.len(), 3 * MASK_BITS + 2 + 2);
        // one held-leaf recompute site (`hash[slot, target, held_mask, 0]`, arity 4).
        assert_eq!(d.hash_sites.len(), 1);
        assert_eq!(d.hash_sites[0].inputs.len(), 4);
        assert_eq!(d.hash_sites[0].arity, 4);
    }

    /// Helper: does the gate body `g·(1 − h)` (a `mul` of `var(g)` with `add(const 1, mul(const -1,
    /// var(h)))`) appear in the constraint list for the given (granted, held) bit columns? This is the
    /// per-bit NON-AMP submask tooth; finding it for every bit confirms `granted ⊑ held` is enforced.
    fn has_submask_gate(d: &EffectVmDescriptor, granted_col: usize, held_col: usize) -> bool {
        d.constraints.iter().any(|c| match c {
            VmConstraint::Gate(LeanExpr::Mul(l, r)) => {
                let lhs_is_granted = matches!(**l, LeanExpr::Var(v) if v == granted_col);
                // r = add(const 1, mul(const -1, var held))
                let rhs_is_one_minus_held = match &**r {
                    LeanExpr::Add(a, b) => {
                        let a_is_one = matches!(**a, LeanExpr::Const(1));
                        let b_is_neg_held = matches!(&**b, LeanExpr::Mul(x, y)
                            if matches!(**x, LeanExpr::Const(-1))
                                && matches!(**y, LeanExpr::Var(v) if v == held_col));
                        a_is_one && b_is_neg_held
                    }
                    _ => false,
                };
                lhs_is_granted && rhs_is_one_minus_held
            }
            _ => false,
        })
    }

    /// THE ANTI-AMPLIFY TOOTH is present in the circuit: for EVERY mask bit, the descriptor carries the
    /// submask gate `granted_bit·(1 − held_bit) = 0` (a granted bit may be set only where the held bit
    /// is). So the interpreted circuit ENFORCES `granted ⊑ held` bitwise — non-amplification in-circuit,
    /// not an executor-trusted side-check.
    #[test]
    fn capreshape_carries_anti_amplify_teeth() {
        let d = cap_reshape_descriptor().unwrap();
        for i in 0..MASK_BITS {
            assert!(
                has_submask_gate(&d, GRANTED_BIT_BASE + i, HELD_BIT_BASE + i),
                "non-amp submask gate missing for bit {i} (granted {} ≤ held {})",
                GRANTED_BIT_BASE + i,
                HELD_BIT_BASE + i
            );
        }
    }

    /// THE ANTI-UNAUTHORIZED-MINT TOOTH is present: the descriptor carries (a) a first-row PI binding
    /// pinning the held cap's `target` param (col 71) to the minted-asset PI (index 0) — the opened
    /// issuer cap must target the asset — and (b) the control-bit gate `held_bit[6] − 1 = 0` forcing the
    /// mint right. So a mint WITHOUT the held issuer cap is rejected in-circuit.
    #[test]
    fn capreshape_carries_production_authority_teeth() {
        let d = cap_reshape_descriptor().unwrap();
        // (a) the asset-binding PI: target param (col 71) == PI[0] on the first row.
        let has_asset_pi = d.constraints.iter().any(|c| {
            matches!(c, VmConstraint::PiBinding { col, pi_index, .. } if *col == 71 && *pi_index == 0)
        });
        assert!(
            has_asset_pi,
            "production-authority asset PI binding missing"
        );
        // (b) the control-bit gate: add(var held_bit[6], mul(const -1, const 1)) = 0, i.e. h6 = 1.
        let has_control_gate = d.constraints.iter().any(|c| match c {
            VmConstraint::Gate(LeanExpr::Add(l, r)) => {
                matches!(**l, LeanExpr::Var(v) if v == HELD_BIT_BASE + CONTROL_BIT_POS)
                    && matches!(&**r, LeanExpr::Mul(x, y)
                        if matches!(**x, LeanExpr::Const(-1)) && matches!(**y, LeanExpr::Const(1)))
            }
            _ => false,
        });
        assert!(
            has_control_gate,
            "production-authority control-bit gate (held_bit[6] = 1) missing"
        );
    }
}
