//! # `cap_delegation_nonamp_descriptor` — the GENUINE-NON-AMP cap-graph descriptor loader.
//!
//! The ARGUS linchpin on the DELEGATION family (`delegate`, `delegateAtten`, `attenuate`, `introduce`,
//! `revoke`, `refresh`). One Lean-verified `EffectVmDescriptor` that, on a cap-graph row, enforces BOTH:
//!
//!   * **genuine cap-root recompute** — `new_cap_root = hash[edge_leaf, old_cap_root]` with
//!     `edge_leaf = hash[holder, target, rights, op]` (the §G prepend-accumulator advance, op-tagged), so
//!     the post `cap_root` is a FORCED function of the bound cap-edge mutation, not an opaque digest
//!     parameter — and the recomputed root is absorbed into `state_commit` (tamper ⇒ UNSAT);
//!   * **in-circuit non-amplification** — the per-bit submask gates `granted_bit ≤ held_bit` over the
//!     SAME `rights` felt the recompute hashes into the edge leaf, so the granted edge's conferred rights
//!     are `⊑` the delegator's held mask. An over-grant (a granted bit set where the held bit is clear)
//!     fails the submask gate. `granted ⊑ held` is now IN-CIRCUIT on the whole cap-graph family.
//!
//! The two legs INTERLOCK on one `rights` felt: tamper it to dodge the submask gate and the recomputed
//! `cap_root` moves ⇒ `state_commit` moves ⇒ UNSAT (the §G `capRoot_binds_edge` anti-ghost). This is the
//! delegation-family counterpart of the mint-flavour `cap_reshape_descriptor` (`granted ⊑ held` PLUS
//! production-authority); here it is `granted ⊑ held` PLUS the cap-root recompute (no production gate —
//! a delegation is not a mint).
//!
//! ## Provenance (anti-drift, the LAW#1 way)
//!
//! `dregg-effectvm-attenuateA-v1-genuine-nonamp.json` is the **byte-exact** output of the verified Lean
//! emit `Dregg2.Circuit.Emit.EffectVmEmitAttenuateA.attenuateVmDescriptorGenuineNonAmp` (via
//! `emitVmJson`, the `EmitAllJson` registry line). The Rust prover INTERPRETS this descriptor via
//! `parse_vm_descriptor` (it AUTHORS NO CONSTRAINT — the gates are emitted from the proved Lean module:
//! `capDeleg_nonAmp_in_circuit` / `capDeleg_rejects_amplify` are the in-circuit teeth, both polarities).
//! The test below re-parses the JSON into the prover's structure; the Lean↔JSON drift gate is
//! generate-fresh `scripts/check-descriptor-drift.sh` (`GENUINE_NONAMP_FP` is a cache-freshness pin,
//! NOT a faithfulness check). ONE descriptor object backs all six effects (the `op` tag distinguishes the mutation,
//! so the JSON is shared — selector→JSON fan-out, like the v1 cap-graph face).
//!
//! This is a STANDALONE loader (its own module + test), NOT registered in the locked
//! `effect_vm_descriptors` registry (whose count assertions would otherwise break) — exactly as
//! `cap_reshape_descriptor` is standalone. The sdk authority-binding routes cap-graph rows to it by name.

use crate::lean_descriptor_air::{EffectVmDescriptor, parse_vm_descriptor};

/// The verified-Lean JSON cache for the genuine-non-amp cap-graph descriptor (Lean is the
/// source of truth; regenerated by `scripts/emit-descriptors.sh`).
pub const GENUINE_NONAMP_JSON: &str =
    include_str!("../descriptors/dregg-effectvm-attenuateA-v1-genuine-nonamp.json");

/// SHA-256 cache-freshness pin for the committed bytes (re-pinned by the emit script; NOT a
/// faithfulness check — the Lean↔JSON gate is generate-fresh `scripts/check-descriptor-drift.sh`).
pub const GENUINE_NONAMP_FP: &str =
    "55bc5205205e9fb4c2ea4cee52eb173f95595fe43a0b96c6997b7d4e1eadbfad";

/// The descriptor name (the canonical wire identity — shared across the six cap-graph effects).
pub const GENUINE_NONAMP_NAME: &str = "dregg-effectvm-attenuateA-v1-genuine-nonamp";

/// The `Auth` rights-mask bit width (8 atoms ⇒ 8 bits): mirrors Lean `EffectVmEmitCapReshape.MASK_BITS`.
pub const MASK_BITS: usize = 8;

/// The DELEGATION held-mask bit columns. Mirrors Lean `dcol.heldBit i = 120 + i`
/// (`col.GRANTED_BIT_BASE + MASK_BITS = 112 + 8 = 120`), past the mint-flavour bit block.
pub const DELEG_HELD_BIT_BASE: usize = 120;

/// The DELEGATION granted-mask bit columns. Mirrors Lean `dcol.grantedBit i = 128 + i`
/// (`col.GRANTED_BIT_BASE + 2·MASK_BITS = 112 + 16 = 128`). These reconstruct `cp.RIGHTS` (param 4,
/// col 72) — the SAME `rights` felt the cap-root edge-leaf site hashes.
pub const DELEG_GRANTED_BIT_BASE: usize = 128;

/// Parse the genuine-non-amp cap-graph descriptor through the running EffectVM interpreter.
/// (The same `parse_vm_descriptor` the cutover dispatcher uses; the descriptor drives the verified
/// circuit for the delegation-family row.)
pub fn cap_delegation_nonamp_descriptor() -> Result<EffectVmDescriptor, String> {
    parse_vm_descriptor(GENUINE_NONAMP_JSON)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lean_descriptor_air::{LeanExpr, VmConstraint};

    /// The committed JSON re-parses through the interpreter into the structure the prover
    /// consumes (name, width, constraint count, hash sites). The Lean↔JSON drift gate is
    /// generate-fresh `scripts/check-descriptor-drift.sh`, not a self-consistent FP rehash.
    #[test]
    fn genuine_nonamp_parses() {
        let d = cap_delegation_nonamp_descriptor()
            .expect("genuine-non-amp descriptor must parse via interpreter");
        assert_eq!(d.name, GENUINE_NONAMP_NAME, "parsed name != wire identity");
        assert_eq!(
            d.trace_width, 187,
            "the genuine-non-amp cap-graph row shares the 187-col EffectVM base trace (P0-2 record-digest)"
        );
        // 30 genuine (12 frame freeze + 14 transition + 4 boundary) + 26 non-amp
        // (8 held-bool + 8 granted-bool + 8 submask + 2 recon) = 56.
        assert_eq!(d.constraints.len(), (12 + 14 + 4) + (3 * MASK_BITS + 2));
        // 6 hash sites: 2 cap-root recompute (edge-leaf + advance) + 4 GROUP-4 state-commitment.
        assert_eq!(d.hash_sites.len(), 6);
    }

    /// Helper: does the per-bit NON-AMP submask gate body `g·(1 − h)` (a `mul` of `var(g)` with
    /// `add(const 1, mul(const -1, var(h)))`) appear in the constraint list for the given (granted,
    /// held) bit columns? Finding it for every bit confirms `granted ⊑ held` is enforced in-circuit.
    fn has_submask_gate(d: &EffectVmDescriptor, granted_col: usize, held_col: usize) -> bool {
        d.constraints.iter().any(|c| match c {
            VmConstraint::Gate(LeanExpr::Mul(l, r)) => {
                let lhs_is_granted = matches!(**l, LeanExpr::Var(v) if v == granted_col);
                let rhs_is_one_minus_held = match &**r {
                    LeanExpr::Add(a, b) => {
                        let a_is_one = matches!(**a, LeanExpr::Const(1));
                        let b_is_neg_held = matches!(&**b, LeanExpr::Mul(x, y)
                            if matches!(**x, LeanExpr::Const(-1))
                                && matches!(**y, LeanExpr::Var(v) if v == held_col));
                        a_is_one && b_is_neg_held
                    }
                    _ => false,
                };
                lhs_is_granted && rhs_is_one_minus_held
            }
            _ => false,
        })
    }

    /// THE ANTI-AMPLIFY TOOTH is present on the cap-graph family: for EVERY mask bit, the descriptor
    /// carries the submask gate `granted_bit·(1 − held_bit) = 0` over the DELEGATION bit columns
    /// (held `[120,128)`, granted `[128,136)`). So the interpreted circuit ENFORCES `granted ⊑ held`
    /// bitwise — in-circuit non-amplification on every delegation effect, not an executor side-check.
    #[test]
    fn genuine_nonamp_carries_anti_amplify_teeth() {
        let d = cap_delegation_nonamp_descriptor().unwrap();
        for i in 0..MASK_BITS {
            assert!(
                has_submask_gate(&d, DELEG_GRANTED_BIT_BASE + i, DELEG_HELD_BIT_BASE + i),
                "non-amp submask gate missing for bit {i} (granted {} ≤ held {})",
                DELEG_GRANTED_BIT_BASE + i,
                DELEG_HELD_BIT_BASE + i
            );
        }
    }

    /// THE GENUINE CAP-ROOT RECOMPUTE is present (NOT an opaque digest): the descriptor carries the two
    /// recompute hash-sites — the edge leaf `hash[holder, target, rights, op]` (arity 4) into the leaf
    /// carrier (col 102) and the advance `hash[edge_leaf, old_cap_root]` (arity 2) into the cap-root
    /// after-column (col 87). So the post `cap_root` is FORCED by the bound edge mutation, interlocking
    /// with the non-amp gate on the same `rights` felt (col 72).
    #[test]
    fn genuine_nonamp_carries_caproot_recompute() {
        let d = cap_delegation_nonamp_descriptor().unwrap();
        // the edge-leaf recompute site: arity 4, digest into col 102 (CAP_EDGE_LEAF), reading params
        // holder/target/rights/op (cols 70/71/72/73).
        let leaf_site = d
            .hash_sites
            .iter()
            .find(|s| s.digest_col == 102)
            .expect("cap-edge-leaf recompute site (digest col 102) missing");
        assert_eq!(leaf_site.arity, 4, "edge leaf is hash[holder,target,rights,op]");
        assert_eq!(leaf_site.inputs.len(), 4);
        // the advance site: arity 2, digest into col 87 (saCol CAP_ROOT), reading the leaf (102) + the
        // old cap-root column (65 = sbCol CAP_ROOT).
        let adv_site = d
            .hash_sites
            .iter()
            .find(|s| s.digest_col == 87)
            .expect("cap-root advance site (digest col 87 = saCol CAP_ROOT) missing");
        assert_eq!(adv_site.arity, 2, "advance is hash[edge_leaf, old_cap_root]");
        assert_eq!(adv_site.inputs.len(), 2);
    }
}
