val _ = load "admitRung3Theory"; val _ = load "admitBytesBridgeTheory";
open admitRung3Theory admitBytesBridgeTheory;
fun tag th = let val (o_,a)=Tag.dest_tag (Thm.tag th) in "[oracles: "^String.concatWith "," o_^"] [axioms: "^String.concatWith "," a^"]" end;
val _ = print ("AAA backbone admit_rung3_native = "^tag admit_rung3_native^"\n");
val _ = print ("AAA linkA admit_decisioncore_refines_spec = "^tag admit_decisioncore_refines_spec^"\n");
val _ = print ("AAA faithful admitIf_faithful = "^tag admitIf_faithful^"\n");
val _ = print ("AAA L2 admit_compile_prog_native = "^tag admit_compile_prog_native^"\n");
val _ = print ("AAA theory-axioms admitRung3 = "^Int.toString(length(axioms "admitRung3"))^"\n");
val _ = print ("AAA theory-axioms admitBytesBridge = "^Int.toString(length(axioms "admitBytesBridge"))^"\n");
val c = concl admitIf_faithful; val (lhs,rhs)=dest_eq c;
fun qn t = let val {Thy,Name,...}=dest_thy_const t in Thy^"$"^Name end;
val progn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="admitProg") lhs);
val ifn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="admitIf") rhs);
val _ = print ("AAA faithful-distinct prog="^progn^" if="^ifn^" DISTINCT="^Bool.toString(progn<>ifn)^"\n");
val bc = concl admit_rung3_native; val (ante,conc)=dest_imp bc;
val _ = print ("AAA backbone antecedent-conjuncts = "^Int.toString(length(strip_conj ante))^"\n");
val _ = print ("AAA backbone concl-mentions-admitProg = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="admitProg")) conc)^"\n");
val _ = print ("AAA backbone ante-mentions-admitBytes = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="admitBytes")) ante)^"\n");
