//! # The Lean-sourced program loader.
//!
//! The multiway-tug play teeth are **authored in Lean**
//! (`metatheory/Dregg2/Games/MultiwayTugProgram.lean :: multiwayTugProgram`) and emitted to the
//! checked-in artifact [`PROGRAM_JSON`] by the verified emit
//! (`metatheory/EmitMultiwayTugProgram.lean`). This module does the ONLY Rust-side work: it
//! deserializes that symbolic artifact and resolves the symbolic slot/method NAMES into the
//! runtime [`CellProgram`] by looking them up in the translation-validated `dregg-schema`
//! allocator ([`Deployment`]). There is NO hand-rolled `CellProgram::Cases` in Rust anymore —
//! the deployed program IS the Lean object by construction (edit a threshold in the Lean source,
//! re-emit via `program/regen.sh`, and the deployed game changes).
//!
//! **What is Lean-sourced vs Rust-resolved.** The teeth STRUCTURE — which methods, which
//! constraints, the conservation sum, the `WriteOnce`/`Monotonic`/`StrictMonotonic` atoms, and
//! the win-gate thresholds (`charm >= 11`, `guilds >= 4`, `round_actions >= 8`) — is entirely
//! the artifact's content. Rust only maps a symbolic NAME to its allocator-assigned index
//! (`reg`/`key`) and a method NAME to its `symbol()` hash. The allocator is itself
//! translation-validated (the RotatedLayout Legal discipline), so the name→index binding is not
//! a hand-authored semantic object; the semantic teeth are the Lean value's.

use dregg_app_framework::{
    CellProgram, StateConstraint, TransitionCase, TransitionGuard, field_from_u64, symbol,
};
use dregg_cell::program::{HeapAtom, SimpleStateConstraint};
use serde::Deserialize;
use spween_dregg::GENESIS_DONE_EXT_KEY;

use crate::state::Deployment;

/// The checked-in Lean-emitted artifact (a CACHE of the verified Lean emission; Lean is the
/// source of truth, regenerated by `program/regen.sh`).
pub const PROGRAM_JSON: &str = include_str!("../program/multiway_tug_program.json");

/// The symbolic top-level program (mirrors the Lean `CellProgram.cases`).
#[derive(Debug, Deserialize)]
struct SymProgram {
    scene: String,
    cases: Vec<SymCase>,
}

#[derive(Debug, Deserialize)]
struct SymCase {
    method: String,
    constraints: Vec<SymConstraint>,
}

/// The symbolic `StateConstraint` subset tug uses (mirrors Lean `Constraint`).
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SymConstraint {
    SumEquals { regs: Vec<String>, value: u64 },
    WriteOnce { reg: String },
    StrictMonotonic { reg: String },
    FieldGte { reg: String, value: u64 },
    HeapField { key: SymKey, atom: SymAtom },
    AnyOf { variants: Vec<SymSimple> },
}

/// The symbolic heap-key reference (mirrors Lean `HeapKeyRef`).
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SymKey {
    Named { name: String },
    Sentinel,
}

/// The symbolic heap-atom subset (mirrors Lean `HeapAtom`).
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SymAtom {
    WriteOnce,
    Monotonic,
    Immutable,
    Equals { value: u64 },
    DeltaEquals { d: i64 },
}

/// The symbolic simple-constraint subset (mirrors Lean `SimpleConstraint`).
#[derive(Debug, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
enum SymSimple {
    FieldEquals { reg: String, value: u64 },
    FieldGte { reg: String, value: u64 },
    Not { inner: Box<SymSimple> },
}

impl SymKey {
    fn resolve(&self, dep: &Deployment) -> u64 {
        match self {
            SymKey::Named { name } => dep.key(name),
            SymKey::Sentinel => GENESIS_DONE_EXT_KEY,
        }
    }
}

impl SymAtom {
    fn resolve(&self) -> HeapAtom {
        match self {
            SymAtom::WriteOnce => HeapAtom::WriteOnce,
            SymAtom::Monotonic => HeapAtom::Monotonic,
            SymAtom::Immutable => HeapAtom::Immutable,
            SymAtom::Equals { value } => HeapAtom::Equals {
                value: field_from_u64(*value),
            },
            SymAtom::DeltaEquals { d } => HeapAtom::DeltaEquals { d: *d },
        }
    }
}

impl SymSimple {
    fn resolve(&self, dep: &Deployment) -> SimpleStateConstraint {
        match self {
            SymSimple::FieldEquals { reg, value } => SimpleStateConstraint::FieldEquals {
                index: dep.reg(reg),
                value: field_from_u64(*value),
            },
            SymSimple::FieldGte { reg, value } => SimpleStateConstraint::FieldGte {
                index: dep.reg(reg),
                value: field_from_u64(*value),
            },
            SymSimple::Not { inner } => SimpleStateConstraint::Not(Box::new(inner.resolve(dep))),
        }
    }
}

impl SymConstraint {
    fn resolve(&self, dep: &Deployment) -> StateConstraint {
        match self {
            SymConstraint::SumEquals { regs, value } => StateConstraint::SumEquals {
                indices: regs.iter().map(|n| dep.reg(n)).collect(),
                value: field_from_u64(*value),
            },
            SymConstraint::WriteOnce { reg } => StateConstraint::WriteOnce {
                index: dep.reg(reg),
            },
            SymConstraint::StrictMonotonic { reg } => StateConstraint::StrictMonotonic {
                index: dep.reg(reg),
            },
            SymConstraint::FieldGte { reg, value } => StateConstraint::FieldGte {
                index: dep.reg(reg),
                value: field_from_u64(*value),
            },
            SymConstraint::HeapField { key, atom } => StateConstraint::HeapField {
                key: key.resolve(dep),
                atom: atom.resolve(),
            },
            SymConstraint::AnyOf { variants } => StateConstraint::AnyOf {
                variants: variants.iter().map(|v| v.resolve(dep)).collect(),
            },
        }
    }
}

/// The scene id the artifact must declare (fixes the deterministic world-cell identity).
pub const EXPECTED_SCENE: &str = "dregg-multiway-tug/phase0";

/// **Load the Lean-authored tug program**, resolving the symbolic slot/method names against the
/// allocator. Panics if the artifact fails to parse or names the wrong scene — a corrupt/stale
/// artifact must fail loud at deploy, never silently ship a different program.
pub fn load_program(dep: &Deployment) -> CellProgram {
    let sym: SymProgram = serde_json::from_str(PROGRAM_JSON)
        .expect("multiway_tug_program.json (Lean-emitted) parses");
    assert_eq!(
        sym.scene, EXPECTED_SCENE,
        "Lean-emitted program scene mismatch (stale/foreign artifact)"
    );
    let cases = sym
        .cases
        .into_iter()
        .map(|c| TransitionCase {
            guard: TransitionGuard::MethodIs {
                method: symbol(&c.method),
            },
            constraints: c.constraints.iter().map(|k| k.resolve(dep)).collect(),
        })
        .collect();
    CellProgram::Cases(cases)
}
