//! Bake the **`portal.dregg.studio` static site** — the public, read-mostly web portal
//! to SEE + trustlessly verify the LIVE DreggNet.
//!
//! It is gpui-FREE and deos-js-FREE (the `web` feature): it reuses the SAME proven
//! renderer the cockpit's web projection uses — [`deos_view::web::portal_css`] (the exact
//! cockpit + trust-banner styling) and [`deos_view::web::render_trustless_cell_document`]
//! (the keystone: a cell's card wrapped in a light-client trust banner that verifies the
//! recursive-STARK aggregate IN THE TAB, re-witnessing nothing). The dynamic, live data
//! (the cells on the devnet, a clicked cell's balance/nonce/caps) is fetched at runtime by
//! `portal.js` from the edge node's read API (`/api/cells`, `/api/cell/<id>`,
//! `/observability/stream`) and layered into that proven shell.
//!
//! Run (from inside `deos-view/`):
//!   cargo run --no-default-features --features web --example portal_bake -- <out-dir>
//! Default out-dir: `portal-dist`. The wasm light-client bundle (`../wasm/pkg`) is copied
//! into `<out-dir>/pkg` if present (the in-tab verify engine). Serve `<out-dir>` over HTTP.

use deos_view::tree::ViewNode;
use deos_view::web::{portal_css, render_trustless_cell_document, TrustlessAttestation};
use deos_view::BindFmt;
use std::fs;
use std::path::Path;

fn main() {
    let out = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "portal-dist".into());
    let out = Path::new(&out);
    fs::create_dir_all(out).expect("create out dir");

    // 1) styles.css — the EXACT cockpit + trust-banner palette, reused verbatim (no drift),
    //    plus the portal-only chrome (header, the live cell grid, the cell graph).
    let css = format!("{}{}", portal_css(), PORTAL_EXTRA_CSS);
    fs::write(out.join("styles.css"), css).expect("write styles.css");

    // 2) index.html — the LIVE NETWORK VIEW. A static shell; portal.js fetches /api/cells at
    //    runtime, renders the cell grid + a hub-and-spoke cell graph, and subscribes to the
    //    /observability/stream SSE feed for liveness.
    fs::write(out.join("index.html"), index_html()).expect("write index.html");

    // 3) cell.html — the TRUSTLESS CELL CARD. Generated by the REAL keystone
    //    (render_trustless_cell_document): a placeholder card wrapped in the light-client
    //    trust banner whose module bootstrap runs the recursive-STARK verify in the tab
    //    (InTabDemo: fold + verify a real history end-to-end, re-witnessing nothing). We splice
    //    in portal.js, which fetches the clicked cell and fills the card body with its live
    //    balance/nonce/caps — so a visitor sees the cell AND watches the light client attest.
    fs::write(out.join("cell.html"), cell_html()).expect("write cell.html");

    // 4) portal.js — the runtime fetch/render layer for both pages.
    fs::write(out.join("portal.js"), PORTAL_JS).expect("write portal.js");

    // 5) the wasm light-client bundle (the in-tab verify engine). Copied from ../wasm/pkg if
    //    present; absent → the trust banner degrades to "attestation check failed to run"
    //    (honest) while the network view still works.
    copy_pkg(out);

    println!("portal baked to {}", out.display());
}

/// Copy the wasm-pack bundle (`dregg_wasm.js`, `dregg_wasm_bg.wasm`, the `.d.ts`/`package.json`)
/// from `../wasm/pkg` into `<out>/pkg`. Best-effort: a missing source warns, never fails.
fn copy_pkg(out: &Path) {
    let src = Path::new("../wasm/pkg");
    if !src.is_dir() {
        eprintln!(
            "warning: {} not found — baking WITHOUT the wasm light-client (trustless verify will \
             not run until pkg/ is dropped in). Build it: cd ../wasm && wasm-pack build --target web",
            src.display()
        );
        return;
    }
    let dst = out.join("pkg");
    fs::create_dir_all(&dst).expect("create pkg dir");
    for entry in fs::read_dir(src).expect("read wasm/pkg") {
        let entry = entry.expect("dir entry");
        let path = entry.path();
        if path.is_file() {
            let name = path.file_name().unwrap();
            fs::copy(&path, dst.join(name)).expect("copy pkg file");
        }
    }
    println!("copied wasm light-client bundle into {}", dst.display());
}

/// The cell page's placeholder card — a "loading" state portal.js replaces with the fetched
/// cell's live fields. The keystone needs a real tree to render; this is it.
fn placeholder_card() -> ViewNode {
    ViewNode::VStack(vec![
        ViewNode::Text("loading cell from the live edge node…".into()),
        ViewNode::Bind {
            slot: 0,
            label: "balance: ".into(),
            fmt: BindFmt::Raw,
        },
    ])
}

/// The trustless cell page — the REAL keystone shell + the portal.js fill layer spliced in.
fn cell_html() -> String {
    // InTabDemo: the tab folds a real k-turn history AND verifies it, so the visitor watches
    // a genuine recursive-STARK light-client verification run in their browser (the
    // differentiator). Binding a SPECIFIC fetched cell's server-supplied history envelope is
    // the next rung (ServerSupplied) — see the portal report / README.
    let doc = render_trustless_cell_document(
        "DreggNet — cell",
        &placeholder_card(),
        &[0],
        &[],
        &TrustlessAttestation::InTabDemo { k: 3, step: 7 },
        "./pkg/dregg_wasm.js",
    );
    // Splice the portal chrome (back-link, the live-fetch note) + portal.js. The keystone's
    // own trust banner + wasm verify bootstrap are kept verbatim.
    let head_inject = "<link rel=\"stylesheet\" href=\"./styles.css\">";
    let body_inject = "<a class=\"portal-back\" href=\"./\">&lsaquo; the live network</a>\n\
<script src=\"./portal.js\"></script>";
    doc.replace("</head>", &format!("{head_inject}\n</head>"))
        .replace("</body>", &format!("{body_inject}\n</body>"))
}

/// The live-network landing page.
fn index_html() -> String {
    format!(
        "<!doctype html>\n\
<html lang=\"en\">\n\
<head>\n\
<meta charset=\"utf-8\">\n\
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
<title>DreggNet — the live network</title>\n\
<link rel=\"stylesheet\" href=\"./styles.css\">\n\
</head>\n\
<body class=\"portal-body\">\n\
<main class=\"portal\">\n\
<header class=\"portal-head\">\n\
<h1>DreggNet</h1>\n\
<p>The live network of sovereign cells. Every card you open verifies the cell&rsquo;s committed \
history <em>in your own browser</em> with a recursive-STARK light client &mdash; don&rsquo;t trust \
the server, verify it.</p>\n\
<div class=\"portal-status\" id=\"portal-status\">connecting to the edge node&hellip;</div>\n\
</header>\n\
<section class=\"portal-section\">\n\
<div class=\"portal-section-title\">cell graph &mdash; the custodial hub and its cells</div>\n\
<div class=\"portal-graph\" id=\"portal-graph\"><svg id=\"portal-graph-svg\" viewBox=\"0 0 600 360\" \
preserveAspectRatio=\"xMidYMid meet\"></svg></div>\n\
</section>\n\
<section class=\"portal-section\">\n\
<div class=\"portal-section-title\">cells on the network</div>\n\
<div class=\"portal-cells\" id=\"portal-cells\">loading cells&hellip;</div>\n\
</section>\n\
<footer class=\"portal-foot\">read-only v1 &middot; the live cells + per-cell trustless verify. \
Drive-actions (open a lease, pay, fire a turn) are the next rung.</footer>\n\
</main>\n\
<script src=\"./portal.js\"></script>\n\
</body>\n\
</html>\n"
    )
}

/// Portal-only chrome on top of the reused cockpit/trust CSS.
const PORTAL_EXTRA_CSS: &str = "
.portal-body{align-items:flex-start;}
.portal{max-width:860px;width:100%;margin:0 auto;display:flex;flex-direction:column;gap:1.2rem;}
.portal-head h1{margin:.25rem 0 .4rem;font-size:1.9rem;font-weight:800;letter-spacing:-.01em;}
.portal-head p{margin:0 0 .8rem;color:var(--muted);line-height:1.5;max-width:620px;}
.portal-head em{color:var(--fg);font-style:normal;font-weight:600;}
.portal-status{display:inline-flex;align-items:center;gap:.5rem;font-size:.82rem;color:var(--muted);padding:.4rem .7rem;border:1px solid var(--border);border-radius:8px;background:rgba(110,160,255,.05);}
.portal-status.live{color:#3fb950;border-color:#27502f;}
.portal-status .dot{width:8px;height:8px;border-radius:999px;background:var(--muted);}
.portal-status.live .dot{background:#3fb950;box-shadow:0 0 8px #3fb95088;}
.portal-section{display:flex;flex-direction:column;gap:.6rem;border:1px solid var(--border);border-radius:12px;padding:1rem 1.1rem;background:var(--card);}
.portal-section-title{font-weight:600;font-size:.74rem;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);}
.portal-graph{width:100%;}
.portal-graph svg{width:100%;height:auto;display:block;}
.portal-graph .edge{stroke:var(--border);stroke-width:1.5;}
.portal-graph .node{cursor:pointer;transition:filter .12s;}
.portal-graph .node:hover{filter:brightness(1.2);}
.portal-graph .node-hub{fill:var(--accent);}
.portal-graph .node-cell{fill:#2f8f4e;}
.portal-graph .node-label{fill:var(--muted);font-size:10px;font-family:ui-monospace,Menlo,monospace;pointer-events:none;}
.portal-cells{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:.8rem;}
.portal-cell{display:flex;flex-direction:column;gap:.35rem;text-decoration:none;background:#181a20;border:1px solid var(--border);border-radius:10px;padding:.9rem 1rem;transition:border-color .12s,transform .12s;}
.portal-cell:hover{border-color:var(--accent);transform:translateY(-2px);}
.portal-cell-id{color:var(--fg);font-weight:700;font-family:ui-monospace,Menlo,monospace;font-size:.92rem;word-break:break-all;}
.portal-cell-row{color:var(--muted);font-size:.8rem;display:flex;justify-content:space-between;gap:.5rem;}
.portal-cell-row b{color:var(--fg);font-weight:600;font-variant-numeric:tabular-nums;}
.portal-cell-tags{display:flex;gap:.3rem;flex-wrap:wrap;margin-top:.2rem;}
.portal-tag{font-size:.64rem;font-weight:700;letter-spacing:.04em;text-transform:uppercase;padding:.1rem .4rem;border-radius:999px;background:var(--border);color:var(--muted);}
.portal-tag.hub{background:var(--accent);color:#101216;}
.portal-tag.prog{background:#2f8f4e;color:#0c1410;}
.portal-foot{color:var(--muted);font-size:.78rem;line-height:1.5;padding:.2rem;}
.portal-back{position:fixed;top:1rem;left:1rem;color:var(--muted);text-decoration:none;font-size:.85rem;z-index:5;}
.portal-back:hover{color:var(--accent);}
.portal-note{font-size:.78rem;color:var(--muted);line-height:1.5;margin:.6rem 0 0;padding:.5rem .7rem;border-left:2px solid var(--border);}
.portal-card-fields{display:flex;flex-direction:column;gap:.5rem;}
.portal-err{color:#f85149;font-size:.85rem;}
";

/// The runtime fetch/render layer. One file drives both pages (it branches on which page
/// elements are present). Configurable API base: `?api=<base>` query param, else same-origin
/// (on `portal.dregg.studio` the edge proxies `/api/*` + `/observability/*` to the bot).
const PORTAL_JS: &str = r#"
(function () {
  "use strict";
  var params = new URLSearchParams(location.search);
  // API base: ?api= override, else same-origin (Caddy proxies /api/* to the edge bot).
  var API = (params.get("api") || "").replace(/\/$/, "");
  function api(path) { return API + path; }
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }
  function shortId(id) { return id && id.length > 18 ? id.slice(0, 10) + "…" + id.slice(-6) : id; }

  // ---- the live network view (index.html) ----------------------------------
  var cellsEl = document.getElementById("portal-cells");
  if (cellsEl) initNetworkView();

  function initNetworkView() {
    var statusEl = document.getElementById("portal-status");
    var graphSvg = document.getElementById("portal-graph-svg");

    function loadCells() {
      fetch(api("/api/cells"), { headers: { accept: "application/json" } })
        .then(function (r) { if (!r.ok) throw new Error("HTTP " + r.status); return r.json(); })
        .then(function (cells) {
          renderCells(cells);
          renderGraph(graphSvg, cells);
        })
        .catch(function (e) {
          cellsEl.innerHTML = '<div class="portal-err">could not load /api/cells: ' + esc(e.message) +
            '<br>if you are testing from another origin, append <code>?api=https://portal.dregg.studio</code></div>';
        });
    }

    function renderCells(cells) {
      if (!cells || !cells.length) { cellsEl.innerHTML = '<div class="portal-err">no cells reported.</div>'; return; }
      cellsEl.innerHTML = cells.map(function (c, i) {
        var hub = i === 0; // list_cells returns the bot/custodial cell first
        var tags = "";
        if (hub) tags += '<span class="portal-tag hub">custodial hub</span>';
        if (c.has_program) tags += '<span class="portal-tag prog">service cell</span>';
        if (c.nullifier_known) tags += '<span class="portal-tag">spent-seen</span>';
        return '<a class="portal-cell" href="./cell.html?id=' + encodeURIComponent(c.id) +
          (API ? "&api=" + encodeURIComponent(API) : "") + '">' +
          '<span class="portal-cell-id">' + esc(shortId(c.id)) + '</span>' +
          '<span class="portal-cell-row">balance <b>' + esc(c.balance) + '</b></span>' +
          '<span class="portal-cell-row">nonce <b>' + esc(c.nonce) + '</b></span>' +
          '<span class="portal-cell-row">capabilities <b>' + esc(c.capability_count) + '</b></span>' +
          (tags ? '<span class="portal-cell-tags">' + tags + '</span>' : '') +
          '</a>';
      }).join("");
    }

    function renderGraph(svg, cells) {
      if (!svg) return;
      var W = 600, H = 360, cx = W / 2, cy = H / 2;
      var hub = cells[0], spokes = cells.slice(1);
      var R = Math.min(W, H) / 2 - 50;
      var parts = [];
      // edges: hub -> each cell (the custodial relationship the read API exposes)
      spokes.forEach(function (c, i) {
        var a = (2 * Math.PI * i) / Math.max(1, spokes.length) - Math.PI / 2;
        var x = cx + R * Math.cos(a), y = cy + R * Math.sin(a);
        parts.push('<line class="edge" x1="' + cx + '" y1="' + cy + '" x2="' + x + '" y2="' + y + '"/>');
      });
      // spoke nodes
      spokes.forEach(function (c, i) {
        var a = (2 * Math.PI * i) / Math.max(1, spokes.length) - Math.PI / 2;
        var x = cx + R * Math.cos(a), y = cy + R * Math.sin(a);
        var r = 8 + Math.min(14, Math.log10(1 + Number(c.balance || 0)) * 4);
        parts.push('<a href="./cell.html?id=' + encodeURIComponent(c.id) + (API ? "&api=" + encodeURIComponent(API) : "") + '">' +
          '<circle class="node node-cell" cx="' + x + '" cy="' + y + '" r="' + r.toFixed(1) + '"><title>' + esc(c.id) + '</title></circle>' +
          '<text class="node-label" x="' + x + '" y="' + (y + r + 12) + '" text-anchor="middle">' + esc(shortId(c.id)) + '</text></a>');
      });
      // hub node (drawn last, on top)
      if (hub) {
        parts.push('<a href="./cell.html?id=' + encodeURIComponent(hub.id) + (API ? "&api=" + encodeURIComponent(API) : "") + '">' +
          '<circle class="node node-hub" cx="' + cx + '" cy="' + cy + '" r="18"><title>' + esc(hub.id) + ' (custodial hub)</title></circle>' +
          '<text class="node-label" x="' + cx + '" y="' + (cy + 32) + '" text-anchor="middle">hub</text></a>');
      }
      svg.innerHTML = parts.join("");
    }

    // liveness via the SSE observability stream (hello + 15s pings)
    function connectStream() {
      try {
        var es = new EventSource(api("/observability/stream"));
        es.addEventListener("hello", function (ev) {
          setLive("live · " + safeField(ev.data, "apps", "?") + " apps · " + safeField(ev.data, "nullifiers", "0") + " nullifiers seen");
          loadCells();
        });
        es.addEventListener("ping", function (ev) {
          setLive("live · seq " + safeField(ev.data, "seq", "?") + " · " + safeField(ev.data, "nullifiers", "0") + " nullifiers seen");
        });
        es.onerror = function () { if (statusEl) statusEl.classList.remove("live"); };
      } catch (e) { /* EventSource unsupported: the poll below still drives it */ }
    }
    function safeField(json, k, dflt) { try { var o = JSON.parse(json); return o[k] != null ? o[k] : dflt; } catch (e) { return dflt; } }
    function setLive(text) { if (statusEl) { statusEl.classList.add("live"); statusEl.innerHTML = '<span class="dot"></span>' + esc(text); } }

    loadCells();
    connectStream();
    setInterval(loadCells, 20000); // gentle refresh in case SSE is proxied without flush
  }

  // ---- the trustless cell card (cell.html) ---------------------------------
  var content = document.getElementById("deos-content");
  if (content && params.get("id")) initCellView(content, params.get("id"));

  function initCellView(content, id) {
    fetch(api("/api/cell/" + encodeURIComponent(id)), { headers: { accept: "application/json" } })
      .then(function (r) { if (!r.ok) throw new Error("HTTP " + r.status); return r.json(); })
      .then(function (c) { fillCell(content, c); })
      .catch(function (e) {
        content.innerHTML = '<div class="deos-vstack"><span class="portal-err">could not load this cell: ' + esc(e.message) + '</span></div>';
      });
  }

  function fillCell(content, c) {
    var found = c.found;
    var rows = [
      ["cell", c.id],
      ["found on chain", found ? "yes" : "no"],
      ["balance", c.balance],
      ["nonce", c.nonce],
      ["capabilities", c.capability_count],
      ["has program", c.has_program ? "yes" : "no"]
    ];
    if (c.program_vk) rows.push(["program vk", shortId(c.program_vk)]);
    if (c.created_by_factory) rows.push(["minted by factory", shortId(c.created_by_factory)]);
    var body = '<div class="deos-vstack"><span class="deos-text" style="font-weight:700">Cell</span>' +
      '<div class="portal-card-fields">' +
      rows.map(function (r) {
        return '<div class="deos-row" style="justify-content:space-between">' +
          '<span class="deos-text">' + esc(r[0]) + '</span>' +
          '<span class="deos-bind">' + esc(r[1]) + '</span></div>';
      }).join("") +
      '</div>' +
      '<p class="portal-note">The fields above are <b>read live</b> from the edge node&rsquo;s API (the server&rsquo;s ' +
      'claim). The trust banner above runs a <b>recursive-STARK light client in this tab</b> that verifies a real ' +
      'finalized history end-to-end, re-witnessing nothing &mdash; the proof that the verification machinery is genuine ' +
      'and runs in your browser. Binding <i>this specific cell&rsquo;s</i> committed history (a server-supplied proof ' +
      'envelope + per-field heap openings) into that banner is the next rung.</p>' +
      '</div>';
    content.innerHTML = body;
  }
})();
"#;
