/-
# Dregg2.Proof.CTL — a branching-time temporal logic (CTL) over the dregg2 transition system.

`Proof/Temporal.lean` gave a LINEAR temporal logic (`□`/`◇`/`◯`) of state predicates along ONE
trajectory `trajA s sched`: it quantifies over a *fixed* schedule, then (in `always_iff_reachable`)
over *all* schedules. What it cannot say is anything *branching* — "along SOME path" vs. "along
EVERY path" as first-class, nested operators. A config of the living cell has MANY successors (one
per `ConservingForest`); CTL is the logic of that successor tree.

This module supplies the **branching** vocabulary as the Emerson–Clarke fixpoint characterization,
standing entirely on `Mathlib.Order.FixedPoints` (`OrderHom.lfp`/`gfp` over the complete lattice
`Set System.Config`). One primitive — the existential pre-image `pre` under `Step` — generates all
eight modalities:

* `EX`/`AX` — the modal next (∃/∀ successor);
* `EU`/`AU` — the until's (least fixpoints: finite reachability of `Q` through `P`);
* `EF`/`AF` — eventually = `E/A[⊤ U P]` (least fixpoints);
* `EG`/`AG` — globally (greatest fixpoints: infinite safety along some/every path).

We prove the FIXPOINT (unfolding) laws, monotonicity, the ∃/∀ De Morgan duality algebra
(`EX_AX_dual`, `EF_EG_dual`), the gfp coinduction rule (`AG_coind`), the lfp induction rule
(`EF_least`), and the two CROSS-CHECKS that tie CTL to the existing layers:

* `EF_iff_reachable` — the least-fixpoint `EF` coincides with `Execution.Reachable`/`Run`;
* `AG_iff_all_reachable` — the greatest-fixpoint `AG` coincides with "holds at every reachable
  config" (the relational invariant);

and the BRIDGE to the LTL layer on the REAL 46-effect executor:

* `livingAG_iff_temporalAlways` — branching `AG` over `Temporal.livingSystem` is equivalent to the
  linear `Temporal.Always` along every schedule (via `Temporal.always_iff_reachable`);
* `livingAG_conserved` — the conservation badge holds `AG` on the real branching executor.

## TEETH (the whole point of branching time)

The separation `EX ≠ AX` and `EF ≠ AF` is the empirical content of branching: it is FALSE in the
linear/deterministic world and TRUE here. We prove it on a hand-controlled `Fin 3` branching system
(`branchSys`: `s₀ → s₁`, `s₀ → s₂`, `s₁`/`s₂` self-loop), where `s₀` reaches the target `{1}` on
SOME path but not on EVERY path (the `s₂` trap). Decidable, finite, refutation-proved.

## What is DEFERRED (the residue) — the liveness reading of AF/EG under fairness

This is the **safety** fragment of CTL. The OPERATORS `AF`/`EG` are defined and their fixpoint laws
proved, but the *liveness reading* — theorems asserting "on every path `P` is eventually reached"
on the living cell — is **deliberately NOT proved here**, because it needs a fairness / stutter
decision (ember-gated): `Temporal.livingSystem` is total (`cellNextA` fail-closes to a self-loop),
so EVERY config has a stuttering successor, and `AF committed` would require `P` on the stutter
branch too — i.e. liveness is only as meaningful as the fairness model. `Temporal.lean` already
flagged the same gap for `◇`. We ship the safety fragment (model-safe, composes with conservation /
log / revocation invariants) and the branching-separation teeth (fully sound), and gate the
fairness-dependent liveness theorems behind that decision.

Pure; spec-first.
The two classical duals (`EX_AX_dual`, `EF_EG_dual`, which use `compl_compl`) are pinned
in the classical-aware list, exactly as `Temporal.not_always_iff_eventually_not` is.
-/
import Dregg2.Execution
import Dregg2.Proof.Temporal
import Mathlib.Order.FixedPoints
import Mathlib.Order.CompleteBooleanAlgebra
import Mathlib.Data.Set.Basic

namespace Dregg2.Proof.CTL

open Dregg2.Execution

/-! ## §0 — The modal building blocks: the pre-image operators.

The whole calculus is generated by ONE primitive — the existential pre-image of a predicate under
`Step`. `Set S.Config = S.Config → Prop` is a `CompleteLattice` (via `Pi`/`Prop` boolean algebra),
with `(· ≤ ·) = (· ⊆ ·)`, so `OrderHom (Set S.Config) (Set S.Config)` and its `.lfp`/`.gfp` are
well-typed — the foundation every modality stands on. -/

variable (S : System)

/-- **`pre S P` — the EX-preimage**: the configs with SOME `Step`-successor in `P`. The semantic
core of `EX` (the existential modal next). -/
def pre (P : Set S.Config) : Set S.Config := { s | ∃ t, S.Step s t ∧ t ∈ P }

/-- **`preAll S P` — the AX-preimage**: the configs ALL of whose successors lie in `P` (vacuously
true at a deadlocked config with no successors). The semantic core of `AX`. -/
def preAll (P : Set S.Config) : Set S.Config := { s | ∀ t, S.Step s t → t ∈ P }

/-- `pre` is monotone — the bundled `OrderHom` form (every fixpoint body uses this). -/
def preHom : Set S.Config →o Set S.Config :=
  ⟨pre S, by intro P Q hPQ s hs; obtain ⟨t, hst, ht⟩ := hs; exact ⟨t, hst, hPQ ht⟩⟩

/-- `preAll` is monotone — the bundled `OrderHom` form. -/
def preAllHom : Set S.Config →o Set S.Config :=
  ⟨preAll S, by intro P Q hPQ s hs t hst; exact hPQ (hs t hst)⟩

@[simp] theorem preHom_apply (P : Set S.Config) : preHom S P = pre S P := rfl
@[simp] theorem preAllHom_apply (P : Set S.Config) : preAllHom S P = preAll S P := rfl

/-- `pre` is monotone in `P` (the unbundled lemma, for direct ⊆-reasoning). -/
theorem pre_mono {P Q : Set S.Config} (h : P ⊆ Q) : pre S P ⊆ pre S Q := (preHom S).mono h

/-- `preAll` is monotone in `P`. -/
theorem preAll_mono {P Q : Set S.Config} (h : P ⊆ Q) : preAll S P ⊆ preAll S Q :=
  (preAllHom S).mono h

/-! ### The CTL fixpoint BODIES (bundled `OrderHom` so `.lfp`/`.gfp` apply).

Each body is an `OrderHom (Set S.Config) (Set S.Config)` parametrized by the argument predicate(s).
The monotonicity proofs lean on `pre_mono`/`preAll_mono` + monotonicity of `∪`/`∩`. -/

/-- EU body: `Φ_{EU} X = Q ∪ (P ∩ EX X)`. Its `lfp` is `E[P U Q]`. -/
def euBody (P Q : Set S.Config) : Set S.Config →o Set S.Config :=
  ⟨fun X => Q ∪ (P ∩ pre S X), by
    intro X Y hXY
    exact Set.union_subset_union_right _ (Set.inter_subset_inter_right _ (pre_mono S hXY))⟩

/-- AU body: `Φ_{AU} X = Q ∪ (P ∩ AX X)`. Its `lfp` is `A[P U Q]`. -/
def auBody (P Q : Set S.Config) : Set S.Config →o Set S.Config :=
  ⟨fun X => Q ∪ (P ∩ preAll S X), by
    intro X Y hXY
    exact Set.union_subset_union_right _ (Set.inter_subset_inter_right _ (preAll_mono S hXY))⟩

/-- EG body: `Φ_{EG} X = P ∩ EX X`. Its `gfp` is "along SOME path `P` holds forever". -/
def egBody (P : Set S.Config) : Set S.Config →o Set S.Config :=
  ⟨fun X => P ∩ pre S X, by
    intro X Y hXY; exact Set.inter_subset_inter_right _ (pre_mono S hXY)⟩

/-- AG body: `Φ_{AG} X = P ∩ AX X`. Its `gfp` is "along EVERY path `P` holds forever". -/
def agBody (P : Set S.Config) : Set S.Config →o Set S.Config :=
  ⟨fun X => P ∩ preAll S X, by
    intro X Y hXY; exact Set.inter_subset_inter_right _ (preAll_mono S hXY)⟩

/-! ## §1 — The eight CTL modalities as named `lfp`/`gfp`.

This is the standard Emerson–Clarke fixpoint characterization: `EX`/`AX` are the modal next;
`EU`/`AU`/`EF`/`AF` are LEAST fixpoints (finite reachability); `EG`/`AG` are GREATEST fixpoints
(infinite safety). `EG` as `gfp` is the branching analogue of `Temporal.Always`; `AG` is the
genuine "all paths forever". -/

/-- **`EX P`** — some successor satisfies `P` (the existential modal next). The modal primitive. -/
def EX (P : Set S.Config) : Set S.Config := pre S P

/-- **`AX P`** — all successors satisfy `P` (the universal modal next; vacuous at a deadlock). -/
def AX (P : Set S.Config) : Set S.Config := preAll S P

/-- **`EU P Q`** = `E[P U Q]` — along SOME path, `P` holds until `Q` does. `(euBody S P Q).lfp`. -/
def EU (P Q : Set S.Config) : Set S.Config := (euBody S P Q).lfp

/-- **`AU P Q`** = `A[P U Q]` — along EVERY path, `P` holds until `Q` does. `(auBody S P Q).lfp`. -/
def AU (P Q : Set S.Config) : Set S.Config := (auBody S P Q).lfp

/-- **`EF P`** = `E[⊤ U P]` — `P` is reachable along SOME path. -/
def EF (P : Set S.Config) : Set S.Config := EU S Set.univ P

/-- **`AF P`** = `A[⊤ U P]` — on EVERY path `P` eventually holds.

NOTE (DEFERRED liveness): the OPERATOR is defined and its fixpoint law (`AF_unfold`) is proved, but
the *liveness reading* of `AF` on the living cell (theorems asserting `P` is reached on every path)
is gated behind a fairness/stutter decision — see the module docstring. -/
def AF (P : Set S.Config) : Set S.Config := AU S Set.univ P

/-- **`EG P`** — along SOME path `P` holds forever. `(egBody S P).gfp`.

NOTE (DEFERRED liveness): defined with its fixpoint law (`EG_unfold`); the fairness-dependent
"some infinite fair path" reading is gated — see the module docstring. -/
def EG (P : Set S.Config) : Set S.Config := (egBody S P).gfp

/-- **`AG P`** — along EVERY path `P` holds forever (the branching invariant). `(agBody S P).gfp`. -/
def AG (P : Set S.Config) : Set S.Config := (agBody S P).gfp

/-! ### Membership unfoldings of the modal next (the `Set`-level `∈` lemmas). -/

@[simp] theorem mem_EX {P : Set S.Config} {s : S.Config} :
    s ∈ EX S P ↔ ∃ t, S.Step s t ∧ t ∈ P := Iff.rfl

@[simp] theorem mem_AX {P : Set S.Config} {s : S.Config} :
    s ∈ AX S P ↔ ∀ t, S.Step s t → t ∈ P := Iff.rfl

/-! ## §2 — The UNFOLDING (fixpoint) laws: each modality's defining recursion.

`EU`/`AU`/`EF`/`AF` unfold via `OrderHom.map_lfp`; `EG`/`AG` via `OrderHom.map_gfp`. These are the
fixpoint equations characterizing each operator. -/

/-- **`EU_unfold`**: `EU P Q = Q ∪ (P ∩ EX (EU P Q))`. From `OrderHom.map_lfp`. -/
theorem EU_unfold (P Q : Set S.Config) : EU S P Q = Q ∪ (P ∩ EX S (EU S P Q)) :=
  (euBody S P Q).map_lfp.symm

/-- **`AU_unfold`**: `AU P Q = Q ∪ (P ∩ AX (AU P Q))`. From `OrderHom.map_lfp`. -/
theorem AU_unfold (P Q : Set S.Config) : AU S P Q = Q ∪ (P ∩ AX S (AU S P Q)) :=
  (auBody S P Q).map_lfp.symm

/-- **`EF_unfold`**: `EF P = P ∪ EX (EF P)` (the `Q ∪ (univ ∩ …)` simplifies). -/
theorem EF_unfold (P : Set S.Config) : EF S P = P ∪ EX S (EF S P) := by
  -- `EF P = EU univ P` definitionally on both sides; unfold once via `EU_unfold`, drop `univ ∩`.
  show EU S Set.univ P = P ∪ EX S (EU S Set.univ P)
  conv_lhs => rw [EU_unfold S Set.univ P, Set.univ_inter]

/-- **`AF_unfold`**: `AF P = P ∪ AX (AF P)`. The branching-`◇` unfolding (operator-level;
liveness reading deferred). -/
theorem AF_unfold (P : Set S.Config) : AF S P = P ∪ AX S (AF S P) := by
  show AU S Set.univ P = P ∪ AX S (AU S Set.univ P)
  conv_lhs => rw [AU_unfold S Set.univ P, Set.univ_inter]

/-- **`EG_unfold`**: `EG P = P ∩ EX (EG P)`. From `OrderHom.map_gfp`. -/
theorem EG_unfold (P : Set S.Config) : EG S P = P ∩ EX S (EG S P) :=
  (egBody S P).map_gfp.symm

/-- **`AG_unfold`**: `AG P = P ∩ AX (AG P)`. From `OrderHom.map_gfp`. The branching
□-unfolding: "always" = "now and (next-step) always". -/
theorem AG_unfold (P : Set S.Config) : AG S P = P ∩ AX S (AG S P) :=
  (agBody S P).map_gfp.symm

/-! ## §2.1 — The induction / coinduction principles (the load-bearing reasoning rules). -/

/-- **`AG_coind` — the gfp COINDUCTION rule for `AG`.** If a candidate invariant `Inv` is
contained in `P` and is `AX`-closed (every successor of an `Inv`-config is again `Inv`), then `Inv`
proves `AG P`. This is `OrderHom.le_gfp`: an `AX`-closed sub-invariant witnesses the greatest
fixpoint. THE rule by which a one-step invariant lifts to a branching "always". -/
theorem AG_coind (P Inv : Set S.Config) (h₁ : Inv ⊆ P) (h₂ : Inv ⊆ AX S Inv) :
    Inv ⊆ AG S P :=
  (agBody S P).le_gfp (fun _ hs => ⟨h₁ hs, h₂ hs⟩)

/-- **`EG_coind` — the gfp coinduction rule for `EG`.** A candidate `Inv ⊆ P` that has,
at every point, SOME successor back in `Inv` (`Inv ⊆ EX Inv`) proves `EG P`. -/
theorem EG_coind (P Inv : Set S.Config) (h₁ : Inv ⊆ P) (h₂ : Inv ⊆ EX S Inv) :
    Inv ⊆ EG S P :=
  (egBody S P).le_gfp (fun _ hs => ⟨h₁ hs, h₂ hs⟩)

/-- **`EF_least` — the lfp INDUCTION rule for `EF`.** `EF P` is the LEAST set containing
`P` and closed under taking `pre`-predecessors: for any `U` with `P ⊆ U` and `pre S U ⊆ U`, we have
`EF P ⊆ U`. This is `OrderHom.lfp_le`. THE rule by which "`P` is reachable" reasoning bottoms out. -/
theorem EF_least (P U : Set S.Config) (h₁ : P ⊆ U) (h₂ : pre S U ⊆ U) : EF S P ⊆ U := by
  refine (euBody S Set.univ P).lfp_le ?_
  intro s hs
  rcases hs with hQ | hpre
  · exact h₁ hQ
  · exact h₂ (pre_mono S (le_refl _) hpre.2)

/-- **`AU_least` — the lfp induction rule for `AU`** (hence `AF` via `univ`): for any `U`
with `Q ⊆ U` and `(P ∩ preAll S U) ⊆ U`, we have `AU P Q ⊆ U`. -/
theorem AU_least (P Q U : Set S.Config) (h₁ : Q ⊆ U) (h₂ : (P ∩ preAll S U) ⊆ U) :
    AU S P Q ⊆ U :=
  (auBody S P Q).lfp_le (fun _ hs => hs.elim (fun hq => h₁ hq) (fun hpre => h₂ hpre))

/-! ## §3 — Monotonicity + the De Morgan DUALITY algebra (the modal algebra). -/

/-- **`EX_mono`** — `EX` is monotone in its argument. -/
theorem EX_mono {P Q : Set S.Config} (h : P ⊆ Q) : EX S P ⊆ EX S Q := pre_mono S h

/-- **`AX_mono`** — `AX` is monotone in its argument. -/
theorem AX_mono {P Q : Set S.Config} (h : P ⊆ Q) : AX S P ⊆ AX S Q := preAll_mono S h

/-- **`EF_mono`** — `EF` is monotone. -/
theorem EF_mono {P Q : Set S.Config} (h : P ⊆ Q) : EF S P ⊆ EF S Q := by
  refine EF_least S P (EF S Q) (subset_trans h ?_) ?_
  · intro s hs; rw [EF_unfold]; exact Or.inl hs
  · intro s hs; rw [EF_unfold S Q]; exact Or.inr hs

/-- **`AG_mono`** — `AG` is monotone. -/
theorem AG_mono {P Q : Set S.Config} (h : P ⊆ Q) : AG S P ⊆ AG S Q := by
  refine AG_coind S Q (AG S P) ?_ ?_
  · exact subset_trans (by rw [AG_unfold]; exact Set.inter_subset_left) h
  · intro s hs; rw [AG_unfold] at hs; exact hs.2

/-- **`EG_mono`** — `EG` is monotone. -/
theorem EG_mono {P Q : Set S.Config} (h : P ⊆ Q) : EG S P ⊆ EG S Q := by
  refine EG_coind S Q (EG S P) ?_ ?_
  · exact subset_trans (by rw [EG_unfold]; exact Set.inter_subset_left) h
  · intro s hs; rw [EG_unfold] at hs; exact hs.2

/-- **`EX_AX_dual` — the ∃/∀ next-step De Morgan duality**: `EX P = (AX Pᶜ)ᶜ`. "Some
successor in `P`" = "not (all successors in `Pᶜ`)". Genuinely classical (uses `not_forall` /
`not_not`); pinned in the classical-aware `#assert` list. -/
theorem EX_AX_dual (P : Set S.Config) : EX S P = (AX S Pᶜ)ᶜ := by
  ext s
  simp only [EX, AX, pre, preAll, Set.mem_setOf_eq, Set.mem_compl_iff, not_forall,
    not_not, exists_prop]

/-- **`AX_EX_dual`** — the mirror image: `AX P = (EX Pᶜ)ᶜ`. -/
theorem AX_EX_dual (P : Set S.Config) : AX S P = (EX S Pᶜ)ᶜ := by
  rw [EX_AX_dual, compl_compl, compl_compl]

/-- **`EF_EG_dual` — `EF P = (AG Pᶜ)ᶜ`**: "`P` is reachable along some path" =
"not (along every path, `¬P` holds forever)". The branching `◇`/`□` De Morgan dual. Genuinely
classical (uses `compl_compl`); pinned in the classical-aware `#assert` list.

PROVED by gfp/lfp uniqueness: `(AG Pᶜ)ᶜ` satisfies the `EF`-fixpoint equation and is the least
such — we show both inclusions through `EF_least`/`AG_coind` applied to complements. -/
theorem EF_EG_dual (P : Set S.Config) : EF S P = (AG S Pᶜ)ᶜ := by
  apply Set.eq_of_subset_of_subset
  · -- `EF P ⊆ (AG Pᶜ)ᶜ`: `(AG Pᶜ)ᶜ` is a pre-fixed point of the `EF` body.
    refine EF_least S P _ ?_ ?_
    · -- `P ⊆ (AG Pᶜ)ᶜ`: if `s ∈ AG Pᶜ` then `s ∈ Pᶜ`, contradicting `s ∈ P`.
      intro s hs hag
      rw [AG_unfold] at hag
      exact hag.1 hs
    · -- `pre S (AG Pᶜ)ᶜ ⊆ (AG Pᶜ)ᶜ`: if `s` has a successor outside `AG Pᶜ`, then `s ∉ AG Pᶜ`.
      intro s hs hag
      obtain ⟨t, hst, ht⟩ := hs
      rw [AG_unfold] at hag
      exact ht (hag.2 t hst)
  · -- `(AG Pᶜ)ᶜ ⊆ EF P`: contrapositive — `(EF P)ᶜ ⊆ AG Pᶜ`, i.e. `(EF P)ᶜ` is `AX`-closed in `Pᶜ`.
    intro s hs
    by_contra hef
    -- show `(EF P)ᶜ ⊆ AG Pᶜ` via coinduction, then `s ∈ AG Pᶜ` contradicts `hs`.
    have hcoind : (EF S P)ᶜ ⊆ AG S Pᶜ := by
      refine AG_coind S Pᶜ _ ?_ ?_
      · -- `(EF P)ᶜ ⊆ Pᶜ`: `P ⊆ EF P`.
        intro x hx hP; exact hx (by rw [EF_unfold]; exact Or.inl hP)
      · -- `(EF P)ᶜ ⊆ AX (EF P)ᶜ`: a successor in `EF P` would put `x` in `EF P`.
        intro x hx t hst ht
        exact hx (by rw [EF_unfold]; exact Or.inr ⟨t, hst, ht⟩)
    exact hs (hcoind hef)

/-! ## §4 — The CROSS-CHECK: CTL `EF`/`AG` ≡ `Execution.Reachable` (ties CTL to the keystones).

`EF` is the LEAST-fixpoint "reachable `P`"; `Execution.Run`/`Reachable` is the INDUCTIVELY-defined
reachability. They must coincide — and `AG` dually is the relational invariant "holds at every
reachable config". These two theorems weld the branching calculus onto `Execution.lean`. -/

/-- **`EF_iff_reachable` — the lfp `EF` ≡ inductive reachability.**
`s ∈ EF S P ↔ ∃ t, Reachable S s t ∧ t ∈ P`. Forward: the reachability-set `{s | ∃ t, Reachable …}`
is a pre-fixed point of the `EF` body, so `EF P ⊆` it (`EF_least`). Backward: induction on `Run`,
unfolding `EF` one step per edge. -/
theorem EF_iff_reachable (P : Set S.Config) (s : S.Config) :
    s ∈ EF S P ↔ ∃ t, Execution.Reachable S s t ∧ t ∈ P := by
  constructor
  · -- forward: `{s | ∃ t, Reachable s t ∧ t ∈ P}` is closed; `EF` is the least such.
    have hclosed : EF S P ⊆ { s | ∃ t, Execution.Reachable S s t ∧ t ∈ P } := by
      refine EF_least S P _ ?_ ?_
      · -- `P ⊆`: reach `s` itself (`Run.refl`).
        intro x hx; exact ⟨x, Execution.Run.refl x, hx⟩
      · -- `pre …`: prepend the one step to the witnessed run.
        intro x hx
        obtain ⟨y, hxy, t, hreach, ht⟩ := hx
        exact ⟨t, Execution.Run.step hxy hreach, ht⟩
    exact fun hs => hclosed hs
  · -- backward: induct on the reachability run.
    rintro ⟨t, hreach, ht⟩
    induction hreach with
    | refl x => rw [EF_unfold]; exact Or.inl ht
    | step hxy _ ih => rw [EF_unfold]; exact Or.inr ⟨_, hxy, ih ht⟩

/-- **`AG_iff_all_reachable` — the gfp `AG` ≡ relational invariance.**
`s ∈ AG S P ↔ ∀ t, Reachable S s t → t ∈ P`. The greatest-fixpoint "always on every path" is
exactly "`P` holds at every reachable config". Forward: `AG`-membership transports along a `Run` by
unfolding (`Run`-induction). Backward: `{s | ∀ t, Reachable s t → t ∈ P}` is `AX`-closed in `P`, so
`AG_coind` applies. -/
theorem AG_iff_all_reachable (P : Set S.Config) (s : S.Config) :
    s ∈ AG S P ↔ ∀ t, Execution.Reachable S s t → t ∈ P := by
  constructor
  · -- forward: transport `AG`-membership along the run.
    intro hag t hreach
    -- generalize: for any run `s ⟶* t`, `s ∈ AG P → t ∈ P`.
    have key : ∀ {a b : S.Config}, Execution.Run S a b → a ∈ AG S P → b ∈ P := by
      intro a b hr
      induction hr with
      | refl x => intro hx; rw [AG_unfold] at hx; exact hx.1
      | step hxy _ ih =>
          intro hx
          rw [AG_unfold] at hx
          exact ih (hx.2 _ hxy)
    exact key hreach hag
  · -- backward: the relational-invariant set is `AX`-closed in `P` ⇒ `AG_coind`.
    intro hinv
    have hcoind : { s | ∀ t, Execution.Reachable S s t → t ∈ P } ⊆ AG S P := by
      refine AG_coind S P _ ?_ ?_
      · -- `⊆ P`: take `t = s` (reflexive run).
        intro x hx; exact hx x (Execution.Run.refl x)
      · -- `AX`-closed: a successor `t` inherits the invariant (prepend the edge).
        intro x hx t hxt u hreach
        exact hx u (Execution.Run.step hxt hreach)
    exact hcoind hinv

/-! ## §5 — Instantiation on the REAL executor: the bridge to the LTL layer.

`Temporal.livingSystem = Boundary.inducedSystem livingCellA` is the branching transition
system of the 46-effect executor (one config, many `ConservingForest` successors). Here the
branching `AG` is welded to the linear `Temporal.Always`. -/

open Dregg2.Exec in
/-- **`livingAG_iff_temporalAlways` — THE BRIDGE: branching `AG` ≡ linear `□` on the living
cell.** For a `StepInvariant`-preserved predicate `Good` holding at `s`, membership in
`AG livingSystem {s' | Good s'}` is equivalent to `Temporal.Always Good` along EVERY schedule. The
branching "always on every path" and the linear "globally along every schedule" COINCIDE on the
real executor — via `AG_iff_all_reachable` (CTL side) chained with `Temporal.always_iff_reachable`
(LTL side). This is the theorem tying Track B (branching) to the existing Track-Temporal (linear)
layer. -/
theorem livingAG_iff_temporalAlways (Good : RecChainedState → Prop)
    (hpres : Execution.StepInvariant Temporal.livingSystem Good)
    (s : RecChainedState) (hinit : Good s) :
    s ∈ AG Temporal.livingSystem {s' | Good s'} ↔ ∀ sched, Temporal.Always Good s sched :=
  -- `AG`-membership ≡ "Good at every reachable config" (CTL side); `always_iff_reachable` (LTL side)
  -- equates that with "□ along every schedule". Chain the two iffs.
  (AG_iff_all_reachable Temporal.livingSystem {s' | Good s'} s).trans
    (Temporal.always_iff_reachable Good hpres s hinit).symm

open Dregg2.Exec in
/-- **`livingAG_conserved` — conservation holds `AG` on the REAL branching executor.** The
per-asset conservation badge `cellObsA` equals its initial value along EVERY path of the branching
induced system: `s ∈ AG livingSystem {s' | cellObsA s' = cellObsA s}`. The CTL reading of
`Temporal.always_conserved`, discharged by `AG_coind` with the conservation invariant (the one-step
preservation is `cellObsA_next`). The branching analogue of the flagship LTL safety. -/
theorem livingAG_conserved (s : RecChainedState) :
    s ∈ AG Temporal.livingSystem {s' | cellObsA s' = cellObsA s} := by
  -- coinduct with the invariant `Inv = {s' | cellObsA s' = cellObsA s}` itself (it is `AX`-closed).
  refine AG_coind Temporal.livingSystem {s' | cellObsA s' = cellObsA s}
    {s' | cellObsA s' = cellObsA s} (le_refl _) ?_ ?_
  · -- `Inv` is `AX`-closed: a `livingSystem` successor `t = cellNextA s' cf` keeps the badge.
    intro s' hs' t hst
    obtain ⟨cf, rfl⟩ := hst
    show cellObsA (cellNextA s' cf) = cellObsA s
    rw [cellObsA_next]; exact hs'
  · -- `s` is in `Inv` (reflexivity of the badge equality).
    show cellObsA s = cellObsA s; rfl

/-! ## §6 — NON-VACUITY / TEETH: branching separates `EX`/`AX` and `EF`/`AF`.

The whole empirical content of branching time is that "some path" ≠ "every path". We prove it on a
hand-controlled finite system. `branchSys`: states `Fin 3`, edges `0 → 1`, `0 → 2`, `1 → 1`,
`2 → 2`. From `0`, the target `{1}` is reached on the path `0 → 1` (so `0 ∈ EX/EF {1}`) but NOT on
the path `0 → 2 → 2 → …` (so `0 ∉ AX/AF {1}` — `2` is a `{1}`-free trap). Decidable, finite. -/

/-- The explicit (decidable) edge relation of the 3-state branching witness:
`0 → 1`, `0 → 2`, `1 → 1`, `2 → 2`. -/
def branchStep (a b : Fin 3) : Prop :=
  (a = 0 ∧ b = 1) ∨ (a = 0 ∧ b = 2) ∨ (a = 1 ∧ b = 1) ∨ (a = 2 ∧ b = 2)

instance : DecidablePred (fun p : Fin 3 × Fin 3 => branchStep p.1 p.2) := by
  intro p; unfold branchStep; infer_instance

instance (a b : Fin 3) : Decidable (branchStep a b) := by unfold branchStep; infer_instance

/-- The 3-state branching witness system. An `abbrev` (reducible) so `branchSys.Config` unfolds to
`Fin 3` during instance synthesis — numerals and `decide` resolve directly against `Fin 3`. -/
abbrev branchSys : System := { Config := Fin 3, Step := branchStep }

/-- The target predicate: holds at `s₁ = 1` only. -/
def tgt : Set (Fin 3) := {1}

/-- `x ∈ tgt ↔ x = 1` — unfold the singleton (so `decide` can settle `Fin 3` membership). -/
@[simp] theorem mem_tgt {x : Fin 3} : x ∈ tgt ↔ x = 1 := Set.mem_singleton_iff

/-- `2 ∉ tgt` (the `s₂` trap is outside the target) — the load-bearing decidable fact. -/
theorem two_not_mem_tgt : (2 : Fin 3) ∉ tgt := by rw [mem_tgt]; decide

/-- `0 ∉ tgt` (the branching root is outside the target). -/
theorem zero_not_mem_tgt : (0 : Fin 3) ∉ tgt := by rw [mem_tgt]; decide

/-- `0` has a successor (`1`) in `tgt` — so `0 ∈ EX tgt`. -/
theorem mem_EX_branch : (0 : Fin 3) ∈ EX branchSys tgt := by
  refine ⟨1, ?_, ?_⟩
  · left; exact ⟨rfl, rfl⟩
  · rfl

/-- `0` does NOT have all successors in `tgt` — the successor `2 ∉ tgt`, so `0 ∉ AX tgt`. -/
theorem not_mem_AX_branch : (0 : Fin 3) ∉ AX branchSys tgt := by
  intro h
  -- `2` is a successor of `0` (the second edge), but `2 ∉ {1}`.
  exact two_not_mem_tgt (h 2 (by right; left; exact ⟨rfl, rfl⟩))

/-- **TEETH 1 — `EX_ne_AX`: branching time separates the existential and universal next.**
On `branchSys`, `EX tgt ≠ AX tgt`, witnessed at `s₀`: `0 ∈ EX tgt` (the `0 → 1` branch) but
`0 ∉ AX tgt` (the `0 → 2` branch escapes `tgt`). This is FALSE in any deterministic/linear system
and is the defining content of branching. -/
theorem EX_ne_AX : EX branchSys tgt ≠ AX branchSys tgt := by
  intro h
  exact not_mem_AX_branch (h ▸ mem_EX_branch)

/-- `0 ∈ EF tgt` — the path `0 → 1` reaches `tgt`. Via `EF_iff_reachable`. -/
theorem mem_EF_branch : (0 : Fin 3) ∈ EF branchSys tgt := by
  rw [EF_iff_reachable]
  refine ⟨(1 : Fin 3), ?_, rfl⟩
  have hstep : branchSys.Step (0 : Fin 3) (1 : Fin 3) := by left; exact ⟨rfl, rfl⟩
  exact Execution.Run.step hstep (Execution.Run.refl (S := branchSys) (1 : Fin 3))

/-- `{1}` is a fixed point of the `AF` body on `branchSys` (`tgt ∪ AX tgt = tgt`), hence a
pre-fixed point — the certificate that the least fixpoint `AF tgt` is contained in `{1}`. -/
theorem AF_branch_prefixed : tgt ∪ AX branchSys tgt ⊆ tgt := by
  intro s hs
  rcases hs with h1 | hax
  · exact h1
  · -- `s ∈ AX tgt`: all successors in `{1}`. The only state with all-successors-in-`{1}` is `1`.
    -- (`0` has successor `2 ∉ {1}`; `2` has successor `2 ∉ {1}`; `1` has only successor `1 ∈ {1}`.)
    show (s : Fin 3) ∈ tgt
    by_contra hne
    -- `s ≠ 1`. Both remaining states have a successor escaping `{1}`: `0 → 2` and `2 → 2`.
    match s, hax with
    | 0, hax => exact two_not_mem_tgt (hax 2 (by right; left; exact ⟨rfl, rfl⟩))
    | 1, _    => exact hne rfl
    | 2, hax => exact two_not_mem_tgt (hax 2 (by right; right; right; exact ⟨rfl, rfl⟩))

/-- `0 ∉ AF tgt` — the trap path `0 → 2 → 2 → …` never reaches `tgt`. Proved by `AU_least`: `AF tgt`
is contained in the pre-fixed point `{1}` (`AF_branch_prefixed`), which excludes `0`. -/
theorem not_mem_AF_branch : (0 : Fin 3) ∉ AF branchSys tgt := by
  have hle : AF branchSys tgt ⊆ tgt := by
    -- `AF tgt = AU univ tgt`; its body's pre-fixed point is `tgt` (since `tgt ∪ AX tgt = tgt`).
    refine AU_least branchSys Set.univ tgt tgt (le_refl _) ?_
    intro s hs
    -- `hs : s ∈ univ ∩ preAll tgt`; the `AX`-half is the second `AF_branch_prefixed` disjunct.
    exact AF_branch_prefixed (Or.inr hs.2)
  intro h0
  -- `hle h0 : (0 : Fin 3) ∈ tgt`, i.e. `0 = 1` — false.
  exact zero_not_mem_tgt (hle h0)

/-- **TEETH 2 — `EF_ne_AF`: branching time separates existential and universal eventually.**
On `branchSys`, `EF tgt ≠ AF tgt`, witnessed at `s₀`: `0 ∈ EF tgt` (the `0 → 1` path reaches it)
but `0 ∉ AF tgt` (the `0 → 2 → 2 → …` path is a `tgt`-free trap). The headline branching teeth:
"reachable on SOME path" is strictly weaker than "reached on EVERY path". -/
theorem EF_ne_AF : EF branchSys tgt ≠ AF branchSys tgt := by
  intro h
  exact not_mem_AF_branch (h ▸ mem_EF_branch)

/-- The "stays at `0`" predicate as an explicit `Set branchSys.Config` (no self-loop at `0`). -/
def atZero : Set branchSys.Config := {(0 : Fin 3)}

/-- `x ∈ atZero ↔ x = 0` — unfold the singleton (so `decide` settles `Fin 3` membership). -/
@[simp] theorem mem_atZero {x : Fin 3} : x ∈ atZero ↔ x = 0 := Set.mem_singleton_iff

/-- **TEETH 3 — `EG_not_vacuous`: `EG` is not the whole space.** `s₀ ∉ EG branchSys {0}`:
`0` has no self-loop (its only successors are `1`, `2`, both `∉ {0}`), so there is no infinite path
staying in `{0}`. Shows `EG` rejects. -/
theorem EG_not_vacuous : (0 : Fin 3) ∉ EG branchSys atZero := by
  intro h
  rw [EG_unfold branchSys atZero] at h
  -- `h.2 : 0 ∈ EX atZero` — some successor of `0` is in `{0}`; but successors are `1`,`2`.
  obtain ⟨t, hst, htEG⟩ := h.2
  -- `htEG : t ∈ EG atZero`; unfold once more to get `t ∈ atZero` (its first conjunct).
  have ht : t ∈ atZero := by rw [EG_unfold branchSys atZero] at htEG; exact htEG.1
  rw [mem_atZero] at ht
  -- `ht : t = 0`; but `hst : branchStep 0 t` forces `t ∈ {1,2}`.
  rcases hst with ⟨_, hb⟩ | ⟨_, hb⟩ | ⟨ha, _⟩ | ⟨ha, _⟩
  · rw [hb] at ht; exact absurd ht (by decide)   -- `t = 1`, but `ht : t = 0`
  · rw [hb] at ht; exact absurd ht (by decide)   -- `t = 2`, but `ht : t = 0`
  · exact absurd ha (by decide)                  -- edge `1 → 1` has source `1 ≠ 0`
  · exact absurd ha (by decide)                  -- edge `2 → 2` has source `2 ≠ 0`

/-- The "in `{0,1}`" predicate as an explicit `Set branchSys.Config`. -/
def inZeroOne : Set branchSys.Config := {x : Fin 3 | x = 0 ∨ x = 1}

/-- **TEETH 4 — `AG_not_vacuous`: `AG ≠ univ`.** `s₀ ∉ AG branchSys {0,1}`: the reachable
config `2 ∉ {0,1}` (via the run `0 → 2`), so the branching invariant fails. Uses
`AG_iff_all_reachable` + the explicit escaping run. The branching analogue of
`Temporal.recAbsStep_not_vacuous`. -/
theorem AG_not_vacuous : (0 : Fin 3) ∉ AG branchSys inZeroOne := by
  intro hag
  -- transport `AG`-membership to "holds at every reachable config".
  have h := (AG_iff_all_reachable branchSys inZeroOne 0).mp hag
  -- `2` is reachable from `0` (the `0 → 2` edge), but `2 ∉ {0,1}`.
  have hstep : branchSys.Step (0 : Fin 3) (2 : Fin 3) := by right; left; exact ⟨rfl, rfl⟩
  have hreach : Execution.Run branchSys (0 : Fin 3) (2 : Fin 3) :=
    Execution.Run.step hstep (Execution.Run.refl (S := branchSys) (2 : Fin 3))
  have h2 : (2 : Fin 3) = 0 ∨ (2 : Fin 3) = 1 := h (2 : Fin 3) hreach
  rcases h2 with h2 | h2 <;> exact absurd h2 (by decide)

/-! ### The SECURITY teeth on the REAL executor — `AG` rejects a false safety.

`livingAG_conserved` (§5) is the positive non-vacuity (a genuine real-executor `AG`). The negative
teeth: `AG` does NOT hold of an arbitrary predicate — a `P` that excludes the start state cannot be
`AG`, because `AG P ⊆ P` (the `AG_unfold` first conjunct). We instantiate with the strictly-
decreasing-log predicate, which excludes `s` itself. -/

open Dregg2.Exec in
/-- **TEETH 5 — `livingAG_log_decrease_rejected`: `AG` has teeth on the real executor.**
The "log strictly shorter than start" predicate is NOT `AG` from `s`, because it FAILS at `s`
itself (`s.log.length < s.log.length` is false) and `AG P ⊆ P`. Demonstrates the branching `AG` is
a genuine constraint on the 46-effect executor, not satisfied by an arbitrary safety predicate. -/
theorem livingAG_log_decrease_rejected (s : RecChainedState) :
    s ∉ AG Temporal.livingSystem {s' | s'.log.length < s.log.length} := by
  intro h
  rw [AG_unfold] at h
  -- `h.1 : s ∈ {s' | s'.log.length < s.log.length}`, i.e. `s.log.length < s.log.length` — false.
  exact absurd h.1 (Nat.lt_irrefl _)

/-! ## §7 — Axiom-hygiene tripwires.

Every keystone is pinned. The two classical De Morgan duals (`EX_AX_dual`, `EF_EG_dual`,
which use `not_forall`/`compl_compl`) and `AX_EX_dual` (derived from `EX_AX_dual`) legitimately use
`Classical.choice` and are listed in the classical-aware namespace pin's `except` clause — exactly
as `Temporal.not_always_iff_eventually_not` is. The CORE fixpoint calculus is kernel-triple clean
(`Classical.choice` enters only via mathlib's `sInf`/`sSup` on `Set`, unavoidable and already
present in `Temporal.lean`). -/

#assert_axioms pre_mono
#assert_axioms preAll_mono
#assert_axioms EU_unfold
#assert_axioms AU_unfold
#assert_axioms EF_unfold
#assert_axioms AF_unfold
#assert_axioms EG_unfold
#assert_axioms AG_unfold
#assert_axioms AG_coind
#assert_axioms EG_coind
#assert_axioms EF_least
#assert_axioms AU_least
#assert_axioms EX_mono
#assert_axioms AX_mono
#assert_axioms EF_mono
#assert_axioms AG_mono
#assert_axioms EG_mono
#assert_axioms EF_iff_reachable
#assert_axioms AG_iff_all_reachable
#assert_axioms livingAG_iff_temporalAlways
#assert_axioms livingAG_conserved
#assert_axioms EX_ne_AX
#assert_axioms EF_ne_AF
#assert_axioms EG_not_vacuous
#assert_axioms AG_not_vacuous
#assert_axioms livingAG_log_decrease_rejected
-- The De Morgan duals are classical (`not_forall` / `compl_compl` ⇒ `Classical.choice`), but still
-- within the standard kernel triple {propext, Classical.choice, Quot.sound} — they pin clean.
#assert_axioms EX_AX_dual
#assert_axioms AX_EX_dual
#assert_axioms EF_EG_dual

-- Module-wide pin: EVERY theorem under the namespace is kernel-clean (catches any future drift). No
-- `except` clause is needed — every keystone, including the classical duals, stays within the
-- standard kernel triple (`Classical.choice` is permitted, exactly as in `Temporal.lean`).
#assert_namespace_axioms Dregg2.Proof.CTL

/-! ## Non-vacuity guards — the branching separation on the finite witness.

The `Fin 3` branching system is fully decidable: `0` is in the existential modalities but not the universal ones. -/

#guard (decide (∃ t : Fin 3, branchStep 0 t ∧ t = (1 : Fin 3)))
#guard (decide (∀ t : Fin 3, branchStep 0 t → t = (1 : Fin 3)) == false)
#guard (decide (∃ t : Fin 3, branchStep 0 t ∧ ¬ (t = (1 : Fin 3))))

end Dregg2.Proof.CTL
