val _ = load "jwtRung3Theory"; val _ = load "jwtBytesBridgeTheory";
open jwtRung3Theory jwtBytesBridgeTheory;
fun tag th = let val (o_,a)=Tag.dest_tag (Thm.tag th) in "[oracles: "^String.concatWith "," o_^"] [axioms: "^String.concatWith "," a^"]" end;
val _ = print ("AAA backbone jwt_rung3_native = "^tag jwt_rung3_native^"\n");
val _ = print ("AAA linkA jwt_decisioncore_refines_spec = "^tag jwt_decisioncore_refines_spec^"\n");
val _ = print ("AAA faithful jwtIf_faithful = "^tag jwtIf_faithful^"\n");
val _ = print ("AAA L2 jwt_compile_prog_native = "^tag jwt_compile_prog_native^"\n");
val _ = print ("AAA theory-axioms jwtRung3 = "^Int.toString(length(axioms "jwtRung3"))^"\n");
val _ = print ("AAA theory-axioms jwtBytesBridge = "^Int.toString(length(axioms "jwtBytesBridge"))^"\n");
val c = concl jwtIf_faithful; val (lhs,rhs)=dest_eq c;
fun qn t = let val {Thy,Name,...}=dest_thy_const t in Thy^"$"^Name end;
val progn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="jwtProg") lhs);
val ifn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="jwtIf") rhs);
val _ = print ("AAA faithful-distinct prog="^progn^" if="^ifn^" DISTINCT="^Bool.toString(progn<>ifn)^"\n");
val bc = concl jwt_rung3_native; val (ante,conc)=dest_imp bc;
val _ = print ("AAA backbone antecedent-conjuncts = "^Int.toString(length(strip_conj ante))^"\n");
val _ = print ("AAA backbone concl-mentions-jwtProg = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="jwtProg")) conc)^"\n");
val _ = print ("AAA backbone ante-mentions-jwtBytes = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="jwtBytes")) ante)^"\n");
