-- Dregg2: the dregg2 vat model — candidate-independent core + coinductive boundary.
--
-- Candidate-independent modules (shared across all dregg2 candidates):
--   * Dregg2.Core              — symmetric-monoidal cells/turns + Σ_k conservation
--   * Dregg2.Laws              — Predicate ⊣ Witness Galois connection + verify/find seam
--   * Dregg2.Authority.Positional — the l4v integrity lift / vat-boundary law template
--   * Dregg2.Confluence        — I-confluence / tier-1 eligibility (third judgement)
--
-- The Boundary/Soundness module is candidate-dependent: dregg2 uses the coinductive
-- (▶-guarded bisimulation) shape (see docs/rebuild/dregg2.md §1.3/§8).
import Dregg2.Tactics       -- shared proof automation
import Dregg2.Core
import Dregg2.Resource
import Dregg2.Resource.TokenAutonomy   -- idempotent resources (capability lattice / GSet) admit no sound retract into a cancellative foreign token: no_substitution_of_idempotent + gset_not_substitutable_by_int; cancellative payment does substitute (honest discriminator); #assert_axioms-clean, #eval non-vacuity
import Dregg2.Laws
import Dregg2.Authority.Positional
import Dregg2.Authority.Caveat   -- keys-as-caps token layer (biscuit/macaroon/caveat/discharge): attenuation chain + attenuate_narrows + token-as-Verify bridge + #eval
import Dregg2.Confluence
import Dregg2.Confluence.CRDT   -- CRDT instance catalog: G/PN-counter, G/OR-set, LWW register (each a MergeState + invariant), bounded-counter non-confluence + escrow/quota-partition refinement; #assert_axioms-clean
import Dregg2.Boundary
import Dregg2.StepCamera     -- step-indexed Iris camera (higher-order resources; shares Boundary's ▶)
import Dregg2.JointTurn      -- cross-cell ⊗ : equalizer + CG-2 pullback + CG-5 aggregate, binding-as-hypothesis
import Dregg2.Finality       -- judgement 2: the 4-tier finality lattice + cross-tier join
import Dregg2.Privacy        -- field / value (Pedersen) / graph (stealth+nullifier) privacy tiers
import Dregg2.Coordination   -- MPST global type G → projection → protocol-cell; deadlock-freedom
import Dregg2.Projection     -- cand-D choreography front-end: blue/red split + epp_correspondence (= boundary_law at two altitudes)
import Dregg2.Await          -- algebraic effects + one-shot continuations; turn-as-rollback-handler
import Dregg2.Liveness       -- GC-as-cell-liveness; lease-expiry; cross-vat cycle leak (impossibility)
import Dregg2.Upgrade        -- anti-brick set_program: AIR_VERSION pin + signature fallback
import Dregg2.Execution      -- userspace programs: configurations, runs, invariant-preservation
import Dregg2.CryptoKernel    -- §8 portal: crypto ops as an uninterpreted interface (Lean⟷Rust); verify/find seam instantiated; cross-vat bridge closed
import Dregg2.PrivacyKernel   -- privacy realized over the portal: committed_conservation + nullifier anti-double-spend via the interface laws
-- ─── The 3-layer CryptoKernel split (docs/rebuild/PHASE-CRYPTOKERNEL.md) ───
import Dregg2.Crypto.Primitives      -- layer A: CryptoPrimitives (Poseidon2, Pedersen commit+commit_hom, nullifier); collisionHard/binding/unlinkable as Prop carriers (not idealized hash_inj)
import Dregg2.Crypto.Merkle          -- §8 discharge #1: CircuitIR + merkleCircuit + merkle_bridge (Satisfies ↔ MerkleMembers, both directions; path-recomposition sound and complete, no primitive seam)
import Dregg2.Crypto.VerifierKernel  -- layer B: verify defined as circuit-satisfiable; merkle_verify_sound derived (accept ⇒ membership, given the STARK extractable carrier) — the §8 verify-law, derived not assumed
import Dregg2.Crypto.PredicateKernel -- layer C: per-kind KindObligation (statement+relation+Dial floor); merkle_registry_cascade (registry_sound ∘ verify_sound) + merkle_dial_wired (EpistemicDial pinned to the Merkle verifier at the acceptanceOnly ZK floor)
import Dregg2.Crypto.PortalFloor      -- 8 §8 @[extern] crypto-portal floor (post-cutover TCB): SignatureKernel(ed25519)/VerifierKernel(STARK)/PedersenKernel(DLog+commit_hom)/Poseidon2Kernel/Blake3Kernel/NullifierKernel/SealKernel(AEAD+X25519)/MacKernelE(HMAC); each = @[extern] oracle + soundness Prop carrier + *_floor_sound taking the carrier as an explicit hypothesis; Reference instances discharge carriers True only in toy ℤ/ℕ (non-vacuity); #assert_axioms-clean
import Dregg2.World           -- sibling portal: network/clock/randomness oracle for consensus; quorum finality derived + Byzantine/GST OPEN
import Dregg2.Exec.Value      -- Preserves data substrate (dregg2 §5): name-keyed records over a Schema; type-directed flatten with proved fixed width (circuit-over-records foundation)
import Dregg2.Exec.Program    -- RecordProgram structure-map over records (mirrors dregg1 cell/program.rs): StateConstraint catalog + Cases/TransitionGuard dispatch + default-deny; Heyting fragment + #eval
import Dregg2.Exec.Cell        -- the living coinductive cell: cexec as a Boundary.TurnCoalg; livingCell_sound = bisimulation-to-golden-oracle; checkpoint/replay as theorems
import Dregg2.Exec.CellReal    -- coinductive living cell over the real per-asset executor: livingCellA_sound = bisimilar to the per-asset conservation oracle forever; livingCellA_obs_invariant = no drift along the unbounded trajectory; livingCellA_supply_disclosed = mint/burn boundary is disclosed (no hidden leak)
import Dregg2.Exec.CellConfine   -- livingCellA_confinement: with a fixed authority ceiling U and initially-confined kernel, every held cap's authority stays ⊆ U forever — coinductive lift of Authority.Positional.confinement_preserved onto the real executor
import Dregg2.Exec.CellNullifier -- livingCellA_no_double_spend: any spent nullifier stays spent at every index forever (registry grow-only); a non-conservation safety on the spent-note set, dual to conservation's equality
import Dregg2.Exec.CellCommit    -- livingCellA_commitments_persist: published commitments persist at every index of the unbounded trajectory (grow-only registry); structural dual of the conservation frame
import Dregg2.Exec.Durability    -- write-ahead log over the real executor: wal_crash_recovery_sound (recover∘crash = live) + wal_torn_write_no_lost_commit + durTraj_recoverable (recovery succeeds along any unbounded turn stream)
import Dregg2.Exec.CellCarry    -- livingCellA_carries: any predicate `Good` preserved by one step holds along the entire unbounded trajectory; app authors supply a one-step proof and get "holds forever" free. Conservation is the trivial instance; livingCellA_logMono (log is append-only forever) is the demo instance. #assert_axioms-clean; #eval non-vacuity
import Dregg2.Exec.VatBoundary -- vat-boundary authority law on the living cell: intra-vat=authorizedB (Integrity.intra) / cross-vat=token discharges (Integrity.cross); unifies Cell+Caveat+Authority + #eval
import Dregg2.Exec.Kernel     -- executable kernel (Design-Spec layer): exec checks conservation+authority, fail-closed + #eval
import Dregg2.Exec.Generators -- mint/burn conservation generators (mint_delta/burn_delta)
import Dregg2.Exec.Caps        -- capability ops (grant/attenuate/derive/revoke/invoke) + integrity bridge
import Dregg2.Exec.Unified      -- unified KernelOp + step: conservation (step_delta) + ledger
import Dregg2.Exec.StepComplete -- step-completeness spine: cexec attests all 4 StepInv conjuncts; conservation_step realized; end-to-end soundness
import Dregg2.Exec.RecordKernel -- concrete cell: KernelState's bal:ℤ lifted to a content-addressed Value record; recKExec_conserves/recKExec_authorized/recCexec_attests proved over the named `balance` field (#assert_axioms-clean)
import Dregg2.Exec.FFI         -- @[export] scalar + record-cell entries → the Lean⟷Rust cascade beachhead (Rust hosts the compiled kernel; PoC round-trips)
import Dregg2.Exec.CodecRoundtrip -- parse∘encode roundtrip theorem (number/digest/string/lit/flag/enum/scalar-value/bal-entry); removes those codec primitives from the Lean-side TCB; #assert_axioms-clean
import Dregg2.Circuit          -- circuit-from-Lean: CCS IR + bridge (satisfied kernelCircuit ↔ fullStepInv); verify-law derived, not assumed
import Dregg2.Exec.CellProgram -- CellProgram DSL = executable coalgebra structure-map; denote_conserves
import Dregg2.Proof.Refine    -- Exec ⊑ Abstract: conservation + integrity-intra refinement, simulation diagram OPEN
-- Executable protocols (concrete, computable):
import Dregg2.Protocol.Transfer  -- two-cell atomic token transfer + payment-channel run; conservation/CG-5/atomicity proved + #eval
import Dregg2.Protocol.Workflow  -- authenticated, capability-gated, attested multi-party workflow; all guarantees proved + #eval
-- ─── Living-cell growth: additional safety and authority slices ───
import Dregg2.Authority.Discharge   -- discharge = the await authority-face: admits_mono_discharge (resolves forward, never un-resolves)
import Dregg2.Authority.CDT          -- capability-derivation-tree spine: path_attenuates (authority shrinks down any derivation chain) + CDT≡biscuit bridge to Caveat
import Dregg2.Authority.BiscuitGraph -- Track F: the biscuit PUBLIC-KEY delegation chain (what CDT abstracts away) — offline attenuation via a signed block chain; biscuit_narrows (leaf rights ⊆ root, mirrors path_attenuates) + amplifying/forged-block teeth; SigChecker = §8 SignatureKernel carrier (unforgeability stays §8, never a Lean law)
import Dregg2.Authority.Intent       -- intent = the ∃-resolver / inverse-vat-boundary await face: intent_fill_verifies (soundness-by-verification vs adversarial matcher); FIND stays undecidable/OPEN
import Dregg2.Exec.MultiAsset        -- multi-asset conservation: maExec_conserves_per_asset (per-asset Σ_k) + camera-FPU bridge
import Dregg2.Exec.RecordCell        -- RecordProgram as the structure-map on a record cell: recExec_admitted (nothing commits the program rejects)
import Dregg2.Exec.JointCell         -- executable bilateral JointTurn: joint_cg5_conserves (cross-side conservation, no global ledger) + binding-as-hypothesis
import Dregg2.Exec.CrossCaveat       -- cross-cell state caveats as a further equalizer on the joint turn: crossCaveat_sound = CG-5 ∧ CG-2-equalizer (SharedBinding) ∧ φ; caveated_check_eq_use = no TOCTOU; crossCaveat_rejects + covenant_rejects_high (teeth); cost is the Agreement dial (free single-machine, blocking distributed)
import Dregg2.Exec.CellFinality      -- finality tier on the cell: commit_at_join (max) + I-confluence tier-1 eligibility gate (enforced, not prose)
import Dregg2.Exec.CellPrivacy       -- value-rib: committed_transfer_conserves (conservation over Pedersen commitments / hidden amounts)
import Dregg2.Exec.CellUpgrade       -- anti-brick upgrade turn: execUpgrade_never_bricks + stale→owner-signature fallback
import Dregg2.Exec.NullifierCell     -- nullifier set as an I-confluent tier-1-safe cell: spend_no_double_spend + balance≥0 NOT tier-1
import Dregg2.Exec.CellLiveness      -- GC = cell-liveness: death_is_timed_out (lease-expiry; death never decided) + cross-vat-cycle impossibility
-- ─── Storage-as-cell-programs + verification key layer ───
import Dregg2.Exec.Factory          -- FactoryDescriptor: constructor_transparency (a factory mints cells carrying exactly its contract)
import Dregg2.Authority.VerificationKey -- content-addressed circuit identity (mirrors dregg1's canonical_vk_v2): proof_binds_current_vk + proved_state + ChildVkStrategy; §8 collision-resistance kept as an oracle hypothesis
import Dregg2.Exec.CapInbox          -- CapInbox cell-program pattern: inbox_fifo (tail≤head, cursors monotone) + sender-auth via the token layer
import Dregg2.Exec.PubSubTopic       -- PubSubTopic cell-program pattern: pubsub_append_only (log grows, cursors only forward)
import Dregg2.Exec.BlindedQueue      -- BlindedQueue (commitments-in/nullifiers-out): blinded_no_double_spend + consume_needs_verify (§8 oracle)
import Dregg2.Exec.RelayOperator     -- RelayOperator (bonded relay): bond_floor_held + bond_decrease_needs_dispute + quota_enforced
-- ─── Predicate registry / algebraic effects / receipt chain / verifiable credentials ───
import Dregg2.Authority.Predicate     -- verify/find predicate registry: registry_sound + adversarial_find_cannot_forge (matcher untrusted, verifier TCB)
import Dregg2.Exec.Effect             -- algebraic effects as turns: conservation_of_effects + disclosed_non_conservation + exhaustive linearity
import Dregg2.Exec.Receipt            -- per-cell WitnessedReceipt chain: chain_tamper_evident (HInj/HFresh hyps) + cexec_appends_receipt
import Dregg2.Authority.Credential    -- verifiable credentials as keys-as-caps: credential_verifies_iff_issued_and_not_revoked + revoke_blocks_verify + revocation no-loss I-confluence; §8 attestation = oracle
import Dregg2.Exec.RecordCellLive     -- Value/RecordProgram cell as a real Boundary.TurnCoalg: recCexec_attests (4-conjunct step-completeness) + recReplay_preserves_sumEquals (conservation over name-keyed records) + stepComplete_preserves instance; #assert_axioms-clean
import Dregg2.Exec.CellRuntime        -- OS-level cell runtime theorems: checkpoint_restore_roundtrip + replay_deterministic_run + replayFrom_conserves + time_travel_fork (two admissible diverging suffixes from one snapshot) over both the ℤ-ledger and name-keyed record cell; #assert_axioms-clean; #eval non-vacuity
-- ─── Proof infrastructure: conservation library, tactics, consensus bridge ───
import Dregg2.Conserve                 -- shared conservation lemma library + `conserve`/`commit_cases` tactics (fail-loud, structural; #assert_axioms-clean)
import Dregg2.Catalog                  -- catalog code-gen (`catalog … where` → smart-ctor + admits-char + auto-#assert_axioms triple) + `discharge` guard-seam tactic + `Dregg2` aesop rule-set + `#assert_namespace_axioms` (all fail-loud; #assert_axioms-clean)
import Dregg2.Exec.Consensus          -- quorum→finality-tier bridge: committedByQuorum→bft tier, net_no_downgrade, finality_monotone_on_net; axiom-clean
-- ─── Atomic hyperedge: turn = wide pullback over shared TurnId ───
import Dregg2.Hyperedge               -- Hyperedge = wide pullback over TurnId + N-ary CG-5; hyperedge_sound proved; SharedTurnId/ring are special cases
-- ─── Abstract spec layer (Dregg2.Spec): the factored dregg2 semantics ───
import Dregg2.Spec.Guard              -- unified verify/find seam (demand⊣supply, first-party|witnessed, meet-semilattice attenuate_narrows, OneOf coproduct); legacy constraints/auths as derived instances
import Dregg2.Spec.Conservation       -- multi-domain LinearityClass-typed conservation: committed_iff_cleartext (hidden-yet-conserved) + multi_domain_independent; range-rib is §8 portal
import Dregg2.Spec.Authority          -- generative capability graph: introduce/amplify/mint + "only connectivity begets connectivity" (gen_step_traces proved); whole-history closure OPEN
import Dregg2.Spec.Lifecycle          -- lifecycle as the attested dual of creation: creation_and_death_are_dual + archival_is_fold(IVC) + reclaim_by_lease + creation_provable_death_temporal; co-witnessability OPEN
-- ─── Spec cross-links: choreography↔hyperedge, await, vat-boundary Φ ───
import Dregg2.Spec.JointViaHyper      -- N-ary joint soundness derived from hyperedge_sound; hyperedge_is_validity_not_canonicity (validity=proof-check, canonicity=consensus)
import Dregg2.Spec.Choreography       -- blue/red projection-split: red_projects_to_hyperedge, blue_needs_no_hyperedge; operational refinement OPEN
import Dregg2.Spec.Await              -- await family = temporal Guard (conditional_is_temporal_guard + resolve_monotone) ⊕ dataflow DAG (Promise); zkpromise/zkawait unification proved; topo-sort OPEN
import Dregg2.Spec.VatBoundary        -- Φ the named-lossy caps↔keys functor: phi_drops_confinement (permission survives, authority doesn't) + forwarded_cap_is_revocable + biscuit/macaroon=Φ-domain; functoriality OPEN
import Dregg2.Spec.Coherence          -- coherence web: guard_is_authority_conferral, conservation_is_hyperedge_cg5, lifecycle_revoke_is_authority_restrictive, choreography_red_conserves, guard_attenuate_narrows_is_meet ⇄ authority_confers_narrows_is_meet
import Dregg2.Spec.ExecRefinement     -- Exec ⊑ Spec beachhead: exec_refines_conservation (toy ℤ ledger = balance domain) + exec_authz_refines_guard (authorizedB = Guard.firstParty); operational LTS OPEN
-- ─── Program logic, §8 discharges, app Spec layer, operational LTS ───
import Dregg2.Proof.WP                 -- VCG/WP calculus over the Option-monad transition: wp/Triple + vcg + vcg_run_sound (reduces to stepComplete_preserves); monotonic-counter + single-ledger escrow proved; cross-vat escrow OPEN
import Dregg2.Exec.AuthTurn            -- authority-mutating turn (dual of the balance turn): recKDelegate/recKRevokeTarget edit `caps`; cap-edit matches Spec.addEdge/removeEdge (Endow/Revoke); dual frame with recTotal fixed
import Dregg2.Proof.LTS                -- single-cell operational LTS: recAbsStep_forward + authAbsStep_forward united in absStep'_forward; cross-cell whole-history closure residual OPEN
import Dregg2.Crypto.NonMembership     -- §8 discharge #3: nonmembership_bridge (Satisfies ↔ NonMember, both directions; sorted_gap_excludes the combinatorial heart, no seam) + nonmembership_verify_sound (derived) + dial at acceptanceOnly floor
-- ─── §8 discharges #4–5, BFT adversary model, cross-cell LTS, closed userspace-verification loop ───
import Dregg2.Crypto.Temporal          -- §8 discharge #4: temporal_bridge (Satisfies ↔ InWindow, both directions; no primitive seam) + temporal_verify_sound (derived) + dial at `selective`
import Dregg2.Crypto.Dfa               -- §8 discharge #5: dfa_bridge (Satisfies ↔ DfaAccepts, both directions; no seam) + dfa_verify_sound (derived) + dial at `fullDisclosure`; reference kernel OPEN
import Dregg2.Proof.BFT                -- Byzantine/honesty model over World: bft_safety (conflicting quorums ⇒ ⊥ via honest-witness intersection, n−f quorum) + GST liveness; all model assumptions are structure fields, #assert_axioms-clean
import Dregg2.Proof.CrossCellLTS       -- cross-cell operational LTS: crossAbsStep_forward (bilateral jointApply square: conservation + authority + grounding) + crossAbsRun_forward; machine-checked that cross-cell does NOT reduce to single-cell (tensor-non-finality); N-ary forest OPEN
import Dregg2.Proof.WPCatalog          -- userspace-verification loop closed end-to-end: vcg_discharge (fail-loud) + eDSL multi-field ledgerSM → vcg → vcg_discharge → vcg_run_sound (conservation + monotonic seq)
-- ─── BFT liveness pacemaker, cross-cell forest, contention dichotomy, §8 discharge #6 ───
import Dregg2.Proof.BFTLiveness        -- closes the GST liveness OPEN: GSTRound obtained from DLS88-GST + ELRS-synchronizer + HotStuff-responsive-quorum Pacemaker; World.gst_liveness derived; randomized synchronizer construction OPEN
import Dregg2.Proof.Synchronizer       -- randomized leader-rotation synchronizer: expected_views_O1 + honest_hit_as (a.s. hit); reduces Pacemaker.synchronizes to the randomness+honest-fraction model; World.rand probability-measure bridge OPEN
import Dregg2.Proof.GST                 -- Track D-GST: a GSTModel BUILDS a BFTLiveness.Pacemaker (pacemaker_of_gstModel) → gst_liveness (∃ committed-by-quorum, the descent closing the consensus OPEN at the combinatorial level via liveness_of_pacemaker); honestLeader co-finality carried as an honest field; teeth = a bounded (r<5) leader admits no sync round past gst=10; World.rand measure bridge stays the SAME named OPEN
import Dregg2.Proof.CoinductiveAdversary -- unbounded-interleaving adversary: obsBisim_traj_of_bisim (confluence-up-to-bisimulation over νF) proved for the safe fragment; deriving it from the finite dichotomy needs up-to-context closure — OPEN
import Dregg2.Proof.BeaconSpace        -- probabilistic oracle layer: Measure over beacon streams + Bernoulli(h) independence; noHonestEverGe_measure_zero + honestLeader_index_exists discharge Synchronizer.hhit; Dirac h=1 boundary witness suffices (interior-h needs an unbuilt mathlib module)
-- ─── §8 kinds 7+8 (registry complete), catalog phase (ii), eDSL-B, dregg1 semantics mirrors ───
import Dregg2.Crypto.BlindedSet        -- §8 #7: blindedset_bridge (= merkle_bridge; a BlindedSet membership IS Merkle vs the issuer root) + HolderAnonymity carrier + dial acceptanceOnly (holder hidden)
import Dregg2.Crypto.Custom            -- §8 #8 (registry complete; extensibility OPEN): custom_bridge parametric over a CustomRegistration's own bridge field; any future kind registers (vk,circuit,relation,bridge) and inherits the cascade
import Dregg2.CatalogInstances         -- dregg1's StateConstraint(27)/Authorization(9) catalogs as derived Guard smart-constructors + Effect::linearity coloring; 101 thms #assert_namespace_axioms-clean
import Dregg2.DSLChoreo                -- `dregg_choreo {…}` choreography eDSL → Coordination.GlobalType; auction inherits deadlock_freedom + privacy_by_projection; #check_projectable elaboration gate
import Dregg2.Exec.CapTP               -- CapTP transport: pipelining_preserves_seam + handoff_is_introduce/_non_amplifying/_forwarder_revocable (3-vat Granovetter handoff = Spec.Authority.Introduce crossing Φ); distributed-GC liveness OPEN
import Dregg2.Authority.Blocklace      -- byzantine-repelling DAG (Cordial-Miners C-spine): equivocation_detectable + honest_no_equivocation + cdt_is_blocklace bridge + attested finality; eventual-exclusion-under-partition OPEN
import Dregg2.Exec.DfaRouting          -- DFA message-routing automaton (mirrors dregg1): routed_message_followed_accepting_route (delivery soundness, fail-closed) + route_authorization (per-hop Guard) + unique_route + routing_projects_message_flow
import Dregg2.Crypto.UCBridge          -- UC cross-system bridge: FComDischarge bundles CryptHOL's Pedersen F_com guarantees as Prop carriers; binding_unlinkable_discharged_by_crypthol proved (#assert_axioms-clean). CAVEATED: trust widens to Isabelle/HOL + transport fidelity; Isabelle theory in uc-crypthol/ (local build blocked by afp-devel↔RC3 skew, see PHASE-UC-TRANSPORT.md)
-- ─── Wire emission, distributed GC, full op-set, cross-cell forest ───
import Dregg2.Exec.CircuitEmit         -- circuit extraction emitter: emit (ConstraintSystem→wire) + emit_faithful + emittedKernel_bridge (emitted kernelCircuit ↔ fullStepInv); fingerprint-bound to the real Rust AIR via dregg-lean-ffi
import Dregg2.Exec.CapTPGC             -- CapTP distributed GC by lease: captp_gc_by_lease + captp_no_premature_reclaim + captp_cycle_leak_is_the_price (the impossibility, not faked)
import Dregg2.CatalogEffects           -- all 52 dregg1 Effect variants colored onto Spec.Conservation LinearityClass + per-class obligations + Regime discriminator; 69 thms #assert_namespace_axioms-clean
import Dregg2.Exec.TurnExecutor        -- turn-executor: Turn = call-forest of catalog-typed Actions run all-or-nothing; execTurn_attests = all 4 StepInv conjuncts over the whole multi-action turn + execTurn_conserves/_balance_domain/_unauthorized_fails
import Dregg2.Exec.TurnForest          -- nested call-forest executor: execForest_no_amplify (Granovetter via derive_no_amplify) + execForest_conserves (N-ary CG-5, Σ=0 whole tree) + execForest_attests (4 StepInv conjuncts); cross-cell forest OPEN
import Dregg2.Paco                      -- vendored+ported from hxrts/paco-lean (MIT): parametrized coinduction (paco/upaco/gpaco/gupaco + companion/up-to + the `pcofix` tactic), 23 modules; powers CoinductiveAdversary's up-to-context closure (obsBisim_of_uptoComm)
import Dregg2.Proof.ForestLTS          -- N-ary cross-cell forest LTS: forestAbsStep_forward (forestApply square, Finset.sum conservation, Σ=0 binding hypothesis-routed) + forestAbsRun_forward; bilateral = ι=Fin 2 slice
import Dregg2.Proof.ContendedCrossCell -- contention dichotomy (both poles): contended_commits_confluent (disjoint/I-confluent ⇒ schedule-agnostic) + coupled_no_schedule_agnostic_commit (coupled Σ=0 ⇒ ¬∃ schedule-agnostic commit — BEC/CAP impossibility); bridged to Confluence
import Dregg2.Crypto.Bridge            -- §8 discharge #6: bridge_bridge (Satisfies ↔ BridgeRelation, both directions; no seam) + bridge_verify_sound (derived) + dial at `selective`
import Dregg2.Crypto.Pedersen         -- §8 discharge #2: pedersen_conservation_bridge (Satisfies ↔ Conserves, both directions; commit_hom-grounded, range-gadget non-negativity, no seam) + pedersen_verify_sound (derived) + dial at `selective`
import Dregg2.Protocol.WorkflowGuard  -- Workflow's authz/order/attest gates as Spec.Guard instances; 3 refinement ↔s + whole-step Guard.all equivalence + exec⇒admits bridge + discriminating #eval
import Dregg2.DSL                      -- `dregg_program {…}` cell-program eDSL → RecordProgram; counter/escrow elaborate by rfl; #eval admit/reject
-- ─── Full op-set, eDSL-C, state migration, circuit gadgets to wire, Temporal/Stingray ───
import Dregg2.Exec.TurnExecutorFull    -- full op-set executor: FullAction = balance | delegate/revoke | mint/burn; execFull_attests = StepInv per kind + execFullTurn_ledger transaction-level conservation
import Dregg2.Exec.CrossCellForest     -- cross-cell nested forest: crossForest_no_amplify + crossForest_conserves (N-ary cross-cell Σ=0) + crossForest_attests; bilateral = Fin-2 slice; overlapping-cells OPEN
import Dregg2.Exec.FullForest          -- FullActionA call-forest (wholesale-swap keystone): execFullForestA = recursive all-or-nothing tree over the full per-asset op-set, proven equal to execFullTurnA over the pre-order lowering; execFullForestA_conserves_per_asset (conservation vector, not scalar) + execFullForestA_no_amplify + execFullForestA_each_attests; cross-target routed to CrossCellForest
import Dregg2.Exec.Handler             -- ★ the EFFECT-HANDLER ALGEBRA scaffold (swap-grade executor foundation, DESIGN-EFFECT-HANDLER-ALGEBRA.md): EffectHandler bundles step/delta/auth/admission/trace + FORCED obligation proofs (auth_gated/admission_gated/conserves) so a handler can't register without its gates (R1-closure is a TYPING condition); Registry=List PackedHandler coproduct replaces the closed FullActionA; turn_conserves = ONE generic foldlM induction (the 56-arm ledger matrix collapses). 3-effect proof-of-approach slice; the 56-effect migration is the staged batches below
import Dregg2.Exec.Handlers.StateSupply -- migration batch 1: mint/burn handlers (the delta≠0 path — turn_conserves sums non-zero deltas) + createCell/factory/spawn (account-growth neutral) + state/write handlers; CLOSES R1/R6 (acceptsEffects Live-gate wrap the bare kernel ops lack)
import Dregg2.Exec.Handlers.Escrow      -- migration batch 1: createEscrow/release/refund/obligation/note handlers; CLOSES R2 (releaseSettleAuthB/refundSettleAuthB = authorizedB over recipient/creator — the bare releaseEscrowKAsset takes only id, no actor); double-spend gate; conserves via the proved escrow combined-conservation lemmas
import Dregg2.Exec.Handlers.Seal        -- migration batch 2: seal/unseal/createSealPair/swiss-ref handlers; CLOSES R3 (pidFresh admission conjunct the bare createSealPairChainA lacks) + export amplification carried; delta=0 cap-routing frame
import Dregg2.Exec.Handlers.Authority   -- migration batch 2: delegate/introduce/validateHandoff/attenuate/revoke/dropRef handlers; KEY FIX — delegation re-routed from rights-BLIND recKDelegate to ATTENUATED recKDelegateAtten (granted⊆held, non-amplifying); revoke/attenuate = total self-limiting (post caps ⊆ pre); delta=0
import Dregg2.Exec.Handlers.Queue       -- migration batch 2: queue allocate/enqueue/dequeue/resize/atomicTx/pipeline handlers; CLOSES codex P0-1 (dequeueBindStep gates r.recipient=actor — the bare queueDequeueRefundK refunds any caller-supplied depId, draining a stranger's deposit); enqueue/dequeue combined-conserving
import Dregg2.Exec.Handlers.Bridge      -- migration batch 2: bridgeLock/finalize/cancel/pipelinedSend handlers; CLOSES R12 (bridgeFinalize.delta = -amount, the disclosed cross-chain OUTFLOW correctly accounted, NOT falsely Conservative) + creator-authority wrap (bridgeAuthOK; the bare op has no actor arg)
import Dregg2.Exec.Handlers.Exercise    -- the LAST handler: exerciseA recursive sub-effect forest; CLOSES R4 (facet-mask — inner effects run under the cap allowed_effects, not the inner-actor's full authority); fuel-bounded structural recursion (NO heartbeat pathology), conserves via subTurn_conserves (the turn_conserves twin); closedToSub drops the proved scaffold handlers into the inner forest. All 56 effects are now sound handlers
import Dregg2.Exec.Handlers.Lifecycle   -- migration batch 3: cellSeal/unseal/destroy + refreshDelegation + emitEvent handlers; REAL side-table semantics (`lifecycle`/`deathCert`/`delegations`, not field-write stubs); aligns handler algebra with execFullA + circuit specs
import Dregg2.Exec.HandlerExecutor      -- ★ THE CUTOVER KEYSTONE (additive; live-switch is mechanical): masterRegistry packs all 47 proved handler entries; toClosedEffect : FullActionA→ClosedEffect maps all 56 ctors (aliases collapse); execHandlerTurn = the registry executor over RecChainedState. execHandlerTurn_conserves = the DERIVED global per-asset conservation, LIFTING the generic turn_conserves (the 56-arm execFullA_ledger_per_asset matrix collapses into ONE lift) + gate companions (head_authorized/_admitted). handler_refines_execFullA_{transfer,release,stateWrite} = the SOUND-STRENGTHENING relation (handler-commits ⊆ execFullA-commits, kernels agree). TEETH: a transfer/state-write into a Sealed cell (R1/R6) + an escrow release by a stranger (R2) — execFullA=some (the live hole) vs execHandlerTurn=none (the algebra closes it)
import Dregg2.Exec.FullForestAuthPortal -- real §8 AuthPortal: RealAuthPortal bundles ed25519/STARK/HMAC floors; portalVerifyReal routes each Authorization variant to its own oracle; realAuthPortal.soundness = ed25519.unforgeable ∧ STARK.extractable ∧ HMAC.unforgeable (not True, not one shared collisionHard); per-variant security theorems take the carrier as an explicit hypothesis; unchecked_arm_rejects + no_reachable_arm_is_trivially_true (anti-vacuity); #assert_axioms-clean
import Dregg2.Exec.FullForestAuth      -- executed credential+caveat auth gate on the call-forest: gated tree FullForestG with NodeAuth (10-variant Authorization + tiered caveats + macaroon chain); gateOK = credentialValid (§8 AuthPortal) ∧ capAuthorityG (granted≤held verified) ∧ caveatsDischarged; execFullForestG_conserves_per_asset/_no_amplify derived via eraseG; gatedNode_check_eq_use = no TOCTOU; non-vacuous (forged cred, false caveat, and per-asset launder all yield none)
import Dregg2.Exec.GatedForestCfg      -- first-class `GatedForestCarriers` bundle + `starbridgeCarriers` instance (replaces pinned Demo/Production namespace)
import Dregg2.Exec.CellExecutor        -- `CellExecutor.production` (gated starbridge) + internal `kernelForest` for erasure reuse
import Dregg2.Exec.SigningMessage      -- byte-exact signing-message preimages (guards the §8 AuthPortal's opaque `stmt` Digest), ported from dregg1 (authorize.rs:1713–1880): 6 preimage builders (sigMsgFull/Partial/Custom/Stealth/Bearer/HandoffCert) + domain-separator theorems (sigMsg*_hasPrefix, domainSep_injective — 15 pairs distinct) + binding teeth (tampered field ⇒ different preimage); #assert_axioms-clean, non-vacuous (#eval tamper ⇒ false)
import Dregg2.Exec.Admission           -- fail-closed admission prologue in front of the FullForestAuth kernel fold (admission ≠ kernel): `admissible` = 8 host-fed gates (expiry + agent-existence + nonce-replay + fee-coverage + write-set/agent freeze + receipt-chain self-binding + Stingray budget); `commitPrologue` (fee-debit + nonce-tick) is never rolled back — prologue_survives_failed_body proves fee−balance ∧ nonce+1 even on body failure (anti-DoS + replay-closed); pure_fold_loses_prologue proves the naive all-or-nothing bind discards the prologue; #assert_axioms-clean; #eval non-vacuity
import Dregg2.Exec.TurnAdmission        -- devnet-shaped entry: `runGatedForestTurn` = `Admission.runTurn` ∘ `FullForestAuth.execFullForestG` (prologue survives gated-forest body failure; inadmissible turns rejected with no edit); #assert_axioms-clean
import Dregg2.Exec.AdmissionWire       -- write-set extraction + `TurnHdr`/`AdmCtx` builders for the FFI admission seam
import Dregg2.Apps.OrbitalScreen       -- continuous-time-sound orbital screen: screen_clear_imp_continuous_clear (a `clear` verdict holds at every continuous time, not just samples; between-samples closest approach covered) + crossing-pair teeth; coarse Lipschitz fallback for speed-bounded trajectories; curvature term OPEN
import Dregg2.Apps.WhoYields           -- graph-symmetry who-yields bridge (computable WL color-refinement): rigid_of_discrete (asymmetric ⇒ forced role) + symmetric_needs_negotiation (tie ⇒ negotiation) + three_mutual_conflict_needs_three_roles + outOfFuel_breaks_symmetry
import Dregg2.Apps.EpistemicSheaf      -- constellation as a sheaf of verifiers: consensus_on_clearance (H⁰ = global section = honest distributed knowledge of a screened fact) + byzantine_section_does_not_glue (witnessed non-gluing obstruction); cohomology-as-object is POETRY (honest)
import Dregg2.Apps.ConservationBridge  -- conservation_is_flow_balance: JointCell Σδ=0 (committed avoidance maneuver) = conjunction graph's flow-balance across the symmetry boundary; multi-edge generalization OPEN
import Dregg2.Apps.RightOfWay          -- verified collision-avoidance referee: referee_sound (adversary-proof) + referee_sound_physics (committed ⇒ clear on the whole continuous step, via OrbitalScreen) + outOfFuel_cannot_burn + forced_trade_excludes_naive + collisionSafety_must_escalate
import Dregg2.Apps.AgentOrchestration  -- verified multi-agent orchestration ("the orchestration is a theorem"): least-privilege attenuated sub-agent delegation (worker_authority_subset_orchestrator, strict write-drop) + real per-asset transfers conserve (workForest_conserves) + out-of-scope worker fail-closed (badWorkerForest_fails_closed = none, PROVED) + escrow combined-conservation (escrowLock_combined_conserves) + credential+caveat auth gate (committed ⇒ credential ∧ caveats; forged-cred & false-caveat denied) + whole forest certified (orchestration_conserves ∧ _no_amplify ∧ _each_attests); #assert_axioms-clean
import Dregg2.Apps.NameserviceGated    -- D4: nameservice as a VERIFIED app on the ONE gated production entry (execFullForestG). 5 end-user theorems (forged-credential rejection ∀s; WriteOnce no-name-squat; Monotonic no-rent-shorten; WriteOnce permanent-revoke; per-asset conservation) + 22 #guard non-vacuity witnesses on a real registry-cell state; #assert_axioms-clean. First real starbridge-app on the credential-gated executor.
import Dregg2.Apps.IdentityGated       -- D4: identity app on the ONE gated entry — PERMANENT REVOCATION as the gate's revocation leg (id_revoked_rejected: a revoked credential's op = none at EVERY state, via gateOK_revoked_fails) + id_forged_rejected + id_op_conserves; #assert_axioms-clean + #guard witnesses (genuine commits / revoked ⇒ none / forged ⇒ none)
import Dregg2.Apps.SubscriptionGated   -- D4: subscription app on the ONE gated entry — replay-safe sequencing as the MonotonicSequence slot caveat (sub_nonsequential_rejected) + sub_queue_wellformed_forever (Hatchery subWFContract on trajG) + sub_forged_rejected + sub_op_conserves; #assert_axioms-clean + #guard witnesses
import Dregg2.Exec.PrivacyTheorems     -- D7 privacy: nullifier NO-DOUBLE-SPEND fully proved at the ledger layer (chainNoteSpend_no_double_spend · nullifier_persists · seq_no_respend) + stealth-freshness⇒unlinkability structural (crypto as NAMED §8 portal hypotheses, no sorry); 13 thms #assert_axioms-clean. Gate-wiring into the executor entry = separate task
import Dregg2.Exec.ShieldedValue        -- A4: noteCreate's commitment WELDED to a hidden value via the Pedersen/range-proof portal — noteCreateBound_binds (set entry IS commit(value,blinding)) + noteCreateBound_in_range (no negative/overflow ⇒ no hidden inflation at creation) + created_value_conservation (Σ commitments = commit(Σ value)(Σ blinding) via commit_hom ⇒ shielded value-conservation over executed state); the value-side dual of the nullifier discipline. Crypto residue = Pedersen binding carrier (no sorry); #assert_axioms-clean
import Dregg2.Apps.GovernedNamespaceGated  -- D4: governed-namespace on the ONE gated entry — committee threshold-sig credential gate + 4 constitutional slot caveats (gn_committee_immutable · gn_threshold_immutable · gn_version_monotonic_seq · gn_dispute_window_cannot_shrink) + gn_forged/gn_revoked_member rejected + gn_commit_conserves
import Dregg2.Apps.PrivacyVotingGated      -- D4: private voting on the ONE gated entry — vote-as-nullifier NO-DOUBLE-VOTE (pv_no_double_vote, WriteOnce per-voter nullifier) + pv_forged/pv_revoked_voter rejected + pv_cast_conserves; the executed dual of PrivacyTheorems.kernel_no_double_spend
import Dregg2.Apps.PrivacyVoting         -- ungated cell-program: private ballot cast via WriteOnce per-voter nullifier slots on execFullForestA; no-double-vote + conservation; dual of PrivacyVotingGated
import Dregg2.Apps.BountyBoardGated     -- D4 (VALUE-MOVING): bounty board on the gated entry via escrow — post/claim/cancel as credential-gated escrow ops; bb_forged/bb_revoked rejected + bb_post/claim/cancel_conserves (value conserved through the gate) + bb_claim_requires_live_claimant / bb_cancel_requires_live_poster (D3 liveness)
import Dregg2.Apps.ComputeExchangeGated -- D4 (VALUE-MOVING): compute market on the gated entry via escrow — order/settle/refund; cx_forged/cx_revoked rejected + cx_order/settle/refund_conserves + cx_settle_requires_live_provider (D3 liveness); 22 #guards, 13 #assert_axioms
import Dregg2.Apps.GalleryGated         -- D4: gallery/artwork registry on the gated entry (8th/8 — suite complete) — mint/transfer/set-metadata; gallery_item_immutable (WriteOnce content-addressed id, no collision) + gallery_forged/gallery_revoked rejected + gallery_conserves; source-faithful to apps/gallery/src/artwork.rs; 17 #guards, 9 #assert_axioms
import Dregg2.Apps.Gallery              -- ungated cell-program: artwork mint/transfer/set-metadata via WriteOnce item slot on execFullForestA; item-immutable + conservation; dual of GalleryGated
import Dregg2.Apps.NameService         -- nameservice cell-programs (register/transfer/revoke): nameservice_registration_forever carried via livingCellA_commitments_persist; nameCommit_inj + revoke tombstone; transfer preserves both old registration and new ownership binding forever
import Dregg2.Apps.Identity            -- identity cell-programs (present/verify/revoke): livingCellA_identity_revoked_forever = a revoked identity can never be re-validated, carried via livingCellA_carries on the grow-only `revoked` registry
import Dregg2.Apps.Subscription        -- subscription cell-programs: §A slot automaton safety (seq_tail ≤ seq_head, no-overflow) + subscription_consumer_safe_forever; §B subscription_wellformed_forever carried by the real execFullForestA living cell against any adversary
import Dregg2.Apps.AtomicSwap          -- REAL-kernel multi-party atomic escrow swap (runs on RecordKernelState, NOT DemoRes): runSwap fail-closed + runSwap_none_rolls_back (atomicity) + per-asset *_conserves (via the kernel laws); AUTHORITY honest (self-auth trivial + unauthorized_lock_rejected = the real cap-gate teeth); LIVENESS ◇ settle_completes/settle_delivers; teeth underfunded_rolls_back + settle_{wrong_id,unlocked}_no_delivery. The APP-THEOREM-SUITE exemplar: real Exec + correctness/safety/liveness with teeth
import Dregg2.Apps.BountyBoard         -- ungated cell-program: bounty post/claim/cancel via real escrow on execFullForestA; combined per-asset conservation + D3 live-recipient/creator teeth; dual of BountyBoardGated
import Dregg2.Apps.GovernedNamespace   -- ungated cell-program: governed route-table writes via setFieldA + constitutional slot caveats on execFullForestA; immutable committee/threshold + monotonic version/window + balance-neutral; dual of GovernedNamespaceGated
import Dregg2.Apps.ComputeExchange     -- ungated cell-program: compute-market order/settle/refund via real escrow on execFullForestA; combined conservation + D3 live-provider teeth; dual of ComputeExchangeGated
import Dregg2.Authority.ClearanceGraph -- compartment clearance as explicit label-dominance graph (mayRead/needsAll); foundation for CompartmentWorkflowMandate
import Dregg2.Apps.CompartmentWorkflowMandate -- Phase A mandate crown: DAG workflow (review→redact→sign) + clearance + Stingray spend demo + cwm_step_legal_forever / cwm_pay_supply_forever on trajA
import Dregg2.Apps.CompartmentWorkflowMandateGated -- production mandate: cwm_safety_forever = step-legal ∩ pay-conserved ∩ revoked-dead ∩ compartment on trajG; MonotonicSequence DAG enforcement + Hatchery composeContracts
import Dregg2.Apps.CompartmentWorkflowMandate.CrossVatBridge -- Phase B: mandate commitment_anchor ↔ CrossVatCharter covenant; cwm_charter_refines_mandate_forest
import Dregg2.Apps.StorageGatewayMandate -- storage gateway mandate (ungated): op/prefix/clearance/volume rejection teeth + sgm_volume_legal_forever + sgm_pay_supply_forever on trajA; Stingray slice demo
import Dregg2.Apps.StorageGatewayMandateGated -- production storage gateway: sgm_safety_forever = step-legal ∩ pay-conserved ∩ revoked-dead ∩ bucket on trajG; execFullForestG setField/emit gated ops
import Dregg2.Apps.CrossCellCovenantGated -- coordinated cross-cell covenant app: ccov_charter_commits + ccov_forged_cred_rejected + ccov_covenant_teeth + ccov_joint_conserves on the joint KernelState bilateral path
import Dregg2.Apps.MultisigVote        -- REAL-kernel multisig/DAO vote on RecordKernelState: enfranchisedB = registry-membership OR Cap.node vote-cap (a GENUINE gate, NOT the actor==src tautology); vote-as-nullifier no-double-vote (reuses the spend-nullifier anti-replay); SAFETY revote_tally_unchanged + AUTHORITY unenfranchised/outsider_vote_rejected (exercises the cap branch, capbearer_admitted) + CORRECTNESS passes_iff (threshold ≤ distinct-enfranchised tally, both directions) + LIVENESS votes_reach_quorum; decide-teeth (empty/sub-threshold does not pass, double-vote counted once)
import Dregg2.Apps.SealedBidAuction    -- Track-A Phase 4 (the proving ground): the gallery sealed-bid auction on the intent stack — (b) no_frontrunning (causal reveal-ordering = a lightcone fact; teeth: a fork-f1 reveal unfillable by concurrent-f2 fill) + (c) settle_conserves & settle_cannot_mint + one-shot settle_no_double + loser-refund ◇ (auction_loser_refunded via just_progress, auction_starvation_rejected). (a) userspace-escrow ≥ kernel = a CARRIED OPEN interface (UserspaceDominatesKernel), not stubbed — needs the userspace-escrow cell-program + a state clock (ember model call)
import Dregg2.Exec.CellRuntime         -- OS-level cell runtime theorems: checkpoint_restore_roundtrip + replay_deterministic_run + replayFrom_conserves + time_travel_fork; νF fork noted
import Dregg2.Exec.StateMigration      -- schema-upgrade state migration: migrate_conforms + migrate_conserves (balance survives) + migrate_anti_brick (gate-fail ⇒ signature fallback, never bricks)
import Dregg2.Exec.CircuitEmitGadgets  -- emits the remaining §8 gadgets to the wire: emittedTemporal/NonMembership/Pedersen/Dfa_bridge (each composes emit-faithfulness with the gadget's *_bridge)
import Dregg2.Circuit.Transfer         -- crown jewel: the circuit⟺protocol bridge for ONE REAL effect (Transfer) over the real recKExec executor — transfer_circuit_sound (circuit ⇒ executor admits + genuine debit/credit/conserve) + transfer_circuit_complete (every committed step satisfies) + transfer_bridge_iff (sat ⇔ admitGuard); NON-VACUOUS (rejects_nonconserving = Orchard-class value-forgery forbidden BY CONSTRUCTION · rejects_unauthorized · rejects_overdraft + decidable #guard forgery witnesses); emitTransferFaithful composes with emit. PLUS Stage-A: TransferSpec (independent declarative FULL-17-field spec) + recKExec_iff_spec (executor⟺spec, both directions, validates recKExec) + recTransfer_correct
import Dregg2.Circuit.Lookup            -- D5 IR extension (ember steer): the LOOKUP-argument IR — LookupConstraint (denotation = membership in a finite table; LogUp is the prover-side enforcement) + CircuitL (arithmetic gates PLUS lookups, ADDITIVE — the bare Constraint/31 specs untouched) + rangeCheck (range [0,2^k) check) with decidable #guards (in-range accepted; out-of-range/negative/boundary REJECTED). Closes the FIELD-soundness gap path: the Rust i64→BabyBear map needs range checks or field-wraparound forges value; this is the Lean IR for them. Poseidon2 gates next
import Dregg2.Circuit.Refinement        -- D5 l4v REFINEMENT framing: the circuit as the bottom of the refinement tower — circuit ⟺ spec ⟺ executor as explicit Refines/Equiv (circuit_refines_spec = soundness/⊑ · spec_refines_circuit = completeness · circuit_refines_exec = the algebraic statement refines the dynamic behaviour the kernel runs) + Refines.preserves (the l4v payoff) instantiated as circuit_conserves (CONSERVATION proven on the abstract spec DESCENDS for free to the arithmetic circuit). Realizable Poseidon-CR portals only
import Dregg2.Circuit.EffectCommit      -- D5 GENERIC framework: full-state circuit⟺spec proved ONCE — EffectSpec (per-effect data) + effect_circuit_full_sound/_complete + 4 anti-ghost teeth + emission, all #assert_axioms-clean (injectivity portals are hypotheses). touchedDigest = StateCommit.frameDigest over carrier T (one binding lemma, any |T|). The `ec_lookup` tactic (concrete wire indices, no omega-tarpit) is the reusable lookup recipe. Per-effect cost ~100 lines (fill EffectSpec + GuardDecodes/Encodes + apex↔bespoke bridge); the crown-jewel theorems come free
import Dregg2.Circuit.KeyedCommit       -- D5 v2 carrier (FUNCTION-field shape): keyedDigest + KeyedDigestBindsKeys — the key-polymorphic, state-free lift of StateCommit.frameDigest/FrameDigestBindsCells to ANY LinearOrder key, so `bal` (key CellId×AssetId) + `caps` (key Label) are bound by the SAME proof. #assert_axioms-clean
import Dregg2.Circuit.ListCommit        -- D5 v2 carrier (the breadth bottleneck-breaker): listDigest + ListDigestBindsList — the list-side-table commitment binding (compressN-inj + injective leaf ⇒ WHOLE post-list pinned, so a drop/reorder/wrong-cons is REJECTED). The ONE new crypto carrier v2 needs; unlocks the ~12 list-changing effects (notes/escrows/queues/seal/swiss/revoked). #assert_axioms-clean
import Dregg2.Circuit.EffectCommit2      -- D5 v2 GENERIC core (single non-cell component): effect2_circuit_full_sound/_complete + 3 anti-ghost teeth + emission, proved ONCE for an effect touching ONE non-cell component (a function-field via funcComponent/keyedComponent, or a list side-table via listComponent — off ListCommit/KeyedCommit). Generalizes v1's "touched=cell" to "touched=one ActiveComponent"; soundness gets the postClause from active.binds (no funext, no ghost). #assert_axioms-clean
import Dregg2.Circuit.EffectCommit2Dual  -- D5 v2-dual GENERIC core (TWO non-cell components): effect2dual_circuit_full_sound/_complete + 4 anti-ghost teeth + emission, proved ONCE for bal+escrows-style effects. Gate 1 keystone; unlocks escrow + bridge-outbound families. #assert_axioms-clean
import Dregg2.Circuit.AccountsCommit    -- D5 accounts-growth carrier: accountsComponent (sorted-Finset list digest) for createCellA/spawnA
import Dregg2.Circuit.BornEmptyCommit -- D5 born-empty side-table digest bundles for account-growth circuit wiring
import Dregg2.Circuit.EffectCommit3   -- D5 v2-triple GENERIC core (THREE non-cell components): queueEnqueue/Dequeue (queues+bal+escrows). #assert_axioms-clean
import Dregg2.Circuit.EffectCommit4    -- D5 v2-quad GENERIC core (FOUR non-cell components): createCellFromFactoryA. #assert_axioms-clean
import Dregg2.Circuit.EffectCommit5    -- D5 v2-quint GENERIC core (FIVE non-cell components): spawnA. #assert_axioms-clean
import Dregg2.Circuit.Inst.createEscrowA   -- D5 v2-dual: createEscrowA_full_sound ⇒ EscrowHoldingCreateSpec
import Dregg2.Circuit.Inst.createCommittedEscrowA -- D5 v2-dual: createCommittedEscrowA_full_sound ⇒ CommittedEscrowCreateSpec (§8 portal)
import Dregg2.Circuit.Inst.createCellA       -- D5 v2-triple: createCellA_full_sound ⇒ CreateCellSpec (accounts+bal+born-empty side)
import Dregg2.Circuit.Inst.createCellFromFactoryA -- D5 v2-quad: createCellFromFactoryA_full_sound ⇒ CreateFromFactorySpec
import Dregg2.Circuit.Inst.spawnA           -- D5 v2-quint: spawnA_full_sound ⇒ SpawnSpec
import Dregg2.Circuit.Inst.releaseEscrowA -- D5 v2-dual: releaseEscrowA_full_sound ⇒ ReleaseEscrowSpec
import Dregg2.Circuit.Inst.refundEscrowA  -- D5 v2-dual: refundEscrowA_full_sound ⇒ RefundEscrowSpec
import Dregg2.Circuit.Inst.bridgeLockA    -- D5 v2-dual: bridgeLockA_full_sound ⇒ BridgeOutboundLockSpec
import Dregg2.Circuit.Inst.bridgeFinalizeA -- D5 v2 breadth: bridgeFinalizeA_full_sound ⇒ BridgeFinalizeSpec (escrows listComponent; bal framed)
import Dregg2.Circuit.Inst.bridgeCancelA -- D5 v2-dual VALIDATION: bridgeCancelA_full_sound ⇒ BridgeOutboundCancelSpec (bal funcComponent + escrows listComponent) through EffectCommit2Dual
import Dregg2.Circuit.Inst.attenuateA        -- D5 v2 breadth: attenuateA_full_sound ⇒ AttenuateSpec (caps funcComponent)
import Dregg2.Circuit.Inst.balanceA         -- D5 v2 breadth: balanceA_full_sound ⇒ BalanceMovementSpec (bal funcComponent)
import Dregg2.Circuit.Inst.bridgeMintA     -- D5 v2 breadth: bridgeMintA_full_sound ⇒ InboundMintSpec (bal credit)
import Dregg2.Circuit.Inst.burnA           -- D5 v2 breadth: burnA_full_sound ⇒ BurnSpec (bal debit)
import Dregg2.Circuit.Inst.createSealPairA -- D5 v2 breadth: createSealPairA_full_sound ⇒ CreateSealPairSpec (sealedBoxes list)
import Dregg2.Circuit.Inst.delegate        -- D5 v2 breadth: delegate_full_sound ⇒ DelegateSpec (caps)
import Dregg2.Circuit.Inst.delegateAttenA  -- D5 v2 breadth: delegateAttenA_full_sound ⇒ DelegateAttenSpec (caps)
import Dregg2.Circuit.Inst.dropRefA        -- D5 v2 breadth: dropRefA_full_sound ⇒ RevokeSpec (caps)
import Dregg2.Circuit.Inst.introduceA      -- D5 v2 breadth: introduceA_full_sound ⇒ DelegateSpec (caps)
import Dregg2.Circuit.Inst.mintA           -- D5 v2 breadth: mintA_full_sound ⇒ MintASpec (bal credit)
import Dregg2.Circuit.EffectRefinement     -- D5 v2 diamond tower: generic effect2CircuitStep ⟺ apex + emitted ⟺ circuit; mint/burn instances (emitted ⟺ circuit ⟺ spec ⟺ execFullA); mint_supply_delta_descends (l4v payoff)
import Dregg2.Circuit.EffectEmittedRefinement -- Wave 2 batch emitted→spec: effect{1,2} emitted_refines_bespoke_spec + per-effect *_emitted_refines_spec diamonds
import Dregg2.Circuit.Spec.Turn            -- Wave 1 turn spec: turnSpec fold + execFullTurnA_iff_turnSpec + turnSpec_append (associativity)
import Dregg2.Circuit.ActionDispatch       -- Wave 1 apex dispatcher: fullActionStep (56/56 arms) + fullActionStep_exec_iff + actionTag
import Dregg2.Circuit.GadgetRefinement      -- Wave 1 gadget bridges: merkle/nonmembership/temporal emitted ⊑ portal; gadget_step auth witness StepRel
import Dregg2.Circuit.Poseidon2Emit         -- Wave 4: in-circuit Poseidon2 sponge compress via emitted `merkle_hash`; poseidon2_emitted_refines_merkle_portal + explicit HOLE sponges
import Dregg2.Circuit.DigestPortal         -- Wave 4: bridge `cellLeafInjective` → Poseidon2 emit / explicit CR `sorry` portals
import Dregg2.Circuit.TurnWitness          -- Wave 1 turn witness: StepWitness/TurnWitness + turnWitnessSatisfies + turn_witness_refines_turnCircuit
import Dregg2.Circuit.EffectEmitRegistry   -- Wave 2 central AIR registry: 53 Inst/commit descriptors + actionAirName (56/56)
import Dregg2.Circuit.TurnEmit             -- Wave 2 turn emission: registry-backed StepEmittedSat/turnEmittedSat + step_emitted_refines_fullActionStep + turn_emitted_refines_turnSpec/exec
import Dregg2.Circuit.TurnCircuitCompose   -- Wave 5 whole-turn composition: turnCircuitOfEmitted fold + turn_emitted_refines_exec_direct (sorry: macaroon/root-glue/multi-step)
import Dregg2.Circuit.TurnAdmission        -- Wave 5 admission gate: turnProofRequired + hole_rust_proof_at_commit (explicit sorry)
import Dregg2.Circuit.TurnRefinement      -- Wave 1 turn refinement: turnCircuitStep ⊑ turnSpec ⊑ execFullTurnA; turn_conservation_descends; TurnStateChain scaffolding
import Dregg2.Circuit.TurnEffectRefinement -- Wave 1 turn effect diamond: fullActionCircuitStep dispatch + fullAction_turn_circuit_refines_spec/exec/conservation
import Dregg2.Circuit.CircuitOpenFronts -- explicit open-front registry (Waves 3–7); no lurking holes
import Dregg2.Circuit.CoordinatedTurnRefinement -- Wave 1 inter-vat: bilateral/coordinated turn spec + circuit scaffold + charter binding
import Dregg2.Circuit.CoordinatedTurnEmit      -- Wave 1 inter-vat emission: coordinatedTurnCircuit + emittedCoordinatedTurn + emit faithfulness + spec soundness
import Dregg2.Circuit.Spec.exercise        -- Wave 1 exercise composite: re-exports ActionDispatch + execFullA_exerciseA_iff_spec
import Dregg2.Circuit.Inst.exerciseA       -- D5 v1 composite: exerciseA_full_sound ⇒ ExerciseHoldSpec; hold circuit + inner turn ⇒ ExerciseSpec
import Dregg2.Circuit.Inst.noteCreateA     -- D5 v2 breadth: noteCreateA_full_sound ⇒ NoteCreateASpec (commitments list)
import Dregg2.Circuit.Inst.noteSpendA      -- D5 v2 breadth: noteSpendA_full_sound ⇒ NoteSpendSpec (nullifiers list)
import Dregg2.Circuit.Inst.queueAllocateA  -- D5 v2 breadth: queueAllocateA_full_sound ⇒ QueueAllocateSpec (queues list)
import Dregg2.Circuit.Inst.queueEnqueueA  -- D5 v2-triple: queueEnqueueA_full_sound ⇒ QueueEnqueueSpec (queues+bal+escrows)
import Dregg2.Circuit.Inst.queueDequeueA  -- D5 v2-triple: queueDequeueA_full_sound ⇒ QueueDequeueSpec (queues+bal+escrows)
import Dregg2.Circuit.Inst.queueAtomicTxA -- D5 v2-triple: queueAtomicTxA_full_sound ⇒ QueueAtomicTxSpec (queues+bal+escrows batch)
import Dregg2.Circuit.Inst.queuePipelineStepA -- D5 v2 breadth: queuePipelineStepA_full_sound ⇒ QueuePipelineFanoutSpec (queues list)
import Dregg2.Circuit.Inst.queueResizeA    -- D5 v2 breadth: queueResizeA_full_sound ⇒ QueueResizeSpec (queues list)
import Dregg2.Circuit.Inst.pipelinedSendA   -- D5 v1 breadth: pipelinedSendA_full_sound ⇒ PipelinedSendSpec (log-only)
import Dregg2.Circuit.Inst.revoke          -- D5 v2 breadth: revoke_full_sound ⇒ RevokeSpec (caps)
import Dregg2.Circuit.Inst.revokeDelegationA -- D5 v2 breadth: revokeDelegationA_full_sound ⇒ RevokeSpec (caps)
import Dregg2.Circuit.Inst.sealA           -- D5 v2 breadth: sealA_full_sound ⇒ SealSpec (sealedBoxes list)
import Dregg2.Circuit.Inst.swissExportA    -- D5 v2 breadth: swissExportA_full_sound ⇒ ExportSpec (swiss list)
import Dregg2.Circuit.Inst.enlivenRefA     -- D5 v2 breadth: enlivenRefA_full_sound ⇒ EnlivenSpec (swiss list)
import Dregg2.Circuit.Inst.swissHandoffA   -- D5 v2 breadth: swissHandoffA_full_sound ⇒ HandoffSpec (swiss list)
import Dregg2.Circuit.Inst.swissDropA      -- D5 v2 breadth: swissDropA_full_sound ⇒ DropSpec (swiss list)
import Dregg2.Circuit.Inst.transfer        -- D5 v2 breadth: transfer_full_sound ⇒ BalanceMovementSpec (bal funcComponent)
import Dregg2.Circuit.Inst.unsealA        -- D5 v2 breadth: unsealA_full_sound ⇒ UnsealSpec (sealedBoxes list)
import Dregg2.Circuit.Inst.validateHandoffA -- D5 v2 breadth: validateHandoffA_full_sound ⇒ DelegateSpec (caps)
import Dregg2.Circuit.Inst.emitEventA      -- D5 v1 breadth: emitEventA_full_sound ⇒ EmitEventSpec (log-only, touched=∅)
import Dregg2.Circuit.Inst.incrementNonceA -- D5 v1 breadth: incrementNonceA_full_sound ⇒ IncrementNonceSpec (cell)
import Dregg2.Circuit.Inst.makeSovereignA -- D5 v1 breadth: makeSovereignA_full_sound ⇒ MakeSovereignSpec (cell rebind)
import Dregg2.Circuit.Inst.receiptArchiveA -- D5 v1 breadth: receiptArchiveA_full_sound ⇒ ReceiptArchiveSpec (cell audit)
import Dregg2.Circuit.Inst.refusalA        -- D5 v1 breadth: refusalA_full_sound ⇒ RefusalSpec (cell audit)
import Dregg2.Circuit.Inst.setPermissionsA -- D5 v1 breadth: setPermissionsA_full_sound ⇒ SetPermissionsSpec (cell)
import Dregg2.Circuit.Inst.setVKA          -- D5 v1 breadth: setVKA_full_sound ⇒ SetVKSpec (cell)
import Dregg2.Circuit.Inst.cellSealA       -- D5 v2 breadth: cellSealA_full_sound ⇒ CellSealSpec (lifecycle funcComponent)
import Dregg2.Circuit.Inst.cellUnsealA    -- D5 v2 breadth: cellUnsealA_full_sound ⇒ CellUnsealSpec (lifecycle funcComponent)
import Dregg2.Circuit.Inst.cellDestroyA    -- D5 v2-dual: cellDestroyA_full_sound ⇒ CellDestroySpec (lifecycle+deathCert)
import Dregg2.Circuit.Inst.refreshDelegationA -- D5 v2 breadth: refreshDelegationA_full_sound ⇒ RefreshDelegationSpec (delegations)
import Dregg2.Circuit.EffectInstances2   -- D5 v2 VALIDATION: mintE_full_sound ⇒ MintASpec (bal, funcComponent) + noteSpendE_full_sound ⇒ NoteSpendSpec (nullifiers list, listComponent + growing log), both re-derived THROUGH the v2 framework. Proves v2 works for BOTH non-cell shapes; the TEMPLATE for the ~25 non-cell effects
import Dregg2.Circuit.EffectInstances   -- D5 framework VALIDATION + templates: transferE/setFieldE re-derive Transfer's & setFieldA's circuit⟺spec THROUGH the generic EffectCommit framework — transferE_full_sound ⇒ TransferSpec, setFieldE_full_sound ⇒ SetFieldSpec (the bespoke specs, from realizable Poseidon-CR portals only). Proves the framework is instantiable + sound; the worked TEMPLATE the remaining ~29 effects copy (~100 lines each). #assert_axioms-clean
import Dregg2.Circuit.SetFieldCommit    -- D5 breadth (effect #2/31): FULL-STATE circuit⟺spec for setFieldA — setfield_circuit_full_sound (satisfiedSF ⇒ the full SetFieldSpec, frame reconstructed by funext) + completeness + 4 ANTI-GHOST teeth (rejects field-tamper / third-cell / wrong-target / log-forge) + concrete #guard. INJECTIVITY-only portals (compressNInjective/cellLeafInjective/RestHashIffFrame REUSED from StateCommit + logHashInjective NEW for the receipt-chain growth + AccountsWF). Confirms the generic framework shape: {restHash ⊕ frame-sponge ⊕ touched-leaf ⊕ log-hash}
import Dregg2.Circuit.StateCommit       -- D5-CORE KEYSTONE: FULL-STATE circuit⟺spec (kills the "two-balance projection" ghost). recStateCommit + injective-only portals (CombineInjective/FrameDigestBindsCells/MovedDigestBindsCells/RestHashIffFrame) + AccountsWF (PROVED preserved); transfer_circuit_full_sound (satisfiedS ⇒ FULL TransferSpec, frame RECONSTRUCTED by funext from reused frame-digest EQ gates + injectivity — NO frame/update-correctness portal) + _full_complete + ANTI-GHOST teeth (stateCircuit_rejects_third_cell / _field_tamper + concrete #guard: a forgery accepted by transferCircuit is REJECTED by stateCircuit). Frame PROVED not portaled. De-portaling (concrete Merkle/Poseidon over finite accounts) = tracked follow-up
import Dregg2.Circuit.TransferWitness   -- VERIFIABLE-EXECUTION BEACHHEAD: the WITNESS GENERATOR connecting the REAL executor (recKExec) to the full-state circuit. transferWitnessVec (execute → satisfying assignment, digest cols filled by the concrete commitment surface) + execute_produces_satisfying_witness (committed recKExec ⇒ encodeS satisfies stateCircuit, via _full_complete) + satisfying_witness_proves_full_state (sat ⇒ 18-field TransferSpec, via _full_sound). Concrete #guard: the EXECUTOR-DERIVED witness SATISFIES; the REAL forged post-state (mint bystander cell 2: 50→999) yields a witness the circuit REJECTS (frame-reuse gate 15≠16 = real UNSAT). honestWitnessJson/forgedWitnessJson = the exact executor-derived bytes the Rust lean_executor_derived_transfer prover proves+verifies / rejects. #assert_axioms-clean
import Dregg2.Circuit.TurnTransferWitness  -- WHOLE-TURN ZKP: compose per-effect proofs into ONE authenticated full-turn proof for a chained transfer FOREST. turnTransferWitnessVec runs the real chained executor (chainKernels over recKExec) + lays TWO per-step full-state witnesses + the turn-independent chain-digest columns into ONE width-44 vector. turnStateCircuit = two stateCircuit blocks (step1 offset 20) ++ rootBindGates (CLOSE the 11/12 caveat: vPreRoot/vPostRoot FORCED = cmbConcrete(compressConcrete frame moved) rest, an Expr over the digest children — tampered post-root ⇒ UNSAT) ++ chainGates (post-state of step i = pre-state of step i+1 via the turn-independent full-cell sponge allCellDig + rest digest). turn_witness_proves_both_steps (sat ⇒ BOTH steps' full TransferSpec, reusing transfer_circuit_full_sound twice) + turn_execute_produces_both_steps (chained recKExec ⇒ both step witnesses satisfy). Concrete #guard: executor-derived WHOLE-TURN witness SATISFIES turnStateCircuit (both blocks + root-bind + chain); the REAL forged FINAL post-state (mint bystander cell 0 in k₂) yields a witness the circuit REJECTS (step-1 frame-reuse gate 35≠36 = real UNSAT over the whole turn). turnHonestWitnessJson/turnForgedWitnessJson + turnStateDescriptorJson = the exact bytes the Rust lean_executor_derived_turn prover proves+verifies / rejects. #assert_axioms-clean.
import Dregg2.Circuit.Witness.DelegateWitness  -- B2 v2 WITNESS BEACHHEAD (delegate): delegateWitnessVec runs recCDelegate + lays the v2 full-state witness (width 72), digest cols from a concrete computable surface (capsDigConcrete/rhConcrete/lhConcrete); execute_produces_satisfying_witness + satisfying_witness_proves_full_state reuse delegate_full_sound/effect2_circuit_full_complete (CR portals carried). Concrete #guard: executor-derived witness SATISFIES; the REAL forged post (recipient steals node 9) yields a witness the circuit REJECTS (component-bind gate 68≠69 = real UNSAT). The v2 witness TEMPLATE.
import Dregg2.Circuit.Witness.CellSealWitness  -- B2 v2 WITNESS (cellSealA/cellUnsealA lifecycle): seal/unsealWitnessVec run execFullA + lifeDigConcrete; executor-derived witness SATISFIES; forged 3rd-cell lifecycle flip REJECTED (component-bind 68≠69). Reuses cellSeal/UnsealA_full_sound.
import Dregg2.Circuit.Witness.CreateSealPairWitness  -- B2 v2 WITNESS (createSealPairA caps): createSealPairWitnessVec runs execFullA + capsDigConcrete; executor-derived witness SATISFIES; forged 3rd-holder stolen cap REJECTED (component-bind 68≠69). Reuses createSealPairA_full_sound.
import Dregg2.Circuit.Witness.CreateEscrowWitness  -- B2 v2-dual WITNESS (createEscrowA bal+escrows): createEscrowWitnessVec runs execFullA + balDigConcrete/escDigConcrete; executor-derived witness SATISFIES; forged 3rd-cell bal mint REJECTED (comp1-bal gate 68≠69). Reuses createEscrowA_full_sound.
import Dregg2.Circuit.Witness.CreateCommittedEscrowWitness  -- B2 v2-dual WITNESS (createCommittedEscrowA bal+escrows, hidingProof gate): executor-derived witness SATISFIES; forged 3rd-cell bal mint REJECTED (comp1-bal gate 68≠69). Reuses createCommittedEscrowA_full_sound.
import Dregg2.Circuit.Witness.CreateCellWitness  -- B2 v2-triple WITNESS (createCellA accounts+bal+born-empty): executor-derived witness SATISFIES; forged 3rd-cell bal mint REJECTED (comp2-bal gate 70≠71). Reuses createCellA_full_sound.
import Dregg2.Circuit.Witness.CreateCellFromFactoryWitness  -- B2 v2-quint WITNESS (createCellFromFactoryA accounts+bal+cell+slotCaveats+born-empty-authority): executor-derived witness (facS fixture) SATISFIES; forged bystander bal mint REJECTED (comp2-bal gate 70≠71). Reuses createCellFromFactoryA_full_sound.
import Dregg2.Circuit.Witness.RefusalWitness          -- B3 v1 WITNESS (refusalA audit-slot write): refusalWitnessVec runs execFullA + lays the v1 full-state witness (width 74) via Common.layoutE/SConc; executor-derived witness SATISFIES; forged 3rd-cell mint (50→999) REJECTED (frame-reuse gate 68≠69). Rust lean_executor_derived_refusal proves+verifies / rejects. Reuses refusalA_full_sound.
import Dregg2.Circuit.Witness.ReceiptArchiveWitness   -- B3 v1 WITNESS (receiptArchiveA lifecycle-slot write): same shape as refusalA; forged 3rd-cell mint REJECTED (frame-reuse 68≠69). Rust lean_executor_derived_receipt_archive. Reuses receiptArchiveA_full_sound.
import Dregg2.Circuit.Witness.RefreshDelegationWitness -- B3 v2 WITNESS (refreshDelegationA delegations funcComponent): refreshWitnessVec runs execFullA + delegationsDigConcrete; executor-derived witness SATISFIES; forged stolen delegation cap REJECTED (component-bind 68≠69). Rust lean_executor_derived_refresh_delegation. Reuses refreshDelegationA_full_sound.
import Dregg2.Circuit.Witness.ReleaseEscrowWitness    -- B3 v2-dual WITNESS (releaseEscrowA bal+escrows): releaseWitnessVec runs execFullA + balDigConcrete/escrowsDigConcrete; executor-derived witness SATISFIES; forged minted recipient credit REJECTED (comp1-bal gate 68≠69). Rust lean_executor_derived_release_escrow. Reuses releaseEscrowA_full_sound.
import Dregg2.Circuit.Witness.RefundEscrowWitness     -- B3 v2-dual WITNESS (refundEscrowA bal+escrows, creator credit): forged minted creator credit REJECTED (comp1-bal gate 68≠69). Rust lean_executor_derived_refund_escrow. Reuses refundEscrowA_full_sound.
import Dregg2.Circuit.Witness.QueueResizeWitness      -- B3 v2 WITNESS (queueResizeA queues listComponent): resizeWitnessVec runs execFullA + queuesDigConcrete (post_queues_eq_resizePostQueues derives the apex from the conditional spec); forged buffer-tamper REJECTED (component-bind 68≠69). Rust lean_executor_derived_queue_resize. Reuses queueResizeA_full_sound.
import Dregg2.Circuit.Witness.QueuePipelineStepWitness -- B3 v2 WITNESS (queuePipelineStepA queues listComponent, message routing): pipelineWitnessVec runs execFullA + queuesDigConcrete; forged dropped-routing-message REJECTED (component-bind 68≠69). Rust lean_executor_derived_queue_pipeline_step. Reuses queuePipelineStepA_full_sound.
import Dregg2.Circuit.Witness.MintWitness            -- B4 v2 WITNESS (mintA bal funcComponent): mintWitnessVec runs execFullA + balDigConcrete; executor-derived witness SATISFIES; forged 3rd-ledger mint (50→999) REJECTED (component-bind 68≠69). Rust b4_executor_derived_mint. Reuses mintA_full_sound.
import Dregg2.Circuit.Witness.NoteCreateWitness      -- B4 v2 WITNESS (noteCreateA commitments listComponent): forged 3rd-commitment tamper REJECTED (component-bind 68≠69). Rust b4_executor_derived_note_create. Reuses noteCreateA_full_sound.
import Dregg2.Circuit.Witness.NoteSpendWitness       -- B4 v2 WITNESS (noteSpendA nullifiers listComponent, anti-replay): forged nullifier-drop (double-spend laundering) REJECTED (component-bind 68≠69). Rust b4_executor_derived_note_spend. Reuses noteSpendA_full_sound.
import Dregg2.Circuit.Witness.QueueAllocateWitness   -- B4 v2 WITNESS (queueAllocateA queues listComponent): forged bystander-queue-capacity tamper REJECTED (component-bind 68≠69). Rust b4_executor_derived_queue_allocate. Reuses queueAllocateA_full_sound.
import Dregg2.Circuit.Witness.QueueEnqueueWitness    -- B4 v3-triple WITNESS (queueEnqueueA queues+bal+escrows): forged escrow-amount tamper REJECTED (escrow bind gate 72≠73). Rust b4_executor_derived_queue_enqueue. Reuses queueEnqueueA_full_sound.
import Dregg2.Circuit.Witness.QueueDequeueWitness    -- B4 v3-triple WITNESS (queueDequeueA queues+bal+escrows, FIFO pop+refund): forged refund-ledger tamper REJECTED (bal bind gate 70≠71). Rust b4_executor_derived_queue_dequeue. Reuses queueDequeueA_full_sound.
import Dregg2.Circuit.Witness.QueueAtomicTxWitness   -- B4 v3-triple WITNESS (queueAtomicTxA all-or-nothing batch): forged FIFO-buffer tamper REJECTED (queues bind gate 68≠69). Rust b4_executor_derived_queue_atomic_tx. Reuses queueAtomicTxA_full_sound.
import Dregg2.Circuit.Witness.PipelinedSendWitness   -- B4 v1 WITNESS (pipelinedSendA touched=∅ log-only): forged bystander-cell mint (frozen-frame) REJECTED (frame-reuse gate 68≠69). Rust b4_executor_derived_pipelined_send. Reuses pipelinedSendA_full_sound.
import Dregg2.Circuit.Witness.Common                  -- B3 SHARED v1 surface: concrete CommitSurface SConc (StateCommit toy primitives + lhConcrete log hash) + layoutE (encodeE tabulated, unconstrained roots 64/65 zeroed for i64-safety) + witnessJson. The v1 witness generators' common base.
import Dregg2.Circuit.Witness.EmitEventWitness        -- B3 v1 WITNESS (emitEventA log-only touched=∅): emitEventWitnessVec runs execFullA + layoutE/SConc; executor-derived witness SATISFIES; forged receipt-row (log gate 72≠73) + minted bystander cell (frame gate 68≠69) REJECTED. Rust lean_executor_derived_emit_event. Reuses emitEventA_full_sound.
import Dregg2.Circuit.Witness.IncrementNonceWitness   -- B3 v1 WITNESS (incrementNonceA touched={cell} nonce bump): forged bystander-cell mint (frame 68≠69) + tampered receipt (log 72≠73) REJECTED (wrong-nonce rides cellLeafInjective: toy leaf=balance-only). Rust lean_executor_derived_increment_nonce. Reuses incrementNonceA_full_sound.
import Dregg2.Circuit.Witness.MakeSovereignWitness    -- B3 v1 WITNESS (makeSovereignA commitment rebind touched={cell}): the rebind MOVES the balance so touched-bind gate (70/71) is meaningful — wrong-rebound (70≠71) + bystander mint (68≠69) REJECTED. Rust lean_executor_derived_make_sovereign. Reuses makeSovereignA_full_sound.
import Dregg2.Circuit.Witness.ExerciseWitness         -- B3 v1 WITNESS (exerciseA composite hold-gate, log-only outer layer): exerciseWitnessVec runs exerciseStepA (kernel frozen + auth receipt); forged auth receipt (log 72≠73) + bystander mint (frame 68≠69) REJECTED. Rust lean_executor_derived_exercise. Reuses exerciseA_full_sound.
import Dregg2.Circuit.Witness.DelegateAttenWitness    -- B3 v2 WITNESS (delegateAttenA gated attenuated caps grant): delegateAttenWitnessVec runs execFullA (recCDelegateAtten); forged stolen-cap REJECTED (component-bind 68≠69). Rust lean_executor_derived_delegate_atten. Reuses delegateAttenA_full_sound.
import Dregg2.Circuit.Witness.DropRefWitness          -- B3 v2 WITNESS (dropRefA CapTP GC removeEdge caps): dropRefWitnessVec runs recCRevoke; forged un-revoked caps REJECTED (component-bind 68≠69). Rust lean_executor_derived_drop_ref. Reuses dropRefA_full_sound.
import Dregg2.Circuit.Witness.IntroduceWitness        -- B3 v2 WITNESS (introduceA authority-introduce caps grant): introduceWitnessVec runs execFullA (recCDelegate); forged stolen-cap REJECTED (component-bind 68≠69). Rust lean_executor_derived_introduce. Reuses introduceA_full_sound.
import Dregg2.Circuit.Witness.EnlivenWitness          -- B3 v2 WITNESS (enlivenRefA swiss-listComponent refcount bump): enlivenWitnessVec runs execFullA (swiss-enliven chain); forged un-enlivened swiss list (refcount not bumped) REJECTED (component-bind 68≠69). Rust lean_executor_derived_enliven. Reuses enlivenRefA_full_sound.
import Dregg2.Circuit.Witness.balanceAWitness        -- B1 v2 WITNESS (balanceA bal funcComponent): balanceWitnessVec runs recCexecAsset + balDigestC; executor-derived witness SATISFIES; forged bystander bal mint (50→999) REJECTED (component-bind 68≠69). Rust lean_executor_derived_balance_a. Reuses balanceA_full_sound.
import Dregg2.Circuit.Witness.burnAWitness           -- B1 v2 WITNESS (burnA bal funcComponent, debit): burnWitnessVec runs recCBurnAsset; forged bystander bal mint REJECTED (component-bind 68≠69). Rust lean_executor_derived_burn_a. Reuses burnA_full_sound.
import Dregg2.Circuit.Witness.bridgeMintAWitness     -- B1 v2 WITNESS (bridgeMintA bal funcComponent, credit): bridgeMintWitnessVec runs recCMintAsset; forged bystander bal mint REJECTED (component-bind 68≠69). Rust lean_executor_derived_bridge_mint_a. Reuses bridgeMintA_full_sound.
import Dregg2.Circuit.Witness.bridgeFinalizeAWitness -- B1 v2 WITNESS (bridgeFinalizeA escrows listComponent): bridgeFinalizeWitnessVec runs bridgeFinalizeChainA; forged un-resolved record (double-finalize laundering) REJECTED (component-bind 68≠69). Rust lean_executor_derived_bridge_finalize_a. Reuses bridgeFinalizeA_full_sound.
import Dregg2.Circuit.Witness.attenuateAWitness      -- B1 v2 WITNESS (attenuateA caps funcComponent, TOTAL): attenuateWitnessVec runs attenuateStepA; forged bystander stolen-cap (privilege escalation) REJECTED (component-bind 68≠69). Rust lean_executor_derived_attenuate_a. Reuses attenuateA_full_sound.
import Dregg2.Circuit.Witness.cellDestroyAWitness    -- B1 v2-dual WITNESS (cellDestroyA lifecycle+deathCert): cellDestroyWitnessVec runs cellDestroyChainA (width 74); forged bystander collateral-kill REJECTED (lifecycle comp-1 gate 68≠69). Rust lean_executor_derived_cell_destroy_a. Reuses cellDestroyA_full_sound.
import Dregg2.Circuit.Witness.bridgeLockAWitness     -- B1 v2-dual WITNESS (bridgeLockA bal+escrows): bridgeLockWitnessVec runs bridgeLockChainA (width 74); forged bystander bal mint REJECTED (bal comp-1 gate 68≠69). Rust lean_executor_derived_bridge_lock_a. Reuses bridgeLockA_full_sound.
import Dregg2.Circuit.Witness.bridgeCancelAWitness   -- B1 v2-dual WITNESS (bridgeCancelA bal+escrows, refund): bridgeCancelWitnessVec runs bridgeCancelChainA (width 74); forged bystander bal mint REJECTED (bal comp-1 gate 68≠69). Rust lean_executor_derived_bridge_cancel_a. Reuses bridgeCancelA_full_sound.
-- D5 executor⟺spec wave (independent declarative full-state spec + executor⟺spec per effect family; each #assert_axioms-clean):
import Dregg2.Circuit.Spec.balancemovement       -- balanceA: recCexecAsset_iff_spec + debit/credit/other-untouched + rejects unauthorized/overdraft/self
import Dregg2.Circuit.Spec.supplycreation        -- mintA: per-asset supply mint spec (supply Δ = +amt at one asset, frame elsewhere)
import Dregg2.Circuit.Spec.supplydestruction     -- burnA: per-asset supply burn spec
import Dregg2.Circuit.Spec.cellstatefield        -- setFieldA: field-write spec + full frame
import Dregg2.Circuit.Spec.cellstatemonotone     -- incrementNonceA: monotone nonce-bump spec
import Dregg2.Circuit.Spec.cellstatepermissions  -- setPermissionsA: permissions-write spec
import Dregg2.Circuit.Spec.cellstatevk           -- setVKA: verification-key-write spec
import Dregg2.Circuit.Spec.cellstateaudit        -- receiptArchiveA: archive/checkpoint spec
import Dregg2.Circuit.Spec.sovereigncommitment   -- makeSovereignA: representation-flip spec (balance-neutral)
import Dregg2.Circuit.Spec.accountgrowth         -- createCellA: fresh-cell growth spec (born empty ⇒ conservation-neutral)
import Dregg2.Circuit.Spec.factorycreation       -- createCellFromFactoryA: factory-mint spec (caveats/programVk installed)
import Dregg2.Circuit.Spec.authorityunattenuated -- introduceA: Granovetter introduce spec (non-amplifying edge)
import Dregg2.Circuit.Spec.authorityattenuation  -- attenuateA/delegateAttenA: attenuated delegation spec (granted ⊆ held)
import Dregg2.Circuit.Spec.authorityrevocation   -- revoke/dropRefA/revokeDelegationA: edge-removal spec (authority shrinks)
import Dregg2.Circuit.Spec.notenullifier         -- noteSpendA: nullifier-set insert spec (anti-replay, balance-neutral)
import Dregg2.Circuit.Spec.notecommitment        -- noteCreateA: commitment-set grow-only spec
import Dregg2.Circuit.Spec.escrowholdingcreate   -- createEscrowA: lock spec (single-cell debit + parked, combined-conserving)
import Dregg2.Circuit.Spec.escrowholdingrelease  -- releaseEscrowA: release-to-recipient spec
import Dregg2.Circuit.Spec.escrowholdingrefund   -- refundEscrowA: refund-to-creator spec
import Dregg2.Circuit.Spec.escrowcommitted       -- createCommittedEscrowA: hiding-portal-gated escrow spec
import Dregg2.Circuit.Spec.bridgeinboundmint     -- bridgeMintA: §8 portal inflow spec (disclosed +value at one asset)
import Dregg2.Circuit.Spec.bridgeoutboundlock    -- bridgeLockA: outbound lock spec (debit + parked bridge record)
import Dregg2.Circuit.Spec.bridgeoutboundfinalize -- bridgeFinalizeA: outbound burn spec (combined measure drops, disclosed outflow)
import Dregg2.Circuit.Spec.sealpaircreation      -- createSealPairA: two c-list grants spec (sealer/unsealer caps)
import Dregg2.Circuit.Spec.sealboxoperations     -- sealA/unsealA: capability box bind/move spec
import Dregg2.Circuit.Spec.queuepipelinedsend    -- queueEnqueueA + deposit: FIFO append + parked deposit spec (combined-conserving)
-- D5 executor⟺spec wave-2 (repaired harder families — root cause was a missing `open Dregg2.Exec.EffectsState (stateAuthB)` that cascaded into leaked sorryAx; gate-verified green + #assert_axioms-clean):
import Dregg2.Circuit.Spec.cellstatelog          -- emitEventA: event/log-append spec + full frame (balance-neutral, no authority gate beyond cell-existence)
import Dregg2.Circuit.Spec.swissexport           -- exportSturdyRefA: CapTP sturdy-ref mint spec (swissExportK; non-amplifying rights ⊆ held, no-dup, balance-neutral)
import Dregg2.Circuit.Spec.queuefifocore         -- queueAllocate/Resize/Enqueue/DequeueA: the 4 FIFO ring-buffer ops (insert-fresh / no-id-reuse / no-shrink-below-occupancy / dead-cell-rejection, balance-neutral)
import Dregg2.Circuit.Spec.queuepipelinefanout   -- queuePipelineStepA: atomic dequeue→fanout-enqueue pipeline step spec
import Dregg2.Circuit.Spec.bridgeoutboundcancel  -- bridgeCancelA: timeout-refund spec (credit originator + resolve, combined-conserving)
import Dregg2.Circuit.Spec.celllifecycle       -- cellSealA/cellUnsealA/cellDestroyA: Live↔Sealed↔Destroyed lifecycle spec
import Dregg2.Circuit.Spec.refreshdelegation     -- refreshDelegationA: parent c-list snapshot into delegations
import Dregg2.DSLEffect                -- `dregg_effect <name> : <Class>` effects eDSL → Spec.Conservation LinearityClass coloring + inherited obligation; #assert_namespace_axioms-clean
import Dregg2.Exec.Gas                  -- gas-metering layered beside execFullTurn: gasCost_pos (no free action) + gas_exhaustion_fails_closed (over-budget ⇒ none, no partial mutation) + gas_sufficient_runs (pure guard, identical state) + gas_conserves/_preserves_attests (removes no safety); Nat-resource orthogonal to ℤ-conservation
import Dregg2.Proof.BeaconSpaceInterior -- interior-h non-vacuity witness: Measure.infinitePi (Bernoulli 3/4)^ℕ at h=3/4, indep_block via infinitePi_pi; BeaconSpace is non-vacuously instantiable at a genuine interior honest-fraction
import Dregg2.Exec.ProofForest         -- proof-carrying forest composition: per-node StepProofValid × Linked ⇒ whole-run StepInv via execForest_attests; aggregation deferred
import Dregg2.Exec.TriDomain            -- tri-domain conservation (balance + authority + metadata): triConserved_of_execFull; the three domains that dregg1's atomic.rs enforces conserve independently
import Dregg2.Exec.AuthModes           -- 6 authorization modes (OneOf/Custom/CapTpDelivered/Bearer/Token/Unchecked) with witness dispatch + soundness; captp_granted_le_held proves non-amplification
import Dregg2.Exec.EffectTransfer      -- Transfer effect vertical-slice reference template: conserves → authorized → metadata → forward-sim (AbsStep); the pattern remaining effects instantiate
import Dregg2.Spike.TransferAirSoundness -- real air.rs:473 Transfer constraint over BabyBear: field-constraint+range ⇒ ℤ balance update + transfer_underflow_attack (off-circuit wrap gap, now closed in-circuit by the RANGECHECK lane)
import Dregg2.Exec.EffectsPaired       -- Conservative/Paired effects (escrow/notes/obligations/queues/bridge-Σ=0) via the EffectTransfer template; generic pairedStep spine
import Dregg2.Exec.EffectsSupply       -- Generative/disclosed-supply effects (CreateCell/Factory/Spawn/BridgeMint/Lock/Cancel/Finalize); foreign-finality §8-portal
import Dregg2.Exec.EffectsAuthority    -- authority-edit effects (Introduce/Attenuate/Exercise/ValidateHandoff/Refresh/Drop/SetPermissions/RevokeDelegation), each with non-amplification
import Dregg2.Exec.EffectsState        -- Neutral/Monotonic/Terminal field+lifecycle effects (setField/seal/sovereign/emit/refusal/archive/destroy/refs…) via the generic field-write + non-interference
import Dregg2.Spec.ExecRefinementFull  -- general forward-sim refinement: exec_full_refines_spec (every execFull step is a permitted abstract step) + full operational square; whole-history closure OPEN
import Dregg2.Exec.ConditionalTurn     -- executable conditional/await turns: execConditionalTurn (topo-sort + EventualRef slots) + condTurn_conserves/_atomic/_dependency_sound/_forward_sim; EventualRef read ↔ Await.Op.await
import Dregg2.Spike.EffectVmConstraints -- real EffectVmAir constraints in Lean: selector exactly-one, NoOp identity, transfer hi/dir, balance-lo range soundness, nonce tick; underflow_now_impossible proves the RANGECHECK closes the wrap gap
import Dregg2.Proof.CordialMiners       -- Cordial-Miners DAG-BFT model (dregg1's actual consensus): cordial_agreement (no two conflicting committed leaders) + cordial_agreement_from_lace (SuperRatification derived); liveness/GST/dissemination/Stingray OPENs
import Dregg2.Spike.EffectVmConstraints2 -- more EffectVmAir constraints: SetField per-field gating + balance_hi range-soundness + state_commitment binding-shape (hash as §8 portal); setfield_aux_honesty_gap (SetField intended-value rests on an off-circuit free aux column — a known gap, as a theorem)
import Dregg2.Proof.Stingray            -- concurrent-spend budget slice: sliceCeiling = balance·(f+1)/(2f+1); stingray_no_concurrent_overspend + stingray_schedules_disagree (concrete two-schedule counterexample) + inbudget_both_commit_schedule_agnostic (in-budget = coordination-free); f=0 ⇒ ceiling=balance degenerate case
import Dregg2.Proof.Temporal            -- temporal logic over the living cell: □/◇/◯ on execFullForestA trajectories + proof algebra + always_of_reachable_invariant bridge; always_conserved + always_logMono + always_revoked_persists + always_conj_safety (□(conservation ∧ log-append-only ∧ revoked-persist))
import Dregg2.Proof.CTL                  -- Track B: branching-time CTL — EX/AX/EU/AU/EF/AF/EG/AG as named OrderHom.lfp/gfp over Set System.Config; fixpoint/monotone/duality laws; EF↔Reachable + AG↔Temporal.always cross-checks; SAFETY fragment + branching teeth (EX p ≠ AX p, EF p ≠ AF p on a Fin-3 system). AF/EG LIVENESS reading deferred to the justness gate (stutter self-loop ⇒ needs just-paths; see INTENT-REFS-fairness.md)
import Dregg2.Proof.MuCalculus           -- Track B: shallow modal-μ embedding over System; μ/ν as lfp/gfp of the interpretation; the CTL-encoding theorems (encode_EX/EF/AG/… each CTL op = its named μ-formula, proved) + a fixpoint-alternation example
import Dregg2.Proof.Fairness             -- Track D: van Glabbeek JUSTNESS over the reactive turn-executor — Just (Def-6 port) + EnabledAt (isSome-commit) + npcA/afcA concurrency relation + just_progress (the genuine ◇, justness ∧ progress-enabled ⟹ Eventually); commits_stable_off_npc stutter-half PROVED + universal half carried as JustLTSC.commits_stable field, de-vacuified by commits_stable_concrete; teeth badSched_not_just (unjust schedule starves an enabled cell) + refundDemo. cellNextA stutter self-loop is why fairness, not progress, is needed
import Dregg2.Proof.CTLLiveness          -- Track B liveness (the justness gate, now answered): AF_just/EG_just restrict CTL's deferred AF/EG path-quantifiers to van Glabbeek-just schedules; livingAF_just_progress derives the genuine ∀◇ from Fairness.just_progress, bridged back into CTL.EF via EF_iff_reachable; teeth af_just_separates_plain (a just schedule reaches Pgoal but NOT every schedule does — the stutter branch is excluded only by justness)
import Dregg2.Proof.Noninterference      -- Track C: confidentiality / seL4-Volpano-Smith — balance = HIGH (ember-locked, sealed-bid secrecy); lowEq over RecChainedState (HIGH = balance/amount/secret, LOW = metadata); unwinding K1 (LOW-write of LOW-derived preserves lowEq) + K2 (HIGH-write confined); teeth makeSovereign_leaks (writes LOW commitment = hash of whole HIGH pre-state ⇒ provable LEAK). Honest scope: transfers are declassifiers under HIGH, only the genuine slice proved
import Dregg2.Authority.CaveatChain      -- real macaroon HMAC append-only chain: verify_iff_wellTagged + append_narrows + integrity_tail_binds + forgery_requires_mac_query (forge ⇒ break-HMAC) + removal_breaks_tail; HMAC = §8 MacKernel portal
import Dregg2.Authority.ThirdPartyDischarge -- real third-party discharge protocol: accepts_iff (ticket/VID key-recovery ∧ bind-to-parent ∧ freshness ∧ predicate) + honest_discharge_accepted + rejection teeth; AEAD = §8 portal
import Dregg2.Authority.SelectiveDisclosure -- hidden-attribute predicate proofs (Gte/Lte/InRange) + selective reveal + anonymous unlinkable multi-show wired to credentials; ZK soundness = §8 portal
import Dregg2.Authority.DesignatedVerifier -- verifier-indexed DischargedFor + transferability dial (public = ∀V ⇒ non-repudiable; designated = V₀-only ⇒ deniable via the simulator property); DV-ZK = §8 portal
-- ── RELATIVISTIC TIME-TYPING (INTENT-AS-CO-RECEIPT.md §4): causal (lightcone, on the lace) vs frame (attested, with explicit δ) — the constructive/classical split applied to time. ──
import Dregg2.Time.Causal       -- causal_after(E) = E ≺ now over the lace partial order (Blocklace.precedes): MONOTONE (causalAfter_mono) + frame-INVARIANT (causalAfter_no_authority, no oracle) + NON-TOTAL (a Byzantine fork is concurrent, neither causally before — real teeth); the lightcone-fact deadline carrying NO §8 carrier
import Dregg2.Time.Frame        -- frame_within(F,T,δ) = a TimeAuthority's attested wall-clock frame, a Temporal WitnessedPredicate: frameWithin_sound (accepted attestation discharges via registry_sound) + frameWithin_false_without_authority (NOT true-for-free) + discharge_skew_is_explicit (the retyped MAX_DISCHARGE_AGE carries δ=300 first-class); FrameHonesty = the explicit §8 skew carrier (proved non-trivial, never True)
import Dregg2.Time.Deadline     -- the Deadline sum type FORCING the distinction (causalAfter_no_frame_dependency = Iff.rfl vs frameWithin_has_frame_dependency = flips across registries) + commit_wait_bridge (THE keystone: frame ∧ waited(2δ) ∧ honesty ⟹ causal — Spanner external consistency; "wait out the skew, frontrunning is causally excluded") + commit_wait_needs_full_2delta (the 2δ is load-bearing, a concrete counter-world)
-- Track A Phase 2 — intent-as-co-receipt (over the Phase-1 time foundation above):
import Dregg2.Intent.Resource    -- resource theory (Coecke–Fritz SMC) + convertibility preorder ⪰ = the match relation (Nonempty (a⟶c)); refl/trans/⊗-monotone; demo asset-bundle Discrete SMC with teeth (res_no_convert)
import Dregg2.Intent.Core        -- the four-faced Intent (offered/wanted boundary · predicate demand · escrow lockbox · Deadline validity); fulfill = the receipt⊣intent counit; fulfill_discharges keystone (outcome=wanted + predicate-satisfied + escrow consumed) + fulfill_conserves + no_double_fulfill; teeth on all four faces; causal-validity met for free
import Dregg2.Intent.Match       -- the solver as mathlib's coend ∫^B (A⟶B)×(B⟶C) (Types.coend over the offer profunctor): oneHop/twoHop non-vacuity + multi-hop typechecks + match_of_converts; the bilateral LensFill (get/put optic, the auction path) embeds as a one-hop route; co-Yoneda collapse PROVED — collapseIso : Match A C ≅ (A⟶C) (density via Quot.sound on the coend), so match_iff_converts
import Dregg2.Intent.Kernel      -- concrete KernelIntent over asset-bundle DreggResources: settle_discharges/settle_conserves/settle_no_double = the abstract keystones TRANSFERRED by instantiation; crossBid_needs_market (cross-asset bid unfillable w/o Phase-4 market offers); causal reveal-ordering = anti-frontrunning
import Dregg2.Intent.Centers     -- Phase-3 (escrow KEPT SEPARATE from one-shot Intent escrow): CommCentralMonoid := CommMon_(Center R); escrowMonad (–⊗M) + escrowMonad_isMonoidal (Thm 5.6, lax-monoidal for ANY braided monoid — NO mul_comm needed); escrowMonadHom = FLP Cor 3.11 monad morphism (–⊗𝟙_)⟹id (component=Prod.fst, not 𝟙) + escrowProjectionEquiv = Cor 3.20 rigidity equivalence; teeth = noncommuting_admits_no_halfBraiding (§4 centrality) + escrow_no_iso_without_rigidity (§7.3); mathlib Center/CommMon_/Rigid reuse
import Dregg2.Metatheory.Lawvere -- Track K: the Lawvere hyperdoctrine triple ∃_f⊣f*⊣∀_f — Part A posetal Set special case (Set.image_preimage/preimage_kernImage + Frobenius via image_inter_preimage + Beck-Chevalley; teeth: BC fails off-pullback, non-monotone reindex breaks Galois) + Part B the faithful relation-form ∀_R=Knows (□/◇ adjunction for ANY relation, contains Part A via the graph; teeth: S4 □□≠□ + ◇ fails binary meets on a Byzantine reflexive-non-transitive Fin 3 relation). K8 dual-H¹ PARKED
import Dregg2.Metatheory.IndexedMonoidal -- the WELD (linear/dependent doctrine FLOOR): IndexedMonoidalCategory (base ⥤ Cat, monoidal fibres, lax reindexing) + Total = Grothendieck; concrete dreggIM (Ctx poset base + non-injective dropArt reindexing + Discrete Bundle ⊗-fibres) carries BOTH the ∃_f⊣f*⊣∀_f reindexing adjoints AND the fibrewise resource ⊗ on ONE total category; projection/Frobenius interaction (equality for the Set fibre, honest lax ⊆ for general relations + frobenius_eq_fails teeth); weldMorphism = one ∫F arrow touching both the predicate base and the resource fibre
import Dregg2.Intent.KernelBridge -- TOY-REMEDIATION: the DemoRes Intent settle REFINES the real RecordKernelState per-asset conservation — toBal (bundle→bal delta) + settleIntent_refines + bridge_accepts_iff_conserves; teeth crossBid_rejected_by_bridge / bridge_rejects_nonconserving (a non-conserving settle the thin shadow would pass is caught by the real ledger)
import Dregg2.Consistency               -- global soundness witness: dregg_consistent_nonempty = a single axiom-clean SystemModel instantiating all 11 Prop-carriers jointly; no carrier-pair derives False; not vacuous, not contradictory at the system level
import Dregg2.HandlerTransformer        -- higher-order handler-transformer: SafeStep preorder + instSafeStepFpu (camera Fpu = safe-composition instance) + safe_transformer_composes + conservation_is_safe_transformer + overshare_rejected (unsafe transformer is genuinely refused); unifies 'safe handler-transformer' with 'frame-preserving update' (Iris handler frame-rule); Fpu=gluing weld + comodel-morphism/sheaf-of-handlers tier are OPENs
import Dregg2.Confluence.DriftStable     -- drift-stable bridge: IConfluentUnder (conditional drift-stability = confluence in the sublattice E cuts out) + driftStable_composes (an I-confluent caveat survives forward drift, no re-check) + locked_driftStable (single-writer collapses merge ⇒ any φ drift-stable) + teeth (monotone composes free; bounded_caveat_needs_coordination) + TieredCaveat (carry the tier-proof, dispatch on DriftTier); #assert_axioms-clean, #eval non-vacuity
import Dregg2.Exec.CoordinatedCaveat     -- Track F (completes it): promotes DriftStable's fail-closed DriftTier.coordinated (DriftWitness=PUnit) onto the proved CrossCaveat equalizer — coordinated_discharge_sound (CG-5 ∧ CG-2 ∧ φ-on-snapshot) + coordinated_no_toctou(_atomic) + coordinated_refines_failclosed + the bridge coordinated_tier_discharges_via_equalizer; teeth = overbroad_discharge_rejected. Single-machine equalizer (distributed variant OPEN)
import Dregg2.Exec.CoordinatedForestGate -- joint-layer bilateral equalizer: execBilateralCoordinated + execBilateralCredGated (coordinated covenant + per-leg credentials); intra-cell `.coordinated` still fail-closed on single-cell nodes
import Dregg2.Exec.CrossVatCharter       -- cross-vat charters as the common bilateral+credential pattern: charterDischarge + charterBilateral + per-leg biscuits; production cross-cell maneuver surface
import Dregg2.Exec.JointCharterBridge    -- charter↔bilateral bridge: charterDischarge refines execBilateralCoordinated; the common cross-vat wiring spine for Apps + regression
import Dregg2.Exec.CoordinatedForestGLift -- RecChainedState lift: execCoordinatedForestG / execCoordinatedForestCredG over BilateralForestPairG; charter_refines_coordinated_forest; honest positive path beside intra-cell fail-closed
-- ── THE HATCHERY (HATCHERY.md H1–H4): the verification toolkit — one-step proof ⇒ "forever, every adversary" free; the userspace smart-contract verification surface. ──
import Dregg2.Verify.Frames     -- Tier 2: the [Dregg2] aesop rule-set's forest-monotone frame family + cellNextA_carries_rel (the reusable one-step body subsuming every grow-only crown — log.length ≤ and registry ⊆ alike, via Trans)
import Dregg2.Verify.Tactics    -- Tier 1: carry_forever (livingCellA_carries plumbing) + exec_frame (executor split; UNIVERSAL stay-put arm; frame/grow commit arm; HONEST hand-back — never fakes a close, proven by logMono_handback_demo); gate reproduces the logMono + revoked-forever crowns via the tactics
import Dregg2.Verify.Contract   -- Tier 3: first-class CellContract (Inv + step_ob) → forever (livingCellA_carries) + always (the REAL LTL □ via Proof.Temporal.always_of_step_invariant); three concrete contracts discharged through the engine
import Dregg2.Verify.Catalog    -- Tier 4: declarative shape macros monotone_registry% / conservation% / confinement% / automaton_inv% → real CellContracts (confinement surfaces its control∈U hypothesis honestly; automaton_inv is genuinely relational, obs a + obs b)
import Dregg2.Verify.Regression -- H4 gate: six shipped crowns (identity_revoked_forever / no_double_spend / commitments_persist / …) reproduced via the catalog with both-directions defeq witnesses vs the hand proofs
import Dregg2.Verify.LivenessBridge   -- production liveness lift: `EventuallyG` + erasure bridge + `transferSchedG`
import Dregg2.Verify.LivenessContract  -- Hatchery liveness tier: `eventually%` + justness bridge
import Dregg2.Verify.ChoreographyBridge -- blue ↦ `CellContract.forever`, red ↦ `HyperAdmissible`
import Dregg2.Verify.JointRegression    -- cross-vat charter regression: joint_charter_commits + joint_forged_cred_rejected + joint_covenant_teeth + joint_cg5_conserved
import Dregg2.Verify.AppComposition     -- cross-app composed crown: agent_mandate_safety_forever (CWM ∩ SGM ∩ Identity on trajG)
import Dregg2.Verify.DemoRegressGated   -- H4 gate on production `trajG` (six crowns, catalog + tactics)
-- ── THE WEB-CITIZEN SURFACE: ProofWidgets driven by REAL Lean terms (no placeholder data — the prime directive). ──
import Dregg2.Widget.Basic             -- shared Html helpers + the trust-badge classifier: tier read off Lean.collectAxioms (KernelChecked / CarrierBounded / ExtraAxioms) — cannot be hand-faked; 2 by-design demo axioms exhibit the amber carrier-bounded tier
import Dregg2.Widget.ProofBadgeGallery -- tabulates the collectAxioms trust verdict over real theorems (green) vs a synthetic carrier-bounded demonstrator (amber)
import Dregg2.Widget.ConservationLedger -- per-asset bal deltas (Recharts) of the REAL committed transferCF-over-fma0 turn; conservation badged via recKExecAsset_conserves_per_asset
import Dregg2.Widget.CapabilityGraph   -- the Granovetter capability graph (InteractiveSvg) over a real Caps table; granted≤held non-amplification badged
import Dregg2.Widget.DreggForest       -- the call-forest (GraphDisplay) off a real FullForestA value; nodes = effects, edges = delegation
import Dregg2.Widget.ContractView      -- a verified guarantee rendered as a card: the invariant + the forever theorem's collectAxioms trust tier
