/-
# EmitRotationV3SetFieldValue8 — the STAGED setField VALUE8 epoch wire-artifact emit executable
(sibling of `EmitRotationV3.lean`).

Prints one TSV line per value8 member from the verified emission
(`Dregg2/Circuit/Emit/EffectVmEmitRotationV3.v3RegistrySetFieldValue8`):

  `<key>\t<descriptor.name>\t<emitVmJson2 descriptor>`

so the staged Rust artifact `circuit/descriptors/rotation-v3-setfield-value8-staged-registry.tsv` can
be regenerated byte-for-byte from the verified Lean emit.

STAGED / ADDITIVE: the 8 `setFieldValue8VmDescriptor2-{slot}R24` members swap the deployed freeze-ALL
setField wrap (`v3OfFrozen (setFieldTickFace slot)`) for the freeze-EXCEPT + VALUE8-completion-pin wrap
(`withSetFieldCompletionPins slot (setFieldV3 slot)`). This CLOSES the R1 large-value completeness seam
(`setfield_completion_lane_forge::honest_large_value_setfield_fails_the_deployed_freeze`) AND binds the
written slot's high 224 bits into the light-client PI view (the ORPHAN-SWEEP §5.2 VALUE8 residual). It
is a NEW set BESIDE `v3RegistryBare` — the live `rotation-v3-staged-registry.tsv` / VK are byte-
untouched, so adoption is a controlled epoch re-point (one-tx, non-destructive; old epochs stay
verifiable).

SCRATCH executable: run with `lake env lean --run EmitRotationV3SetFieldValue8.lean`.
-/
import Dregg2.Circuit.Emit.EffectVmEmitRotationV3Refused

open Dregg2.Circuit.DescriptorIR2 (emitVmJson2)
open Dregg2.Circuit.Emit.EffectVmEmitRotationV3Refused (v3RegistrySetFieldValue8)

def main : IO Unit := do
  for (key, d) in v3RegistrySetFieldValue8 do
    IO.println s!"{key}\t{d.name}\t{emitVmJson2 d}"
