/-
# EmitRotationV3 — the staged ROTATION wire-artifact emit executable (sibling of
`EmitAllJsonV2.lean`).

Prints two TSV lines from the verified rotation emission
(`Dregg2/Circuit/Emit/EffectVmEmitRotation.lean`):

  `rotationLayoutManifest\t<manifest json>`
  `rotationProbeVmDescriptor2\t<descriptor.name>\t<emitVmJson2 descriptor>`
  `rotationProbeVmDescriptorR24\t<name>\t<json>`   (the register-count measurement probes —
  `rotationProbeVmDescriptorR32\t<name>\t<json>`    `EffectVmEmitRotationR.lean`)

so the staged Rust artifacts (`circuit/descriptors/rotation-layout-v3-staged.json`,
`circuit/descriptors/dregg-effectvm-rotation-state-v3-staged.json` and the R=24/R=32
`…-staged-r{24,32}.json` measurement probes) can be regenerated byte-for-byte from the
verified Lean emit. STAGED: nothing rides the live v1 wire — the Rust consumers are the
recursion-gated IR-v2 path + the drift guards
(`effect_vm_descriptors.rs::rotation_layout_matches_lean` / `v3_staged_*`). SCRATCH
executable: run with `lake env lean --run EmitRotationV3.lean`.
-/
import Dregg2.Circuit.Emit.EffectVmEmitRotation
import Dregg2.Circuit.Emit.EffectVmEmitRotationR
import Dregg2.Circuit.Emit.EffectVmEmitRotationCaveat
import Dregg2.Circuit.Emit.EffectVmEmitRotationV3

open Dregg2.Circuit.DescriptorIR2 (emitVmJson2)
open Dregg2.Circuit.Emit.EffectVmEmitRotation
open Dregg2.Circuit.Emit.EffectVmEmitRotationR (rotationProbeVmDescriptorR2)
open Dregg2.Circuit.Emit.EffectVmEmitRotationCaveat
  (rotationCaveatLayoutManifest rotationCaveatProbeVmDescriptor2)
open Dregg2.Circuit.Emit.EffectVmEmitRotationV3 (v3Registry)

def main : IO Unit := do
  IO.println s!"rotationLayoutManifest\t{rotationLayoutManifest}"
  IO.println
    s!"rotationProbeVmDescriptor2\t{rotationProbeVmDescriptor2.name}\t{emitVmJson2 rotationProbeVmDescriptor2}"
  IO.println
    s!"rotationProbeVmDescriptorR24\t{(rotationProbeVmDescriptorR2 24).name}\t{emitVmJson2 (rotationProbeVmDescriptorR2 24)}"
  IO.println
    s!"rotationProbeVmDescriptorR32\t{(rotationProbeVmDescriptorR2 32).name}\t{emitVmJson2 (rotationProbeVmDescriptorR2 32)}"
  IO.println s!"rotationCaveatLayoutManifest\t{rotationCaveatLayoutManifest}"
  IO.println
    s!"rotationCaveatProbeVmDescriptor2\t{rotationCaveatProbeVmDescriptor2.name}\t{emitVmJson2 rotationCaveatProbeVmDescriptor2}"
  -- THE FULL-COHORT REGEN (ROTATION-CUTOVER §5 item 1): all 26 v2Registry members at the
  -- rotated R=24 block — `key\tname\tjson`, the byte source of
  -- `circuit/descriptors/rotation-v3-staged-registry.tsv`.
  for (key, d) in v3Registry do
    IO.println s!"v3rot\t{key}\t{d.name}\t{emitVmJson2 d}"
