/-
# EmitUMemCohortMulti — the staged MULTI-DOMAIN UMEM-FORM cohort wire-artifact emit executable
(sibling of `EmitUMemCohort.lean`).

Prints one TSV line per multi-domain cohort member from the verified umem-form emission
(`Dregg2/Circuit/Emit/EffectVmEmitUMemCohortMulti.lean`):

  `<lean_def_name>\t<descriptor.name>\t<emitVmJson2 descriptor>`

so the staged Rust artifact `circuit/descriptors/umem-cohort-multidomain-v1-staged-registry.tsv`
can be regenerated byte-for-byte from the verified Lean emit. STAGED: a NEW staged set beside the
single-domain `umem-cohort-v1-staged-registry.tsv` and the deployed per-map v1 — nothing rides the
live wire, no VK bump, `umem_witness_enabled` untouched.

SCRATCH executable: run with `lake env lean --run EmitUMemCohortMulti.lean`.
-/
import Dregg2.Circuit.Emit.EffectVmEmitUMemCohortMulti

open Dregg2.Circuit.DescriptorIR2 (emitVmJson2)
open Dregg2.Circuit.Emit.EffectVmEmitUMemCohortMulti (umemCohortMultiRegistry)

def main : IO Unit := do
  for (key, d) in umemCohortMultiRegistry do
    IO.println s!"{key}\t{d.name}\t{emitVmJson2 d}"
