/-
# EmitAllJsonV2 — the IR-v2 descriptor-registry emit executable (the EPOCH flag-day sibling of
`Dregg2/Circuit/Emit/EmitAllJson.lean`).

Prints, for each entry of the verified `v2Registry` (the 26 graduated v2 descriptors), a line

  `<LEAN_DEF_NAME>\t<descriptor.name>\t<emitVmJson2 descriptor>`

so the Rust v2 registry (`circuit/src/effect_vm_descriptors.rs`, the additive v2 block) can be
regenerated byte-for-byte from the verified Lean v2 emit. Each wire string is versioned (`"ir":2`)
with the five EPOCH tables + the lookup/mem-op/map-op constraint grammar that `descriptor_ir2.rs`
interprets. SCRATCH executable: run with `lake env lean --run EmitAllJsonV2.lean`.

NOTE: the v2Registry's descriptor `.name` is INHERITED from the graduated v1 descriptor (e.g. the
graduated transfer keeps `dregg-effectvm-transfer-v1`), so the wire identity is the SAME object the
v1 path names — the `"ir":2` key + the `tables` manifest are what distinguish the v2 wire. The Rust
side keys these by the registry def-name suffix (e.g. `transfer`) into `-ir2.json` files, ALONGSIDE
the v1 JSONs (NOT replacing them) for the transition.
-/
import Dregg2.Circuit.Emit.EffectVmEmitV2

open Dregg2.Circuit.DescriptorIR2 (emitVmJson2)
open Dregg2.Circuit.Emit.EffectVmEmitV2 (v2Registry)

def main : IO Unit := do
  for (defName, d) in v2Registry do
    IO.println s!"{defName}\t{d.name}\t{emitVmJson2 d}"
