/-
# EmitRotationV3 — the staged ROTATION wire-artifact emit executable (sibling of
`EmitAllJsonV2.lean`).

Prints two TSV lines from the verified rotation emission
(`Dregg2/Circuit/Emit/EffectVmEmitRotation.lean`):

  `rotationLayoutManifest\t<manifest json>`
  `rotationProbeVmDescriptor2\t<descriptor.name>\t<emitVmJson2 descriptor>`
  `rotationProbeVmDescriptorR24\t<name>\t<json>`   (the register-count measurement probes —
  `rotationProbeVmDescriptorR32\t<name>\t<json>`    `EffectVmEmitRotationR.lean`)

so the staged Rust artifacts (`circuit/descriptors/rotation-layout-v3-staged.json`,
`circuit/descriptors/dregg-effectvm-rotation-state-v3-staged.json` and the R=24/R=32
`…-staged-r{24,32}.json` measurement probes) can be regenerated byte-for-byte from the
verified Lean emit. STAGED: nothing rides the live v1 wire — the Rust consumers are the
recursion-gated IR-v2 path + the drift guards
(`effect_vm_descriptors.rs::rotation_layout_matches_lean` / `v3_staged_*`). SCRATCH
executable: run with `lake env lean --run EmitRotationV3.lean`.
-/
import Dregg2.Circuit.Emit.EffectVmEmitRotation
import Dregg2.Circuit.Emit.EffectVmEmitRotationR
import Dregg2.Circuit.Emit.EffectVmEmitRotationCaveat
import Dregg2.Circuit.Emit.EffectVmEmitRotationV3
import Dregg2.Circuit.Emit.CapOpenEmit
import Dregg2.Circuit.Emit.CapOpenTurnPins
-- The WRITE-BEARING tail (`v3RegistryHeap` positions 45..49): the apex-proven, registry-deployed
-- heapWrite Class-A descriptor + the 4 write-forcing cap-open wrappers. Emitted PAST the 45 cap-open
-- members so the checked-in wire carries exactly what the circuit-soundness apex proves about
-- (guarantee A: the cap-tree / heap-root WRITE forced, not the authority-read-only wrapper).
import Dregg2.Circuit.RotatedKernelRefinementExercise

open Dregg2.Circuit.DescriptorIR2 (emitVmJson2)
open Dregg2.Circuit.Emit.EffectVmEmitRotation
open Dregg2.Circuit.Emit.EffectVmEmitRotationR (rotationProbeVmDescriptorR2)
open Dregg2.Circuit.Emit.EffectVmEmitRotationCaveat
  (rotationCaveatLayoutManifest rotationCaveatProbeVmDescriptor2)
open Dregg2.Circuit.Emit.EffectVmEmitRotationV3 (v3Registry)
open Dregg2.Circuit.Emit.CapOpenEmit (v3RegistryCapOpen)

def main : IO Unit := do
  IO.println s!"rotationLayoutManifest\t{rotationLayoutManifest}"
  IO.println
    s!"rotationProbeVmDescriptor2\t{rotationProbeVmDescriptor2.name}\t{emitVmJson2 rotationProbeVmDescriptor2}"
  IO.println
    s!"rotationProbeVmDescriptorR24\t{(rotationProbeVmDescriptorR2 24).name}\t{emitVmJson2 (rotationProbeVmDescriptorR2 24)}"
  IO.println
    s!"rotationProbeVmDescriptorR32\t{(rotationProbeVmDescriptorR2 32).name}\t{emitVmJson2 (rotationProbeVmDescriptorR2 32)}"
  IO.println s!"rotationCaveatLayoutManifest\t{rotationCaveatLayoutManifest}"
  IO.println
    s!"rotationCaveatProbeVmDescriptor2\t{rotationCaveatProbeVmDescriptor2.name}\t{emitVmJson2 rotationCaveatProbeVmDescriptor2}"
  -- THE FULL-COHORT REGEN (ROTATION-CUTOVER §5 item 1): all 26 v2Registry members at the
  -- rotated R=24 block — `key\tname\tjson`, the byte source of
  -- `circuit/descriptors/rotation-v3-staged-registry.tsv`.
  -- THE FULL 37-MEMBER REGISTRY (`v3RegistryCapOpen` = the 36 cohort members + the cap-open
  -- authority member as the 37th). Looping over the cap-open registry emits the 36 cohort lines
  -- then the cap-open line `attenuateCapOpenVmDescriptor2R24` — byte-identical to the prior
  -- "loop v3Registry then emit capOpen" shape, now from ONE source of truth (the apex's `Rfix`
  -- re-keys over THIS list, so the wire and the committed registry coincide).
  for (key, d) in v3RegistryCapOpen do
    IO.println s!"v3rot\t{key}\t{d.name}\t{emitVmJson2 d}"
  -- THE TURN-IDENTITY WELD (CapOpenTurnPins): the transfer cap-open PLUS the three turn-identity PI
  -- pins welding `capOpenCols.src`/`actor`/`dst` to published PIs (the in-circuit realization of
  -- `TurnIdentityBound`/`hsrc`). Emitted as a NEW member (`transferCapOpenTBVmDescriptor2R24`) so the
  -- PROVEN turn-pinned descriptor rides the wire and the drift gate covers it. The cutover routing the
  -- live transfer cap-open through THIS (the prover's column-fill + the verifier's turn-identity PI
  -- anchor) is the named remaining integration — see CapOpenTurnPins / proof_verify.
  let transferCapOpenTB : Dregg2.Circuit.DescriptorIR2.EffectVmDescriptor2 :=
    Dregg2.Circuit.Emit.CapOpenTurnPins.effCapOpenV3TB
      Dregg2.Circuit.Emit.CapOpenEmit.transferV3
      "dregg-effectvm-transfer-v1-rot24-v3-capopen-eff-tb" Dregg2.Circuit.Emit.CapOpenEmit.EFF_TRANSFER
  IO.println s!"v3rot\ttransferCapOpenTBVmDescriptor2R24\t{transferCapOpenTB.name}\t{emitVmJson2 transferCapOpenTB}"
  -- THE WRITE-BEARING TAIL (`v3RegistryHeap` positions 45..50): the apex-proven, registry-deployed
  -- descriptors that FORCE guarantee A (the cap-tree / heap-root / DELEG-tree WRITE), now on the wire so the
  -- deployed Rust interpreter parses exactly what the soundness apex proves about. heapWrite is the Class-A
  -- heap-root recompute descriptor (`Rfix 56`); the four `…WriteCapOpenV3` cap-tree wrappers carry the
  -- authority appendix over the MOVING write base (the apex's `Rfix 1/10/11/14` re-pointed off the
  -- authority-only wrappers at positions 36..38); `refreshDelegationWriteCapOpenV3` (position 50, `Rfix 55`
  -- re-pointed) carries the DELEGATIONS-tree UPDATE-write (the `delegRoot_runtime_column_pending` close).
  -- Keys match `v3RegistryHeap`'s declared names.
  IO.println s!"v3rot\theapWriteVmDescriptor2R24\t{Dregg2.Circuit.RotatedKernelRefinementExercise.heapWriteV3.name}\t{emitVmJson2 Dregg2.Circuit.RotatedKernelRefinementExercise.heapWriteV3}"
  IO.println s!"v3rot\tdelegateWriteCapOpenVmDescriptor2R24\t{Dregg2.Circuit.Emit.CapOpenEmit.delegateWriteCapOpenV3.name}\t{emitVmJson2 Dregg2.Circuit.Emit.CapOpenEmit.delegateWriteCapOpenV3}"
  IO.println s!"v3rot\tintroduceWriteCapOpenVmDescriptor2R24\t{Dregg2.Circuit.Emit.CapOpenEmit.introduceWriteCapOpenV3.name}\t{emitVmJson2 Dregg2.Circuit.Emit.CapOpenEmit.introduceWriteCapOpenV3}"
  IO.println s!"v3rot\tdelegateAttenWriteCapOpenVmDescriptor2R24\t{Dregg2.Circuit.Emit.CapOpenEmit.delegateAttenWriteCapOpenV3.name}\t{emitVmJson2 Dregg2.Circuit.Emit.CapOpenEmit.delegateAttenWriteCapOpenV3}"
  IO.println s!"v3rot\trevokeDelegationWriteCapOpenVmDescriptor2R24\t{Dregg2.Circuit.Emit.CapOpenEmit.revokeDelegationWriteCapOpenV3.name}\t{emitVmJson2 Dregg2.Circuit.Emit.CapOpenEmit.revokeDelegationWriteCapOpenV3}"
  IO.println s!"v3rot\trevokeCapabilityWriteCapOpenVmDescriptor2R24\t{Dregg2.Circuit.Emit.CapOpenEmit.revokeCapabilityWriteCapOpenV3.name}\t{emitVmJson2 Dregg2.Circuit.Emit.CapOpenEmit.revokeCapabilityWriteCapOpenV3}"
  IO.println s!"v3rot\trefreshDelegationWriteCapOpenVmDescriptor2R24\t{Dregg2.Circuit.Emit.CapOpenEmit.refreshDelegationWriteCapOpenV3.name}\t{emitVmJson2 Dregg2.Circuit.Emit.CapOpenEmit.refreshDelegationWriteCapOpenV3}"
