/-
# EmitUMemCohort — the staged UMEM-FORM cohort wire-artifact emit executable (sibling of
`EmitRotationV3.lean`).

Prints one TSV line per cohort member from the verified umem-form emission
(`Dregg2/Circuit/Emit/EffectVmEmitUMemCohort.lean`):

  `<lean_def_name>\t<descriptor.name>\t<emitVmJson2 descriptor>`

so the staged Rust artifact `circuit/descriptors/umem-cohort-v1-staged-registry.tsv` can be
regenerated byte-for-byte from the verified Lean emit. STAGED: a NEW staged set beside the
deployed per-map v1 registry — nothing rides the live v1 wire, no VK bump, `umem_witness_enabled`
untouched. The grammar is the already-deployed `umemOp` shape (`demoU`'s wire golden), so the
Rust IR-2 interpreter already parses these; only the (un-done) registry routing is the flip.

SCRATCH executable: run with `lake env lean --run EmitUMemCohort.lean`.
-/
import Dregg2.Circuit.Emit.EffectVmEmitUMemCohort

open Dregg2.Circuit.DescriptorIR2 (emitVmJson2)
open Dregg2.Circuit.Emit.EffectVmEmitUMemCohort (umemCohortRegistry)

def main : IO Unit := do
  for (key, d) in umemCohortRegistry do
    IO.println s!"{key}\t{d.name}\t{emitVmJson2 d}"
