//! # `descent_store` — the DURABLE backing of the no-cheat Descent leaderboard.
//!
//! [`descent::DescentState`](crate::descent::DescentState) is in-RAM: a restart drops every
//! published day and every recorded run. This module makes the board SURVIVE a restart by
//! persisting the ONLY thing that is safe to persist — the **reproducible public input**:
//! - a published day's committed beacon **SEED** (the whole world is regenerated byte-for-byte
//!   from it — never a cached world);
//! - a run's **MOVE SEQUENCE** (the choice indices) + player + display metadata — never a trusted
//!   receipt blob.
//!
//! On boot [`DescentState::load_from_store`](crate::descent::DescentState::load_from_store)
//! **re-verifies every persisted run by REPLAY** (`ugc_dregg::record_playthrough` +
//! `verify_completion` against the day's regenerated universe). A row that no longer re-executes to
//! the win — a tampered seed, an edited move line, a lied turn count, an illegal move — is simply
//! DROPPED; it cannot resurrect a cheat onto the board. This mirrors the discord-bot's
//! `commands::descent::load_board` (and its `SqliteGalleryStore` shape) exactly.
//!
//! ## Why `rusqlite`, not `sqlx`
//! `dreggnet-web` is a **root-workspace member** (unlike the discord-bot, which is an excluded
//! standalone workspace). The workspace already links `sqlite3` once, via `deos-matrix`'s
//! `rusqlite 0.37` → `libsqlite3-sys 0.35`. Cargo permits exactly ONE `links = "sqlite3"` package
//! per resolve, so pulling `sqlx`'s sqlite driver (its own `libsqlite3-sys 0.30`) would break the
//! whole-workspace resolution (see the root `Cargo.toml` note). Depending on the SAME `rusqlite
//! 0.37` unifies onto the existing linker — zero new `links` packages — and, being synchronous,
//! needs no sync↔async bridge at all. The load-bearing pattern (persist reproducible input →
//! re-verify by replay on boot → drop tampered rows) is preserved verbatim.

use std::sync::Mutex;

use rusqlite::Connection;

/// A published day as persisted — its key + the hex of its 32-byte committed beacon seed. The
/// day-world is regenerated byte-for-byte from the seed on boot (never a cached world).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoredDay {
    /// The day key (`?day=` selects it; the demo's default is `"today"`).
    pub key: String,
    /// Hex of the 32-byte committed seed the whole world is drawn from.
    pub seed_hex: String,
}

/// A recorded run as persisted — the **reproducible public input** only: the move sequence (choice
/// indices, JSON array) + player + display metadata. The receipt chain is deliberately NOT stored:
/// it is deterministically re-recorded from the moves on a fresh identically-seeded world and
/// re-verified on boot. A tampered row is only ever a different move line or a lied metric — both
/// re-checked by replay.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct StoredRun {
    /// The shareable run id (the `/descent/run/{id}` path segment + the row PK).
    pub run_id: String,
    /// The day this run belongs to.
    pub day_key: String,
    /// The player label (display).
    pub player: String,
    /// The player's character level at record time (display metadata).
    pub level: u64,
    /// The player's chosen class id at record time (display metadata; `0` = unset).
    pub class: u64,
    /// The move sequence (choice indices) as a JSON array — the un-retconnable material replayed
    /// on boot.
    pub moves_json: String,
}

/// The durable store trait — **sync** (`&self`), so [`DescentState`](crate::descent::DescentState)
/// holds it behind an `Arc` with no async boundary. Persist methods MUST be idempotent by PK, so a
/// double write / a double boot never duplicates a day or a run.
pub trait DescentRunStore: Send + Sync {
    /// Persist a published day (idempotent by `key`).
    fn persist_day(&self, day: &StoredDay) -> Result<(), String>;
    /// Persist a recorded run (idempotent by `run_id`).
    fn persist_run(&self, run: &StoredRun) -> Result<(), String>;
    /// Every persisted day (the boot-replay source).
    fn list_days(&self) -> Result<Vec<StoredDay>, String>;
    /// Every persisted run (re-verified by replay on boot).
    fn list_runs(&self) -> Result<Vec<StoredRun>, String>;
}

/// A thread-safe in-memory [`DescentRunStore`] — the fallback when no `DATABASE_URL` is set (so the
/// committed in-RAM tests are unaffected) and a store for unit tests. Idempotent by PK, matching the
/// sqlite impl's `INSERT OR IGNORE`.
#[derive(Default)]
pub struct InMemoryDescentRunStore {
    inner: Mutex<InMem>,
}

#[derive(Default)]
struct InMem {
    days: Vec<StoredDay>,
    runs: Vec<StoredRun>,
}

impl InMemoryDescentRunStore {
    /// A fresh empty store.
    pub fn new() -> InMemoryDescentRunStore {
        InMemoryDescentRunStore::default()
    }
}

impl DescentRunStore for InMemoryDescentRunStore {
    fn persist_day(&self, day: &StoredDay) -> Result<(), String> {
        let mut g = self
            .inner
            .lock()
            .map_err(|_| "store poisoned".to_string())?;
        if !g.days.iter().any(|d| d.key == day.key) {
            g.days.push(day.clone());
        }
        Ok(())
    }
    fn persist_run(&self, run: &StoredRun) -> Result<(), String> {
        let mut g = self
            .inner
            .lock()
            .map_err(|_| "store poisoned".to_string())?;
        if !g.runs.iter().any(|r| r.run_id == run.run_id) {
            g.runs.push(run.clone());
        }
        Ok(())
    }
    fn list_days(&self) -> Result<Vec<StoredDay>, String> {
        Ok(self
            .inner
            .lock()
            .map_err(|_| "store poisoned".to_string())?
            .days
            .clone())
    }
    fn list_runs(&self) -> Result<Vec<StoredRun>, String> {
        Ok(self
            .inner
            .lock()
            .map_err(|_| "store poisoned".to_string())?
            .runs
            .clone())
    }
}

/// The migration run on [`open`](SqliteDescentRunStore::open) — `CREATE TABLE IF NOT EXISTS`, so an
/// existing database is used as-is (durable across restart) and a fresh one is initialized.
const MIGRATION: &str = "
CREATE TABLE IF NOT EXISTS descent_days (
    key      TEXT PRIMARY KEY,
    seed_hex TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS descent_runs (
    run_id     TEXT PRIMARY KEY,
    day_key    TEXT NOT NULL,
    player     TEXT NOT NULL,
    level      INTEGER NOT NULL,
    class      INTEGER NOT NULL,
    moves_json TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_descent_runs_day ON descent_runs (day_key);
";

/// A [`DescentRunStore`] persisted in a sqlite database (rusqlite). One `Mutex<Connection>` — the
/// demo board is low-traffic (a single-writer store), so a mutexed connection is ample and needs no
/// pool. Days live in `descent_days`, runs in `descent_runs`; both survive restart and are
/// re-verified by replay on boot.
pub struct SqliteDescentRunStore {
    conn: Mutex<Connection>,
}

impl SqliteDescentRunStore {
    /// Open (or create) the sqlite store at `url` and run the migration. Accepts a bare path, a
    /// `sqlite:PATH` / `sqlite://PATH` url (an optional `?query` is ignored), or `:memory:` /
    /// empty (an in-memory database, for tests).
    pub fn open(url: &str) -> Result<SqliteDescentRunStore, String> {
        let path = url
            .strip_prefix("sqlite://")
            .or_else(|| url.strip_prefix("sqlite:"))
            .unwrap_or(url);
        let path = path.split('?').next().unwrap_or(path);
        let conn = if path.is_empty() || path == ":memory:" {
            Connection::open_in_memory()
        } else {
            Connection::open(path)
        }
        .map_err(|e| e.to_string())?;
        conn.execute_batch(MIGRATION).map_err(|e| e.to_string())?;
        Ok(SqliteDescentRunStore {
            conn: Mutex::new(conn),
        })
    }
}

impl DescentRunStore for SqliteDescentRunStore {
    fn persist_day(&self, day: &StoredDay) -> Result<(), String> {
        let conn = self.conn.lock().map_err(|_| "store poisoned".to_string())?;
        conn.execute(
            "INSERT OR IGNORE INTO descent_days (key, seed_hex) VALUES (?1, ?2)",
            (&day.key, &day.seed_hex),
        )
        .map_err(|e| e.to_string())?;
        Ok(())
    }

    fn persist_run(&self, run: &StoredRun) -> Result<(), String> {
        let conn = self.conn.lock().map_err(|_| "store poisoned".to_string())?;
        conn.execute(
            "INSERT OR IGNORE INTO descent_runs
                (run_id, day_key, player, level, class, moves_json)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            (
                &run.run_id,
                &run.day_key,
                &run.player,
                run.level as i64,
                run.class as i64,
                &run.moves_json,
            ),
        )
        .map_err(|e| e.to_string())?;
        Ok(())
    }

    fn list_days(&self) -> Result<Vec<StoredDay>, String> {
        let conn = self.conn.lock().map_err(|_| "store poisoned".to_string())?;
        let mut stmt = conn
            .prepare("SELECT key, seed_hex FROM descent_days")
            .map_err(|e| e.to_string())?;
        let rows = stmt
            .query_map([], |row| {
                Ok(StoredDay {
                    key: row.get(0)?,
                    seed_hex: row.get(1)?,
                })
            })
            .map_err(|e| e.to_string())?;
        rows.collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())
    }

    fn list_runs(&self) -> Result<Vec<StoredRun>, String> {
        let conn = self.conn.lock().map_err(|_| "store poisoned".to_string())?;
        let mut stmt = conn
            .prepare("SELECT run_id, day_key, player, level, class, moves_json FROM descent_runs")
            .map_err(|e| e.to_string())?;
        let rows = stmt
            .query_map([], |row| {
                Ok(StoredRun {
                    run_id: row.get(0)?,
                    day_key: row.get(1)?,
                    player: row.get(2)?,
                    level: row.get::<_, i64>(3)?.max(0) as u64,
                    class: row.get::<_, i64>(4)?.max(0) as u64,
                    moves_json: row.get(5)?,
                })
            })
            .map_err(|e| e.to_string())?;
        rows.collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())
    }
}
