#![cfg(not(feature = "recursion"))]
//! EFFECT-VM CIRCUIT CORRESPONDENCE DIFFERENTIAL — the running p3 AIR vs the
//! constraint reference it is a term-for-term port of.
//!
//! ## The gap this closes
//!
//! The node's commit path proves every finalized turn through
//! `dregg_circuit::effect_vm_p3_full_air::prove_effect_vm_p3` — the `EffectVmP3Air`
//! that runs on the AUDITED `p3-batch-stark` verifier. That AIR is DOCUMENTED as a
//! "term-for-term symbolic mirror" of the bespoke `EffectVmAir::eval_constraints`
//! body (the constraint reference, against which the Lean circuit⟺intent-spec
//! triangle is written). The audited verifier is sound about *whatever
//! constraints `EffectVmP3Air::eval` emits* — so if those drifted from the
//! reference, the soundness would be about the WRONG circuit.
//!
//! Nothing tested that the running AIR decides exactly what the reference decides.
//! This file is that tooth.
//!
//! ## What it asserts
//!
//! For a shared corpus of base Effect-VM traces (honest AND tampered, generated by
//! the SAME `generate_effect_vm_trace` the prover uses), it compares two CONCRETE,
//! FRI-free accept/reject decisions over the SAME witness + public inputs:
//!
//!   * `p3_air_accepts`      — `EffectVmP3Air::eval` evaluated by Plonky3's own
//!     canonical debug constraint checker (`p3_air::check_all_constraints`). This is
//!     EXACTLY the predicate the audited p3 verifier enforces — every constraint
//!     vanishing on every row — but deterministic (no random FRI queries).
//!   * `bespoke_air_accepts` — the reference `EffectVmAir::eval_constraints`
//!     transition gates + `boundary_constraints` pins.
//!
//! Two directions, each a genuine tooth:
//!
//!   1. SOUNDNESS (load-bearing, UNCONDITIONAL on every corpus member):
//!        `p3_air_accepts ⟹ bespoke_air_accepts`.
//!      The running circuit must NEVER accept a (trace, PI) the reference rejects.
//!      A violation = a soundness HOLE in the running circuit (it dropped/loosened
//!      a constraint). This is the critical drift direction.
//!
//!   2. FAITHFULNESS (on the honest corpus):
//!        every honest (trace, PI) is accepted by BOTH.
//!      A violation = the hand-port mangled a constraint so honest traces fail =
//!      a real port bug (over-constraint).
//!
//! The two together pin "the running AIR decides identically to the reference on
//! honest traces, and never more permissively on any trace."
//!
//! ## The mutation tooth (does a genuine drift get caught?)
//!
//! `drift_is_caught_by_the_differential` directly injects a constraint MUTATION
//! (an attacker-style tampered trace that the reference rejects) and asserts the
//! differential's soundness check would flag any AIR that accepts it. It also
//! asserts the honest-corpus faithfulness check is non-vacuous (the honest traces
//! really are accepted by both, not trivially rejected by both).

use dregg_circuit::effect_vm::columns::{STATE_AFTER_BASE, STATE_BEFORE_BASE, state};
use dregg_circuit::effect_vm::{CellState, Effect, generate_effect_vm_trace, pi};
use dregg_circuit::effect_vm_p3_full_air::{bespoke_air_accepts, p3_air_accepts};
use dregg_circuit::field::BabyBear;

/// Independent alphas for the bespoke alpha-fold (so "fold == 0" faithfully ANDs
/// the individual gates rather than canceling for one unlucky challenge).
fn alphas() -> Vec<BabyBear> {
    vec![
        BabyBear::new(7),
        BabyBear::new(13),
        BabyBear::new(101),
        BabyBear::new(997),
        BabyBear::new(65537),
    ]
}

/// A representative spread of single-effect turns + a multi-effect turn. These
/// drive the major constraint groups (selector validity, balance debit/credit +
/// GROUP-2a range, cap-root update, field update, hash sites, state-commit).
fn honest_corpus() -> Vec<(&'static str, Vec<(Vec<Vec<BabyBear>>, Vec<BabyBear>)>)> {
    let mk = |bal: u64, effects: Vec<Effect>| {
        let st = CellState::new(bal, 0);
        let (trace, pis) = generate_effect_vm_trace(&st, &effects);
        (trace, pis)
    };

    let one = |label: &'static str, bal: u64, e: Effect| (label, vec![mk(bal, vec![e])]);

    vec![
        one("NoOp", 100_000, Effect::NoOp),
        one(
            "Transfer-out",
            100_000,
            Effect::Transfer {
                amount: 50,
                direction: 1,
            },
        ),
        one(
            "Transfer-in",
            100_000,
            Effect::Transfer {
                amount: 50,
                direction: 0,
            },
        ),
        one(
            "SetField",
            100_000,
            Effect::SetField {
                field_idx: 2,
                value: BabyBear::new(0x42),
            },
        ),
        (
            "GrantCapability",
            vec![mk(
                100_000,
                vec![Effect::GrantCapability {
                    cap_entry: {
                        let mut a = [BabyBear::ZERO; 8];
                        a[0] = BabyBear::new(0xCAFE);
                        a
                    },
                    phase_b: None,
                }],
            )],
        ),
        one(
            "NoteCreate",
            100_000,
            Effect::NoteCreate {
                commitment: BabyBear::new(0x5678),
                value: 50,
            },
        ),
        one(
            "NoteSpend",
            100_000,
            Effect::NoteSpend {
                nullifier: BabyBear::new(0x1234),
                value: 100,
            },
        ),
        (
            "multi-effect",
            vec![mk(
                100_000,
                vec![
                    Effect::Transfer {
                        amount: 100,
                        direction: 1,
                    },
                    Effect::SetField {
                        field_idx: 0,
                        value: BabyBear::new(1),
                    },
                    Effect::Transfer {
                        amount: 40,
                        direction: 0,
                    },
                ],
            )],
        ),
    ]
}

/// FAITHFULNESS: every honest (trace, PI) is accepted by BOTH the running p3 AIR
/// and the reference — and non-vacuously so.
#[test]
fn honest_corpus_accepted_identically_by_both_airs() {
    let mut total = 0usize;
    for (label, cases) in honest_corpus() {
        for (trace, pis) in cases {
            let p3 = p3_air_accepts(&trace, &pis);
            let bespoke = bespoke_air_accepts(&trace, &pis, &alphas());
            assert!(
                bespoke,
                "[{label}] REFERENCE rejected an honest trace — corpus/reference desync"
            );
            assert!(
                p3,
                "[{label}] RUNNING p3 AIR rejected an honest trace the reference accepts — \
                 the hand-port over-constrains (dropped/mangled a gate); honest turns would FAIL \
                 to prove on the audited verifier. THIS IS A PORT BUG."
            );
            total += 1;
        }
    }
    // VERB LOCKSTEP: the corpus dropped a doomed-effect case with its Effect
    // variant; 8 survivor cases remain.
    assert!(total >= 8, "corpus shrank unexpectedly ({total} cases)");
}

/// SOUNDNESS (the load-bearing direction): build a battery of TAMPERED (trace, PI)
/// pairs and assert that whenever the RUNNING p3 AIR accepts, the REFERENCE also
/// accepts. A running-AIR accept that the reference rejects = a soundness hole in
/// the circuit the node actually proves.
#[test]
fn running_air_never_accepts_what_the_reference_rejects() {
    // A base honest turn with a real non-last row + a balance move to tamper.
    let st = CellState::new(100_000, 0);
    let effects = vec![
        Effect::Transfer {
            amount: 100,
            direction: 1,
        },
        Effect::SetField {
            field_idx: 3,
            value: BabyBear::new(9),
        },
        Effect::Transfer {
            amount: 25,
            direction: 0,
        },
    ];
    let (base_trace, base_pis) = generate_effect_vm_trace(&st, &effects);
    let n = base_trace.len();
    let last = n - 1;

    // Sanity: the honest base is accepted by both.
    assert!(p3_air_accepts(&base_trace, &base_pis));
    assert!(bespoke_air_accepts(&base_trace, &base_pis, &alphas()));

    // The tamper battery: each entry mutates a load-bearing cell or PI. Both
    // circuits should reject every one; the differential's invariant is the
    // weaker, universal one (p3-accept ⟹ ref-accept).
    let mut tampers: Vec<(String, Vec<Vec<BabyBear>>, Vec<BabyBear>)> = Vec::new();

    // -- Selector tampers (GROUP 1) --
    {
        let mut t = base_trace.clone();
        // Break the "selectors sum to 1" gate on row 0: zero out the active sel.
        for s in 0..dregg_circuit::effect_vm::NUM_EFFECTS {
            t[0][s] = BabyBear::ZERO;
        }
        tampers.push(("row0-no-selector".into(), t, base_pis.clone()));
    }
    {
        let mut t = base_trace.clone();
        // Two selectors hot on row 0 (sum=2) — booleanity passes, sum fails.
        t[0][1] = BabyBear::ONE;
        t[0][2] = BabyBear::ONE;
        tampers.push(("row0-two-selectors".into(), t, base_pis.clone()));
    }
    {
        let mut t = base_trace.clone();
        // Non-boolean selector on row 0.
        t[0][0] = BabyBear::new(2);
        tampers.push(("row0-nonboolean-selector".into(), t, base_pis.clone()));
    }

    // -- Balance / GROUP-2a tampers (the underflow-soundness gate) --
    {
        let mut t = base_trace.clone();
        // Corrupt the post-state balance_lo on a non-last row WITHOUT fixing the
        // GROUP-2a bit columns: the bit-recomposition gate must reject.
        t[0][STATE_AFTER_BASE + state::BALANCE_LO] =
            t[0][STATE_AFTER_BASE + state::BALANCE_LO] + BabyBear::new(1);
        tampers.push(("row0-balance_lo-vs-bits".into(), t, base_pis.clone()));
    }
    {
        let mut t = base_trace.clone();
        // Decouple a continuity link: row1.before != row0.after balance.
        t[1][STATE_BEFORE_BASE + state::BALANCE_LO] =
            t[1][STATE_BEFORE_BASE + state::BALANCE_LO] + BabyBear::new(1);
        tampers.push(("row1-balance-continuity".into(), t, base_pis.clone()));
    }

    // -- State-commit tampers (GROUP 4 anti-ghost) --
    {
        let mut t = base_trace.clone();
        t[0][STATE_AFTER_BASE + state::STATE_COMMIT] =
            t[0][STATE_AFTER_BASE + state::STATE_COMMIT] + BabyBear::new(1);
        tampers.push(("row0-state_commit-cell".into(), t, base_pis.clone()));
    }
    {
        // Forge BOTH the last-row state-commit cell AND the NEW_COMMIT PI to keep
        // the boundary `STATE_COMMIT == NEW_COMMIT` satisfied. Only the p3 AIR's
        // unconditional GROUP-4 last-row binding rejects this; the reference's
        // boundary alone would accept. The invariant we check (p3 ⟹ ref) still
        // holds here because p3 REJECTS — this is the documented strengthening,
        // not a soundness drift.
        let mut t = base_trace.clone();
        t[last][STATE_AFTER_BASE + state::STATE_COMMIT] =
            t[last][STATE_AFTER_BASE + state::STATE_COMMIT] + BabyBear::new(1);
        let mut p = base_pis.clone();
        p[pi::NEW_COMMIT] = p[pi::NEW_COMMIT] + BabyBear::new(1);
        tampers.push(("last-row-state_commit+NEW_COMMIT".into(), t, p));
    }

    // -- PI boundary tampers --
    {
        let mut p = base_pis.clone();
        p[pi::OLD_COMMIT] = p[pi::OLD_COMMIT] + BabyBear::new(1);
        tampers.push(("PI-OLD_COMMIT".into(), base_trace.clone(), p));
    }
    {
        let mut p = base_pis.clone();
        p[pi::NEW_COMMIT] = p[pi::NEW_COMMIT] + BabyBear::new(1);
        tampers.push(("PI-NEW_COMMIT-only".into(), base_trace.clone(), p));
    }
    {
        let mut p = base_pis.clone();
        p[pi::FINAL_BAL_LO] = p[pi::FINAL_BAL_LO] + BabyBear::new(1);
        tampers.push(("PI-FINAL_BAL_LO".into(), base_trace.clone(), p));
    }
    {
        let mut p = base_pis.clone();
        p[pi::INIT_BAL_LO] = p[pi::INIT_BAL_LO] + BabyBear::new(1);
        tampers.push(("PI-INIT_BAL_LO".into(), base_trace.clone(), p));
    }
    {
        let mut p = base_pis.clone();
        p[pi::ACTOR_NONCE] = p[pi::ACTOR_NONCE] + BabyBear::new(1);
        tampers.push(("PI-ACTOR_NONCE".into(), base_trace.clone(), p));
    }
    {
        let mut p = base_pis.clone();
        p[pi::EFFECTS_HASH_BASE] = p[pi::EFFECTS_HASH_BASE] + BabyBear::new(1);
        tampers.push(("PI-EFFECTS_HASH".into(), base_trace.clone(), p));
    }

    let mut p3_accepts = 0usize;
    let mut both_reject = 0usize;
    for (label, t, p) in &tampers {
        let p3 = p3_air_accepts(t, p);
        let bespoke = bespoke_air_accepts(t, p, &alphas());

        // THE soundness invariant: the running circuit is no more permissive than
        // the reference.
        assert!(
            !p3 || bespoke,
            "[{label}] SOUNDNESS DRIFT: the RUNNING p3 AIR ACCEPTS a (trace, PI) the \
             reference REJECTS — the audited verifier would accept a state-transition the \
             constraint reference forbids. CRITICAL."
        );

        // Both circuits should reject every tamper here (these are real attacks).
        // A p3-accept would already have tripped the assertion above; flag a
        // reference-only accept too so we notice if a tamper is too weak.
        if p3 {
            p3_accepts += 1;
        }
        if !p3 && !bespoke {
            both_reject += 1;
        }
        assert!(
            !p3,
            "[{label}] the RUNNING p3 AIR accepted a tampered trace — a missing/weak gate \
             in the running circuit"
        );
    }

    // Non-vacuity: the tamper battery must actually exercise rejection (it is NOT
    // the case that every tamper was a no-op both circuits accept).
    assert_eq!(p3_accepts, 0, "no tamper should be p3-accepted");
    assert!(
        both_reject >= tampers.len() - 1,
        "tamper battery is too weak: only {both_reject}/{} both-rejected",
        tampers.len()
    );
}

/// THE MUTATION TOOTH — does a genuine drift get caught?
///
/// We construct the canonical drift scenario by hand: a (trace, PI) the REFERENCE
/// rejects. The differential's soundness assertion is `!p3 || bespoke`. We assert:
///   * the reference DOES reject this trace (so it is a real attack), and
///   * IF a hypothetical drifted running AIR accepted it (p3 == true), the
///     soundness assertion `!p3 || bespoke` would be FALSE — i.e. the differential
///     would fail loudly. This proves the tooth bites: a running AIR that drops the
///     gate this trace violates is caught.
#[test]
fn drift_is_caught_by_the_differential() {
    let st = CellState::new(100_000, 0);
    let effects = vec![Effect::Transfer {
        amount: 100,
        direction: 1,
    }];
    let (base_trace, base_pis) = generate_effect_vm_trace(&st, &effects);

    // Honest base: both accept (non-vacuity of the honest side).
    assert!(
        p3_air_accepts(&base_trace, &base_pis),
        "honest must p3-accept"
    );
    assert!(
        bespoke_air_accepts(&base_trace, &base_pis, &alphas()),
        "honest must reference-accept"
    );

    // A genuine attack the reference rejects: forge the published post-state
    // balance PI away from the trace's actual last-row balance.
    let mut forged_pis = base_pis.clone();
    forged_pis[pi::FINAL_BAL_LO] = forged_pis[pi::FINAL_BAL_LO] + BabyBear::new(123);

    let ref_accepts = bespoke_air_accepts(&base_trace, &forged_pis, &alphas());
    assert!(
        !ref_accepts,
        "the reference MUST reject a forged FINAL_BAL_LO (else the corpus is wrong)"
    );

    // The differential's soundness predicate is `!p3 || ref`. With ref == false,
    // it reduces to `!p3`: a drifted running AIR that ACCEPTED this (p3 == true)
    // would make the predicate FALSE → the differential fails. So the tooth bites
    // exactly when a running AIR is more permissive than the reference.
    let soundness_predicate = |p3: bool, refr: bool| !p3 || refr;
    assert!(
        soundness_predicate(false, ref_accepts),
        "a reference-rejecting trace that the running AIR ALSO rejects passes (correct)"
    );
    assert!(
        !soundness_predicate(true, ref_accepts),
        "a reference-rejecting trace that a drifted running AIR ACCEPTED would FAIL the \
         differential — the tooth bites"
    );

    // And confirm the ACTUAL running AIR rejects it too (it is faithful here).
    assert!(
        !p3_air_accepts(&base_trace, &forged_pis),
        "the actual running p3 AIR must also reject the forged FINAL_BAL_LO"
    );
}
