/-
# `Dregg2.Crypto.KeccakCavp` -- the Keccak floor pinned to GENUINE NIST CAVP vectors.

Before this module the entire evidence for the hand-written FIPS 202 sponge in `Dregg2.Crypto.Keccak`
(plus the SHA-3 wrappers in `Dregg2.Crypto.MlKemDecaps`) was NINE `native_decide` KATs on exactly two
inputs: the empty string and `"abc"`. Both are SHORT -- shorter than every rate -- so together they
exercised **neither** of the two places a sponge implementation actually breaks:

  1. the `q == 1` pad-collapse branch (`msg.length % rate == rate - 1`), where the domain byte and the
     `0x80` terminator must merge into a single byte (`0x9F` for SHAKE, `0x86` for SHA-3), and
  2. a **multi-block absorb** (more than one `keccakF` in `absorb`), i.e. the block loop, the
     `blk*rate + i` offset arithmetic, and state carry-over between blocks.

Those nine, ON THEIR OWN, would all still pass if the block loop were wrong, if the `q == 1` branch
emitted the wrong byte, or if the squeeze never permuted between output blocks. This module
closes that gap with vectors that are DOWNLOADED, DIGEST-VERIFIED and CITED, never hand-written and
never produced by a Rust crate.

## WHAT THIS DOES *NOT* CLAIM (read before quoting the coverage list)

It would be an overclaim to say these branches were never exercised anywhere in the tree. They were
not exercised by any DIRECT Keccak KAT -- that is the precise claim -- but the stack-level NIST ACVP
modules (`MlDsaSigGenAcvp`, `MlDsaSigVerAcvp`, `MlKemEncapsAcvp`, `MlKemDecaps`) hash ML-DSA messages
of 1..8192 bytes and ML-KEM keys of 1184+ bytes through this same sponge, so they certainly drive
multi-block absorb and multi-block squeeze INCIDENTALLY, and may well hit the `q == 1` collapse by
chance at some unrecorded input length.

What this module adds over that incidental exercise is four things, and only these four:

  1. **Isolation.** When a vector here fails, the failing artifact is Keccak. When an ACVP ML-DSA
     vector fails, the failure could be anywhere in a 3309-byte signature pipeline.
  2. **Deliberateness.** The `q == 1` collapse is hit ON PURPOSE at a stated length, at BOTH domain
     bytes, at THREE rates -- rather than possibly-by-accident at a length nobody computed.
  3. **A machine-checked coverage record.** The `#guard` witnesses at the bottom of this file PROVE
     which branch each message length selects, so the coverage claim is checked, not asserted, and
     stays true if someone edits `pad`.
  4. **Direct provenance.** These are SHA-3/SHAKE vectors from the SHA-3 CAVP archives, testing the
     sponge as the algorithm under test, rather than as a subroutine of something else.

It is still, in kind, exactly what it was before: known-answer testing. See RESIDUAL.

## PROVENANCE (download digests computed in-session, 2026-07-20)

Source: NIST Cryptographic Algorithm Validation Program (CAVP), SHA-3 / SHAKE byte-oriented test
vectors, CAVS 19.0, generated by NIST on 2016-01-28.

| archive | URL | SHA-256 of the downloaded archive |
|---|---|---|
| `shakebytetestvectors.zip` | `https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/shakebytetestvectors.zip` | `debfebc3157b3ceea002b84ca38476420389a3bf7e97dc5f53ea4689a16de4c7` |
| `sha-3bytetestvectors.zip` | `https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/sha-3bytetestvectors.zip` | `cd07701af2e47f5cc889d642528b4bf11f8b6eb55797c7307a96828ed8d8fc8c` |

Per-member SHA-256 of the `.rsp` files these vectors were extracted from:

| `.rsp` member | SHA-256 |
|---|---|
| `SHAKE128ShortMsg.rsp` | `c7384e3f84247d90e6b0af9ac618a968bb65f5dcbe9c2ee7e8a66475c551764b` |
| `SHAKE128LongMsg.rsp` | `826b319c265448f5268c7e36f432de31315dd8155eaa038ba76d1acd0d03736f` |
| `SHAKE128VariableOut.rsp` | `56ac04dd47c8063bdd08fd7744aef55c22c22946d722012460703bcae0b2583f` |
| `SHAKE256ShortMsg.rsp` | `a21dd9180a0f0139fa8d4056919f8194ddaca2f36dc5aafa70723682099d64f5` |
| `SHAKE256LongMsg.rsp` | `f7881838fa013853993bf7e0814de0ab53ee93a4dbc2b7bce5bed7cc81e6985f` |
| `SHAKE256VariableOut.rsp` | `90fb72336900b22284477b76d0868fc2822ae42a114079c6c8a7fbda12eb52ca` |
| `SHA3_256ShortMsg.rsp` | `e75b1ded16e9862eaaef9ad9b89402b9832f86fe818292634b2e54dc6b3540ff` |
| `SHA3_256LongMsg.rsp` | `741b75d093aeb1de3536681b5e7e65090a5eca8015eb75c5f9be0feda47660d5` |
| `SHA3_512ShortMsg.rsp` | `f73a39d8091d58c9225cfad8e6d8cfa3e8d67532c7029bf376baef0d0d86d5b6` |
| `SHA3_512LongMsg.rsp` | `142aab2fc0fd41809b1efdf48819e4f863985fb8d5cb30694acf7c8e7080d20e` |

Every theorem names its exact source file and the vector own CAVP identifier (`Len = n` for the
ShortMsg/LongMsg files, `COUNT = n` for the VariableOut files), so any reader can re-extract it from
the digest-pinned archive above. The CAVP convention that a `Len = 0` record still carries a dummy
`Msg = 00` line is handled at extraction: the pinned message for those is the EMPTY string.

## WHAT IS NOW COVERED

- **`q == 1` pad collapse, SHAKE (`0x9F`)**: `shake128_cavp_len1336` (167 B = rate-1),
  `shake256_cavp_len1080` (135 B = rate-1), and again ACROSS a block boundary at
  `shake128_cavp_len2680` (335 B = 2*rate-1) and `shake256_cavp_len2168` (271 B).
- **`q == 1` pad collapse, SHA-3 (`0x86`)**: `sha3_256_cavp_len1080` (135 B at rate 136) and
  `sha3_512_cavp_len568` (71 B at rate 72).
- **`q == 2`, the minimal two-byte pad** (the neighbouring branch, so a mis-placed comparison is
  caught): `shake128_cavp_len1328`, `shake256_cavp_len1072`, `sha3_256_cavp_len1072`,
  `sha3_512_cavp_len560`.
- **`q == rate`, a message that is an exact multiple of the rate** and therefore needs a WHOLE extra
  pad block: `shake128_cavp_len1344`, `shake256_cavp_len1088`, `sha3_256_cavp_len1088`,
  `sha3_512_cavp_len576`.
- **Multi-block absorb** (2, 3 and 5 `keccakF` invocations in `absorb`): `shake128_cavp_len1352`,
  `shake128_cavp_len2688`, `shake128_cavp_long2696`, `shake128_cavp_long5400` (675 B),
  `shake256_cavp_len1096`, `shake256_cavp_len2176`, `shake256_cavp_long2184`,
  `shake256_cavp_long4376` (547 B), `sha3_256_cavp_long2184`, `sha3_512_cavp_long1160`.
- **Multi-block squeeze** (the inter-block `keccakF` in `squeeze`, which no DIRECT Keccak KAT touched,
  every one of them squeezing 32 or 64 bytes -- i.e. strictly under every rate):
  `shake256_cavp_var_c675` (137 B = rate+1, so it reads byte 0 of the second squeeze block) and
  `shake256_cavp_var_c1240` (250 B).
- **Squeeze truncation**: `shake256_cavp_var_c0` (2 bytes out of a 136-byte block),
  `shake256_cavp_var_c670` (exactly one full rate block), `shake128_cavp_var_c1116` (140 of 168).
- **Three distinct rates**: 168 (SHAKE128), 136 (SHAKE256 / SHA3-256), 72 (SHA3-512) -- rate 72 was
  previously exercised only by two short inputs, and never across a block boundary.
- **Both domain bytes**: `0x1F` (SHAKE) and `0x06` (SHA-3), each at its own `q == 1` collapse.

## WHAT IS STILL NOT COVERED (named, not hidden)

- **The FIPS 202 `forall` refinement remains OPEN.** There is no FIPS 202 specification in this tree,
  so there is no theorem of the form `forall msg, shake256 msg n = Fips202.SHAKE256 msg n`. Everything
  here is finitely many input/output pairs. A wrong implementation that happens to agree with the
  permutation on these 35 messages is not excluded by any argument in this file. Closing it needs, in
  order: (a) a Lean transcription of FIPS 202 sec. 3 (the five step mappings theta/rho/pi/chi/iota over
  the 5x5x64 state as a bit-addressed `Fin 5 -> Fin 5 -> Fin 64 -> Bool`) and sec. 6 (`SPONGE`,
  `pad10*1`), written against the standard rather than against this code; (b) a lane-indexing bridge
  lemma proving the `UInt64`-lane/little-endian representation here refines that bit-addressed state;
  (c) a round-function equality by `decide` over the bit indices; (d) an induction over blocks for
  `absorb` and over output blocks for `squeeze`. Steps (b) and (d) are the real work. This is the SAME
  class of residual as `NttFaithful` closed for the NTT, so the pattern exists in-tree.
- **Keccak-f itself is not independently pinned.** The permutation is only observed through the sponge.
  NIST publishes no CAVP vector for the bare permutation.
- **The CAVP Monte-Carlo files are not used** (`SHAKE128Monte.rsp`, `SHA3_512Monte.rsp`, and the rest).
  They chain thousands of iterations and would be a genuinely independent long-run check; not pinned.
- **SHA3-224 / SHA3-384 are not pinned** -- this tree defines neither.
- **SHAKE128 multi-block squeeze specifically is not pinned**: the CAVP `SHAKE128VariableOut.rsp` caps
  output at 1120 bits = 140 bytes, below the 168-byte rate. `squeeze` is rate-parametric and its
  multi-block path IS covered at rate 136, but not at rate 168.
- **The `"abc"` vectors in `Keccak.lean` / `MlKemDecaps.lean` have no NIST-file provenance.** They are
  reference-implementation cross-checks. They are no longer load-bearing: every branch they touch is
  now also covered by a digest-cited CAVP vector. See the citation notes added to those files.

## RESIDUAL (trusted base)

`native_decide`, i.e. `Lean.ofReduceBool` + `Lean.trustCompiler` -- the compiled-evaluation residual,
the same one the existing nine KATs and the ACVP pinning modules already carry. `native_decide` is
acceptable for a KAT: the win here is BRANCH COVERAGE and PROVENANCE, not a reduction in trusted base.
No `sorry`, no user `axiom`.

Non-vacuity was probed adversarially: single-nibble tampers of pinned vectors were checked to make the
corresponding equality evaluate to `false` (results recorded in the crypto TCB ledger).
-/
import Dregg2.Crypto.Keccak
import Dregg2.Crypto.MlKemDecaps
import Dregg2.Crypto.AcvpHex

namespace Dregg2.Crypto.KeccakCavp

-- `Keccak.*` and `MlKemDecaps.*` resolve through the enclosing `Dregg2.Crypto` namespace.
open Dregg2.Crypto.AcvpHex (hexBytes hexOfLen)

/-! ## The CAVP vectors.

Each block is: a docstring naming the CAVP file, the vector id and the branch it exercises; the
`native_decide` KAT itself; and a `#guard` that the pinned hex is well-formed and has exactly the
CAVP-declared byte length, so a truncated transcription fails at elaboration rather than silently
becoming a shorter byte string. -/

/-- CAVP `SHAKE128ShortMsg.rsp`, `Len = 0` -- empty message; re-anchors `Keccak.shake128_empty_kat` (first 16 bytes).

Message 0 B, output 16 B. -/
theorem shake128_cavp_len0 :
    Keccak.shake128 (hexBytes "") 16 =
      hexBytes "7f9c2ba4e88f827d616045507605853e" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "" 0 && hexOfLen "7f9c2ba4e88f827d616045507605853e" 16

/-- CAVP `SHAKE128ShortMsg.rsp`, `Len = 8` -- 1-byte message; q = 167 (long zero-fill pad).

Message 1 B, output 16 B. -/
theorem shake128_cavp_len8 :
    Keccak.shake128 (hexBytes "0e") 16 =
      hexBytes "fa996dafaa208d72287c23bc4ed4bfd5" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "0e" 1 && hexOfLen "fa996dafaa208d72287c23bc4ed4bfd5" 16

/-- CAVP `SHAKE128ShortMsg.rsp`, `Len = 1328` -- 166 bytes: **q == 2** - the minimal two-byte pad `0x1F 0x80`, the branch adjacent to the collapse.

Message 166 B, output 16 B. -/
theorem shake128_cavp_len1328 :
    Keccak.shake128 (hexBytes "e4e932fc9907620ebebffd32b10fda7890a5bc20e5f41d5589882a18c2960e7aafd8730ee697469e5b0abb1d84de92ddba169802e31570374ef9939fde2b960e6b34ac7a65d36bacba4cd33bfa028cbbba486f32367548cb3a36dacf422924d0e0a7e3285ee158a2a42e4b765da3507b56e54998263b2c7b14e7078e35b74127d5d7220018e995e6e1572db5f3e8678357922f1cfd90a5afa6b420c600fd737b136c70e9dd14") 16 =
      hexBytes "459ce4fa824ee1910a678abc77c1f769" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "e4e932fc9907620ebebffd32b10fda7890a5bc20e5f41d5589882a18c2960e7aafd8730ee697469e5b0abb1d84de92ddba169802e31570374ef9939fde2b960e6b34ac7a65d36bacba4cd33bfa028cbbba486f32367548cb3a36dacf422924d0e0a7e3285ee158a2a42e4b765da3507b56e54998263b2c7b14e7078e35b74127d5d7220018e995e6e1572db5f3e8678357922f1cfd90a5afa6b420c600fd737b136c70e9dd14" 166 && hexOfLen "459ce4fa824ee1910a678abc77c1f769" 16

/-- CAVP `SHAKE128ShortMsg.rsp`, `Len = 1336` -- 167 bytes = rate-1: **q == 1 PAD-COLLAPSE BRANCH** (single `0x9F` byte).

Message 167 B, output 16 B. -/
theorem shake128_cavp_len1336 :
    Keccak.shake128 (hexBytes "18636f702f216b1b9302e59d82192f4e002f82d526c3f04cbd4f9b9f0bcd2535ed7a67d326da66bdf7fc821ef0fff1a905d56c81e4472856863908d104301133ad111e39552cd542ef78d9b35f20419b893f4a93aee848e9f86ae3fd53d27fea7fb1fc69631fa0f3a5ff51267785086ab4f682d42baf394b3b6992e9a0bb58a38ce0692df9bbaf183e18523ee1352c5fad817e0c04a3e1c476be7f5e92f482a6fb29cd4bbf09ea") 16 =
      hexBytes "b7b9db481898f888e5ee4ed629859844" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "18636f702f216b1b9302e59d82192f4e002f82d526c3f04cbd4f9b9f0bcd2535ed7a67d326da66bdf7fc821ef0fff1a905d56c81e4472856863908d104301133ad111e39552cd542ef78d9b35f20419b893f4a93aee848e9f86ae3fd53d27fea7fb1fc69631fa0f3a5ff51267785086ab4f682d42baf394b3b6992e9a0bb58a38ce0692df9bbaf183e18523ee1352c5fad817e0c04a3e1c476be7f5e92f482a6fb29cd4bbf09ea" 167 && hexOfLen "b7b9db481898f888e5ee4ed629859844" 16

/-- CAVP `SHAKE128ShortMsg.rsp`, `Len = 1344` -- 168 bytes = exactly 1 rate block: q == 168, a FULL EXTRA pad block -> **2-block absorb**.

Message 168 B, output 16 B. -/
theorem shake128_cavp_len1344 :
    Keccak.shake128 (hexBytes "5d9ff9fe63c328ddbe0c865ac6ba605c52a14ee8e4870ba320ce849283532f2551959e74cf1a54c8b30ed75dd92e076637e4ad5213b3574e73d6640bd6245bc121378174dccdaa769e6e4f2dc650e1166c775d0a982021c0b160fe9438098e86b6cdc786f2a6d1ef68751551f7e99773daa28598d9961002c0b47ab511c8707df69f9b32796b723bf7685251d2c0d08567ad4e8540ddcc1b8a1a01f6c92aaaadcaf42301d9e53463") 16 =
      hexBytes "f50af2684408915871948779a14c147c" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "5d9ff9fe63c328ddbe0c865ac6ba605c52a14ee8e4870ba320ce849283532f2551959e74cf1a54c8b30ed75dd92e076637e4ad5213b3574e73d6640bd6245bc121378174dccdaa769e6e4f2dc650e1166c775d0a982021c0b160fe9438098e86b6cdc786f2a6d1ef68751551f7e99773daa28598d9961002c0b47ab511c8707df69f9b32796b723bf7685251d2c0d08567ad4e8540ddcc1b8a1a01f6c92aaaadcaf42301d9e53463" 168 && hexOfLen "f50af2684408915871948779a14c147c" 16

/-- CAVP `SHAKE128ShortMsg.rsp`, `Len = 1352` -- 169 bytes: **2-block absorb** with a partial second block.

Message 169 B, output 16 B. -/
theorem shake128_cavp_len1352 :
    Keccak.shake128 (hexBytes "38c0be76e7b60f262f1499e328e0519f864bbb9d134d00345d8942d0ab762c3936c0cd1896eca6b77b3c01089dd285e9f61708a62e5ea4bf57c50decda5c215fb18ac149d7ace09ffdfed91e7fbf068d96908e42cf1e7ee7bc001c7ee9e378a311e44311923de4681f24c92eb5f0fb13d07ef679ded3b733f402168dc050568dbf97fb79afe8db994874783e27ad8d040ba8e75343c6762c6793a42247eee5a6216b908817f5edbbdf") 16 =
      hexBytes "e4786ad8f2ea9c8e420a6f50b5feec9a" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "38c0be76e7b60f262f1499e328e0519f864bbb9d134d00345d8942d0ab762c3936c0cd1896eca6b77b3c01089dd285e9f61708a62e5ea4bf57c50decda5c215fb18ac149d7ace09ffdfed91e7fbf068d96908e42cf1e7ee7bc001c7ee9e378a311e44311923de4681f24c92eb5f0fb13d07ef679ded3b733f402168dc050568dbf97fb79afe8db994874783e27ad8d040ba8e75343c6762c6793a42247eee5a6216b908817f5edbbdf" 169 && hexOfLen "e4786ad8f2ea9c8e420a6f50b5feec9a" 16

/-- CAVP `SHAKE128ShortMsg.rsp`, `Len = 2680` -- 335 bytes = 2*rate-1: **q == 1 collapse AT the 2-block boundary**.

Message 335 B, output 16 B. -/
theorem shake128_cavp_len2680 :
    Keccak.shake128 (hexBytes "37e780aa7d82aa7a6119556a002c8f9b0a73c51d6120ee54e36406a08334be3c9f4d72678e765bc2780506fa6aa404a6a955e47347b45e7ef57cd101184df0321fadb768134ca5806f8c257f33404d7834b4cab1b6ef1b013c34fe7c9fcf28535e0e39f5358def7af1b69a428289d0d95299611ed5578da5629375594140d0660578df561bc0a379a48c4d8b8006f691ab0b9004cd761d310ca21fe0252a4f34bbf391d2ef6d2845301526a2543f2767e8123fa9c5d4316fe468e25974140d85298837b2d61ce6a63e5a0ece28bccc25b1b65656e6f7332592eda70b55877220f63eba3ffa5645647661eb5821064b91ad00be535869891cbe39573ff10ae6cfcb1e00be83a2ad467f34a78869a40e7485f75de842b29d1c0f55d83d6f25d158502ef27a9989861602db28a6281e7b95e1a41c5dcc58d5ed2d48144df8609b842c7878ba6292389aa65c58fa85fdfc") 16 =
      hexBytes "177241c74dc8a061dd66cf2abaab284a" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "37e780aa7d82aa7a6119556a002c8f9b0a73c51d6120ee54e36406a08334be3c9f4d72678e765bc2780506fa6aa404a6a955e47347b45e7ef57cd101184df0321fadb768134ca5806f8c257f33404d7834b4cab1b6ef1b013c34fe7c9fcf28535e0e39f5358def7af1b69a428289d0d95299611ed5578da5629375594140d0660578df561bc0a379a48c4d8b8006f691ab0b9004cd761d310ca21fe0252a4f34bbf391d2ef6d2845301526a2543f2767e8123fa9c5d4316fe468e25974140d85298837b2d61ce6a63e5a0ece28bccc25b1b65656e6f7332592eda70b55877220f63eba3ffa5645647661eb5821064b91ad00be535869891cbe39573ff10ae6cfcb1e00be83a2ad467f34a78869a40e7485f75de842b29d1c0f55d83d6f25d158502ef27a9989861602db28a6281e7b95e1a41c5dcc58d5ed2d48144df8609b842c7878ba6292389aa65c58fa85fdfc" 335 && hexOfLen "177241c74dc8a061dd66cf2abaab284a" 16

/-- CAVP `SHAKE128ShortMsg.rsp`, `Len = 2688` -- 336 bytes = exactly 2 rate blocks -> **3-block absorb**.

Message 336 B, output 16 B. -/
theorem shake128_cavp_len2688 :
    Keccak.shake128 (hexBytes "5d8f84b2f208b58a68e88ce8efb543a8404f0ec0c9805c760ad359d13faab84d3f8bb1d2a4bb45e72c0ec9245ffda2e572f94e466cffa44b876d5c5ed914d1ff338e06b74ad1e74d1405d23d759356661b7f3b03a7f7c2dc0d2c2dbe3d60822803408d472b752424ea76af1d79a0e7920388dde0c1903e9364b8d6d7b3b75430754b4d6b91cd83d5740866aab34bdbd0f1bd3dc504f1a1d753ba5f938241ce7f52544e0cc2018cc67b6401ce6abdbc8aafc5629bb643730fa3daced8f425787d61069910073ac760c631876fe81d1127034a544820ad3aa51cbf2d904f8cda936c063561a8a0bd0b1f1801777394630fb6f11cb68a588000861283a2dc9d7d2739ff2ae5ed5af5304cc176cd544a39a99064c1cb3b6bcc88a97ad9f6e381e8a3929781861e91f73516d3ee59d3661b5f584b4b717d0fa7a54da03674ac5fa36d3d76412a826c4c8445f7720337119198") 16 =
      hexBytes "b4813895ae01b43c9d9ed85a8b03aaf4" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "5d8f84b2f208b58a68e88ce8efb543a8404f0ec0c9805c760ad359d13faab84d3f8bb1d2a4bb45e72c0ec9245ffda2e572f94e466cffa44b876d5c5ed914d1ff338e06b74ad1e74d1405d23d759356661b7f3b03a7f7c2dc0d2c2dbe3d60822803408d472b752424ea76af1d79a0e7920388dde0c1903e9364b8d6d7b3b75430754b4d6b91cd83d5740866aab34bdbd0f1bd3dc504f1a1d753ba5f938241ce7f52544e0cc2018cc67b6401ce6abdbc8aafc5629bb643730fa3daced8f425787d61069910073ac760c631876fe81d1127034a544820ad3aa51cbf2d904f8cda936c063561a8a0bd0b1f1801777394630fb6f11cb68a588000861283a2dc9d7d2739ff2ae5ed5af5304cc176cd544a39a99064c1cb3b6bcc88a97ad9f6e381e8a3929781861e91f73516d3ee59d3661b5f584b4b717d0fa7a54da03674ac5fa36d3d76412a826c4c8445f7720337119198" 336 && hexOfLen "b4813895ae01b43c9d9ed85a8b03aaf4" 16

/-- CAVP `SHAKE128LongMsg.rsp`, `Len = 2696` -- 337 bytes: LongMsg, 3-block absorb.

Message 337 B, output 16 B. -/
theorem shake128_cavp_long2696 :
    Keccak.shake128 (hexBytes "a6fe00064257aa318b621c5eb311d32bb8004c2fa1a969d205d71762cc5d2e633907992629d1b69d9557ff6d5e8deb454ab00f6e497c89a4fea09e257a6fa2074bd818ceb5981b3e3faefd6e720f2d1edd9c5e4a5c51e5009abf636ed5bca53fe159c8287014a1bd904f5c8a7501625f79ac81eb618f478ce21cae6664acffb30572f059e1ad0fc2912264e8f1ca52af26c8bf78e09d75f3dd9fc734afa8770abe0bd78c90cc2ff448105fb16dd2c5b7edd8611a62e537db9331f5023e16d6ec150cc6e706d7c7fcbfff930c7281831fd5c4aff86ece57ed0db882f59a5fe403105d0592ca38a081fed84922873f538ee774f13b8cc09bd0521db4374aec69f4bae6dcb66455822c0b84c91a3474ffac2ad06f0a4423cd2c6a49d4f0d6242d6a1890937b5d9835a5f0ea5b1d01884d22a6c1718e1f60b3ab5e232947c76ef70b344171083c688093b5f1475377e3069863") 16 =
      hexBytes "3109d9472ca436e805c6b3db2251a9bc" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "a6fe00064257aa318b621c5eb311d32bb8004c2fa1a969d205d71762cc5d2e633907992629d1b69d9557ff6d5e8deb454ab00f6e497c89a4fea09e257a6fa2074bd818ceb5981b3e3faefd6e720f2d1edd9c5e4a5c51e5009abf636ed5bca53fe159c8287014a1bd904f5c8a7501625f79ac81eb618f478ce21cae6664acffb30572f059e1ad0fc2912264e8f1ca52af26c8bf78e09d75f3dd9fc734afa8770abe0bd78c90cc2ff448105fb16dd2c5b7edd8611a62e537db9331f5023e16d6ec150cc6e706d7c7fcbfff930c7281831fd5c4aff86ece57ed0db882f59a5fe403105d0592ca38a081fed84922873f538ee774f13b8cc09bd0521db4374aec69f4bae6dcb66455822c0b84c91a3474ffac2ad06f0a4423cd2c6a49d4f0d6242d6a1890937b5d9835a5f0ea5b1d01884d22a6c1718e1f60b3ab5e232947c76ef70b344171083c688093b5f1475377e3069863" 337 && hexOfLen "3109d9472ca436e805c6b3db2251a9bc" 16

/-- CAVP `SHAKE128LongMsg.rsp`, `Len = 5400` -- 675 bytes: LongMsg, 5-block absorb.

Message 675 B, output 16 B. -/
theorem shake128_cavp_long5400 :
    Keccak.shake128 (hexBytes "790c3f0fd4951582e17f64a586a5f43363b8fc9412798caead2c28fd9149b5e662749a4850af1f5598cf18a04d2cc876589d0072bea4874c21e5bef28add84da65d05896cd03bda90a2ce39958278345eaea0b792fbbfbc054a18f790a189e2d8908c220d5f8b926407f0bb830fced47228766d0ef28b0b14e46e1bb9b62cb88d705200feff6da7541b1d9275c15ce25075d59a186516ec818bdfde0c423d29355adba8aa465e73e15a8950b64d8ee87a2522b117aa0fdadb9ef2b0f0ec37cf50de9d7ba7aaea928c54e878fd1af1513f94f264a557b240739c3b370ffaa915707a2c0c7fb37e8dc588af7d82a010a74173d90749e4cac7ea120dc2c2140d9604abebed8af696b02d6432c11f73696500102b2b6de7a5ebbf8f0ef6bfcee1bb9de2717151dacfc4148636f60c1b68150c188d4399c6d0066461a3454161a2109cbc313a7cd696141b5d108ed0ee8931b5db53e25608d5a279486f310f92eb1f9197cfcb6470663ab25753fe16936935ae07337a1b34236a4e91c74c62d909431d138186914edca27a0375b6457074bb44fa908d51bf45a884dc4fe9f38aa9258fbe1b1e9bb845e5c2fffa69d62c481d2b43ffaea220b8f79c866dbc3a4e272169d5e0d5ec435e7f3d9b566b511d3fe5b161c530850ef9d1f63ea5159f9a2fe15c19774efb8672c93a741e4d4ec9d8af87e2a5b562c084c242538a98abd51fcfa6e7430c41d81f6e59f8b68207c8aec51f3505cfd3ebf642d17382b7d7a563570addd88067eed0d91cc7c3ac44803ee0d7d769c250e7aace53fd31e5bb71b711d85bac3dd6012393e33faa1e6d96e56d4248464f425a2edf1a7efcc4bfd0777a9fef32a704d584294deeee7afb534ed50f163fc950aa0effc57757b76d38211bd207005e8cc27ef3dd441524666be7b27ebf9ac2e45da7aac554e7403c1f40501f41a9c") 16 =
      hexBytes "aa01fa03bf2287b01f5a747c1536e103" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "790c3f0fd4951582e17f64a586a5f43363b8fc9412798caead2c28fd9149b5e662749a4850af1f5598cf18a04d2cc876589d0072bea4874c21e5bef28add84da65d05896cd03bda90a2ce39958278345eaea0b792fbbfbc054a18f790a189e2d8908c220d5f8b926407f0bb830fced47228766d0ef28b0b14e46e1bb9b62cb88d705200feff6da7541b1d9275c15ce25075d59a186516ec818bdfde0c423d29355adba8aa465e73e15a8950b64d8ee87a2522b117aa0fdadb9ef2b0f0ec37cf50de9d7ba7aaea928c54e878fd1af1513f94f264a557b240739c3b370ffaa915707a2c0c7fb37e8dc588af7d82a010a74173d90749e4cac7ea120dc2c2140d9604abebed8af696b02d6432c11f73696500102b2b6de7a5ebbf8f0ef6bfcee1bb9de2717151dacfc4148636f60c1b68150c188d4399c6d0066461a3454161a2109cbc313a7cd696141b5d108ed0ee8931b5db53e25608d5a279486f310f92eb1f9197cfcb6470663ab25753fe16936935ae07337a1b34236a4e91c74c62d909431d138186914edca27a0375b6457074bb44fa908d51bf45a884dc4fe9f38aa9258fbe1b1e9bb845e5c2fffa69d62c481d2b43ffaea220b8f79c866dbc3a4e272169d5e0d5ec435e7f3d9b566b511d3fe5b161c530850ef9d1f63ea5159f9a2fe15c19774efb8672c93a741e4d4ec9d8af87e2a5b562c084c242538a98abd51fcfa6e7430c41d81f6e59f8b68207c8aec51f3505cfd3ebf642d17382b7d7a563570addd88067eed0d91cc7c3ac44803ee0d7d769c250e7aace53fd31e5bb71b711d85bac3dd6012393e33faa1e6d96e56d4248464f425a2edf1a7efcc4bfd0777a9fef32a704d584294deeee7afb534ed50f163fc950aa0effc57757b76d38211bd207005e8cc27ef3dd441524666be7b27ebf9ac2e45da7aac554e7403c1f40501f41a9c" 675 && hexOfLen "aa01fa03bf2287b01f5a747c1536e103" 16

/-- CAVP `SHAKE256ShortMsg.rsp`, `Len = 0` -- empty message; re-anchors `Keccak.shake256_empty_kat` (all 32 bytes).

Message 0 B, output 32 B. -/
theorem shake256_cavp_len0 :
    Keccak.shake256 (hexBytes "") 32 =
      hexBytes "46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762f" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "" 0 && hexOfLen "46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762f" 32

/-- CAVP `SHAKE256ShortMsg.rsp`, `Len = 1072` -- 134 bytes: **q == 2** minimal two-byte pad `0x1F 0x80`.

Message 134 B, output 32 B. -/
theorem shake256_cavp_len1072 :
    Keccak.shake256 (hexBytes "719effd45ed3a8394bf6c49b43f35879176a598601bd6f598867f966a38f512d21dc51b1488c162cbdc00301a41a09f2078a26937c652cfe02b8c4c92ddbb23583495ba825ae845eb2425c5b6856bda48c2cafae0c0c2e1764942d94be50da2b5d8b24a23b647a37f124d691d8cefbf76ef8fbc0fbdafb0a74a53aaf9f165075784ab485d4d4") 32 =
      hexBytes "6881babbb48e9eea72eeb3524db56e4efc323f3350b6be3cdb1f9c6826e359da" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "719effd45ed3a8394bf6c49b43f35879176a598601bd6f598867f966a38f512d21dc51b1488c162cbdc00301a41a09f2078a26937c652cfe02b8c4c92ddbb23583495ba825ae845eb2425c5b6856bda48c2cafae0c0c2e1764942d94be50da2b5d8b24a23b647a37f124d691d8cefbf76ef8fbc0fbdafb0a74a53aaf9f165075784ab485d4d4" 134 && hexOfLen "6881babbb48e9eea72eeb3524db56e4efc323f3350b6be3cdb1f9c6826e359da" 32

/-- CAVP `SHAKE256ShortMsg.rsp`, `Len = 1080` -- 135 bytes = rate-1: **q == 1 PAD-COLLAPSE BRANCH** (single `0x9F` byte).

Message 135 B, output 32 B. -/
theorem shake256_cavp_len1080 :
    Keccak.shake256 (hexBytes "362f1eb00b37a9613b1ae82b90452579d42f8b1f9ede95f86badc6cdf04c9b79af08be4bc94d7cac136979026b92a2d44d2b642ea1431b47d75fce61367919f171486a007cc271d19de0d1c4c6a11c7a2251fe3aee0bb8938a7dd043d0eb0758a4768c95cc9f6f1703075839487879b47c29c10b2c3e5326ac8f363c65aa4ef76f1b8bd363eb60") 32 =
      hexBytes "c6ce60c1852ea780ed845aac4ca6a30e09f5c0064c9675865178717cfeb1dc97" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "362f1eb00b37a9613b1ae82b90452579d42f8b1f9ede95f86badc6cdf04c9b79af08be4bc94d7cac136979026b92a2d44d2b642ea1431b47d75fce61367919f171486a007cc271d19de0d1c4c6a11c7a2251fe3aee0bb8938a7dd043d0eb0758a4768c95cc9f6f1703075839487879b47c29c10b2c3e5326ac8f363c65aa4ef76f1b8bd363eb60" 135 && hexOfLen "c6ce60c1852ea780ed845aac4ca6a30e09f5c0064c9675865178717cfeb1dc97" 32

/-- CAVP `SHAKE256ShortMsg.rsp`, `Len = 1088` -- 136 bytes = exactly 1 rate block: FULL EXTRA pad block -> **2-block absorb**.

Message 136 B, output 32 B. -/
theorem shake256_cavp_len1088 :
    Keccak.shake256 (hexBytes "d8f12b97f81d47aebbfb7314ff04172cf2be71c3778e238bcccdeecb691fbd542b00e5b7b1a0abb507f107f781fea700ea7e375fdea9e029754a0ea62216774bda3c59e8783d022360fe9625621c0d93e27f7bc03632942150716f019d048a752ccc0f93139c55df0f4aaa066a0550cf22e8c54e47d0475ba56b9842a392ffbc6bd98f1e4b64abd1") 32 =
      hexBytes "e2e1c432dd07c2ee89a78f31211c92eeb5306c4fa4db93c4e5cd43080d6079e4" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "d8f12b97f81d47aebbfb7314ff04172cf2be71c3778e238bcccdeecb691fbd542b00e5b7b1a0abb507f107f781fea700ea7e375fdea9e029754a0ea62216774bda3c59e8783d022360fe9625621c0d93e27f7bc03632942150716f019d048a752ccc0f93139c55df0f4aaa066a0550cf22e8c54e47d0475ba56b9842a392ffbc6bd98f1e4b64abd1" 136 && hexOfLen "e2e1c432dd07c2ee89a78f31211c92eeb5306c4fa4db93c4e5cd43080d6079e4" 32

/-- CAVP `SHAKE256ShortMsg.rsp`, `Len = 1096` -- 137 bytes: **2-block absorb**, partial second block.

Message 137 B, output 32 B. -/
theorem shake256_cavp_len1096 :
    Keccak.shake256 (hexBytes "a10d05d7e51e75dc150f640ec4722837220b86df2a3580ca1c826ec22ea250977e8663634cc4f212663e6f22e3ffc2a81465e194b885a1356fcbcc0072e1738d80d285e21c70a1f4f5f3296ba6e298a69f3715ff63be4850f5be6cb68cdba5948e3b94dbbce82989aa75b97073e55139aac849a894a71c2294a2776ce6588fb59007b8d796f434da6e") 32 =
      hexBytes "02f17bf86dc7b7f9c3fb96e4b3a10ca574cd0f8dedda50f3dda8008ce9e8fec9" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "a10d05d7e51e75dc150f640ec4722837220b86df2a3580ca1c826ec22ea250977e8663634cc4f212663e6f22e3ffc2a81465e194b885a1356fcbcc0072e1738d80d285e21c70a1f4f5f3296ba6e298a69f3715ff63be4850f5be6cb68cdba5948e3b94dbbce82989aa75b97073e55139aac849a894a71c2294a2776ce6588fb59007b8d796f434da6e" 137 && hexOfLen "02f17bf86dc7b7f9c3fb96e4b3a10ca574cd0f8dedda50f3dda8008ce9e8fec9" 32

/-- CAVP `SHAKE256ShortMsg.rsp`, `Len = 2168` -- 271 bytes = 2*rate-1: **q == 1 collapse AT the 2-block boundary**.

Message 271 B, output 32 B. -/
theorem shake256_cavp_len2168 :
    Keccak.shake256 (hexBytes "a1ce406d09c02ca1c3cc97f25c9b96eeb9d3480c053b67edee201ce111f718adb243e08cb1b96873b9a2e499bb82db379bf77d8c29e3362552cd835b9885051dbf07d4f0c9a21533255acfa8248afa30acced9d6301f8a0fdf40dc401c5a60812fe3c3a13ac35a6a6ebaff267efc1c62541f05f104378b34fe40ce9987bc52626a9c55a8ea64609ffc8b1d1bb3206853fcb4a8e58b73601b1594016dc0f40347d8fd330cc3cd4f5a3794d090aa3e078d0a536bbbaf1b324d8e051ec4af499ab8e1cd05d5ac464e24879fc18b4b9e2098e8c5f67a56762850cf5bcda73c053f3dedd3720b8c168583547297177e88dcfafcd1f02a6acd6bae425eb51c4f6e1c5f64d823b74d861d0106d7fb392b4363") 32 =
      hexBytes "a7835b81740824ebfc4a0dda40da7a70a66f9f3a8ea77cf857664ff955c5c5fe" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "a1ce406d09c02ca1c3cc97f25c9b96eeb9d3480c053b67edee201ce111f718adb243e08cb1b96873b9a2e499bb82db379bf77d8c29e3362552cd835b9885051dbf07d4f0c9a21533255acfa8248afa30acced9d6301f8a0fdf40dc401c5a60812fe3c3a13ac35a6a6ebaff267efc1c62541f05f104378b34fe40ce9987bc52626a9c55a8ea64609ffc8b1d1bb3206853fcb4a8e58b73601b1594016dc0f40347d8fd330cc3cd4f5a3794d090aa3e078d0a536bbbaf1b324d8e051ec4af499ab8e1cd05d5ac464e24879fc18b4b9e2098e8c5f67a56762850cf5bcda73c053f3dedd3720b8c168583547297177e88dcfafcd1f02a6acd6bae425eb51c4f6e1c5f64d823b74d861d0106d7fb392b4363" 271 && hexOfLen "a7835b81740824ebfc4a0dda40da7a70a66f9f3a8ea77cf857664ff955c5c5fe" 32

/-- CAVP `SHAKE256ShortMsg.rsp`, `Len = 2176` -- 272 bytes = exactly 2 rate blocks -> **3-block absorb**.

Message 272 B, output 32 B. -/
theorem shake256_cavp_len2176 :
    Keccak.shake256 (hexBytes "104fefe89f08d15d36a2233f42a7defa917c5ad2642e06cac56d5cc51ad914ecfb7d984f4199b9cf5fa5a03bf69207b9a353a9681c9cf6437bea0c49d9c3e3db1f3fc76519c70c40cc1dfdd70a9c150943c272cf9eeb861f485f10100c8f4a3e259c6470501932782512225ba64d70b219cf9d5013a21d25d6d65062dcc6b3deb49d58b90d18933f118df70ff42c807ccc851233a34a221eca56b38971ef858475488988794a975d3894633a19c1ae2f05e9b9c0756affd3cfe823ccf29228f60fa7e025bc39a79943325126409460926b057a3fb28a1b098b938872883804fd2bc245d7fd6d29bcda6ca6198f2eff6ea7e03ef78133de8ba65fc8c45a688160719fa1e7646d878ea44c4b5c2e16f48b") 32 =
      hexBytes "46293a63c235750d58a24edca5ba637b96cae74325c6c8122c4155c0d15805e6" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "104fefe89f08d15d36a2233f42a7defa917c5ad2642e06cac56d5cc51ad914ecfb7d984f4199b9cf5fa5a03bf69207b9a353a9681c9cf6437bea0c49d9c3e3db1f3fc76519c70c40cc1dfdd70a9c150943c272cf9eeb861f485f10100c8f4a3e259c6470501932782512225ba64d70b219cf9d5013a21d25d6d65062dcc6b3deb49d58b90d18933f118df70ff42c807ccc851233a34a221eca56b38971ef858475488988794a975d3894633a19c1ae2f05e9b9c0756affd3cfe823ccf29228f60fa7e025bc39a79943325126409460926b057a3fb28a1b098b938872883804fd2bc245d7fd6d29bcda6ca6198f2eff6ea7e03ef78133de8ba65fc8c45a688160719fa1e7646d878ea44c4b5c2e16f48b" 272 && hexOfLen "46293a63c235750d58a24edca5ba637b96cae74325c6c8122c4155c0d15805e6" 32

/-- CAVP `SHAKE256LongMsg.rsp`, `Len = 2184` -- 273 bytes: LongMsg, 3-block absorb.

Message 273 B, output 32 B. -/
theorem shake256_cavp_long2184 :
    Keccak.shake256 (hexBytes "dc5a100fa16df1583c79722a0d72833d3bf22c109b8889dbd35213c6bfce205813edae3242695cfd9f59b9a1c203c1b72ef1a5423147cb990b5316a85266675894e2644c3f9578cebe451a09e58c53788fe77a9e850943f8a275f830354b0593a762bac55e984db3e0661eca3cb83f67a6fb348e6177f7dee2df40c4322602f094953905681be3954fe44c4c902c8f6bba565a788b38f13411ba76ce0f9f6756a2a2687424c5435a51e62df7a8934b6e141f74c6ccf539e3782d22b5955d3baf1ab2cf7b5c3f74ec2f9447344e937957fd7f0bdfec56d5d25f61cde18c0986e244ecf780d6307e313117256948d4230ebb9ea62bb302cfe80d7dfebabc4a51d7687967ed5b416a139e974c005fff507a96") 32 =
      hexBytes "2bac5716803a9cda8f9e84365ab0a681327b5ba34fdedfb1c12e6e807f45284b" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "dc5a100fa16df1583c79722a0d72833d3bf22c109b8889dbd35213c6bfce205813edae3242695cfd9f59b9a1c203c1b72ef1a5423147cb990b5316a85266675894e2644c3f9578cebe451a09e58c53788fe77a9e850943f8a275f830354b0593a762bac55e984db3e0661eca3cb83f67a6fb348e6177f7dee2df40c4322602f094953905681be3954fe44c4c902c8f6bba565a788b38f13411ba76ce0f9f6756a2a2687424c5435a51e62df7a8934b6e141f74c6ccf539e3782d22b5955d3baf1ab2cf7b5c3f74ec2f9447344e937957fd7f0bdfec56d5d25f61cde18c0986e244ecf780d6307e313117256948d4230ebb9ea62bb302cfe80d7dfebabc4a51d7687967ed5b416a139e974c005fff507a96" 273 && hexOfLen "2bac5716803a9cda8f9e84365ab0a681327b5ba34fdedfb1c12e6e807f45284b" 32

/-- CAVP `SHAKE256LongMsg.rsp`, `Len = 4376` -- 547 bytes: LongMsg, 5-block absorb.

Message 547 B, output 32 B. -/
theorem shake256_cavp_long4376 :
    Keccak.shake256 (hexBytes "fbcfacf7a3667d043ca2f2670d7fab8ede75cc610a43ac23d6ebd29901fe1d6f9c1942d71cb07c73ae0a7e75ca8dad050b3c8ce33e7e774db9219523ee9e08493f9f664d14be6d492b90f20b30e21b748e42ce1e84c269417bf8b4d8974914ff8c6801a0b319b94e5d3b367167055ea40e907b5b0595eac9c57917012586a95b2a7cf9192048c94ae91333ef967edf5d342c79e2e88262ab3faaa6e5bfde2f23c2e3380084d304057a20cfcde5d60566a820b2fb560e39b090954ace8ed80e20fba5a49d0643d146b66bf3527d94378911740cee77c3d8a06042e902b9fcae1a7ecb2737cf1f9ad745fb88c78640df8c172e71027228a54359b76cca69d277d9f25da81706efc67ed0d87474276364386358c88070c5096121febc6ec6e3d22400610e86d43cbd04ff0ba1a189842e559df9f9b098236dc1601fbf36f7b625c450e143ca618ce631799bf596d42ba5ab6d1aebda13c9372cbf205f6a25d3d98289e42e2bd46aabcce7905a9a2fe0310179c28846083fd16ae50b835177c357245373b7f3555b739ff0f3b7f7c22c3a216cf9b73ca00ea1437ce71334160d06725895c6680ee9a7703dcbf3f3b69628d1ecc7600303bd117f29bdf65b29394d363d5243d4249bad087520f8d733a763daa1356be458d487e59694160ed9d09636adb2167dc2f9ee2f41faadeb60e55304354ac127c7dc6d3e6b745a954e59483b4ebe28ac0e8cd2ac4962fa7666da60164d0f48147a5c2a524f66aa37af5cca0dc87d5f") 32 =
      hexBytes "f7c566438926889d92f8d59c070bb2cdd7ea5c79cda501c7cf1fba605ce984fd" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "fbcfacf7a3667d043ca2f2670d7fab8ede75cc610a43ac23d6ebd29901fe1d6f9c1942d71cb07c73ae0a7e75ca8dad050b3c8ce33e7e774db9219523ee9e08493f9f664d14be6d492b90f20b30e21b748e42ce1e84c269417bf8b4d8974914ff8c6801a0b319b94e5d3b367167055ea40e907b5b0595eac9c57917012586a95b2a7cf9192048c94ae91333ef967edf5d342c79e2e88262ab3faaa6e5bfde2f23c2e3380084d304057a20cfcde5d60566a820b2fb560e39b090954ace8ed80e20fba5a49d0643d146b66bf3527d94378911740cee77c3d8a06042e902b9fcae1a7ecb2737cf1f9ad745fb88c78640df8c172e71027228a54359b76cca69d277d9f25da81706efc67ed0d87474276364386358c88070c5096121febc6ec6e3d22400610e86d43cbd04ff0ba1a189842e559df9f9b098236dc1601fbf36f7b625c450e143ca618ce631799bf596d42ba5ab6d1aebda13c9372cbf205f6a25d3d98289e42e2bd46aabcce7905a9a2fe0310179c28846083fd16ae50b835177c357245373b7f3555b739ff0f3b7f7c22c3a216cf9b73ca00ea1437ce71334160d06725895c6680ee9a7703dcbf3f3b69628d1ecc7600303bd117f29bdf65b29394d363d5243d4249bad087520f8d733a763daa1356be458d487e59694160ed9d09636adb2167dc2f9ee2f41faadeb60e55304354ac127c7dc6d3e6b745a954e59483b4ebe28ac0e8cd2ac4962fa7666da60164d0f48147a5c2a524f66aa37af5cca0dc87d5f" 547 && hexOfLen "f7c566438926889d92f8d59c070bb2cdd7ea5c79cda501c7cf1fba605ce984fd" 32

/-- CAVP `SHA3_256ShortMsg.rsp`, `Len = 0` -- empty message; re-anchors `MlKemDecaps.sha3_256_empty_kat`.

Message 0 B, output 32 B. -/
theorem sha3_256_cavp_len0 :
    MlKemDecaps.sha3_256 (hexBytes "") =
      hexBytes "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "" 0 && hexOfLen "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a" 32

/-- CAVP `SHA3_256ShortMsg.rsp`, `Len = 1072` -- 134 bytes: **q == 2** minimal two-byte pad `0x06 0x80`.

Message 134 B, output 32 B. -/
theorem sha3_256_cavp_len1072 :
    MlKemDecaps.sha3_256 (hexBytes "e5022f4c7dfe2dbd207105e2f27aaedd5a765c27c0bc60de958b49609440501848ccf398cf66dfe8dd7d131e04f1432f32827a057b8904d218e68ba3b0398038d755bd13d5f168cfa8a11ab34c0540873940c2a62eace3552dcd6953c683fdb29983d4e417078f1988c560c9521e6f8c78997c32618fc510db282a985f868f2d973f82351d11") =
      hexBytes "3293a4b9aeb8a65e1014d3847500ffc8241594e9c4564cbd7ce978bfa50767fe" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "e5022f4c7dfe2dbd207105e2f27aaedd5a765c27c0bc60de958b49609440501848ccf398cf66dfe8dd7d131e04f1432f32827a057b8904d218e68ba3b0398038d755bd13d5f168cfa8a11ab34c0540873940c2a62eace3552dcd6953c683fdb29983d4e417078f1988c560c9521e6f8c78997c32618fc510db282a985f868f2d973f82351d11" 134 && hexOfLen "3293a4b9aeb8a65e1014d3847500ffc8241594e9c4564cbd7ce978bfa50767fe" 32

/-- CAVP `SHA3_256ShortMsg.rsp`, `Len = 1080` -- 135 bytes = rate-1: **sha3Pad q == 1 COLLAPSE BRANCH** (single `0x86` byte).

Message 135 B, output 32 B. -/
theorem sha3_256_cavp_len1080 :
    MlKemDecaps.sha3_256 (hexBytes "b1f6076509938432145bb15dbe1a7b2e007934be5f753908b50fd24333455970a7429f2ffbd28bd6fe1804c4688311f318fe3fcd9f6744410243e115bcb00d7e039a4fee4c326c2d119c42abd2e8f4155a44472643704cc0bc72403b8a8ab0fd4d68e04a059d6e5ed45033b906326abb4eb4147052779bad6a03b55ca5bd8b140e131bed2dfada") =
      hexBytes "f82d9602b231d332d902cb6436b15aef89acc591cb8626233ced20c0a6e80d7a" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "b1f6076509938432145bb15dbe1a7b2e007934be5f753908b50fd24333455970a7429f2ffbd28bd6fe1804c4688311f318fe3fcd9f6744410243e115bcb00d7e039a4fee4c326c2d119c42abd2e8f4155a44472643704cc0bc72403b8a8ab0fd4d68e04a059d6e5ed45033b906326abb4eb4147052779bad6a03b55ca5bd8b140e131bed2dfada" 135 && hexOfLen "f82d9602b231d332d902cb6436b15aef89acc591cb8626233ced20c0a6e80d7a" 32

/-- CAVP `SHA3_256ShortMsg.rsp`, `Len = 1088` -- 136 bytes = exactly 1 rate block -> **2-block absorb**.

Message 136 B, output 32 B. -/
theorem sha3_256_cavp_len1088 :
    MlKemDecaps.sha3_256 (hexBytes "56ea14d7fcb0db748ff649aaa5d0afdc2357528a9aad6076d73b2805b53d89e73681abfad26bee6c0f3d20215295f354f538ae80990d2281be6de0f6919aa9eb048c26b524f4d91ca87b54c0c54aa9b54ad02171e8bf31e8d158a9f586e92ffce994ecce9a5185cc80364d50a6f7b94849a914242fcb73f33a86ecc83c3403630d20650ddb8cd9c4") =
      hexBytes "4beae3515ba35ec8cbd1d94567e22b0d7809c466abfbafe9610349597ba15b45" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "56ea14d7fcb0db748ff649aaa5d0afdc2357528a9aad6076d73b2805b53d89e73681abfad26bee6c0f3d20215295f354f538ae80990d2281be6de0f6919aa9eb048c26b524f4d91ca87b54c0c54aa9b54ad02171e8bf31e8d158a9f586e92ffce994ecce9a5185cc80364d50a6f7b94849a914242fcb73f33a86ecc83c3403630d20650ddb8cd9c4" 136 && hexOfLen "4beae3515ba35ec8cbd1d94567e22b0d7809c466abfbafe9610349597ba15b45" 32

/-- CAVP `SHA3_256LongMsg.rsp`, `Len = 2184` -- 273 bytes: LongMsg, 3-block absorb.

Message 273 B, output 32 B. -/
theorem sha3_256_cavp_long2184 :
    MlKemDecaps.sha3_256 (hexBytes "b1caa396771a09a1db9bc20543e988e359d47c2a616417bbca1b62cb02796a888fc6eeff5c0b5c3d5062fcb4256f6ae1782f492c1cf03610b4a1fb7b814c057878e1190b9835425c7a4a0e182ad1f91535ed2a35033a5d8c670e21c575ff43c194a58a82d4a1a44881dd61f9f8161fc6b998860cbe4975780be93b6f87980bad0a99aa2cb7556b478ca35d1f3746c33e2bb7c47af426641cc7bbb3425e2144820345e1d0ea5b7da2c3236a52906acdc3b4d34e474dd714c0c40bf006a3a1d889a632983814bbc4a14fe5f159aa89249e7c738b3b73666bac2a615a83fd21ae0a1ce7352ade7b278b587158fd2fabb217aa1fe31d0bda53272045598015a8ae4d8cec226fefa58daa05500906c4d85e7567") =
      hexBytes "cb5648a1d61c6c5bdacd96f81c9591debc3950dcf658145b8d996570ba881a05" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "b1caa396771a09a1db9bc20543e988e359d47c2a616417bbca1b62cb02796a888fc6eeff5c0b5c3d5062fcb4256f6ae1782f492c1cf03610b4a1fb7b814c057878e1190b9835425c7a4a0e182ad1f91535ed2a35033a5d8c670e21c575ff43c194a58a82d4a1a44881dd61f9f8161fc6b998860cbe4975780be93b6f87980bad0a99aa2cb7556b478ca35d1f3746c33e2bb7c47af426641cc7bbb3425e2144820345e1d0ea5b7da2c3236a52906acdc3b4d34e474dd714c0c40bf006a3a1d889a632983814bbc4a14fe5f159aa89249e7c738b3b73666bac2a615a83fd21ae0a1ce7352ade7b278b587158fd2fabb217aa1fe31d0bda53272045598015a8ae4d8cec226fefa58daa05500906c4d85e7567" 273 && hexOfLen "cb5648a1d61c6c5bdacd96f81c9591debc3950dcf658145b8d996570ba881a05" 32

/-- CAVP `SHA3_512ShortMsg.rsp`, `Len = 0` -- empty message; re-anchors `MlKemDecaps.sha3_512_empty_kat`.

Message 0 B, output 64 B. -/
theorem sha3_512_cavp_len0 :
    MlKemDecaps.sha3_512 (hexBytes "") =
      hexBytes "a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "" 0 && hexOfLen "a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26" 64

/-- CAVP `SHA3_512ShortMsg.rsp`, `Len = 560` -- 70 bytes: **q == 2** minimal two-byte pad `0x06 0x80` at rate 72.

Message 70 B, output 64 B. -/
theorem sha3_512_cavp_len560 :
    MlKemDecaps.sha3_512 (hexBytes "881ff70ca34a3e1a0e864fd2615ca2a0e63def254e688c37a20ef6297cb3ae4c76d746b5e3d6bb41bd0d05d7df3eeded74351f4eb0ac801abe6dc10ef9b635055ee1dfbf4144") =
      hexBytes "9a10a7ce23c0497fe8783927f833232ae664f1e1b91302266b6ace25a9c253d1ecab1aaaa62f865469480b2145ed0e489ae3f3f9f7e6da27492c81b07e606fb6" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "881ff70ca34a3e1a0e864fd2615ca2a0e63def254e688c37a20ef6297cb3ae4c76d746b5e3d6bb41bd0d05d7df3eeded74351f4eb0ac801abe6dc10ef9b635055ee1dfbf4144" 70 && hexOfLen "9a10a7ce23c0497fe8783927f833232ae664f1e1b91302266b6ace25a9c253d1ecab1aaaa62f865469480b2145ed0e489ae3f3f9f7e6da27492c81b07e606fb6" 64

/-- CAVP `SHA3_512ShortMsg.rsp`, `Len = 568` -- 71 bytes = rate-1: **sha3Pad q == 1 COLLAPSE BRANCH** at rate 72 (single `0x86`).

Message 71 B, output 64 B. -/
theorem sha3_512_cavp_len568 :
    MlKemDecaps.sha3_512 (hexBytes "b0de0430c200d74bf41ea0c92f8f28e11b68006a884e0d4b0d884533ee58b38a438cc1a75750b6434f467e2d0cd9aa4052ceb793291b93ef83fd5d8620456ce1aff2941b3605a4") =
      hexBytes "9e9e469ca9226cd012f5c9cc39c96adc22f420030fcee305a0ed27974e3c802701603dac873ae4476e9c3d57e55524483fc01adaef87daa9e304078c59802757" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "b0de0430c200d74bf41ea0c92f8f28e11b68006a884e0d4b0d884533ee58b38a438cc1a75750b6434f467e2d0cd9aa4052ceb793291b93ef83fd5d8620456ce1aff2941b3605a4" 71 && hexOfLen "9e9e469ca9226cd012f5c9cc39c96adc22f420030fcee305a0ed27974e3c802701603dac873ae4476e9c3d57e55524483fc01adaef87daa9e304078c59802757" 64

/-- CAVP `SHA3_512ShortMsg.rsp`, `Len = 576` -- 72 bytes = exactly 1 rate block -> **2-block absorb** at rate 72.

Message 72 B, output 64 B. -/
theorem sha3_512_cavp_len576 :
    MlKemDecaps.sha3_512 (hexBytes "0ce9f8c3a990c268f34efd9befdb0f7c4ef8466cfdb01171f8de70dc5fefa92acbe93d29e2ac1a5c2979129f1ab08c0e77de7924ddf68a209cdfa0adc62f85c18637d9c6b33f4ff8") =
      hexBytes "b018a20fcf831dde290e4fb18c56342efe138472cbe142da6b77eea4fce52588c04c808eb32912faa345245a850346faec46c3a16d39bd2e1ddb1816bc57d2da" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "0ce9f8c3a990c268f34efd9befdb0f7c4ef8466cfdb01171f8de70dc5fefa92acbe93d29e2ac1a5c2979129f1ab08c0e77de7924ddf68a209cdfa0adc62f85c18637d9c6b33f4ff8" 72 && hexOfLen "b018a20fcf831dde290e4fb18c56342efe138472cbe142da6b77eea4fce52588c04c808eb32912faa345245a850346faec46c3a16d39bd2e1ddb1816bc57d2da" 64

/-- CAVP `SHA3_512LongMsg.rsp`, `Len = 1160` -- 145 bytes: LongMsg at rate 72 -> **3-block absorb**.

Message 145 B, output 64 B. -/
theorem sha3_512_cavp_long1160 :
    MlKemDecaps.sha3_512 (hexBytes "664ef2e3a7059daf1c58caf52008c5227e85cdcb83b4c59457f02c508d4f4f69f826bd82c0cffc5cb6a97af6e561c6f96970005285e58f21ef6511d26e709889a7e513c434c90a3cf7448f0caeec7114c747b2a0758a3b4503a7cf0c69873ed31d94dbef2b7b2f168830ef7da3322c3d3e10cafb7c2c33c83bbf4c46a31da90cff3bfd4ccc6ed4b310758491eeba603a76") =
      hexBytes "e5825ff1a3c070d5a52fbbe711854a440554295ffb7a7969a17908d10163bfbe8f1d52a676e8a0137b56a11cdf0ffbb456bc899fc727d14bd8882232549d914e" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "664ef2e3a7059daf1c58caf52008c5227e85cdcb83b4c59457f02c508d4f4f69f826bd82c0cffc5cb6a97af6e561c6f96970005285e58f21ef6511d26e709889a7e513c434c90a3cf7448f0caeec7114c747b2a0758a3b4503a7cf0c69873ed31d94dbef2b7b2f168830ef7da3322c3d3e10cafb7c2c33c83bbf4c46a31da90cff3bfd4ccc6ed4b310758491eeba603a76" 145 && hexOfLen "e5825ff1a3c070d5a52fbbe711854a440554295ffb7a7969a17908d10163bfbe8f1d52a676e8a0137b56a11cdf0ffbb456bc899fc727d14bd8882232549d914e" 64

/-- CAVP `SHAKE256VariableOut.rsp`, `COUNT = 0` (`Outputlen = 16`) -- outLen = 2 bytes: **extreme squeeze truncation** (2 of 136 rate bytes kept).

Message 32 B, output 2 B. -/
theorem shake256_cavp_var_c0 :
    Keccak.shake256 (hexBytes "c61a9188812ae73994bc0d6d4021e31bf124dc72669749111232da7ac29e61c4") 2 =
      hexBytes "23ce" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "c61a9188812ae73994bc0d6d4021e31bf124dc72669749111232da7ac29e61c4" 32 && hexOfLen "23ce" 2

/-- CAVP `SHAKE256VariableOut.rsp`, `COUNT = 670` (`Outputlen = 1088`) -- outLen = 136 bytes = **exactly one rate block** (nblocks = 1, no inter-block permutation).

Message 32 B, output 136 B. -/
theorem shake256_cavp_var_c670 :
    Keccak.shake256 (hexBytes "dc886df3f69c49513de3627e9481db5871e8ee88eb9f99611541930a8bc885e0") 136 =
      hexBytes "00648afbc5e651649db1fd82936b00dbbc122fb4c877860d385c4950d56de7e096d613d7a3f27ed8f26334b0ccc1407b41dccb23dfaa529818d1125cd5348092524366b85fabb97c6cd1e6066f459bcc566da87ec9b7ba36792d118ac39a4ccef6192bbf3a54af18e57b0c146101f6aeaa822bc4b4c9708b09f0b3bab41bcce964d999d1107bd7c2" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "dc886df3f69c49513de3627e9481db5871e8ee88eb9f99611541930a8bc885e0" 32 && hexOfLen "00648afbc5e651649db1fd82936b00dbbc122fb4c877860d385c4950d56de7e096d613d7a3f27ed8f26334b0ccc1407b41dccb23dfaa529818d1125cd5348092524366b85fabb97c6cd1e6066f459bcc566da87ec9b7ba36792d118ac39a4ccef6192bbf3a54af18e57b0c146101f6aeaa822bc4b4c9708b09f0b3bab41bcce964d999d1107bd7c2" 136

/-- CAVP `SHAKE256VariableOut.rsp`, `COUNT = 675` (`Outputlen = 1096`) -- outLen = 137 bytes = rate+1: **MULTI-BLOCK SQUEEZE** - forces the inter-block `keccakF` and reads byte 0 of block 2.

Message 32 B, output 137 B. -/
theorem shake256_cavp_var_c675 :
    Keccak.shake256 (hexBytes "8d8001e2c096f1b88e7c9224a086efd4797fbf74a8033a2d422a2b6b8f6747e4") 137 =
      hexBytes "2e975f6a8a14f0704d51b13667d8195c219f71e6345696c49fa4b9d08e9225d3d39393425152c97e71dd24601c11abcfa0f12f53c680bd3ae757b8134a9c10d429615869217fdd5885c4db174985703a6d6de94a667eac3023443a8337ae1bc601b76d7d38ec3c34463105f0d3949d78e562a039e4469548b609395de5a4fd43c46ca9fd6ee29ada5e" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "8d8001e2c096f1b88e7c9224a086efd4797fbf74a8033a2d422a2b6b8f6747e4" 32 && hexOfLen "2e975f6a8a14f0704d51b13667d8195c219f71e6345696c49fa4b9d08e9225d3d39393425152c97e71dd24601c11abcfa0f12f53c680bd3ae757b8134a9c10d429615869217fdd5885c4db174985703a6d6de94a667eac3023443a8337ae1bc601b76d7d38ec3c34463105f0d3949d78e562a039e4469548b609395de5a4fd43c46ca9fd6ee29ada5e" 137

/-- CAVP `SHAKE256VariableOut.rsp`, `COUNT = 1240` (`Outputlen = 2000`) -- outLen = 250 bytes: **multi-block squeeze**, deep into the second block.

Message 32 B, output 250 B. -/
theorem shake256_cavp_var_c1240 :
    Keccak.shake256 (hexBytes "dc886df3f69c49513de3627e9481db5871e8ee88eb9f99611541930a8bc885e0") 250 =
      hexBytes "00648afbc5e651649db1fd82936b00dbbc122fb4c877860d385c4950d56de7e096d613d7a3f27ed8f26334b0ccc1407b41dccb23dfaa529818d1125cd5348092524366b85fabb97c6cd1e6066f459bcc566da87ec9b7ba36792d118ac39a4ccef6192bbf3a54af18e57b0c146101f6aeaa822bc4b4c9708b09f0b3bab41bcce964d999d1107bd7c27af989ebe1e104a35478df362ec4c9628f5ea29cc1164b92960d42068a59b1ddcb8875722ed59df36ea654d97b6bf39e5075121ec93f8a8ea6ee5d923997ae8a9d4c315a3d074e3ff83dfa26490f0f5b00a3cc3f110f0f761eaac885a3d1eee302014191733bf77b4d58cca49258897d6460" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "dc886df3f69c49513de3627e9481db5871e8ee88eb9f99611541930a8bc885e0" 32 && hexOfLen "00648afbc5e651649db1fd82936b00dbbc122fb4c877860d385c4950d56de7e096d613d7a3f27ed8f26334b0ccc1407b41dccb23dfaa529818d1125cd5348092524366b85fabb97c6cd1e6066f459bcc566da87ec9b7ba36792d118ac39a4ccef6192bbf3a54af18e57b0c146101f6aeaa822bc4b4c9708b09f0b3bab41bcce964d999d1107bd7c27af989ebe1e104a35478df362ec4c9628f5ea29cc1164b92960d42068a59b1ddcb8875722ed59df36ea654d97b6bf39e5075121ec93f8a8ea6ee5d923997ae8a9d4c315a3d074e3ff83dfa26490f0f5b00a3cc3f110f0f761eaac885a3d1eee302014191733bf77b4d58cca49258897d6460" 250

/-- CAVP `SHAKE128VariableOut.rsp`, `COUNT = 0` (`Outputlen = 128`) -- outLen = 16 bytes at rate 168.

Message 16 B, output 16 B. -/
theorem shake128_cavp_var_c0 :
    Keccak.shake128 (hexBytes "84e950051876050dc851fbd99e6247b8") 16 =
      hexBytes "8599bd89f63a848c49ca593ec37a12c6" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "84e950051876050dc851fbd99e6247b8" 16 && hexOfLen "8599bd89f63a848c49ca593ec37a12c6" 16

/-- CAVP `SHAKE128VariableOut.rsp`, `COUNT = 1116` (`Outputlen = 1120`) -- outLen = 140 bytes at rate 168: large single-block squeeze with truncation.

Message 16 B, output 140 B. -/
theorem shake128_cavp_var_c1116 :
    Keccak.shake128 (hexBytes "a8ded9816defca8327c194a48a88ae4e") 140 =
      hexBytes "ed7397b2215c6c412bf444b1b96fc55c531aef025c6dd13fb4ab53fcc20c91917d82c8d6710a8d7b4c24d18b54150490e98ee01b4a4b9790d1878810a8392d3fa203b066327c0c67cace3a08c57d0d30b62ba43121d8d715637884f055c55ad6689692249885dce01c96979f1a2b309943e14abb0ba8e227bceb381667579e10694bd442b99064aa88501431" := by native_decide
-- transcription guard: the pinned hex is even-length, all-hex, and exactly the CAVP byte count
#guard hexOfLen "a8ded9816defca8327c194a48a88ae4e" 16 && hexOfLen "ed7397b2215c6c412bf444b1b96fc55c531aef025c6dd13fb4ab53fcc20c91917d82c8d6710a8d7b4c24d18b54150490e98ee01b4a4b9790d1878810a8392d3fa203b066327c0c67cace3a08c57d0d30b62ba43121d8d715637884f055c55ad6689692249885dce01c96979f1a2b309943e14abb0ba8e227bceb381667579e10694bd442b99064aa88501431" 140

/-! ## Branch-reachability witnesses.

The coverage claims in the header are MACHINE-CHECKED here rather than merely asserted. These
`#guard`s show (a) that the vectors above really do drive `pad` / `sha3Pad` into the `q == 1`
collapse and `absorb` into more than one block, and (b) that the pre-existing nine KATs on the empty
string and `"abc"` really did NOT. If someone later deletes the long vectors, these witnesses still
document which branch each message length selects. -/

-- The `q == 1` collapse IS reached at rate-1, and emits the merged byte (`0x9F` for SHAKE).
#guard (Keccak.pad 136 (List.replicate 135 0x00)).length == 136
#guard (Keccak.pad 136 (List.replicate 135 0x00)).getLast! == 0x9F
#guard (Keccak.pad 168 (List.replicate 167 0x00)).getLast! == 0x9F

-- ... and `0x86` for SHA-3, at both SHA-3 rates.
#guard (MlKemDecaps.sha3Pad 136 (List.replicate 135 0x00)).getLast! == 0x86
#guard (MlKemDecaps.sha3Pad 72 (List.replicate 71 0x00)).getLast! == 0x86
#guard (MlKemDecaps.sha3Pad 72 (List.replicate 71 0x00)).length == 72

-- The neighbouring `q == 2` branch emits TWO distinct bytes, not the merged one.
#guard (Keccak.pad 136 (List.replicate 134 0x00)).drop 134 == [0x1F, 0x80]
#guard (MlKemDecaps.sha3Pad 72 (List.replicate 70 0x00)).drop 70 == [0x06, 0x80]

-- THE OLD EVIDENCE, restated as a witness: the empty string and `"abc"` both pad to exactly ONE
-- block and both take the `else` branch, so neither could ever have caught a `q == 1` bug.
#guard (Keccak.pad 136 []).length == 136
#guard (Keccak.pad 136 [0x61, 0x62, 0x63]).length == 136
#guard (Keccak.pad 136 []).drop 134 == [0x00, 0x80]
#guard (MlKemDecaps.sha3Pad 72 []).length == 72

-- Multi-block absorb IS reached: an exact-rate message needs a whole extra pad block, and the long
-- vectors need three and five.
#guard (Keccak.pad 136 (List.replicate 136 0x00)).length == 272          -- 2 blocks
#guard (Keccak.pad 136 (List.replicate 273 0x00)).length == 408          -- 3 blocks
#guard (Keccak.pad 168 (List.replicate 675 0x00)).length == 840          -- 5 blocks
#guard (MlKemDecaps.sha3Pad 72 (List.replicate 145 0x00)).length == 216  -- 3 blocks at rate 72

-- Multi-block SQUEEZE is reached only by the VariableOut vectors: every pre-existing KAT squeezed
-- 32 or 64 bytes, i.e. strictly one block at every rate in this tree.
#guard (137 + 136 - 1) / 136 == 2   -- shake256_cavp_var_c675 -> 2 squeeze blocks
#guard (250 + 136 - 1) / 136 == 2   -- shake256_cavp_var_c1240 -> 2 squeeze blocks
#guard (32 + 136 - 1) / 136 == 1    -- the OLD 32-byte KATs -> 1 squeeze block (no inter-block keccakF)
#guard (64 + 72 - 1) / 72 == 1      -- the OLD sha3_512 KAT -> 1 squeeze block

end Dregg2.Crypto.KeccakCavp
