// @generated by metatheory/EmitLayoutManifest.lean — DO NOT EDIT BY HAND.
//
// The rotated EffectVM column layout, exported from the Lean that DEFINES it and that emits the
// constraint descriptors READING it. The Rust producer (`turn::rotation_witness`) WRITES these
// same columns, and the audit gates check them — so all three now read one source instead of
// three hand-maintained mirrors.
//
// This module exists because the mirrors drifted, and drift here is not a lint failure — it is a
// soundness bug. The perms/VK completion weld once read limb 37 (`revoked_root` lane-0) while the
// producer wrote limb 38, and every honest setPermissions/setVerificationKey turn was UNSAT.
//
// Regenerate with the ack-gated emit pipeline (`scripts/emit_descriptors.py`); never hand-edit.

/// the v1 EffectVM face width — the base every rotated member graduates from
pub const EFFECT_VM_WIDTH: usize = 188;

/// one rotated state block's span (BEFORE and AFTER each occupy B_SPAN columns)
pub const B_SPAN: usize = 239;

/// column offset from a member's face to its AFTER block (= B_SPAN)
pub const AFTER_BLOCK_OFF: usize = 239;

/// the caveat region's span
pub const C_SPAN: usize = 43;

/// the caveat commitment carrier, in-region
pub const C_COMMIT: usize = 38;

/// the DFA route-commitment (rc) carrier, in-region
pub const C_RC_OFF: usize = 39;

/// 2*B_SPAN + C_SPAN — the rotated appendix appended to the v1 face
pub const APPENDIX_SPAN: usize = 521;

/// committed record/authority digest limb
pub const B_RECORD_DIGEST: usize = 24;

/// committed capability-root limb
pub const B_CAP_ROOT: usize = 25;

/// committed nullifier-root limb
pub const B_NULLIFIER_ROOT_OFF: usize = 26;

/// committed commitments-root limb
pub const B_COMMITMENTS_ROOT: usize = 27;

/// committed heap-root limb
pub const B_HEAP_ROOT: usize = 28;

/// committed lifecycle limb
pub const B_LIFECYCLE: usize = 29;

/// committed epoch limb
pub const B_EPOCH: usize = 30;

/// last SCALAR pre-iroot limb (disc/perms/vk/mode/fields-root ride past it)
pub const B_COMMITTED_HEIGHT: usize = 31;

/// WAVE-1 committed discriminant limb
pub const B_DISC: usize = 32;

/// WAVE-2 committed permissions-digest limb (lane 0 of the faithful 8-felt group)
pub const B_PERMS: usize = 33;

/// WAVE-2 committed verification-key-digest limb (lane 0 of the 8-felt group)
pub const B_VK: usize = 34;

/// WAVE-3 committed mode limb
pub const B_MODE: usize = 35;

/// WAVE-3 committed fields-root digest limb
pub const B_FIELDS_ROOT: usize = 36;

/// REVOKED-ROOT flag-day limb — inserted at 37, shifting every limb >= 37 by +1
pub const B_REVOKED_ROOT: usize = 37;

/// FIRST perms-digest completion limb; permsHash[1..7] ride B_PERMS_COMPLETION..+6. The producer writes these lanes and the in-circuit weld reads them: ONE source.
pub const B_PERMS_COMPLETION: usize = 38;

/// FIRST vk-digest completion limb; vkHash[1..7] ride B_VK_COMPLETION..+6
pub const B_VK_COMPLETION: usize = 45;

/// the iroot limb (pre-iroot limbs end here)
pub const B_IROOT: usize = 178;

/// the state-commitment limb
pub const B_STATE_COMMIT: usize = 179;
