// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IDreggVault.sol";

/// @title DreggVault
/// @notice Holds bridged assets (ERC-20 and ETH) with private note-based accounting.
///
/// Deposits create note commitments that the dregg federation observes and mirrors
/// into its private note tree. Withdrawals require an SP1-wrapped STARK proof that
/// verifies note ownership and spending validity.
///
/// SP1 verification is delegated to the SP1 Verifier Gateway (deterministic CREATE2
/// deployment across all EVM chains). The vault only needs to check that the proof
/// was generated by the correct program (matching programVkey) and that the public
/// outputs encode the expected withdrawal parameters.
contract DreggVault is IDreggVault {
    // ─── Immutables ─────────────────────────────────────────────────────────

    /// Address of the SP1 Verifier Gateway contract (same on all EVM chains).
    address public immutable sp1Verifier;

    /// Verification key identifying the dregg STARK verifier guest program.
    /// The SP1 verifier checks that the proof was generated by this exact program.
    bytes32 public immutable programVkey;

    // ─── State ──────────────────────────────────────────────────────────────

    /// Incremental Merkle tree of note commitments (simplified: stores leaves only).
    ///
    /// PLACEHOLDER: this keccak256 tree is a stand-in pending Poseidon2 circuit
    /// alignment. The real note tree is Poseidon2 (see IDreggVault noteCommitment
    /// docs); the SP1 guest program proves membership against the Poseidon2 tree,
    /// so until the on-chain tree is rebuilt as an incremental Poseidon2 tree the
    /// keccak root here and the circuit root only agree because the federation
    /// mirrors deposits. The root COMPARISON below is real (withdraw proofs must
    /// commit to the current root or one of the last ROOT_HISTORY_SIZE roots);
    /// the hash function is the placeholder.
    bytes32[] private noteCommitments;

    /// Current root of the note commitment tree.
    bytes32 public noteTreeRoot;

    /// Total number of deposits (== noteCommitments.length).
    uint256 public depositCount;

    /// Ring buffer of recent tree roots (Tornado-style). Withdrawals may prove
    /// against any of the last ROOT_HISTORY_SIZE roots, so a proof generated
    /// just before a new deposit remains spendable.
    uint256 public constant ROOT_HISTORY_SIZE = 32;
    bytes32[ROOT_HISTORY_SIZE] public rootHistory;
    uint256 public rootHistoryCount;

    /// Spent nullifiers (prevents double-withdrawal).
    mapping(bytes32 => bool) public usedNullifiers;

    /// Deposits indexed by note commitment (for frontend querying).
    mapping(bytes32 => DepositRecord) public deposits;

    /// Per-token deposited balance (address(0) = native ETH). Withdrawals may
    /// never exceed what was actually deposited for that token (solvency).
    mapping(address => uint256) public tokenBalances;

    /// Reentrancy guard status.
    uint256 private constant _NOT_ENTERED = 1;
    uint256 private constant _ENTERED = 2;
    uint256 private _reentrancyStatus = _NOT_ENTERED;

    // ─── Types ──────────────────────────────────────────────────────────────

    struct DepositRecord {
        address token;
        address depositor;
        uint256 amount;
        uint256 leafIndex;
        uint256 blockNumber;
    }

    // ─── Errors ─────────────────────────────────────────────────────────────

    error ZeroAmount();
    error DuplicateNoteCommitment();
    error NullifierAlreadyUsed(bytes32 nullifier);
    error ProofVerificationFailed();
    error TransferFailed();
    error InvalidProofOutputs();
    error AmountMismatch();
    error RecipientMismatch();
    error TokenMismatch();
    error VerifierNotContract();
    error UnknownRoot(bytes32 root);
    error InsufficientVaultBalance(address token, uint256 requested, uint256 available);
    error ReentrantCall();

    // ─── Modifiers ──────────────────────────────────────────────────────────

    /// Minimal hand-rolled reentrancy guard (no external dependency).
    modifier nonReentrant() {
        if (_reentrancyStatus == _ENTERED) revert ReentrantCall();
        _reentrancyStatus = _ENTERED;
        _;
        _reentrancyStatus = _NOT_ENTERED;
    }

    // ─── Constructor ────────────────────────────────────────────────────────

    /// @param _sp1Verifier Address of the SP1 Verifier Gateway.
    /// @param _programVkey Verification key for the dregg guest program.
    constructor(address _sp1Verifier, bytes32 _programVkey) {
        // Fail-closed: a staticcall to a codeless address returns success, so a
        // misconfigured verifier would silently accept every proof. Refuse to
        // deploy against an address with no code.
        if (_sp1Verifier.code.length == 0) revert VerifierNotContract();
        sp1Verifier = _sp1Verifier;
        programVkey = _programVkey;
    }

    // ─── Deposits ───────────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function deposit(
        address token,
        uint256 amount,
        bytes32 noteCommitment
    ) external {
        if (amount == 0) revert ZeroAmount();
        if (deposits[noteCommitment].blockNumber != 0) revert DuplicateNoteCommitment();

        // Transfer ERC-20 tokens from sender to this contract.
        // Using a low-level call to support non-standard ERC-20s (USDT, etc.).
        (bool success, bytes memory data) = token.call(
            abi.encodeWithSignature(
                "transferFrom(address,address,uint256)",
                msg.sender,
                address(this),
                amount
            )
        );
        if (!success || (data.length > 0 && !abi.decode(data, (bool)))) {
            revert TransferFailed();
        }

        // Record the deposit and update the note tree.
        uint256 leafIndex = depositCount;
        deposits[noteCommitment] = DepositRecord({
            token: token,
            depositor: msg.sender,
            amount: amount,
            leafIndex: leafIndex,
            blockNumber: block.number
        });
        noteCommitments.push(noteCommitment);
        depositCount = leafIndex + 1;
        tokenBalances[token] += amount;

        // Update the tree root (simplified: hash of all commitments).
        // In production, use an incremental Merkle tree for O(log n) updates.
        noteTreeRoot = _computeRoot();
        _recordRoot(noteTreeRoot);

        emit Deposit(token, amount, noteCommitment, leafIndex);
    }

    /// @inheritdoc IDreggVault
    function depositETH(bytes32 noteCommitment) external payable {
        if (msg.value == 0) revert ZeroAmount();
        if (deposits[noteCommitment].blockNumber != 0) revert DuplicateNoteCommitment();

        // Record the ETH deposit (token = address(0) for native ETH).
        uint256 leafIndex = depositCount;
        deposits[noteCommitment] = DepositRecord({
            token: address(0),
            depositor: msg.sender,
            amount: msg.value,
            leafIndex: leafIndex,
            blockNumber: block.number
        });
        noteCommitments.push(noteCommitment);
        depositCount = leafIndex + 1;
        tokenBalances[address(0)] += msg.value;

        noteTreeRoot = _computeRoot();
        _recordRoot(noteTreeRoot);

        emit Deposit(address(0), msg.value, noteCommitment, leafIndex);
    }

    // ─── Withdrawals ────────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function withdraw(
        address token,
        uint256 amount,
        address recipient,
        bytes calldata sp1Proof
    ) external nonReentrant {
        if (amount == 0) revert ZeroAmount();

        // Decode + verify the SP1 proof (fail-closed on a codeless verifier).
        bytes memory publicValues = _verifySp1(sp1Proof);

        // Decode public values committed by the SP1 guest program.
        // Expected format: (bool valid, bytes32 nullifier, address token, uint256 amount, address recipient, bytes32 noteTreeRoot)
        (
            bool valid,
            bytes32 nullifier,
            address proofToken,
            uint256 proofAmount,
            address proofRecipient,
            bytes32 proofRoot
        ) = abi.decode(publicValues, (bool, bytes32, address, uint256, address, bytes32));

        // Verify the proof's public outputs match the withdrawal parameters.
        if (!valid) revert ProofVerificationFailed();
        if (proofAmount != amount) revert AmountMismatch();
        if (proofRecipient != recipient) revert RecipientMismatch();
        if (proofToken != token) revert TokenMismatch();

        // The proof must commit to the current note tree root or one of the
        // recent roots in the ring buffer (Tornado-style grace window).
        if (!isKnownRoot(proofRoot)) revert UnknownRoot(proofRoot);

        // Solvency: never release more of a token than was deposited.
        uint256 available = tokenBalances[token];
        if (amount > available) revert InsufficientVaultBalance(token, amount, available);

        // Check and mark the nullifier as used BEFORE any external transfer.
        if (usedNullifiers[nullifier]) revert NullifierAlreadyUsed(nullifier);
        usedNullifiers[nullifier] = true;
        tokenBalances[token] = available - amount;

        // Transfer funds to recipient.
        if (token == address(0)) {
            // Native ETH withdrawal.
            (bool ethSuccess, ) = recipient.call{value: amount}("");
            if (!ethSuccess) revert TransferFailed();
        } else {
            // ERC-20 withdrawal.
            (bool transferSuccess, bytes memory transferData) = token.call(
                abi.encodeWithSignature(
                    "transfer(address,uint256)",
                    recipient,
                    amount
                )
            );
            if (!transferSuccess || (transferData.length > 0 && !abi.decode(transferData, (bool)))) {
                revert TransferFailed();
            }
        }

        emit Withdrawal(token, amount, recipient, nullifier);
    }

    // ─── View Functions ─────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }

    /// @notice True if `root` is the current note tree root or one of the last
    ///         ROOT_HISTORY_SIZE roots. The zero root is never accepted.
    function isKnownRoot(bytes32 root) public view returns (bool) {
        if (root == bytes32(0)) return false;
        if (root == noteTreeRoot) return true;
        uint256 filled = rootHistoryCount < ROOT_HISTORY_SIZE ? rootHistoryCount : ROOT_HISTORY_SIZE;
        for (uint256 i = 0; i < filled; i++) {
            if (rootHistory[i] == root) return true;
        }
        return false;
    }

    // ─── Internal ───────────────────────────────────────────────────────────

    /// Decode an SP1 proof envelope and verify it via the SP1 Verifier Gateway.
    /// Fail-closed: a staticcall to a codeless address succeeds vacuously, so a
    /// verifier with no code (even one that lost its code after deploy) must
    /// never be able to accept. Returns the proof's public values on success.
    function _verifySp1(bytes calldata sp1Proof) internal view returns (bytes memory publicValues) {
        if (sp1Verifier.code.length == 0) revert VerifierNotContract();

        // SP1 proofs are encoded as: abi.encode(proofBytes, publicValues)
        bytes memory proofBytes;
        (proofBytes, publicValues) = abi.decode(sp1Proof, (bytes, bytes));

        // The gateway reverts if the proof is invalid.
        (bool verifySuccess, ) = sp1Verifier.staticcall(
            abi.encodeWithSignature(
                "verifyProof(bytes32,bytes,bytes)",
                programVkey,
                publicValues,
                proofBytes
            )
        );
        if (!verifySuccess) revert ProofVerificationFailed();
    }

    /// Record a new root in the ring buffer of recent roots.
    function _recordRoot(bytes32 newRoot) internal {
        rootHistory[rootHistoryCount % ROOT_HISTORY_SIZE] = newRoot;
        rootHistoryCount += 1;
    }

    /// Compute the Merkle root of all note commitments.
    /// Simplified implementation: iterative hashing. In production, use an
    /// incremental Merkle tree with fixed depth (e.g., 20 levels = 1M leaves).
    function _computeRoot() internal view returns (bytes32) {
        uint256 count = noteCommitments.length;
        if (count == 0) return bytes32(0);
        if (count == 1) return noteCommitments[0];

        // Build a simple binary hash tree.
        bytes32[] memory layer = new bytes32[](count);
        for (uint256 i = 0; i < count; i++) {
            layer[i] = noteCommitments[i];
        }

        while (layer.length > 1) {
            uint256 newLen = (layer.length + 1) / 2;
            bytes32[] memory newLayer = new bytes32[](newLen);
            for (uint256 i = 0; i < newLen; i++) {
                if (2 * i + 1 < layer.length) {
                    newLayer[i] = keccak256(abi.encodePacked(layer[2 * i], layer[2 * i + 1]));
                } else {
                    newLayer[i] = layer[2 * i]; // Odd leaf promoted.
                }
            }
            layer = newLayer;
        }

        return layer[0];
    }
}
