// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./IDreggVault.sol";

/// @title DreggVault
/// @notice Holds bridged assets (ERC-20 and ETH) with private note-based accounting.
///
/// Deposits create note commitments that the dregg federation observes and mirrors
/// into its private note tree. Withdrawals require an SP1-wrapped STARK proof that
/// verifies note ownership and spending validity.
///
/// SP1 verification is delegated to the SP1 Verifier Gateway (deterministic CREATE2
/// deployment across all EVM chains). The vault only needs to check that the proof
/// was generated by the correct program (matching programVkey) and that the public
/// outputs encode the expected withdrawal parameters.
contract DreggVault is IDreggVault {
    // ─── Immutables ─────────────────────────────────────────────────────────

    /// Address of the SP1 Verifier Gateway contract (same on all EVM chains).
    address public immutable sp1Verifier;

    /// Verification key identifying the dregg STARK verifier guest program.
    /// The SP1 verifier checks that the proof was generated by this exact program.
    bytes32 public immutable programVkey;

    // ─── State ──────────────────────────────────────────────────────────────

    /// Incremental Merkle tree of note commitments (simplified: stores leaves only).
    /// In production, this would be an incremental Merkle tree (like Tornado Cash's).
    /// For now, we track the leaves and recompute roots on demand.
    bytes32[] private noteCommitments;

    /// Current root of the note commitment tree.
    bytes32 public noteTreeRoot;

    /// Total number of deposits (== noteCommitments.length).
    uint256 public depositCount;

    /// Spent nullifiers (prevents double-withdrawal).
    mapping(bytes32 => bool) public usedNullifiers;

    /// Deposits indexed by note commitment (for frontend querying).
    mapping(bytes32 => DepositRecord) public deposits;

    // ─── Types ──────────────────────────────────────────────────────────────

    struct DepositRecord {
        address token;
        address depositor;
        uint256 amount;
        uint256 leafIndex;
        uint256 blockNumber;
    }

    // ─── Errors ─────────────────────────────────────────────────────────────

    error ZeroAmount();
    error DuplicateNoteCommitment();
    error NullifierAlreadyUsed(bytes32 nullifier);
    error ProofVerificationFailed();
    error TransferFailed();
    error InvalidProofOutputs();
    error AmountMismatch();
    error RecipientMismatch();
    error TokenMismatch();

    // ─── Constructor ────────────────────────────────────────────────────────

    /// @param _sp1Verifier Address of the SP1 Verifier Gateway.
    /// @param _programVkey Verification key for the dregg guest program.
    constructor(address _sp1Verifier, bytes32 _programVkey) {
        sp1Verifier = _sp1Verifier;
        programVkey = _programVkey;
    }

    // ─── Deposits ───────────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function deposit(
        address token,
        uint256 amount,
        bytes32 noteCommitment
    ) external {
        if (amount == 0) revert ZeroAmount();
        if (deposits[noteCommitment].blockNumber != 0) revert DuplicateNoteCommitment();

        // Transfer ERC-20 tokens from sender to this contract.
        // Using a low-level call to support non-standard ERC-20s (USDT, etc.).
        (bool success, bytes memory data) = token.call(
            abi.encodeWithSignature(
                "transferFrom(address,address,uint256)",
                msg.sender,
                address(this),
                amount
            )
        );
        if (!success || (data.length > 0 && !abi.decode(data, (bool)))) {
            revert TransferFailed();
        }

        // Record the deposit and update the note tree.
        uint256 leafIndex = depositCount;
        deposits[noteCommitment] = DepositRecord({
            token: token,
            depositor: msg.sender,
            amount: amount,
            leafIndex: leafIndex,
            blockNumber: block.number
        });
        noteCommitments.push(noteCommitment);
        depositCount = leafIndex + 1;

        // Update the tree root (simplified: hash of all commitments).
        // In production, use an incremental Merkle tree for O(log n) updates.
        noteTreeRoot = _computeRoot();

        emit Deposit(token, amount, noteCommitment, leafIndex);
    }

    /// @inheritdoc IDreggVault
    function depositETH(bytes32 noteCommitment) external payable {
        if (msg.value == 0) revert ZeroAmount();
        if (deposits[noteCommitment].blockNumber != 0) revert DuplicateNoteCommitment();

        // Record the ETH deposit (token = address(0) for native ETH).
        uint256 leafIndex = depositCount;
        deposits[noteCommitment] = DepositRecord({
            token: address(0),
            depositor: msg.sender,
            amount: msg.value,
            leafIndex: leafIndex,
            blockNumber: block.number
        });
        noteCommitments.push(noteCommitment);
        depositCount = leafIndex + 1;

        noteTreeRoot = _computeRoot();

        emit Deposit(address(0), msg.value, noteCommitment, leafIndex);
    }

    // ─── Withdrawals ────────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function withdraw(
        address token,
        uint256 amount,
        address recipient,
        bytes calldata sp1Proof
    ) external {
        if (amount == 0) revert ZeroAmount();

        // Decode the SP1 proof into its components.
        // SP1 proofs are encoded as: abi.encode(proofBytes, publicValues)
        (bytes memory proofBytes, bytes memory publicValues) = abi.decode(
            sp1Proof,
            (bytes, bytes)
        );

        // Verify the proof via the SP1 Verifier Gateway.
        // The gateway reverts if the proof is invalid.
        (bool verifySuccess, ) = sp1Verifier.staticcall(
            abi.encodeWithSignature(
                "verifyProof(bytes32,bytes,bytes)",
                programVkey,
                publicValues,
                proofBytes
            )
        );
        if (!verifySuccess) revert ProofVerificationFailed();

        // Decode public values committed by the SP1 guest program.
        // Expected format: (bool valid, bytes32 nullifier, address token, uint256 amount, address recipient, bytes32 noteTreeRoot)
        (
            bool valid,
            bytes32 nullifier,
            address proofToken,
            uint256 proofAmount,
            address proofRecipient,
            /* bytes32 proofRoot -- we trust the proof verified against our program */
        ) = abi.decode(publicValues, (bool, bytes32, address, uint256, address, bytes32));

        // Verify the proof's public outputs match the withdrawal parameters.
        if (!valid) revert ProofVerificationFailed();
        if (proofAmount != amount) revert AmountMismatch();
        if (proofRecipient != recipient) revert RecipientMismatch();
        if (proofToken != token) revert TokenMismatch();

        // Check and mark the nullifier as used.
        if (usedNullifiers[nullifier]) revert NullifierAlreadyUsed(nullifier);
        usedNullifiers[nullifier] = true;

        // Transfer funds to recipient.
        if (token == address(0)) {
            // Native ETH withdrawal.
            (bool ethSuccess, ) = recipient.call{value: amount}("");
            if (!ethSuccess) revert TransferFailed();
        } else {
            // ERC-20 withdrawal.
            (bool transferSuccess, bytes memory transferData) = token.call(
                abi.encodeWithSignature(
                    "transfer(address,uint256)",
                    recipient,
                    amount
                )
            );
            if (!transferSuccess || (transferData.length > 0 && !abi.decode(transferData, (bool)))) {
                revert TransferFailed();
            }
        }

        emit Withdrawal(token, amount, recipient, nullifier);
    }

    // ─── View Functions ─────────────────────────────────────────────────────

    /// @inheritdoc IDreggVault
    function isNullifierUsed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }

    // ─── Internal ───────────────────────────────────────────────────────────

    /// Compute the Merkle root of all note commitments.
    /// Simplified implementation: iterative hashing. In production, use an
    /// incremental Merkle tree with fixed depth (e.g., 20 levels = 1M leaves).
    function _computeRoot() internal view returns (bytes32) {
        uint256 count = noteCommitments.length;
        if (count == 0) return bytes32(0);
        if (count == 1) return noteCommitments[0];

        // Build a simple binary hash tree.
        bytes32[] memory layer = new bytes32[](count);
        for (uint256 i = 0; i < count; i++) {
            layer[i] = noteCommitments[i];
        }

        while (layer.length > 1) {
            uint256 newLen = (layer.length + 1) / 2;
            bytes32[] memory newLayer = new bytes32[](newLen);
            for (uint256 i = 0; i < newLen; i++) {
                if (2 * i + 1 < layer.length) {
                    newLayer[i] = keccak256(abi.encodePacked(layer[2 * i], layer[2 * i + 1]));
                } else {
                    newLayer[i] = layer[2 * i]; // Odd leaf promoted.
                }
            }
            layer = newLayer;
        }

        return layer[0];
    }
}
