// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// Groth16(BN254) verifier over exactly 25 public inputs — the dregg
/// whole-chain settlement statement (post-v11 proof shape).
///
/// The concrete implementation is generated by gnark-solidity-verifier from
/// the STARK->SNARK wrap circuit (see `docs/deos/ETH-NATIVE-WRAP.md`); this
/// interface pins the call shape the settlement contract consumes.
///
/// Public-input lane order (pinned, must match the gnark circuit exactly):
///   [0..8)   genesis_root  — 8 BabyBear lanes (SEG_ANCHOR_WIDTH = 8)
///   [8..16)  final_root    — 8 BabyBear lanes
///   [16]     num_turns     — 1 lane
///   [17..25) chain_digest  — 8 BabyBear lanes (SEG_DIGEST_WIDTH = 8)
///
/// Every lane is a canonical BabyBear residue: strictly less than
/// p = 2^31 - 2^27 + 1 = 2013265921 (0x78000001). Callers MUST enforce the
/// bound before calling; a non-canonical lane makes the statement ill-formed.
interface IGroth16Verifier25 {
    /// Run the BN254 pairing check for proof (a, b, c) against the 25-lane
    /// public-input vector. Word order for `b` matches EIP-197 (the imaginary
    /// coordinate first). Returns true iff the proof verifies.
    ///
    /// `commitments`/`commitmentPok`: the wrap circuit (chain/gnark
    /// SettlementCircuit) uses gnark's commit-based range checker, so every
    /// proof carries ONE Pedersen commitment (2 words) plus its proof of
    /// knowledge (2 words) — gnark `MarshalSolidity` words [8..10) and
    /// [10..12) after the 8 proof words. They are part of the proof, not the
    /// statement.
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[2] calldata commitments,
        uint256[2] calldata commitmentPok,
        uint256[25] calldata publicInputs
    ) external view returns (bool);
}
