/-
# Dregg2.Circuit.Emit.EffectVmEmitNoopWide — a genuine RUNNABLE no-op descriptor LIFTED to FULL-STATE
(the magnesium breadth, on the circuit the prover RUNS).

## What this module adds (vs `Argus/Effects/Noop` welding against `skipDescriptor`)

`Argus/Effects/Noop` welds the no-op IR term against `skipDescriptor` — the EMPTY AIR (zero constraints,
zero hash sites), which pins NOTHING (it is satisfied by EVERY witness, and is sound for the no-op ONLY
because the executor freezes). That weld carries the empty circuit as an honest, NAMED divergence. It is
the strongest statement available when the no-op's circuit is the empty descriptor — but the published
`state_commit` then binds NO field at all.

This module supplies the FULL-STATE-on-RUNNABLE alternative: the FAITHFUL runnable no-op row the running
prover actually lays — a PAD row whose every state-block column is FROZEN (`state_after[i] =
state_before[i]`, the global nonce gate freezing the nonce too on a `s_noop = 1` row) — WIDENED to bind
the `system_roots` sub-block. `noopVmDescriptorWide` (`EFFECT_VM_WIDTH_SYSROOTS = 188`, `hashSites =
wideHashSites`) and the crown `noop_runnable_full_sound` prove: a satisfying witness of the RUNNABLE
no-op descriptor pins the FULL 17-field declarative post-state — the per-cell block FROZEN (via the
absorbed columns, BOUND into the published commitment) AND ALL 8 side-table roots FROZEN. The frame
freeze IS the full-state proof for a no-op: the post-state EQUALS the pre-state on every field, and now
the published commitment WITNESSES that (every absorbed column + the side-table digest), rather than the
empty descriptor's vacuous satisfaction.

## The honest distinction this module makes precise

`skipDescriptor` (the Argus weld's circuit) pins nothing — its soundness is the trivial freeze-agreement,
carried by the executor. `noopVmDescriptorWide` (this module's circuit) GENUINELY ENFORCES the freeze: a
row violating any column-freeze fails a `gFreeze` gate, and a row tampering the bound state while claiming
the published `NEW_COMMIT` is UNSAT (the §4 anti-ghost). So a no-op trace generated by the running prover
— a real PAD row with all columns frozen — satisfies a circuit that BINDS the whole frozen post-state,
not the empty AIR. We reuse `EffectVmEmitEmitEvent.gFreeze` (the SAME `state_after[off] - state_before[off]`
passthrough body) for the 14 whole-block freeze gates: the no-op row and the emit row have the identical
KERNEL shape (both freeze the whole block), differing only in their selector (`sel.NOOP` vs `EMIT_EVENT`).

## The recipe applied (`EffectVmFullStateRunnable §6`, the transfer reference template)

  * **the wide descriptor** — 14 whole-block freeze gates `state_after[off] = state_before[off]` ++
    transition continuity ++ the 7 boundary PI pins, `traceWidth := EFFECT_VM_WIDTH_SYSROOTS`, `hashSites
    := wideHashSites` (so `usesWideSites := rfl`). NO root-update gate — the no-op moves NO side table,
    so the carrier is FROZEN at `before`. (No selector gate: the no-op PAD row IS the `sel.NOOP = 1`
    padding, not an effect selector — the selector-binding tooth is for effect descriptors.)
  * **`isRow`** := `IsNoopRow` (`sel.NOOP = 1`); **`decodeAfter`** := `RowEncodes` + frozen-roots witness;
    **`fullClause`** := `CellFreezeSpec` (the whole block FROZEN) AND `postRoots = preRoots`;
    **`decodeFull`** := THIN, projecting the wide gates to the hash-site-free `noopGates_give_cellSpec`.

The anti-ghost on ALL 17 fields falls out of the generic `runnable_full_commit_binds` /
`wide_rejects_root_tamper` (§4).

## The terminal (named, the ONLY acceptable irreducible)

`Poseidon2Binding.Poseidon2SpongeCR hash` — discharged ONCE in the generic crown; this module carries NO
new portal. `#assert_axioms` ⊆ {propext, Classical.choice, Quot.sound} on every theorem. No `sorry`,
no `:= True`, no `native_decide`. Imports are read-only; this file owns only itself.
-/
import Dregg2.Circuit.Emit.EffectVmEmitEmitEvent
import Dregg2.Circuit.Emit.EffectVmFullStateRunnable

namespace Dregg2.Circuit.Emit.EffectVmEmitNoopWide

open Dregg2.Circuit
open Dregg2.Circuit.Emit.EffectVmEmit
open Dregg2.Circuit.Emit.EffectVmEmitTransfer
  (transitionAll boundaryFirstPins boundaryLastPins)
open Dregg2.Circuit.Emit.EffectVmEmitTransferSound (CellState)
open Dregg2.Circuit.Emit.EffectVmEmitEmitEvent
  (gFreeze emitRowGates EmitRowIntent emitEventVm_faithful emitRowGates_flag_indep
   RowEncodes CellFreezeSpec intent_to_cellSpec)
open Dregg2.Circuit.Emit.EffectVmFullStateRunnable
  (baseAbsorbedCols wideHashSites RunnableFullStateSpec runnable_full_sound)
open Dregg2.Circuit.Poseidon2Binding (Poseidon2SpongeCR)
open Dregg2.Exec.SystemRoots (SysRoots systemRootsDigest emptySystemRoots N_SYSTEM_ROOTS)

set_option linter.unusedVariables false

/-! ## §0 — the no-op PAD row + the whole-block-freeze gate set.

The running prover models the no-op as the PAD row (`sel.NOOP = 1`); the global nonce gate
`new_nonce = old_nonce + (1 - s_noop)` FREEZES the nonce on it, and the state-block passthrough freezes the
rest. We reuse `EffectVmEmitEmitEvent.emitRowGates` (the 14 whole-block `gFreeze off` gates, offsets
0..13 — the SAME passthrough bodies), since the no-op row and the emit row freeze the IDENTICAL kernel
block; only the selector differs. -/

/-- The no-op PAD row: `s_noop = 1`. -/
def IsNoopRow (env : VmRowEnv) : Prop := env.loc sel.NOOP = 1

/-! ## §1 — the WIDE descriptor (the `system_roots`-absorbing runnable no-op circuit). -/

/-- **`noopVmDescriptorWide`** — the FAITHFUL runnable no-op row, WIDENED: 14 whole-block freeze gates ++
transition continuity ++ the 7 boundary PI pins, `traceWidth := EFFECT_VM_WIDTH_SYSROOTS`, `hashSites :=
wideHashSites` (so the published `state_commit` absorbs the — frozen — side-table digest). No range checks
(the no-op moves no balance), no selector gate (the no-op IS the `sel.NOOP` pad). -/
def noopVmDescriptorWide : EffectVmDescriptor :=
  { name := "dregg-effectvm-noop-sysroots"
  , traceWidth := EFFECT_VM_WIDTH_SYSROOTS
  , piCount := 42
  , constraints := emitRowGates ++ transitionAll ++ boundaryFirstPins ++ boundaryLastPins
  , hashSites := wideHashSites
  , ranges := [] }

/-! ## §2 — the GATE-ONLY per-cell soundness (no hash-site hypothesis).

The whole-block freeze factors through `emitEventVm_faithful` (`emitRowGates ⟺ EmitRowIntent`) +
`intent_to_cellSpec`, NEITHER of which reads the hash sites or the selector. So the runnable per-cell
soundness depends ONLY on the freeze gates. The analog of
`EffectVmFullStateRunnable.transferGates_give_cellSpec`. -/

/-- **`noopGates_give_cellSpec` — the GATE-ONLY per-cell soundness.** The no-op descriptor's per-row freeze
gates (a constraint-list segment), on a row decoded by `RowEncodes`, force `CellFreezeSpec` (the whole
block FROZEN). No hash-site hypothesis. -/
theorem noopGates_give_cellSpec (env : VmRowEnv) (pre post : CellState)
    (henc : RowEncodes env pre post)
    (hgates : ∀ c ∈ noopVmDescriptorWide.constraints, c.holdsVm env true false) :
    CellFreezeSpec pre post := by
  have hrowgates : ∀ c ∈ emitRowGates, c.holdsVm env true false := by
    intro c hc
    apply hgates
    unfold noopVmDescriptorWide
    simp only [List.mem_append]
    exact Or.inl (Or.inl (Or.inl hc))
  have hrowgates' := emitRowGates_flag_indep env true hrowgates
  exact intent_to_cellSpec env pre post henc ((emitEventVm_faithful env).mp hrowgates')

#assert_axioms noopGates_give_cellSpec

/-! ## §3 — the FULL clause + the VALIDATED RUNNABLE instance.

The no-op freezes EVERYTHING — every kernel field AND every side-table root: the full clause is the
per-cell `CellFreezeSpec` (the whole block frozen) AND `postRoots = preRoots`. -/

/-- **`NoopFullClause`** — the full declarative post-state for the no-op over `(pre, post, postRoots)`: the
per-cell `CellFreezeSpec` (the whole block FROZEN) AND the 8 side-table roots FROZEN. Non-vacuous
(`goodNoop_realizes` / `noop_clause_not_trivial`). -/
def NoopFullClause (preRoots : SysRoots)
    (pre post : CellState) (postRoots : SysRoots) : Prop :=
  CellFreezeSpec pre post ∧ postRoots = preRoots

/-- **`noopRunnableSpec` — the FULL-state RUNNABLE instance.** `decodeFull` projects the wide gates to the
GATE-ONLY `noopGates_give_cellSpec`, then carries the frozen-roots fact. THIN, NON-VACUOUS. -/
def noopRunnableSpec (preRoots : SysRoots) : RunnableFullStateSpec CellState where
  descriptor    := noopVmDescriptorWide
  usesWideSites := rfl
  isRow         := IsNoopRow
  decodeAfter   := fun env pre post postRoots =>
    RowEncodes env pre post ∧ postRoots = preRoots
  fullClause    := NoopFullClause preRoots
  decodeFull    := by
    intro env pre post postRoots hrow hdec hgates
    obtain ⟨henc, hroots⟩ := hdec
    exact ⟨noopGates_give_cellSpec env pre post henc hgates, hroots⟩

/-- **`noop_runnable_full_sound` — THE CROWN (no-op slice).** A row satisfying the RUNNABLE wide no-op
descriptor (`satisfiedVm noopVmDescriptorWide`, first/last active), under the structured decode
(`RowEncodes` + frozen roots), pins the FULL 17-field declarative post-state: the per-cell `CellFreezeSpec`
(the whole block FROZEN) AND all 8 side-table roots FROZEN. This is the FULL-STATE freeze for the no-op on
the circuit the prover ACTUALLY RUNS — STRICTLY STRONGER than the `skipDescriptor` weld (whose empty AIR
binds no field), because the published commitment now witnesses the whole frozen post-state. -/
theorem noop_runnable_full_sound (hash : List ℤ → ℤ)
    (env : VmRowEnv) (pre post : CellState) (sr preRoots : SysRoots)
    (hrow : IsNoopRow env)
    (henc : RowEncodes env pre post) (hroots : sr = preRoots)
    (hgatesat : satisfiedVm hash noopVmDescriptorWide env true false) :
    CellFreezeSpec pre post ∧ sr = preRoots :=
  runnable_full_sound (noopRunnableSpec preRoots) hash env pre post sr
    hrow ⟨henc, hroots⟩ hgatesat

#assert_axioms noop_runnable_full_sound

/-! ## §4 — ANTI-GHOST on ALL 17 fields (the generic teeth, instantiated). -/

/-- **`noop_wide_binds_full_state` — the whole-state anti-ghost.** Two rows satisfying the wide no-op
descriptor that publish the SAME `NEW_COMMIT`, whose carriers ARE the `systemRootsDigest` of their post
sub-blocks, agree on EVERY absorbed state-block column AND every side-table root. So even the EMPTY-effect
no-op binds the whole post-state (the contrast with `skipDescriptor`, which binds nothing). -/
theorem noop_wide_binds_full_state (hash : List ℤ → ℤ) (hCR : Poseidon2SpongeCR hash)
    (e₁ e₂ : VmRowEnv) (sr₁ sr₂ : SysRoots) (preRoots : SysRoots)
    (hsat₁ : satisfiedVm hash noopVmDescriptorWide e₁ true true)
    (hsat₂ : satisfiedVm hash noopVmDescriptorWide e₂ true true)
    (hpin₁ : e₁.loc (saCol state.STATE_COMMIT) = e₁.pub pi.NEW_COMMIT)
    (hpin₂ : e₂.loc (saCol state.STATE_COMMIT) = e₂.pub pi.NEW_COMMIT)
    (hpub : e₁.pub pi.NEW_COMMIT = e₂.pub pi.NEW_COMMIT)
    (hd₁ : e₁.loc sysRootsDigestCol = systemRootsDigest hash sr₁)
    (hd₂ : e₂.loc sysRootsDigestCol = systemRootsDigest hash sr₂) :
    baseAbsorbedCols e₁ = baseAbsorbedCols e₂ ∧ (∀ i : Fin N_SYSTEM_ROOTS, sr₁ i = sr₂ i) :=
  EffectVmFullStateRunnable.runnable_full_commit_binds (noopRunnableSpec preRoots)
    hash hCR e₁ e₂ sr₁ sr₂ hsat₁ hsat₂ hpin₁ hpin₂ hpub hd₁ hd₂

/-- **`noop_wide_rejects_root_tamper` — side-table anti-ghost.** Two wide no-op rows publishing the same
`NEW_COMMIT` (with `systemRootsDigest` carriers) whose side-table sub-blocks DIFFER cannot both satisfy —
the no-op's published commitment BINDS the side-table state (the empty AIR could not). -/
theorem noop_wide_rejects_root_tamper (hash : List ℤ → ℤ) (hCR : Poseidon2SpongeCR hash)
    (e₁ e₂ : VmRowEnv) (sr₁ sr₂ : SysRoots) (preRoots : SysRoots)
    (hsat₁ : satisfiedVm hash noopVmDescriptorWide e₁ true true)
    (hsat₂ : satisfiedVm hash noopVmDescriptorWide e₂ true true)
    (hpin₁ : e₁.loc (saCol state.STATE_COMMIT) = e₁.pub pi.NEW_COMMIT)
    (hpin₂ : e₂.loc (saCol state.STATE_COMMIT) = e₂.pub pi.NEW_COMMIT)
    (hpub : e₁.pub pi.NEW_COMMIT = e₂.pub pi.NEW_COMMIT)
    (hd₁ : e₁.loc sysRootsDigestCol = systemRootsDigest hash sr₁)
    (hd₂ : e₂.loc sysRootsDigestCol = systemRootsDigest hash sr₂)
    {i : Fin N_SYSTEM_ROOTS} (htamper : sr₁ i ≠ sr₂ i) : False :=
  EffectVmFullStateRunnable.wide_rejects_root_tamper (noopRunnableSpec preRoots)
    hash hCR e₁ e₂ sr₁ sr₂ hsat₁ hsat₂ hpin₁ hpin₂ hpub hd₁ hd₂ htamper

#assert_axioms noop_wide_binds_full_state
#assert_axioms noop_wide_rejects_root_tamper

/-! ## §5 — NON-VACUITY: the full clause is INHABITED (TRUE) and REFUTABLE (FALSE), the wide descriptor is
the genuine 188-wide `system_roots`-absorbing circuit, and it is NON-EMPTY (unlike `skipDescriptor`). -/

/-- A frozen reference sub-block (the empty `system_roots`, since the no-op touches no side table). -/
def goodPreRoots : SysRoots := emptySystemRoots

/-- A content-rich pre-state for the witnesses: bal_lo 100, nonce 5, field[2] = 7. -/
def noopPre : CellState :=
  { balLo := 100, balHi := 0, nonce := 5, fields := fun i => if i = 2 then 7 else 0, capRoot := 0
  , reserved := 0, commit := 0 }

/-- The post-state the no-op produces: the WHOLE block frozen (= `noopPre`). -/
def noopPost : CellState := noopPre

/-- **`goodNoop_realizes` — NON-VACUITY (witness TRUE).** The no-op `fullClause` is INHABITED by the real
freeze: `noopPost` IS `noopPre` (every block component FROZEN) and the roots are frozen. So the full clause
is NOT `True`. -/
theorem goodNoop_realizes :
    (noopRunnableSpec goodPreRoots).fullClause noopPre noopPost goodPreRoots :=
  ⟨⟨rfl, rfl, rfl, fun _ => rfl, rfl, rfl⟩, rfl⟩

/-- **`noop_clause_not_trivial` — the clause is REFUTABLE (witness FALSE).** A post-state whose nonce is
NOT frozen (`noopPre.nonce = 5`, but a forged `6` — a no-op must NOT tick the nonce) FAILS the full clause
— non-vacuity from BOTH sides. (Contrast `pipelinedSend`/`exercise`, which DO tick; the no-op freezes
EVERYTHING including the nonce.) -/
theorem noop_clause_not_trivial :
    ¬ NoopFullClause goodPreRoots noopPre { noopPost with nonce := 6 } goodPreRoots := by
  rintro ⟨⟨_, _, hnon, _⟩, _⟩
  -- hnon : (6) = noopPost.nonce = noopPre.nonce = 5
  simp only [noopPre] at hnon
  norm_num at hnon

/-- **NON-VACUITY (the wide descriptor is the genuine 188-wide circuit, and NON-EMPTY).**
`noopVmDescriptorWide` declares `traceWidth = 188`, its `hashSites` are the four `system_roots`-absorbing
`wideHashSites`, AND it carries 35 constraints + 4 hash sites — GENUINELY NON-EMPTY, the precise contrast
with `skipDescriptor` (0 constraints / 0 hash sites). So `noop_runnable_full_sound` binds a real circuit's
whole post-state, where the `skipDescriptor` weld bound nothing. -/
theorem noopWide_is_genuine_nonempty :
    noopVmDescriptorWide.traceWidth = EFFECT_VM_WIDTH_SYSROOTS
    ∧ noopVmDescriptorWide.hashSites = wideHashSites
    ∧ noopVmDescriptorWide.constraints.length = 14 + 14 + 4 + 3
    ∧ noopVmDescriptorWide.hashSites.length = 4 := by
  refine ⟨rfl, rfl, ?_, ?_⟩
  · decide
  · show wideHashSites.length = 4; decide

#assert_axioms goodNoop_realizes
#assert_axioms noop_clause_not_trivial
#assert_axioms noopWide_is_genuine_nonempty

/-! ## §6 — axiom-hygiene tripwires. -/

#guard noopVmDescriptorWide.traceWidth == 190
#guard noopVmDescriptorWide.hashSites.length == 4
#guard noopVmDescriptorWide.constraints.length == 14 + 14 + 4 + 3
#guard noopVmDescriptorWide.ranges.length == 0

end Dregg2.Circuit.Emit.EffectVmEmitNoopWide
