//! Canonical JS-constants generation for starbridge-apps — the anti-drift
//! bridge between a Rust `src/lib.rs` (the single source of truth) and its
//! `pages/*.js` web surface.
//!
//! # The drift problem
//!
//! Every starbridge-app pins a fixed slot layout (`pub const FOO_SLOT: u8 =
//! 0;`) and a set of event-topic names in `src/lib.rs`. Its web pages
//! (`pages/turn-builders.js`, `pages/inspectors.js`) historically *hand-copied*
//! those numbers and strings into local `const FOO_SLOT = 0;` declarations.
//! Nothing stopped the two from drifting: bump a slot in Rust, forget the JS,
//! and the page silently reads/writes the wrong field — a class of bug that
//! type-checking can never catch because the boundary is a string/number copy
//! across languages.
//!
//! # The fix
//!
//! An app declares its constants ONCE as a [`ConstantsModule`] (built from its
//! own `pub const`s, so the Rust values are authoritative), then:
//!
//! 1. a tiny generator (an `examples/` bin or a test) renders the module to JS
//!    with [`ConstantsModule::render_js`] and writes
//!    `pages/constants.generated.js`;
//! 2. its web pages `import { FOO_SLOT, TOPICS } from
//!    './constants.generated.js'` instead of re-declaring the values;
//! 3. a drift test calls [`ConstantsModule::assert_matches_file`] (or compares
//!    `render_js()` against the committed file) so CI fails the moment the JS
//!    is regenerated-stale.
//!
//! The generated file is deterministic: the same `ConstantsModule` always
//! renders byte-identical output, so the drift check is a plain string compare.

use std::fmt::Write as _;

/// A named numeric slot constant (`pub const FOO_SLOT: u8 = 3` ⇒
/// `Slot { js_name: "FOO_SLOT", value: 3 }`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Slot {
    /// The JS identifier to emit (conventionally the same SCREAMING_SNAKE name
    /// as the Rust `const`).
    pub js_name: &'static str,
    /// The slot index. Sourced from the Rust `const` so it cannot drift.
    pub value: u64,
}

/// A canonical constants module for one starbridge-app: the slot layout, the
/// event-topic vocabulary, and any extra scalar/string values the pages need
/// (e.g. a factory-vk hex).
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ConstantsModule {
    /// The app name, used only in the generated banner comment.
    pub app: &'static str,
    /// Slot-index constants, emitted as `export const FOO_SLOT = N;`.
    pub slots: Vec<Slot>,
    /// Event-topic names, emitted as a frozen `TOPICS` object keyed by an
    /// UPPERCASE alias so JS reads `TOPICS.REGISTERED` rather than a magic
    /// string. Each entry is `(js_key, topic_string)`.
    pub topics: Vec<(&'static str, String)>,
    /// Extra string constants (e.g. `("FACTORY_VK_HEX", "ab…")`), emitted as
    /// `export const FACTORY_VK_HEX = "…";`.
    pub strings: Vec<(&'static str, String)>,
}

impl ConstantsModule {
    /// Start an empty module for `app`.
    pub fn new(app: &'static str) -> Self {
        Self {
            app,
            ..Default::default()
        }
    }

    /// Add a slot constant. `value` should come from the Rust `const` directly
    /// (e.g. `.slot("NAME_HASH_SLOT", NAME_HASH_SLOT as u64)`).
    pub fn slot(mut self, js_name: &'static str, value: u64) -> Self {
        self.slots.push(Slot { js_name, value });
        self
    }

    /// Add an event-topic. `js_key` is the UPPERCASE alias used in JS
    /// (`TOPICS.REGISTERED`); `topic` is the exact `symbol()` string the Rust
    /// side emits.
    pub fn topic(mut self, js_key: &'static str, topic: impl Into<String>) -> Self {
        self.topics.push((js_key, topic.into()));
        self
    }

    /// Add an extra string constant (factory-vk hex, tombstone prefix, …).
    pub fn string(mut self, js_name: &'static str, value: impl Into<String>) -> Self {
        self.strings.push((js_name, value.into()));
        self
    }

    /// Render the canonical, deterministic JS module text.
    ///
    /// The output is stable: identical input always yields byte-identical
    /// output, so a drift test can compare it against the committed file with a
    /// plain `==`.
    pub fn render_js(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(
            s,
            "// AUTOGENERATED — do not edit by hand.\n\
             //\n\
             // Canonical constants for the `{app}` starbridge-app, generated from\n\
             // its Rust `src/lib.rs` (the single source of truth) so the web pages\n\
             // cannot drift from the executor's slot layout / event vocabulary.\n\
             //\n\
             // Regenerate with the app's constants generator; a drift test fails if\n\
             // this file is stale.",
            app = self.app
        );
        s.push('\n');

        if !self.slots.is_empty() {
            let _ = writeln!(
                s,
                "// Slot indices (mirror `pub const *_SLOT` in src/lib.rs)."
            );
            for slot in &self.slots {
                let _ = writeln!(s, "export const {} = {};", slot.js_name, slot.value);
            }
            s.push('\n');
        }

        if !self.strings.is_empty() {
            for (name, value) in &self.strings {
                let _ = writeln!(s, "export const {} = {};", name, js_string(value));
            }
            s.push('\n');
        }

        if !self.topics.is_empty() {
            let _ = writeln!(
                s,
                "// Event-topic names (mirror the `symbol(\"…\")` calls in src/lib.rs)."
            );
            let _ = writeln!(s, "export const TOPICS = Object.freeze({{");
            for (key, topic) in &self.topics {
                let _ = writeln!(s, "  {}: {},", key, js_string(topic));
            }
            let _ = writeln!(s, "}});");
        }

        s
    }

    /// Assert the committed file at `path` byte-equals [`render_js`]. Use this
    /// in a drift test: if it fails, the JS is stale — regenerate it.
    ///
    /// On mismatch the panic message names the path and shows the first
    /// differing line so the fix is obvious.
    ///
    /// [`render_js`]: Self::render_js
    pub fn assert_matches_file(&self, path: &std::path::Path) {
        let expected = self.render_js();
        let actual = std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("constants drift check: cannot read {path:?}: {e}"));
        if actual != expected {
            let first_diff = expected
                .lines()
                .zip(actual.lines())
                .enumerate()
                .find(|(_, (e, a))| e != a)
                .map(|(i, (e, a))| {
                    format!("\n  line {}:\n    expected: {e}\n    actual:   {a}", i + 1)
                })
                .unwrap_or_else(|| "\n  (length differs)".to_string());
            panic!(
                "constants drift: {path:?} is stale vs the Rust source of truth.\n\
                 Regenerate the app's constants.generated.js.{first_diff}"
            );
        }
    }
}

/// Render a Rust string as a double-quoted JS string literal (escaping `\` and
/// `"`). The topic/string values are ASCII identifiers in practice, but escape
/// defensively so the generator is total.
fn js_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_deterministic_and_well_formed() {
        let m = ConstantsModule::new("nameservice")
            .slot("NAME_HASH_SLOT", 2)
            .slot("OWNER_HASH_SLOT", 3)
            .string("FACTORY_VK_HEX", "abcd")
            .topic("REGISTERED", "name-registered")
            .topic("REVOKED", "name-revoked");

        let a = m.render_js();
        let b = m.render_js();
        assert_eq!(a, b, "render must be deterministic");

        assert!(a.contains("export const NAME_HASH_SLOT = 2;"));
        assert!(a.contains("export const OWNER_HASH_SLOT = 3;"));
        assert!(a.contains("export const FACTORY_VK_HEX = \"abcd\";"));
        assert!(a.contains("REGISTERED: \"name-registered\","));
        assert!(a.contains("REVOKED: \"name-revoked\","));
        assert!(a.contains("Object.freeze("));
    }

    #[test]
    fn js_string_escapes() {
        assert_eq!(js_string("a\"b\\c"), "\"a\\\"b\\\\c\"");
    }

    #[test]
    fn assert_matches_file_roundtrips(/* uses a temp file */) {
        let m = ConstantsModule::new("x").slot("FOO_SLOT", 7);
        let dir = std::env::temp_dir();
        let path = dir.join(format!("webgen-test-{}.generated.js", std::process::id()));
        std::fs::write(&path, m.render_js()).unwrap();
        m.assert_matches_file(&path);
        std::fs::remove_file(&path).ok();
    }
}
