use dregg_dsl::{dregg_caveat, dregg_effect};

pub mod accumulator_dsl;
pub mod advanced_circuits;
pub mod arithmetic_predicate_dsl;
pub mod block_transition_dsl;
pub mod compound_predicate_dsl;
pub mod derivation_dsl;
pub mod dispute_dsl;
pub mod dregg_definitions;
pub mod factory_dsl;
pub mod fold_dsl;
pub mod fri_verifier_dsl;
pub mod garbled_dsl;
pub mod gpu_worker;
pub mod merkle_dsl;
pub mod merkle_poseidon2_dsl;
pub mod multi_step_dsl;
pub mod native_signature_dsl;
pub mod non_revocation_dsl;
pub mod note_spending_dsl;
pub mod poseidon2_dsl;
pub mod predicate_dsl;
pub mod presentation_dsl;
pub mod relational_predicate_dsl;
pub mod schnorr_dsl;
pub mod sovereign_transition_dsl;
pub mod temporal_dsl;
pub mod temporal_macro;

// --- Phase 1 caveats (preserved) ---

#[dregg_caveat]
fn not_after(token_expiry: u64, current_time: u64) {
    require!(current_time <= token_expiry);
}

#[dregg_caveat]
fn minimum_balance(balance: u64, threshold: u64) {
    require!(balance >= threshold);
}

#[dregg_caveat]
fn exact_match(expected: u64, actual: u64) {
    require!(expected == actual);
}

#[dregg_caveat]
fn different_parties(sender: u64, receiver: u64) {
    require!(sender != receiver);
}

// --- Phase 2: Multi-constraint composition ---

#[dregg_caveat]
fn compound_check(balance: u64, threshold: u64, sender: u64, receiver: u64) {
    require!(balance >= threshold);
    require!(sender != receiver);
}

// --- Phase 2: Set membership ---

#[dregg_caveat]
fn service_scope(allowed_services: &std::collections::HashSet<u64>, requested: u64) {
    require!(allowed_services.contains(requested));
}

// --- Phase 2: Effects with mutation ---

// DSL surface: modeled transfer direction; variants are only constructed in #[cfg(test)] arms.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Direction {
    Outgoing,
    Incoming,
}

#[dregg_effect]
fn transfer(balance: &mut u64, amount: u64, direction: Direction) {
    match direction {
        Direction::Outgoing => {
            require!(*balance >= amount);
            *balance = *balance - amount;
        }
        Direction::Incoming => {
            *balance = *balance + amount;
        }
    }
}

// --- Phase 2: Effect with permission ---

#[dregg_effect(requires = "Send")]
fn guarded_transfer(balance: &mut u64, amount: u64) {
    require!(*balance >= amount);
    *balance = *balance - amount;
}

// --- Phase 2: Simple effect (no match) ---

#[dregg_effect]
fn decrement(counter: &mut u64, step: u64) {
    require!(*counter >= step);
    *counter = *counter - step;
}

#[cfg(test)]
mod tests {
    use super::*;
    use dregg_circuit::field::BabyBear;
    use dregg_circuit::stark::{self, StarkAir};

    // --- Phase 3: Compile-time StarkAir impl prove/verify ---

    #[test]
    fn test_not_after_stark_prove_verify() {
        // NotAfterCircuit generated by #[dregg_caveat] on not_after
        let circuit = NotAfterCircuit;

        // Verify baked-in constants.
        // 2 params + 3 range-check blocks of (1 diff + 30 bits) = 2 + 3*31 = 95.
        // The three blocks are: the diff (token_expiry - current_time) plus the
        // two OPERAND range-checks (current_time, token_expiry) that close the
        // field wrap-around (see emit_stark_impl::OPERAND_RANGE_BITS).
        assert_eq!(circuit.width(), 95);
        assert_eq!(circuit.constraint_degree(), 2);
        assert_eq!(circuit.air_name(), "dregg-not_after-v1");

        // Generate trace: token_expiry=100, current_time=50 (valid: 50 <= 100)
        let trace = circuit.generate_trace(100, 50);

        // Public inputs match the parameters
        let pi = vec![
            BabyBear::from_u64(100), // token_expiry
            BabyBear::from_u64(50),  // current_time
        ];

        // Prove through the real STARK pipeline
        let proof = stark::prove(&circuit, &trace, &pi);

        // Verify the proof
        let result = stark::verify(&circuit, &proof, &pi);
        assert!(
            result.is_ok(),
            "NotAfterCircuit prove/verify failed: {:?}",
            result.err()
        );
    }

    #[test]
    fn test_not_after_stark_boundary_equal() {
        // Boundary case: current_time == token_expiry (should still pass)
        let circuit = NotAfterCircuit;
        let trace = circuit.generate_trace(100, 100);
        let pi = vec![BabyBear::from_u64(100), BabyBear::from_u64(100)];
        let proof = stark::prove(&circuit, &trace, &pi);
        let result = stark::verify(&circuit, &proof, &pi);
        assert!(result.is_ok(), "boundary case failed: {:?}", result.err());
    }

    #[test]
    fn test_exact_match_stark_prove_verify() {
        // ExactMatchCircuit: require!(expected == actual)
        let circuit = ExactMatchCircuit;
        assert_eq!(circuit.width(), 2); // 2 params, no aux
        assert_eq!(circuit.constraint_degree(), 1);
        assert_eq!(circuit.air_name(), "dregg-exact_match-v1");

        let trace = circuit.generate_trace(42, 42);
        let pi = vec![BabyBear::from_u64(42), BabyBear::from_u64(42)];
        let proof = stark::prove(&circuit, &trace, &pi);
        let result = stark::verify(&circuit, &proof, &pi);
        assert!(
            result.is_ok(),
            "ExactMatchCircuit prove/verify failed: {:?}",
            result.err()
        );
    }

    #[test]
    fn test_minimum_balance_stark_prove_verify() {
        // MinimumBalanceCircuit: require!(balance >= threshold)
        let circuit = MinimumBalanceCircuit;
        // 2 params + 3 range-check blocks of (1 diff + 30 bits) = 2 + 3*31 = 95
        // (diff = balance - threshold, plus the two operand range-checks that
        // close the wrap-around).
        assert_eq!(circuit.width(), 95);
        assert_eq!(circuit.constraint_degree(), 2);

        let trace = circuit.generate_trace(100, 50);
        let pi = vec![BabyBear::from_u64(100), BabyBear::from_u64(50)];
        let proof = stark::prove(&circuit, &trace, &pi);
        let result = stark::verify(&circuit, &proof, &pi);
        assert!(
            result.is_ok(),
            "MinimumBalanceCircuit prove/verify failed: {:?}",
            result.err()
        );
    }

    #[test]
    fn test_different_parties_stark_prove_verify() {
        // DifferentPartiesCircuit: require!(sender != receiver)
        let circuit = DifferentPartiesCircuit;
        assert_eq!(circuit.width(), 3); // 2 params + 1 inv
        assert_eq!(circuit.constraint_degree(), 2);

        let trace = circuit.generate_trace(1, 2);
        let pi = vec![BabyBear::from_u64(1), BabyBear::from_u64(2)];
        let proof = stark::prove(&circuit, &trace, &pi);
        let result = stark::verify(&circuit, &proof, &pi);
        assert!(
            result.is_ok(),
            "DifferentPartiesCircuit prove/verify failed: {:?}",
            result.err()
        );
    }

    #[test]
    fn test_compound_check_stark_prove_verify() {
        // CompoundCheckCircuit: require!(balance >= threshold); require!(sender != receiver)
        let circuit = CompoundCheckCircuit;
        // 4 params + 3 range-check blocks of (1 diff + 30 bits) for the `>=`
        // (diff + two operand range-checks) + 1 inverse for the `!=`
        // = 4 + 3*31 + 1 = 98
        assert_eq!(circuit.width(), 98);
        assert_eq!(circuit.constraint_degree(), 2);

        let trace = circuit.generate_trace(100, 50, 1, 2);
        let pi = vec![
            BabyBear::from_u64(100),
            BabyBear::from_u64(50),
            BabyBear::from_u64(1),
            BabyBear::from_u64(2),
        ];
        let proof = stark::prove(&circuit, &trace, &pi);
        let result = stark::verify(&circuit, &proof, &pi);
        assert!(
            result.is_ok(),
            "CompoundCheckCircuit prove/verify failed: {:?}",
            result.err()
        );
    }

    #[test]
    fn test_decrement_stark_prove_verify() {
        // DecrementCircuit: effect with &mut counter, step
        // require!(*counter >= step); *counter = *counter - step;
        let circuit = DecrementCircuit;
        // 2 cols for counter (old+new) + 1 for step + aux columns
        assert!(circuit.width() >= 3);

        // counter old=10, new=7, step=3
        let trace = circuit.generate_trace(10, 7, 3);
        let pi = vec![
            BabyBear::from_u64(10), // counter_old
            BabyBear::from_u64(7),  // counter_new
            BabyBear::from_u64(3),  // step
        ];
        let proof = stark::prove(&circuit, &trace, &pi);
        let result = stark::verify(&circuit, &proof, &pi);
        assert!(
            result.is_ok(),
            "DecrementCircuit prove/verify failed: {:?}",
            result.err()
        );
    }

    // --- FORGE DETECTOR: the emit_stark inequality range check ---
    //
    // Before the bit-decomposition fix, the LessEqual/GreaterEqual range check
    // emitted only: (diff == right - left) + (bit binary) + (bit == 0), with NO
    // constraint tying `bit` to the high bit of `diff`. The trace-gen set bit = 0
    // unconditionally, so an inequality VIOLATION (left > right => diff wraps
    // negative in BabyBear) satisfied all three terms and was ACCEPTED.
    //
    // These tests pin the fixed behavior at both poles:
    //   - an honest witness (left <= right) is ACCEPTED, and
    //   - the exact malicious witness the old code accepted is now REJECTED.

    /// Build the `NotAfterCircuit` AIR verdict for an explicit witness row.
    ///
    /// Predicate is `require!(current_time <= token_expiry)`, i.e. the IR is
    /// `LessEqual { left: current_time, right: token_expiry }` and
    /// `diff = token_expiry - current_time`. The operand range-checks (which
    /// close the field wrap-around) decompose the two operands in IR order
    /// `[left, right] = [current_time, token_expiry]`.
    ///
    /// Aux column layout (width = 2 params + 3*(1 + 30 bits) = 95):
    ///   col 0  = token_expiry,  col 1 = current_time
    ///   col 2  = diff,            cols 3..33  = 30 little-endian bits of diff
    ///   col 33 = current_time,    cols 34..64 = 30 bits of current_time (operand 1)
    ///   col 64 = token_expiry,    cols 65..95 = 30 bits of token_expiry  (operand 2)
    ///
    /// The operand diff/bit columns are filled HONESTLY from the supplied
    /// `current_time` / `token_expiry` (canonical u32 decomposition) so that an
    /// honest small-operand witness passes; the wrap-around forge detector
    /// instead drives them via [`not_after_air_is_zero_operands`].
    fn not_after_air_is_zero(
        token_expiry: u64,
        current_time: u64,
        diff: BabyBear,
        bits: &[u32; 30],
    ) -> bool {
        // Honest operand fill: operand 1 = current_time, operand 2 = token_expiry.
        let ct = BabyBear::from_u64(current_time);
        let te = BabyBear::from_u64(token_expiry);
        not_after_air_is_zero_operands(
            token_expiry,
            current_time,
            diff,
            bits,
            ct,
            &bits30(ct.as_u32()),
            te,
            &bits30(te.as_u32()),
        )
    }

    /// Lower-level NotAfter AIR verdict with EXPLICIT operand range-check
    /// witnesses, so the wrap-around forge detector can feed a malicious operand
    /// decomposition (e.g. a tiny fake diff with bogus operand bits) and observe
    /// that the operand range-check rejects it.
    #[allow(clippy::too_many_arguments)]
    fn not_after_air_is_zero_operands(
        token_expiry: u64,
        current_time: u64,
        diff: BabyBear,
        diff_bits: &[u32; 30],
        operand1_diff: BabyBear,
        operand1_bits: &[u32; 30],
        operand2_diff: BabyBear,
        operand2_bits: &[u32; 30],
    ) -> bool {
        let circuit = NotAfterCircuit;
        let width = circuit.width();
        let mut row = vec![BabyBear::ZERO; width];
        row[0] = BabyBear::from_u64(token_expiry);
        row[1] = BabyBear::from_u64(current_time);
        // Diff range-check block.
        row[2] = diff;
        for (i, b) in diff_bits.iter().enumerate() {
            row[3 + i] = BabyBear::new(*b);
        }
        // Operand 1 range-check block (current_time = LE left operand).
        row[33] = operand1_diff;
        for (i, b) in operand1_bits.iter().enumerate() {
            row[34 + i] = BabyBear::new(*b);
        }
        // Operand 2 range-check block (token_expiry = LE right operand).
        row[64] = operand2_diff;
        for (i, b) in operand2_bits.iter().enumerate() {
            row[65 + i] = BabyBear::new(*b);
        }
        let pi = vec![
            BabyBear::from_u64(token_expiry),
            BabyBear::from_u64(current_time),
        ];
        // The AIR accepts the row iff the constraint polynomial is zero for ALL
        // alpha challenges; a single random alpha suffices to expose a nonzero
        // sub-constraint with overwhelming probability, and we additionally test
        // a second alpha to be sure no aliasing hides the violation.
        let a1 = circuit.eval_constraints(&row, &row, &pi, BabyBear::new(7));
        let a2 = circuit.eval_constraints(&row, &row, &pi, BabyBear::new(31));
        a1 == BabyBear::ZERO && a2 == BabyBear::ZERO
    }

    /// Honest decomposition of `v` into 30 little-endian bits.
    fn bits30(v: u32) -> [u32; 30] {
        let mut out = [0u32; 30];
        for (i, b) in out.iter_mut().enumerate() {
            *b = (v >> i) & 1;
        }
        out
    }

    #[test]
    fn forge_detector_le_honest_accepts() {
        // current_time = 50 <= token_expiry = 100. diff = 50, bits = decomp(50).
        let diff = BabyBear::from_u64(100) - BabyBear::from_u64(50);
        assert!(
            not_after_air_is_zero(100, 50, diff, &bits30(50)),
            "honest witness (50 <= 100) must be ACCEPTED"
        );
        // Boundary: equality also accepts (diff = 0).
        let diff0 = BabyBear::ZERO;
        assert!(
            not_after_air_is_zero(100, 100, diff0, &bits30(0)),
            "boundary witness (100 <= 100) must be ACCEPTED"
        );
    }

    #[test]
    fn forge_detector_le_violation_rejected() {
        // VIOLATION: current_time = 60 > token_expiry = 40. The OLD circuit
        // accepted this with the malicious witness (diff = right - left wrapped
        // negative, all bits = 0): diff_check = 0, bit_binary = 0, bit_zero = 0.
        // Replay EXACTLY that witness; the fixed circuit must REJECT it because
        // the bit reconstruction can no longer match the wrapped-negative diff
        // while keeping the high bits zero.
        let wrapped_neg = BabyBear::from_u64(40) - BabyBear::from_u64(60); // = -20 mod p
        let all_zero_bits = [0u32; 30];
        assert!(
            !not_after_air_is_zero(40, 60, wrapped_neg, &all_zero_bits),
            "the old vacuity: diff=right-left wrapped negative with all-zero bits \
             must now be REJECTED"
        );

        // The honest decomposition of a violation is ALSO rejected: the canonical
        // u32 of -20 mod p is ~2^31, whose true bit-decomposition needs bits above
        // index 29 — forced to zero — so reconstruction is unsatisfiable.
        let canon = wrapped_neg.as_u32();
        assert!(
            !not_after_air_is_zero(40, 60, wrapped_neg, &bits30(canon)),
            "honest decomposition of a wrapped-negative diff must be REJECTED \
             (high bits required but forced zero)"
        );

        // And the prover cannot rescue it by feeding a fake small diff: binding
        // diff_col to a value != (token_expiry - current_time) trips the diff
        // consistency sub-constraint.
        assert!(
            !not_after_air_is_zero(40, 60, BabyBear::ZERO, &all_zero_bits),
            "fake diff = 0 (!= -20) must be REJECTED by the diff-binding constraint"
        );
    }

    // --- FORGE DETECTOR: the field WRAP-AROUND hole (operands unchecked) ---
    //
    // The diff range-check alone is sound ONLY IF |left - right| < p/2. The prior
    // fix range-checked `diff` but NOT the operands, leaving a wrap-around hole:
    // a malicious prover picks a LARGE operand near the field size p so the diff
    // WRAPS to a small value that fits the 30-bit diff window.
    //
    // Concretely for `require!(current_time <= token_expiry)`: set
    //   current_time = p - 1   (a violation: p-1 is NOT <= 0)
    //   token_expiry = 0
    // Then diff = token_expiry - current_time = 0 - (p-1) ≡ 1 (mod p), which is
    // tiny and passes the diff range-check. BEFORE the operand range-check this
    // wrap-around was ACCEPTED. AFTER, the operand range-check on current_time
    // (= p-1, which does NOT fit in OPERAND_RANGE_BITS = 29 bits) REJECTS it.

    #[test]
    fn forge_detector_le_wraparound_rejected() {
        use dregg_circuit::field::BABYBEAR_P;
        let p = BABYBEAR_P as u64;

        // current_time = p - 1 (a genuine violation), token_expiry = 0.
        let ct_u = p - 1;
        let te_u = 0u64;
        let ct = BabyBear::from_u64(ct_u);
        let te = BabyBear::from_u64(te_u);

        // The WRAPPED diff: token_expiry - current_time = 0 - (p-1) ≡ 1.
        let wrapped_diff = te - ct;
        // The honest 30-bit decomposition of the wrapped diff (= 1) fits the diff
        // window perfectly — this is exactly why the diff check alone is fooled.
        let wrapped_diff_bits = bits30(wrapped_diff.as_u32());

        // BEFORE (the residual hole): the DIFF range-check block, in isolation,
        // ACCEPTS this witness. We witness that here directly: the wrapped diff is
        // a genuine 30-bit value, so reconstruction holds and no high bit is set.
        assert!(
            wrapped_diff == BabyBear::from_u64(1),
            "the wrap: 0 - (p-1) collapses to the tiny value 1"
        );
        let recon: u32 = (0..30)
            .map(|i| wrapped_diff_bits[i] << i)
            .sum();
        assert_eq!(
            recon, 1,
            "BEFORE: the wrapped diff (=1) has a clean 30-bit decomposition that the \
             diff range-check accepts — the operand-unchecked hole"
        );

        // AFTER (the operand range-check closes it): drive the operand blocks with
        // the prover's BEST attempt. Operand 1 = current_time = p-1. There is NO
        // valid 29-bit decomposition of p-1 (it needs bits at index >= 29, which
        // are forced to zero). We feed its honest canonical decomposition; the
        // forced-zero high bits make the reconstruction sub-constraint nonzero.
        assert!(
            !not_after_air_is_zero_operands(
                te_u, // token_expiry = 0
                ct_u, // current_time = p-1
                wrapped_diff,
                &wrapped_diff_bits,
                ct,                  // operand 1 diff = current_time = p-1
                &bits30(ct.as_u32()),
                te,                  // operand 2 diff = token_expiry = 0
                &bits30(te.as_u32()),
            ),
            "AFTER: current_time = p-1 does NOT fit OPERAND_RANGE_BITS (=29) bits, so \
             the operand range-check REJECTS the wrap-around violation"
        );

        // The prover cannot rescue it by lying about the operand bits either: any
        // 29-bit (high-bits-zeroed) decomposition reconstructs to some value v <
        // 2^29 != p-1, so the operand BINDING sub-constraint (op_diff == operand)
        // trips. Feed a small fake operand value with a clean small decomposition.
        let fake_small = BabyBear::from_u64(7);
        assert!(
            !not_after_air_is_zero_operands(
                te_u,
                ct_u,
                wrapped_diff,
                &wrapped_diff_bits,
                fake_small,          // fake operand-1 diff != current_time (=p-1)
                &bits30(7),
                te,
                &bits30(te.as_u32()),
            ),
            "AFTER: a fake small operand-1 value (!= p-1) trips the operand-binding \
             sub-constraint; the wrap-around stays REJECTED"
        );

        // CONTROL: a genuinely small, honest, satisfying witness still ACCEPTS
        // (current_time = 5 <= token_expiry = 9), confirming operands in [0, 2^29)
        // remain provable.
        let diff_ok = BabyBear::from_u64(9) - BabyBear::from_u64(5);
        assert!(
            not_after_air_is_zero(9, 5, diff_ok, &bits30(4)),
            "CONTROL: an honest small-operand witness (5 <= 9) must still be ACCEPTED"
        );
    }

    #[test]
    fn test_stark_impl_rejects_invalid_trace() {
        // Invalid trace: constraint is non-zero, proof should fail verification
        // with different public inputs.
        let circuit = ExactMatchCircuit;
        let trace = circuit.generate_trace(42, 42);
        let pi = vec![BabyBear::from_u64(42), BabyBear::from_u64(42)];
        let wrong_pi = vec![BabyBear::from_u64(42), BabyBear::from_u64(99)];

        let proof = stark::prove(&circuit, &trace, &pi);
        // Verify with wrong public inputs should fail
        let result = stark::verify(&circuit, &proof, &wrong_pi);
        assert!(
            result.is_err(),
            "Should reject proof with wrong public inputs"
        );
    }

    // --- Phase 1 tests (preserved) ---

    #[test]
    fn test_not_after_evaluator_pass() {
        assert!(not_after_check(100, 50).is_ok());
    }

    #[test]
    fn test_not_after_evaluator_boundary() {
        assert!(not_after_check(100, 100).is_ok());
    }

    #[test]
    fn test_not_after_evaluator_fail() {
        assert!(not_after_check(50, 100).is_err());
    }

    #[test]
    fn test_not_after_air_descriptor() {
        let air = not_after_air_constraints();
        assert_eq!(air.name, "not_after");
        assert!(air.width > 0);
        // 2 params + 2 auxiliary (diff + bit) = 4
        assert_eq!(air.width, 4);
        assert_eq!(air.constraints.len(), 1);
        assert_eq!(air.public_inputs.len(), 2);
    }

    #[test]
    fn test_not_after_datalog() {
        let rule = not_after_datalog();
        assert!(rule.contains("not_after_satisfied"));
        assert!(rule.contains("<="));
    }

    #[test]
    fn test_minimum_balance_pass() {
        assert!(minimum_balance_check(100, 50).is_ok());
        assert!(minimum_balance_check(50, 50).is_ok());
    }

    #[test]
    fn test_minimum_balance_fail() {
        assert!(minimum_balance_check(49, 50).is_err());
    }

    #[test]
    fn test_exact_match_pass() {
        assert!(exact_match_check(42, 42).is_ok());
    }

    #[test]
    fn test_exact_match_fail() {
        assert!(exact_match_check(42, 43).is_err());
    }

    #[test]
    fn test_different_parties_pass() {
        assert!(different_parties_check(1, 2).is_ok());
    }

    #[test]
    fn test_different_parties_fail() {
        assert!(different_parties_check(1, 1).is_err());
    }

    #[test]
    fn test_exact_match_air_no_extra_cols() {
        let air = exact_match_air_constraints();
        // equality needs no auxiliary columns: just 2 param columns
        assert_eq!(air.width, 2);
    }

    #[test]
    fn test_different_parties_air_inverse_col() {
        let air = different_parties_air_constraints();
        // 2 params + 1 inverse witness = 3
        assert_eq!(air.width, 3);
    }

    // --- Phase 2: Effect mutation tests ---

    #[test]
    fn test_transfer_outgoing_pass() {
        let mut balance = 100u64;
        let result = transfer_check(&mut balance, 30, Direction::Outgoing);
        assert!(result.is_ok());
        assert_eq!(balance, 70);
    }

    #[test]
    fn test_transfer_outgoing_fail_insufficient() {
        let mut balance = 20u64;
        let result = transfer_check(&mut balance, 30, Direction::Outgoing);
        assert!(result.is_err());
        // Balance should not be mutated on failure
        assert_eq!(balance, 20);
    }

    #[test]
    fn test_transfer_incoming() {
        let mut balance = 50u64;
        let result = transfer_check(&mut balance, 25, Direction::Incoming);
        assert!(result.is_ok());
        assert_eq!(balance, 75);
    }

    #[test]
    fn test_decrement_pass() {
        let mut counter = 10u64;
        let result = decrement_check(&mut counter, 3);
        assert!(result.is_ok());
        assert_eq!(counter, 7);
    }

    #[test]
    fn test_decrement_fail() {
        let mut counter = 2u64;
        let result = decrement_check(&mut counter, 5);
        assert!(result.is_err());
        assert_eq!(counter, 2);
    }

    // --- Phase 2: AIR descriptor for effects (old+new columns) ---

    #[test]
    fn test_effect_air_has_old_new_columns() {
        let air = decrement_air_constraints();
        // Mutable param `counter` gets 2 columns (old + new)
        // Immutable param `step` gets 1 column
        // Plus auxiliary columns from require (2) + mutation transition (2)
        assert!(air.width >= 3); // at minimum: 2 (counter old+new) + 1 (step)
        // Should have both a RangeCheck constraint and a Transition constraint
        let has_transition = air
            .constraints
            .iter()
            .any(|c| matches!(c, dregg_dsl_runtime::Constraint::Transition { .. }));
        assert!(
            has_transition,
            "effect AIR should have Transition constraint"
        );
    }

    #[test]
    fn test_transfer_air_has_match_constraints() {
        let air = transfer_air_constraints();
        // Transfer has mutable balance (2 cols) + amount (1) + direction (1)
        // Plus match selector + arm constraints
        assert!(air.width >= 4);
        assert!(!air.constraints.is_empty());
    }

    // --- Phase 2: Set membership ---

    #[test]
    fn test_service_scope_pass() {
        let mut allowed = std::collections::HashSet::new();
        allowed.insert(1u64);
        allowed.insert(2);
        allowed.insert(3);
        assert!(service_scope_check(&allowed, 2).is_ok());
    }

    #[test]
    fn test_service_scope_fail() {
        let mut allowed = std::collections::HashSet::new();
        allowed.insert(1u64);
        allowed.insert(2);
        assert!(service_scope_check(&allowed, 99).is_err());
    }

    #[test]
    fn test_service_scope_air_membership() {
        let air = service_scope_air_constraints();
        let has_membership = air
            .constraints
            .iter()
            .any(|c| matches!(c, dregg_dsl_runtime::Constraint::MerkleMembership { .. }));
        assert!(
            has_membership,
            "membership caveat should emit MerkleMembership constraint"
        );
    }

    // --- Phase 2: Multi-constraint composition ---

    #[test]
    fn test_compound_check_pass() {
        assert!(compound_check_check(100, 50, 1, 2).is_ok());
    }

    #[test]
    fn test_compound_check_fail_balance() {
        assert!(compound_check_check(30, 50, 1, 2).is_err());
    }

    #[test]
    fn test_compound_check_fail_same_party() {
        assert!(compound_check_check(100, 50, 1, 1).is_err());
    }

    #[test]
    fn test_compound_air_width_is_sum() {
        let air = compound_check_air_constraints();
        // 4 params (balance, threshold, sender, receiver) = 4
        // + range check aux (2) for >=
        // + inverse witness (1) for !=
        // total = 7
        assert_eq!(air.width, 7);
        assert_eq!(air.constraints.len(), 2);
    }

    // --- Phase 2: Kimchi descriptor ---

    #[test]
    fn test_kimchi_equality_gate() {
        let kimchi = exact_match_kimchi();
        assert!(!kimchi.gates.is_empty());
        assert_eq!(kimchi.public_input_count, 2);
        // Equality gate has non-zero coefficients
        let gate = &kimchi.gates[0];
        assert_eq!(gate.typ, dregg_dsl_runtime::KimchiGateType::Generic);
        assert!(gate.coeffs.iter().any(|c| *c != 0));
    }

    #[test]
    fn test_kimchi_range_check_gates() {
        let kimchi = not_after_kimchi();
        // Range check: 1 diff gate + 64 binary gates + 1 reconstruction = 66
        assert_eq!(kimchi.gates.len(), 66);
        assert_eq!(kimchi.public_input_count, 2);
        assert!(kimchi.trace_width > 2); // params + auxiliary
    }

    #[test]
    fn test_kimchi_neq_inverse_gate() {
        let kimchi = different_parties_kimchi();
        assert!(!kimchi.gates.is_empty());
        let gate = &kimchi.gates[0];
        assert_eq!(gate.typ, dregg_dsl_runtime::KimchiGateType::Generic);
        // Inverse-existence: coeffs[3]=1, coeffs[4]=-1
        assert_eq!(gate.coeffs[3], 1);
        assert_eq!(gate.coeffs[4], -1);
    }

    #[test]
    fn test_kimchi_mutation_gate() {
        let kimchi = decrement_kimchi();
        // Should have gates for the range check AND the mutation
        assert!(kimchi.gates.len() > 1);
        // Find the SubAssign gate (coeffs[0]=1, coeffs[1]=-1, coeffs[2]=-1)
        let has_sub_gate = kimchi.gates.iter().any(|g| {
            g.typ == dregg_dsl_runtime::KimchiGateType::Generic
                && g.coeffs.len() >= 3
                && g.coeffs[0] == 1
                && g.coeffs[1] == -1
                && g.coeffs[2] == -1
        });
        assert!(has_sub_gate, "decrement kimchi should have SubAssign gate");
    }

    #[test]
    fn test_kimchi_membership_poseidon() {
        let kimchi = service_scope_kimchi();
        // Membership uses Poseidon gates
        let poseidon_count = kimchi
            .gates
            .iter()
            .filter(|g| g.typ == dregg_dsl_runtime::KimchiGateType::Poseidon)
            .count();
        assert_eq!(
            poseidon_count, 32,
            "membership should emit 32 Poseidon gates (one per tree level)"
        );
    }

    // --- Phase 2: Permission annotation ---

    #[test]
    fn test_permission_in_effect_descriptor() {
        let desc = guarded_transfer_effect_descriptor();
        assert_eq!(desc.name, "guarded_transfer");
        assert_eq!(desc.required_permission, Some("Send"));
        assert_eq!(desc.mutable_params, vec!["balance"]);
    }

    #[test]
    fn test_effect_descriptor_no_permission() {
        let desc = transfer_effect_descriptor();
        assert_eq!(desc.name, "transfer");
        assert_eq!(desc.required_permission, None);
        assert_eq!(desc.mutable_params, vec!["balance"]);
    }
}
