val _ = load "corsRung3Theory"; val _ = load "corsBytesBridgeTheory";
open corsRung3Theory corsBytesBridgeTheory;
fun tag th = let val (o_,a)=Tag.dest_tag (Thm.tag th) in "[oracles: "^String.concatWith "," o_^"] [axioms: "^String.concatWith "," a^"]" end;
val _ = print ("AAA backbone cors_rung3_native = "^tag cors_rung3_native^"\n");
val _ = print ("AAA linkA cors_decisioncore_refines_spec = "^tag cors_decisioncore_refines_spec^"\n");
val _ = print ("AAA faithful corsIf_faithful = "^tag corsIf_faithful^"\n");
val _ = print ("AAA L2 cors_compile_prog_native = "^tag cors_compile_prog_native^"\n");
val _ = print ("AAA theory-axioms corsRung3 = "^Int.toString(length(axioms "corsRung3"))^"\n");
val _ = print ("AAA theory-axioms corsBytesBridge = "^Int.toString(length(axioms "corsBytesBridge"))^"\n");
val c = concl corsIf_faithful; val (lhs,rhs)=dest_eq c;
fun qn t = let val {Thy,Name,...}=dest_thy_const t in Thy^"$"^Name end;
val progn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="corsProg") lhs);
val ifn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="corsIf") rhs);
val _ = print ("AAA faithful-distinct prog="^progn^" if="^ifn^" DISTINCT="^Bool.toString(progn<>ifn)^"\n");
val bc = concl cors_rung3_native; val (ante,conc)=dest_imp bc;
val _ = print ("AAA backbone antecedent-conjuncts = "^Int.toString(length(strip_conj ante))^"\n");
val _ = print ("AAA backbone concl-mentions-corsProg = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="corsProg")) conc)^"\n");
val _ = print ("AAA backbone ante-mentions-corsBytes = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="corsBytes")) ante)^"\n");
