/-
# Dregg2.Calculus.BiorthRelational — the RELATIONAL fronts: TEMPORAL and EPISTEMIC guards under
biorthogonality (the bridge's last two named families, `docs/TRANSCENDENTAL-SYNTAX-BRIDGE.md` STATUS).

`Biorthogonality.lean` proved the literal/order family closed (rectangles — the trivial case);
`BiorthTensor.lean` proved the linear verdict: conservation is a behaviour IFF the tests may
CORRELATE the pair (`linearity_recovered_from_orthogonality`), and NO rectangular family can carve
it (`rect_mix_in_biorth`). This module pushes the same question onto the two remaining families.

## TEMPORAL VERDICT: behaviour at the point level — with an EXACT characterization — and the modal
(until/since) content is a CORRELATION ACROSS TIME-STEPS, conservation-shaped.

  * **Point level (heights/records): YES, trivially — and more: COMPLETE.** Every temporal-atom
    guard and every until/since (event) guard is a behaviour (`temporal_guard_is_behaviour` /
    `event_guard_is_behaviour`, the generic `listAdm` engine; the installed gates ARE orthogonality
    membership, definitionally: `temporalAtomsAdmit_is_orthogonality` /
    `eventAtomsAdmit_is_orthogonality` — the welds onto `temporalStateStepGuarded` /
    `eventStateStepGuarded`). The NEW content beyond the literal case: the height family's
    behaviours are characterized EXACTLY — `height_behaviour_iff_convex`: a set of heights is a
    behaviour of the after/before test family IFF it is convex (an interval). The closure is
    CONVEXIFICATION (`gap_closure_adds_midpoint`: `{0,2}^⊥⊥ ∋ 1`), and — completeness — every
    behaviour IS a window guard of the deployed family (`behaviour_is_window_guard`): behaviours =
    intervals = `withinWindow`/`afterHeight`/`beforeHeight` admission sets. The until/since SHAPE
    (a window = "since lo until hi") is not merely closed under `^⊥⊥`; it is everything `^⊥⊥` can
    say about heights. Upward-closed behaviours are the vesting/`AG`-permanence classes
    (`after_class_upward`; the branching reading is the landed `afterHeight_iff_AG`).
  * **Trace level (the MODAL face): the obstruction is real, and it is time-correlation.** What
    makes until/since temporal rather than literal is the run discipline `sinceEvent_iff_AG`
    rides: the WRITE-ONCE step (`flagClock.Step`'s monotone conjunct — flag may flip `false→true`,
    never back). That discipline, as a class of steps `Mono ⊆ Bool × Bool`, is **NOT a behaviour
    under ANY rectangular (per-time-point) test family** (`writeOnce_not_behaviour_rectangular`,
    via the same generic mix law as conservation: `(true,true)` and `(false,false)` are both
    monotone, the mixed corner `(true,false)` is the forbidden flip-back) — and **IS a behaviour
    the moment the STEP observable is fielded as a test** (`writeOnce_is_behaviour`:
    `Mono = {stepOk}^⊥`). A temporal guard correlates across time-steps EXACTLY the way
    conservation correlates across the pair: per-point tests are blind to the step, the one
    relational observable (the transition reading) is the whole gap. Welded to the executor:
    every committed close write's flag transition lands in the behaviour
    (`committed_close_lands_in_behaviour`, via `committed_flip_write_steps_flagClock`). And the
    until-gate's REFUTATIONS are exactly the since-witnesses
    (`until_refusal_is_since_witness`, via `until_since_complement`): the counter-witness to
    "still before E" IS the post-E witness — the orthogonal of the until class is generated by
    the since side.

## EPISTEMIC VERDICT: K, E_G, C_G are behaviours (one-party challenges suffice — E is the additive
`&`, C is K of the LEDGER); IGNORANCE is not a behaviour; and D_G needs the TENSOR exactly as
conservation does — pooled knowledge IS a correlation (the shared randomness of the sharing).

  * **The orthogonality**: a refutation is a CHALLENGE a party cannot answer — `answerPerp e φ` =
    "the evidence state `e` exhibits a witness discharging `φ`" (the `Verifiable`/`Discharged`
    seam of `Dregg2.Laws`, the same one `Epistemic.Knows` is built on). `Knows pocket a φ` IS
    membership of `a`'s pocket in `{φ}^⊥` (`knows_iff_mem_class`) — so every K-class is a
    behaviour (`knows_class_is_behaviour`). `EveryoneKnows` is the orthogonal of the challenge
    set `{(a, φ) | a ∈ G}` — each challenge names ONE member, so E is rectangular/additive: the
    behaviour MEET of the members' K-classes (`everyone_pair_is_meet`, an instance of the landed
    `coOrth_union`). `CommonAt floor d φ` is LITERALLY K of the ledger — membership of the
    finalized-at-`d` set in the same `{φ}^⊥` (`common_iff_ledger_in_knows_class`): orthogonality
    classifies C's witness-shape as one existential over ONE (virtual) party; what separates C
    from K — the floor's delivery law `finalized_visible`, the partition story — is INVISIBLE to
    the testing relation. Honest scope, stated.
  * **The forced structure**: challenge-semantics behaviours are MONOTONE in exhibitable evidence
    (`knows_behaviour_monotone` — more witnesses never destroy knowledge; attenuation's dual),
    so IGNORANCE — "cannot answer φ" — is NOT a behaviour (`ignorance_not_behaviour`): its
    closure floods upward. In a witness semantics, non-knowledge is not a type.
  * **D_G — the sharp one (`distributed_knowledge_recovered_from_orthogonality`).** Over the
    2-of-2 additive sharing (the simplest real threshold scheme: shares `(r, s − r)`, pool =
    sum — `ThresholdKnows` with the real `sumPool`, welded by `threshold_iff_sum`), the D-class
    of share PAIRS is `{m | m.1 + m.2 = 66}` — an affine correlation, the SAME mathematical shape
    as conservation. Hence: **NOT a behaviour under ANY rectangular per-member challenge family**
    (`distributed_not_behaviour_rectangular`; live instance = paired one-member challenges,
    `distributed_not_behaviour_member_challenges`) — two reconstructing coalitions mixed
    member-wise need not reconstruct — and **IS a behaviour once the POOLED challenge (the
    reconstruction test, `Verify` of the combined witness) is fielded**
    (`distributed_is_behaviour`), and is then EXACTLY the closure of the matched-randomness
    tensors `⋃ᵣ {r} ⊙ {66 − r}` (`dclass_eq_closure_of_matched_tensors`) — the sharing randomness
    plays the role the matched delta played for `move`. No single member knows
    (`d_without_k`): the correlation IS the knowledge. The parallel to
    `linearity_recovered_from_orthogonality` is exact, clause for clause.

## THE SYNTHESIS (`correlation_classifies_the_family`): ONE pattern across all four families.

The trivial guards (literal/order, height-points, K/E/C) are the ONE-COMPONENT ones — each test
reads a single turn / single height / single party, and closure is automatic (everything is an
orthogonal) with at most gap-filling. EVERY interesting guard is a behaviour exactly when the
test language fields the RIGHT correlating observable, and fails rectangularly otherwise:

  | family     | correlated across | the one observable that crosses the line  |
  |------------|-------------------|--------------------------------------------|
  | resource   | the paired writes | `Σδ` (the `valTotal` comparator)           |
  | temporal   | adjacent steps    | `stepOk` (the transition reading)          |
  | epistemic-D| the members       | the pooled reconstruction (`combine` + `Verify`) |

Biorthogonality is load-bearing precisely where correlation matters, and the correlation TYPE
(time-adjacency / resource-sum / shared-randomness) classifies the guard family. That is the
bridge's real content: the guard algebra's interesting modalities are not assembled — each is
the `^⊥⊥`-closure of its family's one relational observable, and the trivial ones are the
rectangles. All three negative halves are instances of ONE generic law (`rect_mix_in_biorth`).

No `sorry`, no `:= True`, no `native_decide`; non-vacuity both polarities per closure claim;
every keystone `#assert_axioms`-pinned.
-/
import Dregg2.Calculus.BiorthTensor
import Dregg2.Authority.TemporalAlgebra2
import Dregg2.Authority.Epistemic

namespace Dregg2.Calculus.Biorth

open Dregg2.Exec
open Dregg2.Exec.EffectsState (stateStepGuarded)
open Dregg2.Authority.TemporalAlgebra
open Dregg2.Authority.TemporalAlgebra2

/-! ## §1 — TEMPORAL, point level: guards are behaviours; the installed gates are orthogonality. -/

namespace Ht

/-- The temporal-atom evaluator in `listAdm` shape: a point is `(height, record)`
(`TemporalAtom.eval`'s exact domain, `TemporalAlgebra.lean:150`). -/
def tsurvB (t : Nat × Value) (a : TemporalAtom) : Bool := a.eval t.1 t.2

/-- The event-atom (until/since) evaluator in `listAdm` shape (`TemporalAlgebra2.lean:154`). -/
def esurvB (rec : Value) (a : EventAtom) : Bool := a.eval rec

/-- **Every temporal guard is a behaviour** — any finite conjunction of the six temporal atoms
(after/before/within/cooled/rate/challenge), by the generic engine. -/
theorem temporal_guard_is_behaviour (g : List TemporalAtom) :
    IsBehaviour (fun t a => tsurvB t a = true) (listAdm tsurvB g) :=
  listAdm_isBehaviour tsurvB g

/-- **Every until/since guard is a behaviour** — the U/S atoms at the record level. -/
theorem event_guard_is_behaviour (g : List EventAtom) :
    IsBehaviour (fun rec a => esurvB rec a = true) (listAdm esurvB g) :=
  listAdm_isBehaviour esurvB g

/-- **THE INSTALLED-GATE WELD (definitional)**: `temporalAtomsAdmit` — the gate
`temporalStateStepGuarded` runs — IS orthogonality-set membership. -/
theorem temporalAtomsAdmit_is_orthogonality (atoms : List TemporalAtom) (ht : Nat) (rec : Value) :
    temporalAtomsAdmit atoms ht rec = true
      ↔ ((ht, rec) : Nat × Value) ∈ listAdm tsurvB atoms :=
  Iff.rfl

/-- The same weld at the U/S gate: `eventAtomsAdmit` — the gate `eventStateStepGuarded` runs —
IS orthogonality-set membership. -/
theorem eventAtomsAdmit_is_orthogonality (atoms : List EventAtom) (rec : Value) :
    eventAtomsAdmit atoms rec = true ↔ rec ∈ listAdm esurvB atoms :=
  Iff.rfl

/-! ### The height family characterized EXACTLY: behaviours = convex sets = window guards. -/

/-- The height test family — the two monotone half-gates (the shapes of
`afterHeight`/`beforeHeight`, hence of dregg1's `TemporalGate` decomposition). -/
inductive HtTest where
  /-- survive iff `h ≤ height` (the vesting half). -/
  | after (h : Nat)
  /-- survive iff `height ≤ h` (the deadline half). -/
  | before (h : Nat)
  deriving Repr, DecidableEq

/-- The evaluator — VERBATIM the height-only atoms' verdicts (`htTest_denotes`). -/
def hsurvB (ht : Nat) : HtTest → Bool
  | .after h  => decide (h ≤ ht)
  | .before h => decide (ht ≤ h)

/-- `ht ⊥ r` at the height level. Decidable. -/
def HSurvives (ht : Nat) (r : HtTest) : Prop := hsurvB ht r = true

instance (ht : Nat) (r : HtTest) : Decidable (HSurvives ht r) :=
  inferInstanceAs (Decidable (hsurvB ht r = true))

/-- FAITHFULNESS: each test is the live atom's evaluator, verbatim (record-blind, as the
height-only class is — `eval_heightOnly_rec_irrel`). -/
theorem htTest_denotes (h ht : Nat) (rec : Value) :
    hsurvB ht (.after h) = (TemporalAtom.afterHeight h).eval ht rec
      ∧ hsurvB ht (.before h) = (TemporalAtom.beforeHeight h).eval ht rec :=
  ⟨rfl, rfl⟩

/-- Convexity in `ℕ` — the interval property. -/
def Convex (S : Set Nat) : Prop :=
  ∀ a ∈ S, ∀ c ∈ S, ∀ b, a ≤ b → b ≤ c → b ∈ S

/-- Every orthogonal of height tests is convex (each survivor set is a half-line; intersections
of half-lines are intervals). -/
theorem coOrth_convex (X : Set HtTest) : Convex (coOrthSet HSurvives X) := by
  intro a ha c hc b hab hbc r hr
  have h1 := ha r hr
  have h2 := hc r hr
  cases r with
  | after h =>
      have h1' : h ≤ a := of_decide_eq_true h1
      exact decide_eq_true (by omega)
  | before h =>
      have h2' : c ≤ h := of_decide_eq_true h2
      exact decide_eq_true (by omega)

/-- A height behaviour is convex. -/
theorem behaviour_convex {S : Set Nat} (h : IsBehaviour HSurvives S) : Convex S := by
  have he : S = coOrthSet HSurvives (orthSet HSurvives S) := h.symm
  rw [he]
  exact coOrth_convex _

/-- A convex set of heights is a behaviour: anything in the closure is bracketed by members
(otherwise a half-line test in `S^⊥` refutes it), and convexity absorbs the bracket. -/
theorem convex_isBehaviour {S : Set Nat} (hconv : Convex S) : IsBehaviour HSurvives S := by
  refine Set.Subset.antisymm ?_ (subset_biorth HSurvives S)
  intro t ht
  by_cases h₁ : ∃ a ∈ S, a ≤ t
  · by_cases h₂ : ∃ c ∈ S, t ≤ c
    · obtain ⟨a, ha, hat⟩ := h₁
      obtain ⟨c, hc, htc⟩ := h₂
      exact hconv a ha c hc t hat htc
    · push Not at h₂
      obtain ⟨a, ha, _⟩ := h₁
      have hb : HtTest.before (t - 1) ∈ orthSet HSurvives S := by
        intro s hs
        have := h₂ s hs
        exact decide_eq_true (by omega)
      have hsurv : t ≤ t - 1 := of_decide_eq_true (ht (HtTest.before (t - 1)) hb)
      have hat : a < t := h₂ a ha
      omega
  · push Not at h₁
    have hb : HtTest.after (t + 1) ∈ orthSet HSurvives S := by
      intro s hs
      have := h₁ s hs
      exact decide_eq_true (by omega)
    have hsurv : t + 1 ≤ t := of_decide_eq_true (ht (HtTest.after (t + 1)) hb)
    omega

/-- **THE TEMPORAL CHARACTERIZATION** — a set of heights is a behaviour of the height family IFF
it is convex. The biorthogonal closure over heights is CONVEXIFICATION; the behaviour lattice is
the interval lattice — exactly the until/since ("since lo until hi") shape. -/
theorem height_behaviour_iff_convex (S : Set Nat) :
    IsBehaviour HSurvives S ↔ Convex S :=
  ⟨behaviour_convex, convex_isBehaviour⟩

/-- **COMPLETENESS — every height behaviour IS a window guard of the deployed family.** Beyond
the literal case (where guards were behaviours but behaviours were not characterized): here the
behaviours are EXACTLY the guard-expressible classes — `∅` (the contradictory window), a window
`[sInf S, sSup S]`, or a pure vesting gate `[sInf S, ∞)`. The until/since algebra is complete for
its own orthogonality. -/
theorem behaviour_is_window_guard {S : Set Nat} (hS : IsBehaviour HSurvives S) :
    ∃ g : List HtTest, S = listAdm hsurvB g := by
  rcases Set.eq_empty_or_nonempty S with rfl | hne
  · refine ⟨[.after 1, .before 0], ?_⟩
    ext t
    constructor
    · intro h
      exact h.elim
    · intro hall
      exfalso
      rw [mem_listAdm_iff] at hall
      have h1 : 1 ≤ t := of_decide_eq_true (hall (HtTest.after 1) (by simp))
      have h2 : t ≤ 0 := of_decide_eq_true (hall (HtTest.before 0) (by simp))
      omega
  · have hcv := behaviour_convex hS
    have hmin : sInf S ∈ S := Nat.sInf_mem hne
    by_cases hbdd : BddAbove S
    · have hmax : sSup S ∈ S := Nat.sSup_mem hne hbdd
      refine ⟨[.after (sInf S), .before (sSup S)], ?_⟩
      ext t
      rw [mem_listAdm_iff]
      constructor
      · intro htS r hr
        rcases (by simpa using hr :
            r = HtTest.after (sInf S) ∨ r = HtTest.before (sSup S)) with rfl | rfl
        · exact decide_eq_true (Nat.sInf_le htS)
        · exact decide_eq_true (le_csSup hbdd htS)
      · intro hall
        have h1 : hsurvB t (.after (sInf S)) = true := hall (HtTest.after (sInf S)) (by simp)
        have h2 : hsurvB t (.before (sSup S)) = true := hall (HtTest.before (sSup S)) (by simp)
        exact hcv _ hmin _ hmax t (of_decide_eq_true h1) (of_decide_eq_true h2)
    · refine ⟨[.after (sInf S)], ?_⟩
      ext t
      rw [mem_listAdm_iff]
      constructor
      · intro htS r hr
        rcases (by simpa using hr : r = HtTest.after (sInf S)) with rfl
        exact decide_eq_true (Nat.sInf_le htS)
      · intro hall
        have h1 : hsurvB t (.after (sInf S)) = true := hall (HtTest.after (sInf S)) (by simp)
        obtain ⟨c, hc, htc⟩ := (not_bddAbove_iff.mp hbdd) t
        exact hcv _ hmin _ hc t (of_decide_eq_true h1) (le_of_lt htc)

/-- The window guard `[after lo, before hi]` — dregg1's `TemporalGate`, in test form. -/
def windowGuard (lo hi : Nat) : List HtTest := [.after lo, .before hi]

/-- Every window class is a behaviour (the S2-style positive, instantiated). -/
theorem window_class_is_behaviour (lo hi : Nat) :
    IsBehaviour HSurvives (listAdm hsurvB (windowGuard lo hi)) :=
  listAdm_isBehaviour hsurvB _

/-- The window guard denotes the LIVE `withinWindow` atom — same Bool verdict at every height. -/
theorem window_guard_denotes (lo hi ht : Nat) (rec : Value) :
    ht ∈ listAdm hsurvB (windowGuard lo hi)
      ↔ (TemporalAtom.withinWindow lo hi).eval ht rec = true := by
  rw [mem_listAdm_iff]
  show _ ↔ (decide (lo ≤ ht) && decide (ht ≤ hi)) = true
  rw [Bool.and_eq_true]
  constructor
  · intro h
    exact ⟨h (HtTest.after lo) (by simp [windowGuard]), h (HtTest.before hi) (by simp [windowGuard])⟩
  · rintro ⟨h1, h2⟩ r hr
    rcases (by simpa [windowGuard] using hr :
        r = HtTest.after lo ∨ r = HtTest.before hi) with rfl | rfl
    · exact h1
    · exact h2

/-- Non-vacuity (TRUE polarity): the `[10,20]` window behaviour is proper. -/
theorem window_proper :
    (15 : Nat) ∈ listAdm hsurvB (windowGuard 10 20)
      ∧ (5 : Nat) ∉ listAdm hsurvB (windowGuard 10 20)
      ∧ IsBehaviour HSurvives (listAdm hsurvB (windowGuard 10 20)) := by
  refine ⟨?_, ?_, window_class_is_behaviour 10 20⟩
  · show (windowGuard 10 20).all (hsurvB 15) = true
    decide
  · show ¬ (windowGuard 10 20).all (hsurvB 5) = true
    decide

/-- The gap candidate `{0, 2}`. -/
def gapSet : Set Nat := {0, 2}

/-- The closure of `{0, 2}` captures the midpoint `1`: every half-line test both endpoints
survive, the midpoint survives. -/
theorem gap_closure_adds_midpoint : 1 ∈ biorth HSurvives gapSet := by
  intro r hr
  have h0 := hr 0 (Or.inl rfl)
  have h2 := hr 2 (Or.inr rfl)
  cases r with
  | after h =>
      have := of_decide_eq_true h0
      exact decide_eq_true (by omega)
  | before h =>
      have := of_decide_eq_true h2
      exact decide_eq_true (by omega)

/-- Non-vacuity (FALSE polarity): `{0, 2}` is NOT a behaviour — the closure convexifies. -/
theorem gap_not_behaviour : ¬ IsBehaviour HSurvives gapSet := by
  intro h
  have h1 : (1 : Nat) ∈ gapSet := h ▸ gap_closure_adds_midpoint
  rcases h1 with h1 | h1 <;> exact absurd h1 (by decide)

/-- The vesting (`after`) classes are UPWARD-closed — the order-theoretic face of the landed
`AG`-permanence reading (`afterHeight_iff_AG`): up-closed behaviours are the "once open, open
forever" classes. -/
theorem after_class_upward {h t t' : Nat} (hle : t ≤ t')
    (ht : t ∈ listAdm hsurvB [HtTest.after h]) :
    t' ∈ listAdm hsurvB [HtTest.after h] := by
  rw [mem_listAdm_iff] at *
  intro r hr
  rcases (by simpa using hr : r = HtTest.after h) with rfl
  have := of_decide_eq_true (ht (HtTest.after h) (by simp))
  exact decide_eq_true (by omega)

end Ht

/-! ## §2 — TEMPORAL, trace level: the until/since MODAL content is a time-step correlation. -/

namespace Tm

/-- **The write-once (monotone-register) step discipline** — the correlation the U/S modal layer
rides: `flagClock.Step`'s second conjunct (`TemporalAlgebra2.lean:172`), as a CLASS of observed
flag steps `(pre, post)`. `sinceEvent_iff_AG` ("once closed, closed forever") is true BECAUSE
every step lands here. -/
def Mono : Set (Bool × Bool) := {p | p.1 = true → p.2 = true}

/-- **THE OBSTRUCTION, fully general** — under ANY rectangular (per-time-point) test family,
over ANY test type, the write-once discipline is NOT a behaviour: `(true,true)` and
`(false,false)` are monotone steps, and every rectangular biorthogonal must contain the mixed
corner `(true,false)` — the forbidden flip-back. Per-point tests are structurally blind to the
step correlation, exactly as per-component tests were blind to `Σδ`. -/
theorem writeOnce_not_behaviour_rectangular
    {R : Type*} (perp : Bool × Bool → R → Prop) (hrect : Rectangular perp) :
    ¬ IsBehaviour perp Mono := by
  intro h
  have h1 : ((true, true) : Bool × Bool) ∈ Mono := fun _ => rfl
  have h2 : ((false, false) : Bool × Bool) ∈ Mono := fun hc => hc
  have hmix : ((true, false) : Bool × Bool) ∈ biorth perp Mono :=
    rect_mix_in_biorth hrect h1 h2
  rw [show biorth perp Mono = Mono from h] at hmix
  exact Bool.false_ne_true (hmix rfl)

/-- The canonical per-point instance: pin tests on each endpoint (the pre-flag reading and the
post-flag reading, paired componentwise — the time-shape of `cavPairPerp`). -/
theorem writeOnce_not_behaviour_pointwise :
    ¬ IsBehaviour (fun (p r : Bool × Bool) => p.1 = r.1 ∧ p.2 = r.2) Mono :=
  writeOnce_not_behaviour_rectangular _ (prodPerp_rectangular (· = ·) (· = ·))

/-- **The step test family**: the two point readings PLUS the one relational observable — the
TRANSITION reading `stepOk` (survive iff the step does not flip back), the temporal analogue of
the `Σδ` comparator. -/
inductive StepTest where
  /-- the step observable: no `true → false` flip-back. -/
  | stepOk
  /-- point reading of the pre-flag. -/
  | preIs (b : Bool)
  /-- point reading of the post-flag. -/
  | postIs (b : Bool)
  deriving Repr, DecidableEq

/-- The Bool evaluator. -/
def ssurvB (p : Bool × Bool) : StepTest → Bool
  | .stepOk   => !p.1 || p.2
  | .preIs b  => p.1 == b
  | .postIs b => p.2 == b

/-- `p ⊥ r` over flag steps. Decidable. -/
def SSurvives (p : Bool × Bool) (r : StepTest) : Prop := ssurvB p r = true

instance (p : Bool × Bool) (r : StepTest) : Decidable (SSurvives p r) :=
  inferInstanceAs (Decidable (ssurvB p r = true))

/-- **The discipline IS an orthogonal**: `Mono = {stepOk}^⊥` — one relational test carves it. -/
theorem mono_eq_coOrth : Mono = coOrthSet SSurvives {StepTest.stepOk} := by
  ext p
  constructor
  · intro hp r hr
    have hr' : r = .stepOk := hr
    subst hr'
    show (!p.1 || p.2) = true
    cases hb : p.1 with
    | false => simp
    | true  => simp [hp hb]
  · intro h hp1
    have hs : (!p.1 || p.2) = true := h .stepOk rfl
    rw [hp1] at hs
    simpa using hs

/-- **THE RECOVERY** — with the step observable fielded, the write-once discipline is a
behaviour. Time-correlation recovered from orthogonality, exactly the conservation mechanism. -/
theorem writeOnce_is_behaviour : IsBehaviour SSurvives Mono := by
  rw [mono_eq_coOrth]
  exact coOrth_isBehaviour SSurvives _

/-- Non-vacuity (TRUE polarity): the behaviour is proper — the flip is in, the flip-back is out. -/
theorem mono_proper :
    ((false, true) : Bool × Bool) ∈ Mono
      ∧ ((true, false) : Bool × Bool) ∉ Mono
      ∧ IsBehaviour SSurvives Mono :=
  ⟨fun _ => rfl, fun h => Bool.false_ne_true (h rfl), writeOnce_is_behaviour⟩

/-- The stutter steps. -/
def stt : Bool × Bool := (true, true)
/-- See `stt`. -/
def sff : Bool × Bool := (false, false)
/-- The genuine flip the closure adds to the stutter pair. -/
def sflip : Bool × Bool := (false, true)

/-- Non-vacuity (FALSE polarity): the stutter pair `{(true,true), (false,false)}` is not a
behaviour in THIS family either — its closure adds the flip (the only test both survive is
`stepOk`, and the flip survives it). The closure does real work over steps too. -/
theorem step_pair_closure_grows :
    sflip ∈ biorth SSurvives ({stt, sff} : Set (Bool × Bool))
      ∧ sflip ∉ ({stt, sff} : Set (Bool × Bool))
      ∧ ¬ IsBehaviour SSurvives ({stt, sff} : Set (Bool × Bool)) := by
  have hmem : sflip ∈ biorth SSurvives ({stt, sff} : Set (Bool × Bool)) := by
    intro r hr
    have h1 : SSurvives stt r := hr stt (Or.inl rfl)
    have h2 : SSurvives sff r := hr sff (Or.inr rfl)
    cases r with
    | stepOk => decide
    | preIs b =>
        have h1' : (true == b) = true := h1
        have h2' : (false == b) = true := h2
        rw [beq_iff_eq] at h1' h2'
        rw [← h1'] at h2'
        exact absurd h2' (by decide)
    | postIs b =>
        have h1' : (true == b) = true := h1
        have h2' : (false == b) = true := h2
        rw [beq_iff_eq] at h1' h2'
        rw [← h1'] at h2'
        exact absurd h2' (by decide)
  have hnot : sflip ∉ ({stt, sff} : Set (Bool × Bool)) := by
    intro h
    rcases h with h | h
    · exact absurd (congrArg Prod.fst h) (by decide)
    · exact absurd (congrArg Prod.snd h) (by decide)
  exact ⟨hmem, hnot, fun h => hnot (h ▸ hmem)⟩

/-- Every abstract `flagClock` step lands in the discipline (definitional: the monotone conjunct
IS `Mono`-membership). -/
theorem flagClock_step_in_Mono {s t : Nat × Bool} (h : flagClock.Step s t) :
    (s.2, t.2) ∈ Mono :=
  h.2

/-- **THE EXECUTOR WELD** — a committed close write (the real `stateStepGuarded`, non-zero value
to the flag slot) has its observed flag transition land in the write-once BEHAVIOUR: via the
landed `committed_flip_write_steps_flagClock`, the running executor's every U/S-relevant step is
membership in a biorthogonally-closed class — once the test language carries the step
observable. -/
theorem committed_close_lands_in_behaviour {s s' : RecChainedState} {flagField : FieldName}
    {actor target : CellId} {n : Int}
    (h : stateStepGuarded s flagField actor target n = some s') (hn : n ≠ 0) :
    (flagOf flagField (s.kernel.cell target), flagOf flagField (s'.kernel.cell target)) ∈ Mono
      ∧ IsBehaviour SSurvives Mono :=
  ⟨flagClock_step_in_Mono (committed_flip_write_steps_flagClock h hn),
   writeOnce_is_behaviour⟩

/-- **The until-gate's refutations ARE the since-witnesses** (via `until_since_complement`): a
record refutes "admitted until E" exactly by exhibiting the post-E (since) witness. The orthogonal
of the until class is generated by the since side — the U/S partition, read as orthogonality. -/
theorem until_refusal_is_since_witness (f : FieldName) (rec : Value) :
    (EventAtom.untilEvent f).eval rec = false
      ↔ (EventAtom.sinceEvent f).eval rec = true := by
  rw [until_since_complement]
  cases (EventAtom.sinceEvent f).eval rec <;> simp

end Tm

/-! ## §3 — EPISTEMIC: orthogonality over who-can-refute (a refutation = an unanswerable
challenge). -/

namespace Ep

open Dregg2.Laws
open Dregg2.Authority.Epistemic

universe u v w

variable {Agent : Type u} {P : Type v} {W : Type w}

/-- **The challenge orthogonality**: an EVIDENCE STATE `e` (the witnesses one party can exhibit —
one agent's pocket, or the finalized ledger) survives the challenge `φ` iff it can produce a
discharging witness. The same `Verifiable`/`Discharged` seam `Epistemic.Knows` is built on. -/
def answerPerp [Verifiable P W] (e : W → Prop) (φ : P) : Prop :=
  ∃ w : W, e w ∧ Discharged φ w

/-- The K-class of a statement: the evidence states that answer it — `{φ}^⊥`. -/
def KnowsClass [Verifiable P W] (φ : P) : Set (W → Prop) :=
  coOrthSet answerPerp {φ}

/-- **`Knows` IS orthogonality membership**: agent `a` knows `φ` iff its pocket lies in `{φ}^⊥`. -/
theorem knows_iff_mem_class [Verifiable P W] (pocket : Pocket Agent W) (a : Agent) (φ : P) :
    Knows pocket a φ ↔ pocket a ∈ KnowsClass φ := by
  constructor
  · rintro h r rfl
    exact h
  · intro h
    exact h φ rfl

/-- **Every K-class is a behaviour** (it is an orthogonal). One-party challenges suffice: K is
the trivially-closed rung, like the literal rectangles. -/
theorem knows_class_is_behaviour [Verifiable P W] (φ : P) :
    IsBehaviour (answerPerp (P := P) (W := W)) (KnowsClass φ) :=
  coOrth_isBehaviour _ _

/-- **`CommonAt` IS `Knows` OF THE LEDGER** — the C_G constructor is membership of the
finalized-at-`d` witness set in the SAME `{φ}^⊥`. Orthogonality classifies C's witness shape as
one existential over one (virtual) party; the floor law (`finalized_visible` — delivery,
partition-safety) is INVISIBLE to the testing relation. C is a behaviour for the trivial reason
K is; its distributed content lives elsewhere, honestly. -/
theorem common_iff_ledger_in_knows_class [Verifiable P W] (floor : FinalityFloor Agent W)
    (d : Nat) (φ : P) :
    CommonAt floor d φ ↔ floor.Finalized d ∈ KnowsClass φ := by
  constructor
  · rintro h r rfl
    exact h
  · intro h
    exact h φ rfl

/-- The E-orthogonality over FULL pockets: a challenge names WHO must answer and WHAT. -/
def epPerp [Verifiable P W] (pk : Pocket Agent W) (c : Agent × P) : Prop :=
  Knows pk c.1 c.2

/-- **`EveryoneKnows` IS orthogonality to the per-member challenge set** `{(a, φ) | a ∈ G}` —
hence a behaviour. Each challenge reads ONE member: E is rectangular over the group. -/
theorem everyone_iff_mem [Verifiable P W] (pk : Pocket Agent W) (G : List Agent) (φ : P) :
    EveryoneKnows pk G φ
      ↔ pk ∈ coOrthSet epPerp {c : Agent × P | c.1 ∈ G ∧ c.2 = φ} := by
  constructor
  · rintro h ⟨a, ψ⟩ ⟨ha, rfl⟩
    exact h a ha
  · intro h a ha
    exact h (a, φ) ⟨ha, rfl⟩

/-- Every E-class is a behaviour. -/
theorem everyone_class_is_behaviour [Verifiable P W] (G : List Agent) (φ : P) :
    IsBehaviour (epPerp (Agent := Agent) (P := P) (W := W))
      (coOrthSet epPerp {c : Agent × P | c.1 ∈ G ∧ c.2 = φ}) :=
  coOrth_isBehaviour _ _

/-- **E is the ADDITIVE `&`** — the two-member E-class is the behaviour MEET of the members'
K-classes (an instance of the landed `coOrth_union`): no correlation, just intersection. The
sharp contrast with D below. -/
theorem everyone_pair_is_meet [Verifiable P W] (a b : Agent) (φ : P) :
    coOrthSet (epPerp (Agent := Agent) (P := P) (W := W))
        {c : Agent × P | c.1 ∈ [a, b] ∧ c.2 = φ}
      = coOrthSet epPerp {(a, φ)} ∩ coOrthSet epPerp {(b, φ)} := by
  rw [← coOrth_union]
  congr 1
  ext ⟨x, ψ⟩
  simp only [Set.mem_setOf_eq, List.mem_cons, List.not_mem_nil, or_false,
    Set.mem_union, Set.mem_singleton_iff, Prod.mk.injEq]
  tauto

/-! ### The forced structure: challenge behaviours are evidence-MONOTONE; ignorance is not a type. -/

/-- Every behaviour of the challenge orthogonality is MONOTONE in exhibitable evidence: more
witnesses never destroy membership. (The attenuation dual on the epistemic side.) -/
theorem knows_behaviour_monotone [Verifiable P W] {B : Set (W → Prop)}
    (hB : IsBehaviour (answerPerp (P := P) (W := W)) B)
    {p q : W → Prop} (hpq : ∀ w, p w → q w) (hp : p ∈ B) : q ∈ B := by
  rw [← hB]
  intro r hr
  obtain ⟨w, hw, hd⟩ := hr p hp
  exact ⟨w, hpq w hw, hd⟩

/-- The empty evidence state. -/
def emptyEv : Nat → Prop := fun _ => False
/-- The full evidence state. -/
def fullEv : Nat → Prop := fun _ => True

/-- Non-vacuity (TRUE polarity): the K-class of `⟨5⟩` (over the live `Demo` verifier) is a
proper behaviour — the `{7}` pocket answers, the empty pocket cannot. -/
theorem knows_class_proper :
    (fun w : Nat => w = 7) ∈ KnowsClass (W := Nat) (⟨5⟩ : Demo.Stmt)
      ∧ emptyEv ∉ KnowsClass (W := Nat) (⟨5⟩ : Demo.Stmt)
      ∧ IsBehaviour (answerPerp (P := Demo.Stmt) (W := Nat))
          (KnowsClass (W := Nat) (⟨5⟩ : Demo.Stmt)) := by
  refine ⟨?_, ?_, knows_class_is_behaviour _⟩
  · rintro r rfl
    exact ⟨7, rfl, by decide⟩
  · intro h
    obtain ⟨w, hw, _⟩ := h ⟨5⟩ rfl
    exact hw

/-- The ignorance candidate: the evidence states that CANNOT answer `φ`. -/
def Ignorance (φ : Demo.Stmt) : Set (Nat → Prop) := {p | ¬ answerPerp p φ}

/-- **Non-vacuity (FALSE polarity): IGNORANCE IS NOT A BEHAVIOUR.** "Cannot answer `⟨5⟩`" holds
of the empty pocket and fails of the full one, so it is not evidence-monotone — but every
behaviour is (`knows_behaviour_monotone`). In a witness semantics, non-knowledge is not a type:
the closure floods it upward. -/
theorem ignorance_not_behaviour :
    ¬ IsBehaviour (answerPerp (P := Demo.Stmt) (W := Nat)) (Ignorance ⟨5⟩) := by
  intro h
  have hempty : emptyEv ∈ Ignorance ⟨5⟩ := by
    rintro ⟨w, hw, -⟩
    exact hw
  have hfull : fullEv ∉ Ignorance ⟨5⟩ := by
    intro hf
    exact hf ⟨7, trivial, by decide⟩
  exact hfull (knows_behaviour_monotone h (fun w _ => trivial) hempty)

/-- The E-class over the live `Demo` pockets is proper (via the landed `everyone_true` /
`everyone_false`), and a behaviour. -/
theorem everyone_class_proper :
    Demo.pock ∈ coOrthSet epPerp {c : Nat × Demo.Stmt | c.1 ∈ [0, 1] ∧ c.2 = (⟨5⟩ : Demo.Stmt)}
      ∧ Demo.pock ∉
          coOrthSet epPerp {c : Nat × Demo.Stmt | c.1 ∈ [0, 1] ∧ c.2 = (⟨8⟩ : Demo.Stmt)} :=
  ⟨(everyone_iff_mem Demo.pock [0, 1] (⟨5⟩ : Demo.Stmt)).mp Demo.everyone_true,
   fun h => Demo.everyone_false ((everyone_iff_mem Demo.pock [0, 1] (⟨8⟩ : Demo.Stmt)).mpr h)⟩

/-- The C-class over the live `Demo.toyFloor` is proper (via the landed `common_true` /
`common_false`), through the ledger-knowledge weld. -/
theorem common_class_proper :
    Demo.toyFloor.Finalized 0 ∈ KnowsClass (W := Nat) (⟨5⟩ : Demo.Stmt)
      ∧ Demo.toyFloor.Finalized 1 ∉ KnowsClass (W := Nat) (⟨5⟩ : Demo.Stmt) :=
  ⟨(common_iff_ledger_in_knows_class Demo.toyFloor 0 (⟨5⟩ : Demo.Stmt)).mp Demo.common_true,
   fun h => Demo.common_false
     ((common_iff_ledger_in_knows_class Demo.toyFloor 1 (⟨5⟩ : Demo.Stmt)).mpr h)⟩

/-! ### §3D — DISTRIBUTED knowledge: the tensor front (the conservation parallel, exact). -/

/-- The secret statement: "the shared secret is `val`". -/
structure SecStmt where
  val : Int
  deriving DecidableEq, Repr

instance : Verifiable SecStmt Int := ⟨fun s w => decide (w = s.val)⟩

/-- The verifier characterized. -/
theorem secDischarged_iff (s : SecStmt) (w : Int) : Discharged s w ↔ w = s.val := by
  show decide (w = s.val) = true ↔ _
  constructor
  · exact of_decide_eq_true
  · exact decide_eq_true

/-- The ADDITIVE 2-of-2 pool: combining = summing the shares (the simplest real threshold
scheme — secret `s` split as `(r, s − r)` with randomness `r`; reconstruction is the sum). -/
def sumPool : PoolOps Int := { combine := fun ws => ws.sum }

/-- The pool on a pair, computed. -/
theorem combine_pair (x y : Int) : sumPool.combine [x, y] = x + y := by
  simp [sumPool]

/-- Member `1` holds the first share, member `2` the second — each pocket is exactly its share. -/
def pockOf (m : Int × Int) : Pocket Nat Int :=
  fun i w => (i = 1 ∧ w = m.1) ∨ (i = 2 ∧ w = m.2)

/-- **The D-class over share PAIRS**: the pairs from which the 2-member federation
threshold-knows the secret `66` — the REAL `ThresholdKnows` (quorum + distinctness + pooled
reconstruction), instantiated at the additive pool. -/
def DClass : Set (Int × Int) :=
  {m | ThresholdKnows sumPool (pockOf m) [1, 2] 2 (⟨66⟩ : SecStmt)}

/-- A `⊆ [1,2]`, nodup, length-≥2 member list is `[1,2]` or `[2,1]`. -/
theorem pair_members {ms : List Nat} (hsub : ∀ a ∈ ms, a ∈ ([1, 2] : List Nat))
    (hnd : ms.Nodup) (hlen : 2 ≤ ms.length) : ms = [1, 2] ∨ ms = [2, 1] := by
  cases ms with
  | nil => simp at hlen
  | cons a t =>
    cases t with
    | nil => simp at hlen
    | cons b rest =>
      have ha : a = 1 ∨ a = 2 := by simpa using hsub a (by simp)
      have hb : b = 1 ∨ b = 2 := by simpa using hsub b (by simp)
      have hnd1 := List.nodup_cons.mp hnd
      have hab : a ≠ b := fun h => hnd1.1 (by simp [h])
      cases rest with
      | nil =>
          rcases ha with rfl | rfl <;> rcases hb with rfl | rfl
          · exact absurd rfl hab
          · exact Or.inl rfl
          · exact Or.inr rfl
          · exact absurd rfl hab
      | cons c cs =>
          have hc : c = 1 ∨ c = 2 := by simpa using hsub c (by simp)
          have hnd2 := List.nodup_cons.mp hnd1.2
          have hac : a ≠ c := fun h => hnd1.1 (by simp [h])
          have hbc : b ≠ c := fun h => hnd2.1 (by simp [h])
          rcases ha with rfl | rfl <;> rcases hb with rfl | rfl <;>
            rcases hc with rfl | rfl <;> omega

/-- **THE WELD — the real threshold rung, characterized**: the federation threshold-knows the
secret IFF the shares CORRELATE through the sharing — `m.1 + m.2 = 66`. Pooled knowledge IS an
affine correlation across the members, the same mathematical shape as conservation's `Σδ = 0`. -/
theorem threshold_iff_sum (m : Int × Int) :
    ThresholdKnows sumPool (pockOf m) [1, 2] 2 (⟨66⟩ : SecStmt) ↔ m.1 + m.2 = 66 := by
  constructor
  · rintro ⟨ms, sel, hsub, hnd, hlen, hpock, hdis⟩
    rcases pair_members hsub hnd hlen with rfl | rfl
    · have hp1 := hpock 1 (by simp)
      have hp2 := hpock 2 (by simp)
      rcases hp1 with ⟨-, h1⟩ | ⟨hc, -⟩
      · rcases hp2 with ⟨hc, -⟩ | ⟨-, h2⟩
        · omega
        · rw [secDischarged_iff] at hdis
          simp only [List.map_cons, List.map_nil] at hdis
          rw [combine_pair] at hdis
          have hd : sel 1 + sel 2 = 66 := hdis
          omega
      · omega
    · have hp1 := hpock 1 (by simp)
      have hp2 := hpock 2 (by simp)
      rcases hp1 with ⟨-, h1⟩ | ⟨hc, -⟩
      · rcases hp2 with ⟨hc, -⟩ | ⟨-, h2⟩
        · omega
        · rw [secDischarged_iff] at hdis
          simp only [List.map_cons, List.map_nil] at hdis
          rw [combine_pair] at hdis
          have hd : sel 2 + sel 1 = 66 := hdis
          omega
      · omega
  · intro h
    refine ⟨[1, 2], fun i => if i = 1 then m.1 else m.2,
      fun a ha => ha, by decide, by decide, ?_, ?_⟩
    · intro a ha
      rcases (by simpa using ha : a = 1 ∨ a = 2) with rfl | rfl
      · exact Or.inl ⟨rfl, by simp⟩
      · exact Or.inr ⟨rfl, by simp⟩
    · have hcomb : sumPool.combine ([1, 2].map fun i => if i = 1 then m.1 else m.2)
          = m.1 + m.2 := by
        simp [sumPool]
      rw [secDischarged_iff, hcomb]
      exact h

/-- The D-class IS the correlation class. -/
theorem DClass_eq_sum : DClass = {m : Int × Int | m.1 + m.2 = 66} :=
  Set.ext threshold_iff_sum

/-- **THE OBSTRUCTION, fully general** — under ANY rectangular per-member challenge family, over
ANY challenge type, distributed knowledge is NOT a behaviour: `(10,56)` and `(20,46)` both
reconstruct, the member-wise mix `(10,46)` does not (mismatched randomness). Per-member testing
is structurally blind to the correlation pooled knowledge IS — the D-front mirror of
`conservation_not_behaviour_rectangular`. -/
theorem distributed_not_behaviour_rectangular
    {R : Type*} (perp : Int × Int → R → Prop) (hrect : Rectangular perp) :
    ¬ IsBehaviour perp DClass := by
  intro h
  have h1 : ((10, 56) : Int × Int) ∈ DClass := by
    rw [DClass_eq_sum]
    show (10 : Int) + 56 = 66
    decide
  have h2 : ((20, 46) : Int × Int) ∈ DClass := by
    rw [DClass_eq_sum]
    show (20 : Int) + 46 = 66
    decide
  have hmix : ((10, 46) : Int × Int) ∈ biorth perp DClass :=
    rect_mix_in_biorth hrect h1 h2
  rw [show biorth perp DClass = DClass from h] at hmix
  rw [DClass_eq_sum] at hmix
  exact absurd (hmix : (10 : Int) + 46 = 66) (by decide)

/-- The live instance: PAIRS of one-member challenges (each member separately challenged with a
statement its own share must discharge — the verbatim `Discharged`, componentwise). -/
def memberPerp (m : Int × Int) (r : SecStmt × SecStmt) : Prop :=
  Discharged r.1 m.1 ∧ Discharged r.2 m.2

theorem memberPerp_rectangular : Rectangular memberPerp :=
  fun _ _ _ ha hb => ⟨ha.1, hb.2⟩

/-- **Per-member challenges cannot see distributed knowledge.** -/
theorem distributed_not_behaviour_member_challenges : ¬ IsBehaviour memberPerp DClass :=
  distributed_not_behaviour_rectangular memberPerp memberPerp_rectangular

/-- **The composite challenge family**: the per-member challenges PLUS the one POOLED challenge —
"exhibit the reconstruction": `Verify` of the pool's combine, the deployed reconstruction test. -/
inductive PoolTest where
  /-- challenge member 1's share. -/
  | onShare1 (ψ : SecStmt)
  /-- challenge member 2's share. -/
  | onShare2 (ψ : SecStmt)
  /-- the pooled challenge: the COMBINED witness must discharge `ψ`. -/
  | pooled (ψ : SecStmt)

/-- The Bool evaluator (every arm the verbatim verifier; the pooled arm reads BOTH shares). -/
def psurvB (m : Int × Int) : PoolTest → Bool
  | .onShare1 ψ => Verifiable.Verify ψ m.1
  | .onShare2 ψ => Verifiable.Verify ψ m.2
  | .pooled ψ   => Verifiable.Verify ψ (sumPool.combine [m.1, m.2])

/-- `m ⊥ r` over share pairs. Decidable. -/
def PSurvives (m : Int × Int) (r : PoolTest) : Prop := psurvB m r = true

instance (m : Int × Int) (r : PoolTest) : Decidable (PSurvives m r) :=
  inferInstanceAs (Decidable (psurvB m r = true))

/-- The share challenges, characterized. -/
theorem psurv_share1_iff (m : Int × Int) (ψ : SecStmt) :
    PSurvives m (.onShare1 ψ) ↔ m.1 = ψ.val := by
  show Discharged ψ m.1 ↔ _
  rw [secDischarged_iff]

/-- See `psurv_share1_iff`. -/
theorem psurv_share2_iff (m : Int × Int) (ψ : SecStmt) :
    PSurvives m (.onShare2 ψ) ↔ m.2 = ψ.val := by
  show Discharged ψ m.2 ↔ _
  rw [secDischarged_iff]

/-- The pooled challenge, characterized: it reads the SUM — the correlating observable. -/
theorem psurv_pooled_iff (m : Int × Int) (ψ : SecStmt) :
    PSurvives m (.pooled ψ) ↔ m.1 + m.2 = ψ.val := by
  show Discharged ψ (sumPool.combine [m.1, m.2]) ↔ _
  rw [combine_pair, secDischarged_iff]

/-- **D IS an orthogonal**: `DClass = {pooled ⟨66⟩}^⊥` — the one reconstruction challenge carves
the distributed-knowledge class exactly. -/
theorem DClass_eq_coOrth :
    DClass = coOrthSet PSurvives {PoolTest.pooled ⟨66⟩} := by
  rw [DClass_eq_sum]
  ext m
  constructor
  · intro hm r hr
    have hr' : r = .pooled ⟨66⟩ := hr
    subst hr'
    exact (psurv_pooled_iff m ⟨66⟩).mpr hm
  · intro h
    exact (psurv_pooled_iff m ⟨66⟩).mp (h (.pooled ⟨66⟩) rfl)

/-- **THE RECOVERY** — with the pooled challenge fielded, distributed knowledge IS a behaviour. -/
theorem distributed_is_behaviour : IsBehaviour PSurvives DClass := by
  rw [DClass_eq_coOrth]
  exact coOrth_isBehaviour PSurvives _

/-- The single-share class (one fixed randomness reading). -/
def ShareIs (r : Int) : Set Int := {x | x = r}

/-- D is exactly the union of the MATCHED-RANDOMNESS pre-tensors: a reconstructing pair is two
shares of the SAME sharing — `(r, 66 − r)` for some randomness `r`. The index `r` plays the role
the matched delta `k` played for `move`. -/
theorem dclass_eq_union_matched :
    DClass = ⋃ r : Int, ShareIs r ×ˢ ShareIs (66 - r) := by
  rw [DClass_eq_sum]
  ext m
  simp only [Set.mem_setOf_eq, Set.mem_iUnion, Set.mem_prod, ShareIs]
  constructor
  · intro h
    exact ⟨m.1, rfl, by omega⟩
  · rintro ⟨r, h1, h2⟩
    omega

/-- Each matched-randomness tensor lands inside D (closure cannot escape the behaviour). -/
theorem matched_tensor_subset_distributed (r : Int) :
    tensor PSurvives (ShareIs r) (ShareIs (66 - r)) ⊆ DClass := by
  have hsub : ShareIs r ×ˢ ShareIs (66 - r) ⊆ DClass := by
    rw [DClass_eq_sum]
    rintro ⟨a, b⟩ ⟨h1, h2⟩
    have h1' : a = r := h1
    have h2' : b = 66 - r := h2
    show a + b = 66
    omega
  have hmono := biorth_mono PSurvives hsub
  rw [show biorth PSurvives DClass = DClass from distributed_is_behaviour] at hmono
  exact hmono

/-- **D IS the behaviour generated by the matched tensors**: `DClass = (⋃ᵣ Δᵣ ⊙ Δ₆₆₋ᵣ)^⊥⊥` —
the `⊗`-decomposition of pooled knowledge, exact. -/
theorem dclass_eq_closure_of_matched_tensors :
    DClass = biorth PSurvives (⋃ r : Int, ShareIs r ×ˢ ShareIs (66 - r)) := by
  rw [← dclass_eq_union_matched]
  exact distributed_is_behaviour.symm

/-- Non-vacuity (TRUE polarity): D is a proper behaviour. -/
theorem distributed_proper :
    ((10, 56) : Int × Int) ∈ DClass
      ∧ ((10, 46) : Int × Int) ∉ DClass
      ∧ IsBehaviour PSurvives DClass := by
  refine ⟨?_, ?_, distributed_is_behaviour⟩
  · rw [DClass_eq_sum]
    show (10 : Int) + 56 = 66
    decide
  · rw [DClass_eq_sum]
    intro h
    exact absurd (h : (10 : Int) + 46 = 66) (by decide)

/-- The reconstructing candidate pair's first member. -/
def dp : Int × Int := (10, 56)
/-- A second reconstructing pair (different randomness). -/
def dq : Int × Int := (20, 46)
/-- A re-paired sharing the closure adds (still reconstructing — consistent with the behaviour). -/
def drep : Int × Int := (0, 66)

/-- Non-vacuity (FALSE polarity): the two-element reconstructing candidate `{dp, dq}` is not a
behaviour in the COMPOSITE family either — its closure adds further matched sharings (every
challenge both survive is sum-reading; `(0,66)` reads the same sum). The closure does real work
here too, and what it adds is reconstruction-compatible, never more. -/
theorem dpair_closure_grows :
    drep ∈ biorth PSurvives ({dp, dq} : Set (Int × Int))
      ∧ drep ∉ ({dp, dq} : Set (Int × Int))
      ∧ ¬ IsBehaviour PSurvives ({dp, dq} : Set (Int × Int)) := by
  have hmem : drep ∈ biorth PSurvives ({dp, dq} : Set (Int × Int)) := by
    intro r hr
    have h1 : PSurvives dp r := hr dp (Or.inl rfl)
    have h2 : PSurvives dq r := hr dq (Or.inr rfl)
    cases r with
    | onShare1 ψ =>
        have e1 : (10 : Int) = ψ.val := (psurv_share1_iff dp ψ).mp h1
        have e2 : (20 : Int) = ψ.val := (psurv_share1_iff dq ψ).mp h2
        exact absurd (e1.trans e2.symm) (by decide)
    | onShare2 ψ =>
        have e1 : (56 : Int) = ψ.val := (psurv_share2_iff dp ψ).mp h1
        have e2 : (46 : Int) = ψ.val := (psurv_share2_iff dq ψ).mp h2
        exact absurd (e1.trans e2.symm) (by decide)
    | pooled ψ =>
        have e1 : (10 : Int) + 56 = ψ.val := (psurv_pooled_iff dp ψ).mp h1
        rw [psurv_pooled_iff]
        show (0 : Int) + 66 = ψ.val
        omega
  have hnot : drep ∉ ({dp, dq} : Set (Int × Int)) := by
    intro h
    rcases h with h | h
    · have h' : (0 : Int) = 10 := congrArg Prod.fst h
      exact absurd h' (by decide)
    · have h' : (0 : Int) = 20 := congrArg Prod.fst h
      exact absurd h' (by decide)
  exact ⟨hmem, hnot, fun h => hnot (h ▸ hmem)⟩

/-- **D without K, on the same pair**: the federation distributedly knows the secret while NO
single member does — each pocket holds one share, and a lone share never discharges. The
correlation IS the knowledge; that is exactly why no rectangular (single-member) challenge family
can carve the class. -/
theorem d_without_k :
    ((10, 56) : Int × Int) ∈ DClass
      ∧ ∀ i, ¬ Knows (pockOf (10, 56)) i (⟨66⟩ : SecStmt) := by
  refine ⟨distributed_proper.1, ?_⟩
  rintro i ⟨w, hp, hd⟩
  rw [secDischarged_iff] at hd
  rcases hp with ⟨-, rfl⟩ | ⟨-, rfl⟩
  · exact absurd (hd : (10 : Int) = 66) (by decide)
  · exact absurd (hd : (56 : Int) = 66) (by decide)

/-- **THE D-FRONT HEADLINE — the exact mirror of `linearity_recovered_from_orthogonality`.**
(1) With the pooled reconstruction challenge fielded, DISTRIBUTED KNOWLEDGE IS A BEHAVIOUR;
(2) it is EXACTLY the closure of the matched-randomness tensors — pooled knowledge decomposes
through `⊗`, indexed by the sharing randomness; (3) NO rectangular (per-member) challenge
family, over ANY challenge type, can carve it. Distributed knowledge is recovered from
orthogonality IFF the challenges may correlate the members — D_G needs the tensor exactly as
conservation does. -/
theorem distributed_knowledge_recovered_from_orthogonality :
    IsBehaviour PSurvives DClass
      ∧ DClass = biorth PSurvives (⋃ r : Int, ShareIs r ×ˢ ShareIs (66 - r))
      ∧ ∀ {R : Type} (perp : Int × Int → R → Prop), Rectangular perp → ¬ IsBehaviour perp DClass :=
  ⟨distributed_is_behaviour, dclass_eq_closure_of_matched_tensors,
   fun perp h => distributed_not_behaviour_rectangular perp h⟩

end Ep

/-! ## §4 — THE SYNTHESIS: correlation classifies the guard family. -/

/-- **`correlation_classifies_the_family` — THE PATTERN, packaged.** Across the three
non-trivial fronts, ONE two-sided shape: the class is NOT a behaviour under any rectangular
(one-component) test family — all three negatives are instances of the single generic mix law
`rect_mix_in_biorth` — and IS a behaviour the moment the family's one correlating observable is
fielded: the step reading for time (write-once), the `Σδ` reading for resources (conservation,
re-cited from `BiorthTensor`), the pooled reconstruction for distributed knowledge. The trivial
guards (literal/order, height points, K/E/C) are exactly the one-component ones. Biorthogonality
is load-bearing precisely where correlation matters, and the correlation TYPE — time-adjacency /
resource-sum / shared-randomness — classifies the family. -/
theorem correlation_classifies_the_family :
    -- TEMPORAL: correlation across adjacent time-steps
    ((∀ {R : Type} (perp : Bool × Bool → R → Prop), Rectangular perp → ¬ IsBehaviour perp Tm.Mono)
        ∧ IsBehaviour Tm.SSurvives Tm.Mono)
    -- RESOURCE: correlation across the paired writes (the BiorthTensor verdict)
    ∧ ((∀ {R : Type} (perp : Mv.Move → R → Prop), Rectangular perp → ¬ IsBehaviour perp Mv.Cons)
        ∧ IsBehaviour Mv.MSurvives Mv.Cons)
    -- EPISTEMIC-D: correlation across the members (the shared randomness)
    ∧ ((∀ {R : Type} (perp : Int × Int → R → Prop), Rectangular perp → ¬ IsBehaviour perp Ep.DClass)
        ∧ IsBehaviour Ep.PSurvives Ep.DClass) :=
  ⟨⟨fun perp h => Tm.writeOnce_not_behaviour_rectangular perp h, Tm.writeOnce_is_behaviour⟩,
   ⟨fun perp h => Mv.conservation_not_behaviour_rectangular perp h, Mv.conservation_is_behaviour⟩,
   ⟨fun perp h => Ep.distributed_not_behaviour_rectangular perp h, Ep.distributed_is_behaviour⟩⟩

/-! ## §5 — Computational spot-checks (both polarities, executable). -/

-- height tests compute, both ways:
#guard Ht.hsurvB 150 (.after 100)
#guard !(Ht.hsurvB 50 (.after 100))
#guard Ht.hsurvB 150 (.before 200)
#guard !(Ht.hsurvB 250 (.before 200))
-- the step observable separates the flip-back from the flip:
#guard Tm.ssurvB (false, true) .stepOk
#guard !(Tm.ssurvB (true, false) .stepOk)
#guard Tm.ssurvB (true, true) .stepOk
-- the pooled challenge separates matched from mismatched sharings:
#guard Ep.psurvB (10, 56) (.pooled ⟨66⟩)
#guard !(Ep.psurvB (10, 46) (.pooled ⟨66⟩))
-- a lone share never answers the secret challenge:
#guard !(Ep.psurvB (10, 56) (.onShare1 ⟨66⟩))

/-! ## §6 — Axiom hygiene. -/

-- §1 temporal point level: behaviours + the installed-gate welds + the characterization
#assert_axioms Ht.temporal_guard_is_behaviour
#assert_axioms Ht.event_guard_is_behaviour
#assert_axioms Ht.temporalAtomsAdmit_is_orthogonality
#assert_axioms Ht.eventAtomsAdmit_is_orthogonality
#assert_axioms Ht.htTest_denotes
#assert_axioms Ht.height_behaviour_iff_convex
#assert_axioms Ht.behaviour_is_window_guard
#assert_axioms Ht.window_class_is_behaviour
#assert_axioms Ht.window_guard_denotes
#assert_axioms Ht.window_proper
#assert_axioms Ht.gap_closure_adds_midpoint
#assert_axioms Ht.gap_not_behaviour
#assert_axioms Ht.after_class_upward
-- §2 temporal trace level: obstruction + recovery + welds
#assert_axioms Tm.writeOnce_not_behaviour_rectangular
#assert_axioms Tm.writeOnce_not_behaviour_pointwise
#assert_axioms Tm.mono_eq_coOrth
#assert_axioms Tm.writeOnce_is_behaviour
#assert_axioms Tm.mono_proper
#assert_axioms Tm.step_pair_closure_grows
#assert_axioms Tm.flagClock_step_in_Mono
#assert_axioms Tm.committed_close_lands_in_behaviour
#assert_axioms Tm.until_refusal_is_since_witness
-- §3 epistemic: K/E/C welds + the forced monotonicity + ignorance
#assert_axioms Ep.knows_iff_mem_class
#assert_axioms Ep.knows_class_is_behaviour
#assert_axioms Ep.common_iff_ledger_in_knows_class
#assert_axioms Ep.everyone_iff_mem
#assert_axioms Ep.everyone_class_is_behaviour
#assert_axioms Ep.everyone_pair_is_meet
#assert_axioms Ep.knows_behaviour_monotone
#assert_axioms Ep.knows_class_proper
#assert_axioms Ep.ignorance_not_behaviour
#assert_axioms Ep.everyone_class_proper
#assert_axioms Ep.common_class_proper
-- §3D the distributed front
#assert_axioms Ep.threshold_iff_sum
#assert_axioms Ep.distributed_not_behaviour_rectangular
#assert_axioms Ep.distributed_not_behaviour_member_challenges
#assert_axioms Ep.DClass_eq_coOrth
#assert_axioms Ep.distributed_is_behaviour
#assert_axioms Ep.dclass_eq_union_matched
#assert_axioms Ep.matched_tensor_subset_distributed
#assert_axioms Ep.dclass_eq_closure_of_matched_tensors
#assert_axioms Ep.distributed_proper
#assert_axioms Ep.dpair_closure_grows
#assert_axioms Ep.d_without_k
#assert_axioms Ep.distributed_knowledge_recovered_from_orthogonality
-- §4 the synthesis
#assert_axioms correlation_classifies_the_family

end Dregg2.Calculus.Biorth
