val _ = load "traversalRung3Theory"; val _ = load "traversalBytesBridgeTheory";
open traversalRung3Theory traversalBytesBridgeTheory;
fun tag th = let val (o_,a)=Tag.dest_tag (Thm.tag th) in "[oracles: "^String.concatWith "," o_^"] [axioms: "^String.concatWith "," a^"]" end;
val _ = print ("AAA backbone traversal_rung3_native = "^tag traversal_rung3_native^"\n");
val _ = print ("AAA linkA traversal_decisioncore_refines_spec = "^tag traversal_decisioncore_refines_spec^"\n");
val _ = print ("AAA faithful traversalIf_faithful = "^tag traversalIf_faithful^"\n");
val _ = print ("AAA L2 traversal_compile_prog_native = "^tag traversal_compile_prog_native^"\n");
val _ = print ("AAA theory-axioms traversalRung3 = "^Int.toString(length(axioms "traversalRung3"))^"\n");
val _ = print ("AAA theory-axioms traversalBytesBridge = "^Int.toString(length(axioms "traversalBytesBridge"))^"\n");
val c = concl traversalIf_faithful; val (lhs,rhs)=dest_eq c;
fun qn t = let val {Thy,Name,...}=dest_thy_const t in Thy^"$"^Name end;
val progn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="traversalProg") lhs);
val ifn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="traversalIf") rhs);
val _ = print ("AAA faithful-distinct prog="^progn^" if="^ifn^" DISTINCT="^Bool.toString(progn<>ifn)^"\n");
val bc = concl traversal_rung3_native; val (ante,conc)=dest_imp bc;
val _ = print ("AAA backbone antecedent-conjuncts = "^Int.toString(length(strip_conj ante))^"\n");
val _ = print ("AAA backbone concl-mentions-traversalProg = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="traversalProg")) conc)^"\n");
val _ = print ("AAA backbone ante-mentions-traversalBytes = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="traversalBytes")) ante)^"\n");
