#!/usr/bin/env bash
# relink-roottask.sh — assemble the executor's seL4-musl object set (out/exec-sel4/)
# for linking into the root-task PD.
#
# What needs what libc:
#   * The verified Lean CLOSURE (libdregg_lean_elf.a) is compiled -ffreestanding
#     against aarch64-unknown-none and calls only `lean_*` runtime entry points —
#     it is libc-AGNOSTIC. Reused as-is from executor-pd/out.
#   * The Lean RUNTIME archives (leanrt/Init/Std/Lean/mathlib/deps/leancpp) + GMP
#     call malloc/write/etc. Those resolve from `libc.a` AT LINK TIME — so swapping
#     in the seL4 musl libc.a (syscalls via __sysinfo) is what makes them route to
#     the PD handler. The runtime *objects* are reused from executor-pd/out; only
#     the libc they bind to changes (supplied by the root-task link, not here).
#   * The C STUB TUs (crypto/kernel/dead/init-stubs/aux-defs) + the driver are
#     recompiled here against the seL4 musl headers so any libc surface they touch
#     is the seL4 one.
#
# Output: out/exec-sel4/ holding the archive set build.rs links, plus demo-wire.o
# (the verified wire as a C string) and the recompiled stubs/driver objects.
#
# NOTE: this REUSES the executor-pd ELF archives (compiled with the homebrew musl
# g++ against stock musl headers). If the root-task link surfaces an undefined or
# mismatched stock-musl-internal symbol, the fallback is a full recompile of the
# runtime against the seL4 musl headers (the heavy path) — see WALL-roottask.md.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$HERE/.."
OUT="$ROOT/out"
EXEC_SEL4="$OUT/exec-sel4"
EPD="$ROOT/../executor-pd/out"          # the banked executor-pd artifacts
MUSLSEL4="$OUT/musl-sel4"               # provisioned by provision-sel4.sh
MBASE=/opt/homebrew/Cellar/aarch64-unknown-linux-musl/15.2.0/toolchain
GCC="$MBASE/bin/aarch64-linux-musl-gcc"
GXX="$MBASE/bin/aarch64-linux-musl-g++"
LEAN_INC="${LEAN_INC:-$(lean --print-prefix)/include}"

[ -d "$EPD" ] || { echo "[relink] FATAL: $EPD missing — run executor-pd's build first (cross-compile-closure.sh + the leanrt/leanlib/leancpp/gmp builds)"; exit 1; }
[ -d "$MUSLSEL4/include" ] || { echo "[relink] FATAL: seL4 musl not provisioned — run scripts/provision-sel4.sh"; exit 1; }
mkdir -p "$EXEC_SEL4"

# (1) Reuse the libc-agnostic closure + the runtime/GMP archives verbatim.
for a in libdregg_lean_elf.a \
         leanrt-elf/libleanrt_elf.a \
         leanlib-elf/libInit_elf.a leanlib-elf/libStd_elf.a leanlib-elf/libLean_elf.a \
         leanlib-elf/libmathlib_elf.a leanlib-elf/libBatteries_elf.a \
         leanlib-elf/libAesop_elf.a leanlib-elf/libQq_elf.a \
         leanlib-elf/libProofWidgets_elf.a leanlib-elf/libPlausible_elf.a \
         leanlib-elf/libImportGraph_elf.a leanlib-elf/libLeanSearchClient_elf.a \
         leanlib-elf/libMetatheory_elf.a \
         leancpp-elf/libleancpp_kernel_elf.a \
         gmp-elf/libgmp.a; do
  if [ -f "$EPD/$a" ]; then cp "$EPD/$a" "$EXEC_SEL4/$(basename "$a")"; else echo "[relink] WARN missing $a"; fi
done

# (2) The verified demo wire as a C string constant (out/exec-sel4/demo-wire.o).
WIRE_TXT="$EPD/demo-wire.txt"; [ -f "$WIRE_TXT" ] || WIRE_TXT="$OUT/demo-wire.txt"
if [ -f "$WIRE_TXT" ]; then
  python3 - "$WIRE_TXT" > "$EXEC_SEL4/demo-wire.c" <<'PY'
import sys, json
w = open(sys.argv[1]).read().strip()
# Emit as a C string literal with proper escaping.
print('const char dregg_demo_wire[] = ' + json.dumps(w) + ';')
PY
  "$GCC" -O2 -c "$EXEC_SEL4/demo-wire.c" -o "$EXEC_SEL4/demo-wire.o"
  echo "[relink] demo-wire.o ($(wc -c < "$WIRE_TXT" | tr -d ' ') bytes of verified wire)"
else
  echo "[relink] WARN: no demo-wire.txt; the turn will run on the empty/fail-closed wire"
fi

# (3) Recompile the C stub TUs + driver against the seL4 musl headers.
#     The stub *sources* are regenerated by executor-pd/scripts/link-probe.sh; we
#     reuse those generated .c files (in $EPD) and recompile them here.
recompile_c () { # <src> <out.o> [extra cc args...]
  # Match executor-pd/scripts/link-probe.sh: the C++ stubs that #include <lean/lean.h>
  # (which pulls libc++ <memory> via mimalloc.h) are HOSTED C++ (NOT -ffreestanding);
  # the seL4 musl headers replace only the libc surface, via -isystem.
  local src="$1" obj="$2"; shift 2
  "$GXX" -std=c++20 -O2 -isystem "$MUSLSEL4/include" -I "$LEAN_INC" "$@" \
    -c "$src" -o "$obj"
}
# (3a) libc-compat shim: GMP references `secure_getenv` (a glibc extension musl
#      lacks). In an seL4 PD with no environment, the correct answer is NULL (no
#      env var is set), so secure_getenv == "always not found". A single tiny TU.
cat > "$EXEC_SEL4/libc-compat.c" <<'EOF'
/* libc-compat.c — fill the libc gaps the seL4 static no-loader environment leaves
 * for GMP + the C++ exception runtime. */
#include <stddef.h>

/* GMP calls secure_getenv("GMP_*") to allow env overrides; an seL4 PD has no
 * environment, so NULL (not-set) is the faithful result. */
char *secure_getenv(const char *name) { (void)name; return NULL; }

/* dl_iterate_phdr override (musl's is `weak`). The libgcc C++ static ctors
 * (`frame_dummy` -> `__register_frame_info_bases`) call dl_iterate_phdr to find
 * `.eh_frame` for exception unwinding. On a STATIC seL4 binary there is no
 * dynamic loader, and musl's static dl_iterate_phdr dereferences a null phdr
 * list -> "vm fault on data at address 0" in dl_iterate_phdr (the boot wall
 * after the syscall-handler fix). This PD is built `panic = "abort"` (no Rust
 * unwinding) and the verified executor turn throws no C++ exception that needs an
 * unwind, so registering ZERO eh_frame is correct: return 0 (iterate nothing) so
 * the frame registration is a harmless no-op. (If C++ unwinding were ever needed,
 * the faithful fix is sel4_phdrs::locate_phdrs over the static image's own PT_LOAD
 * /PT_GNU_EH_FRAME — but the turn does not need it.) */
struct dl_phdr_info;
int dl_iterate_phdr(int (*cb)(struct dl_phdr_info *, size_t, void *), void *data) {
    (void)cb; (void)data;
    return 0;
}
EOF
"$GCC" -O2 -isystem "$MUSLSEL4/include" -c "$EXEC_SEL4/libc-compat.c" -o "$EXEC_SEL4/libc-compat.o"
[ -f "$EPD/crypto-stub.c" ] && "$GCC" -O2 -isystem "$MUSLSEL4/include" -c "$EPD/crypto-stub.c" -o "$EXEC_SEL4/crypto-stub.o"
[ -f "$EPD/kernel-stub.c" ] && "$GCC" -O2 -isystem "$MUSLSEL4/include" -c "$EPD/kernel-stub.c" -o "$EXEC_SEL4/kernel-stub.o"
[ -f "$EPD/dead-stub.c" ]   && recompile_c "$EPD/dead-stub.c"   "$EXEC_SEL4/dead-stub.o"
[ -f "$ROOT/../executor-pd/scripts/init-stubs.c" ] && recompile_c "$ROOT/../executor-pd/scripts/init-stubs.c" "$EXEC_SEL4/init-stubs.o"
[ -f "$ROOT/../executor-pd/scripts/aux-defs.c" ]   && recompile_c "$ROOT/../executor-pd/scripts/aux-defs.c"   "$EXEC_SEL4/aux-defs.o"

echo "[relink] out/exec-sel4 assembled:"
ls -la "$EXEC_SEL4" | awk 'NR>1{print "    ", $9, $5}'
echo "[relink] DONE. Now: cargo build the root-task PD (build.rs links these)."
