val _ = load "ipfRung3Theory"; val _ = load "ipfBytesBridgeTheory";
open ipfRung3Theory ipfBytesBridgeTheory;
fun tag th = let val (o_,a)=Tag.dest_tag (Thm.tag th) in "[oracles: "^String.concatWith "," o_^"] [axioms: "^String.concatWith "," a^"]" end;
val _ = print ("AAA backbone ipf_rung3_native = "^tag ipf_rung3_native^"\n");
val _ = print ("AAA linkA ipf_decisioncore_refines_spec = "^tag ipf_decisioncore_refines_spec^"\n");
val _ = print ("AAA faithful ipfIf_faithful = "^tag ipfIf_faithful^"\n");
val _ = print ("AAA L2 ipf_compile_prog_native = "^tag ipf_compile_prog_native^"\n");
val _ = print ("AAA theory-axioms ipfRung3 = "^Int.toString(length(axioms "ipfRung3"))^"\n");
val _ = print ("AAA theory-axioms ipfBytesBridge = "^Int.toString(length(axioms "ipfBytesBridge"))^"\n");
val c = concl ipfIf_faithful; val (lhs,rhs)=dest_eq c;
fun qn t = let val {Thy,Name,...}=dest_thy_const t in Thy^"$"^Name end;
val progn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="ipfProg") lhs);
val ifn = qn (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="ipfIf") rhs);
val _ = print ("AAA faithful-distinct prog="^progn^" if="^ifn^" DISTINCT="^Bool.toString(progn<>ifn)^"\n");
val bc = concl ipf_rung3_native; val (ante,conc)=dest_imp bc;
val _ = print ("AAA backbone antecedent-conjuncts = "^Int.toString(length(strip_conj ante))^"\n");
val _ = print ("AAA backbone concl-mentions-ipfProg = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="ipfProg")) conc)^"\n");
val _ = print ("AAA backbone ante-mentions-ipfBytes = "^Bool.toString(can (find_term (fn t=>is_const t andalso #Name(dest_thy_const t)="ipfBytes")) ante)^"\n");
