#!/usr/bin/env bash
# build-gate.sh — run THE GATE end to end: cross-build static LLVM 20.1.8 for
# aarch64-musl, then cross-build Mesa-lavapipe against it. The two together are the
# make-or-break for the lavapipe-in-a-PD render path (SEL4-RENDER-PATH.md Q2).
#
# Host prereqs (macOS arm64):
#   brew install aarch64-unknown-linux-musl llvm@20 cmake ninja glslang bison flex
#   python3 -m venv /tmp/mesa-build-venv && /tmp/mesa-build-venv/bin/pip install meson mako packaging pyyaml
#   /opt/homebrew/bin/python3 -m pip install --user --break-system-packages mako pyyaml packaging
# Sources (auto-fetched into /tmp by the steps below if absent): LLVM 20.1.8,
# Mesa 25.0.7, libdrm 2.4.120.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "== GATE 1/2: static LLVM 20.1.8 for aarch64-unknown-linux-musl =="
bash "$HERE/build-llvm-elf.sh"

echo "== libdrm (a linux-musl cross target re-enables Mesa's DRM dep the macOS"
echo "   rerun build never hits; supply a minimal cross-built libdrm) =="
# (kept inline here for reproducibility; see SEL4-RENDER-PATH.md §THE SPIKE RESULT)
SYSROOT=/opt/homebrew/opt/aarch64-unknown-linux-musl/toolchain/aarch64-unknown-linux-musl
if [ ! -f "$SYSROOT/lib/pkgconfig/libdrm.pc" ]; then
  echo "   libdrm not in the musl sysroot — cross-build it (libdrm-2.4.120):"
  echo "   meson setup … --cross-file out/aarch64-musl-cross.meson -Dintel/radeon/...=disabled --prefix $SYSROOT"
  echo "   (run scripts/build-libdrm.sh — generated by build-mesa-lavapipe-elf.sh on first run)"
fi

echo "== GATE 2/2: Mesa-lavapipe (libvulkan_lvp.so) against the cross LLVM =="
bash "$HERE/build-mesa-lavapipe-elf.sh"

echo "== GATE COMPLETE — see out/llvm-elf, out/mesa-elf, and SEL4-RENDER-PATH.md =="
