// driver-render.c — the in-PD lavapipe smoke: resolve the software-Vulkan ICD
// LOADER-LESS (vk_icdGetInstanceProcAddr, never the static vkXxx symbols, so the
// dispatchable-handle magic stays Mesa's), create an instance, enumerate the
// llvmpipe VkPhysicalDevice, create a logical device, and build a trivial COMPUTE
// pipeline from SPIR-V — which forces lavapipe's LLVM shader JIT to run, the path
// that exercises the W→X executable mapping the seL4-musl syscall handler now
// services (src/main.rs::handle_by_number MMAP/MPROTECT).
//
// This is the render-PD's `driver-sel4.c` analogue (executor-rootserver): the
// Rust root task calls dregg_render_pd_run() after installing the syscall handler.
// It prints what it observed over the seL4 debug serial and returns 0 on the full
// chain succeeding, or a precise nonzero STAGE code (so a stall names its rung).
//
// The full gpui-offscreen render (gpui::Scene -> wgpu -> this ICD -> RGBA ->
// ramfb) is the Rust-side path layered ON TOP of this smoke once the wgpu/gpui
// crates link for the target (WIRING.md "The render call"); this C smoke is the
// first thing that puts a JIT'd lavapipe inside the PD and proves the W→X mapping.

#include <stddef.h>
#include <stdint.h>

// The Vulkan + ICD headers ship in the Mesa source tree (no Vulkan SDK needed);
// build.rs adds -I/tmp/mesa-src/include (so `vulkan/...` + the `vk_video/...`
// chain vulkan_core.h pulls both resolve). We use the C ABI directly.
#include <vulkan/vulkan_core.h>
#include <vulkan/vk_icd.h>

// printf-free: the Rust PD routes fd 1/2 writes to the seL4 debug serial, so we
// use the libc the closure is linked against. Declare the few we call.
extern int   puts(const char *s);
extern int   printf(const char *fmt, ...);

// The Rust side's W→X counters (src/main.rs).
extern size_t dregg_render_pd_jit_exec_maps(void);
extern size_t dregg_render_pd_jit_wx_flips(void);

// The LLVM JIT target-registration lever/diagnostic (scripts/llvm-target-diag.c):
// drives LLVMInitializeAArch64Target* explicitly + prints the registry state the
// JIT's selectTarget will see. Driven before vkCreateDevice (the JIT-init wall).
extern int dregg_llvm_target_diag(void);

// The ICD's single loader-less entry point (vk_icd.h type), defined in
// libvulkan_lvp.so and linked in statically.
extern PFN_vkVoidFunction vk_icdGetInstanceProcAddr(VkInstance instance, const char *pName);
extern VkResult vk_icdNegotiateLoaderICDInterfaceVersion(uint32_t *pVersion);

// A minimal valid SPIR-V compute shader: `void main() {}` for local_size (1,1,1).
// Compiling this through the pipeline forces lavapipe's NIR->LLVM->machine-code
// JIT, which is the W→X exercise. (Generated by glslangValidator -V on an empty
// `#version 450\nlayout(local_size_x=1) in; void main(){}`; the canonical empty
// compute module. Kept inline so the PD needs no filesystem.)
static const uint32_t empty_comp_spv[] = {
    0x07230203, 0x00010000, 0x0008000a, 0x00000006,
    0x00000000, 0x00020011, 0x00000001, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0006000f, 0x00000005, 0x00000004, 0x6e69616d,
    0x00000000, 0x00000000, 0x00060010, 0x00000004,
    0x00000011, 0x00000001, 0x00000001, 0x00000001,
    0x00030003, 0x00000002, 0x000001c2, 0x00040005,
    0x00000004, 0x6e69616d, 0x00000000, 0x00020013,
    0x00000002, 0x00030021, 0x00000003, 0x00000002,
    0x00050036, 0x00000002, 0x00000004, 0x00000000,
    0x00000003, 0x000200f8, 0x00000005, 0x000100fd,
    0x00010038,
};

// Resolve a global proc (instance==NULL is valid for the global commands:
// vkCreateInstance, vkEnumerateInstanceVersion, ...).
#define GIPA(inst, name) ((PFN_##name) vk_icdGetInstanceProcAddr((inst), #name))

int dregg_render_pd_run(void) {
    // (0) Negotiate the loader<->ICD interface version (the loader-less protocol:
    //     we play the loader's role, asking the ICD for its version).
    uint32_t icd_ver = 0;
    if (vk_icdNegotiateLoaderICDInterfaceVersion(&icd_ver) != VK_SUCCESS) {
        puts("[driver] STAGE 0 FAIL: ICD interface negotiation");
        return 10;
    }
    printf("[driver] ICD interface version = %u (loader-less; lavapipe in-PD)\n", icd_ver);

    // (1) Resolve + call vkCreateInstance via the ICD proc-addr chain.
    PFN_vkCreateInstance pCreateInstance = GIPA(VK_NULL_HANDLE, vkCreateInstance);
    if (!pCreateInstance) {
        puts("[driver] STAGE 1 FAIL: vkCreateInstance not resolvable from the ICD");
        return 11;
    }
    VkApplicationInfo app = {
        .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
        .pApplicationName = "dregg-render-pd",
        .apiVersion = VK_API_VERSION_1_1,
    };
    VkInstanceCreateInfo ici = {
        .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
        .pApplicationInfo = &app,
    };
    VkInstance inst = VK_NULL_HANDLE;
    VkResult r = pCreateInstance(&ici, NULL, &inst);
    if (r != VK_SUCCESS || inst == VK_NULL_HANDLE) {
        printf("[driver] STAGE 1 FAIL: vkCreateInstance = %d\n", (int)r);
        return 12;
    }
    puts("[driver] vkCreateInstance OK — lavapipe VkInstance live in the PD");

    // (2) Enumerate the physical device(s): the llvmpipe VkPhysicalDevice.
    PFN_vkEnumeratePhysicalDevices pEnum = GIPA(inst, vkEnumeratePhysicalDevices);
    PFN_vkGetPhysicalDeviceProperties pProps = GIPA(inst, vkGetPhysicalDeviceProperties);
    if (!pEnum || !pProps) {
        puts("[driver] STAGE 2 FAIL: device-enumeration procs not resolvable");
        return 13;
    }
    uint32_t n = 0;
    pEnum(inst, &n, NULL);
    if (n == 0) {
        puts("[driver] STAGE 2 FAIL: zero physical devices (lavapipe should expose one)");
        return 14;
    }
    VkPhysicalDevice phys[4];
    if (n > 4) n = 4;
    pEnum(inst, &n, phys);
    VkPhysicalDeviceProperties pd = {0};
    pProps(phys[0], &pd);
    printf("[driver] VkPhysicalDevice[0] = \"%s\" (apiVersion %u.%u.%u)\n",
           pd.deviceName,
           VK_VERSION_MAJOR(pd.apiVersion),
           VK_VERSION_MINOR(pd.apiVersion),
           VK_VERSION_PATCH(pd.apiVersion));

    // (3) Create a logical device with one compute-capable queue.
    PFN_vkGetPhysicalDeviceQueueFamilyProperties pQF =
        GIPA(inst, vkGetPhysicalDeviceQueueFamilyProperties);
    PFN_vkCreateDevice pCreateDevice = GIPA(inst, vkCreateDevice);
    PFN_vkGetDeviceProcAddr pGDPA = GIPA(inst, vkGetDeviceProcAddr);
    if (!pQF || !pCreateDevice || !pGDPA) {
        puts("[driver] STAGE 3 FAIL: device-creation procs not resolvable");
        return 15;
    }
    uint32_t qn = 0;
    pQF(phys[0], &qn, NULL);
    if (qn == 0) { puts("[driver] STAGE 3 FAIL: no queue families"); return 16; }

    // THE JIT TARGET LEVER: register the AArch64 target explicitly + measure the
    // registry state BEFORE vkCreateDevice triggers the JIT init
    // (lp_build_create_jit_compiler_for_module -> EngineBuilder::selectTarget).
    // The wall was selectTarget() returning NULL (a NULL-vtable virtual call); this
    // tells us whether the process triple now resolves to a registered target.
    (void) dregg_llvm_target_diag();
    float prio = 1.0f;
    VkDeviceQueueCreateInfo qci = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
        .queueFamilyIndex = 0,
        .queueCount = 1,
        .pQueuePriorities = &prio,
    };
    VkDeviceCreateInfo dci = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
        .queueCreateInfoCount = 1,
        .pQueueCreateInfos = &qci,
    };
    VkDevice dev = VK_NULL_HANDLE;
    r = pCreateDevice(phys[0], &dci, NULL, &dev);
    // Report the W→X JIT activity that instance + physical-device + screen
    // creation ALREADY provoked, even if device creation then fails — this is the
    // measured proof the in-PD JIT executable-mapping path fired.
    printf("[driver] W->X so far: %lu executable mmap(s), %lu PROT_EXEC mprotect flip(s)\n",
           (unsigned long) dregg_render_pd_jit_exec_maps(),
           (unsigned long) dregg_render_pd_jit_wx_flips());
    if (r != VK_SUCCESS || dev == VK_NULL_HANDLE) {
        printf("[driver] STAGE 3: vkCreateDevice = %d (VK_ERROR_UNKNOWN=-13).\n", (int)r);
        printf("[driver]   lavapipe's lvp_queue_init unconditionally calls\n");
        printf("[driver]   vk_queue_enable_submit_thread -> thrd_create: this single-thread\n");
        printf("[driver]   seL4 root task cannot spawn a 2nd TCB. The NEXT OS demand =\n");
        printf("[driver]   real thread creation (sel4-musl pthread -> a scheduled seL4 TCB).\n");
        return 17;
    }
    puts("[driver] vkCreateDevice OK — logical device live");

    // (4) THE JIT EXERCISE: build a compute pipeline from the empty SPIR-V. This
    //     drives lavapipe's NIR->LLVM->machine-code path, which mmaps a W region,
    //     writes the shader's machine code, and makes it executable (the W→X the
    //     handler services). vkCreateComputePipelines forces the JIT eagerly.
    PFN_vkCreateShaderModule pCSM =
        (PFN_vkCreateShaderModule) pGDPA(dev, "vkCreateShaderModule");
    PFN_vkCreatePipelineLayout pCPL =
        (PFN_vkCreatePipelineLayout) pGDPA(dev, "vkCreatePipelineLayout");
    PFN_vkCreateComputePipelines pCCP =
        (PFN_vkCreateComputePipelines) pGDPA(dev, "vkCreateComputePipelines");
    if (!pCSM || !pCPL || !pCCP) {
        puts("[driver] STAGE 4 FAIL: pipeline procs not resolvable");
        return 18;
    }
    VkShaderModuleCreateInfo smci = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = sizeof(empty_comp_spv),
        .pCode = empty_comp_spv,
    };
    VkShaderModule sm = VK_NULL_HANDLE;
    r = pCSM(dev, &smci, NULL, &sm);
    if (r != VK_SUCCESS) { printf("[driver] STAGE 4 FAIL: vkCreateShaderModule = %d\n", (int)r); return 19; }

    VkPipelineLayoutCreateInfo plci = { .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO };
    VkPipelineLayout pl = VK_NULL_HANDLE;
    r = pCPL(dev, &plci, NULL, &pl);
    if (r != VK_SUCCESS) { printf("[driver] STAGE 4 FAIL: vkCreatePipelineLayout = %d\n", (int)r); return 20; }

    VkComputePipelineCreateInfo cpci = {
        .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .stage = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .stage = VK_SHADER_STAGE_COMPUTE_BIT,
            .module = sm,
            .pName = "main",
        },
        .layout = pl,
    };
    VkPipeline pipe = VK_NULL_HANDLE;
    r = pCCP(dev, VK_NULL_HANDLE, 1, &cpci, NULL, &pipe);
    if (r != VK_SUCCESS || pipe == VK_NULL_HANDLE) {
        printf("[driver] STAGE 4 FAIL: vkCreateComputePipelines = %d (the JIT path)\n", (int)r);
        return 21;
    }
    puts("[driver] vkCreateComputePipelines OK — lavapipe JIT'd a shader IN-PD");

    // Report the W→X activity the JIT provoked (the seL4-musl handler counted it).
    printf("[driver] W->X observed: %lu executable mmap(s), %lu PROT_EXEC mprotect flip(s)\n",
           (unsigned long) dregg_render_pd_jit_exec_maps(),
           (unsigned long) dregg_render_pd_jit_wx_flips());

    puts("[driver] === lavapipe software-Vulkan RAN inside the seL4 PD ===");
    return 0;
}
