// driver-render.c — the in-PD lavapipe smoke: resolve the software-Vulkan ICD
// LOADER-LESS (vk_icdGetInstanceProcAddr, never the static vkXxx symbols, so the
// dispatchable-handle magic stays Mesa's), create an instance, enumerate the
// llvmpipe VkPhysicalDevice, create a logical device, and build a trivial COMPUTE
// pipeline from SPIR-V — which forces lavapipe's LLVM shader JIT to run, the path
// that exercises the W→X executable mapping the seL4-musl syscall handler now
// services (src/main.rs::handle_by_number MMAP/MPROTECT).
//
// This is the render-PD's `driver-sel4.c` analogue (executor-rootserver): the
// Rust root task calls dregg_render_pd_run() after installing the syscall handler.
// It prints what it observed over the seL4 debug serial and returns 0 on the full
// chain succeeding, or a precise nonzero STAGE code (so a stall names its rung).
//
// The full gpui-offscreen render (gpui::Scene -> wgpu -> this ICD -> RGBA ->
// ramfb) is the Rust-side path layered ON TOP of this smoke once the wgpu/gpui
// crates link for the target (WIRING.md "The render call"); this C smoke is the
// first thing that puts a JIT'd lavapipe inside the PD and proves the W→X mapping.

#include <stddef.h>
#include <stdint.h>

// The Vulkan + ICD headers ship in the Mesa source tree (no Vulkan SDK needed);
// build.rs adds -I/tmp/mesa-src/include (so `vulkan/...` + the `vk_video/...`
// chain vulkan_core.h pulls both resolve). We use the C ABI directly.
#include <vulkan/vulkan_core.h>
#include <vulkan/vk_icd.h>

// printf-free: the Rust PD routes fd 1/2 writes to the seL4 debug serial, so we
// use the libc the closure is linked against. Declare the few we call.
extern int   puts(const char *s);
extern int   printf(const char *fmt, ...);

// The Rust side's W→X counters (src/main.rs).
extern size_t dregg_render_pd_jit_exec_maps(void);
extern size_t dregg_render_pd_jit_wx_flips(void);

// ───────────────────────── the in-PD RGBA staging buffer ────────────────────
//
// THE RENDER WELD: the lavapipe graphics render (dregg_render_pd_render below)
// rasterizes one 800×600 frame INTO this buffer (RGBA8, row-major, no padding —
// WIDTH*HEIGHT*4 bytes). The Rust boot path (main.rs) reads it via the accessors
// below and drives `render_blit::blit_rgba_to_framebuffer` (RGBA → XRGB8888 →
// the PD framebuffer). This is the actual in-PD RGBA the static bake replaces —
// produced by the SAME lavapipe/llvmpipe renderer, now rasterizing in-VM.
#define RENDER_W 800u
#define RENDER_H 600u
static unsigned char g_render_rgba[RENDER_W * RENDER_H * 4];
static int           g_render_ready = 0;

// Accessors the Rust side reads (src/main.rs welds these into render_blit).
const unsigned char *dregg_render_pd_rgba(void)   { return g_render_rgba; }
size_t               dregg_render_pd_rgba_len(void){ return sizeof(g_render_rgba); }
unsigned             dregg_render_pd_rgba_w(void)  { return RENDER_W; }
unsigned             dregg_render_pd_rgba_h(void)  { return RENDER_H; }
int                  dregg_render_pd_rgba_ready(void){ return g_render_ready; }

// The LLVM JIT target-registration lever/diagnostic (scripts/llvm-target-diag.c):
// drives LLVMInitializeAArch64Target* explicitly + prints the registry state the
// JIT's selectTarget will see. Driven before vkCreateDevice (the JIT-init wall).
extern int dregg_llvm_target_diag(void);

// The ICD's single loader-less entry point (vk_icd.h type), defined in
// libvulkan_lvp.so and linked in statically.
extern PFN_vkVoidFunction vk_icdGetInstanceProcAddr(VkInstance instance, const char *pName);
extern VkResult vk_icdNegotiateLoaderICDInterfaceVersion(uint32_t *pVersion);

// A minimal valid SPIR-V compute shader: `void main() {}` for local_size (1,1,1).
// Compiling this through the pipeline forces lavapipe's NIR->LLVM->machine-code
// JIT, which is the W→X exercise. (Generated by glslangValidator -V on an empty
// `#version 450\nlayout(local_size_x=1) in; void main(){}`; the canonical empty
// compute module. Kept inline so the PD needs no filesystem.)
static const uint32_t empty_comp_spv[] = {
    0x07230203, 0x00010000, 0x0008000a, 0x00000006,
    0x00000000, 0x00020011, 0x00000001, 0x0006000b,
    0x00000001, 0x4c534c47, 0x6474732e, 0x3035342e,
    0x00000000, 0x0003000e, 0x00000000, 0x00000001,
    0x0006000f, 0x00000005, 0x00000004, 0x6e69616d,
    0x00000000, 0x00000000, 0x00060010, 0x00000004,
    0x00000011, 0x00000001, 0x00000001, 0x00000001,
    0x00030003, 0x00000002, 0x000001c2, 0x00040005,
    0x00000004, 0x6e69616d, 0x00000000, 0x00020013,
    0x00000002, 0x00030021, 0x00000003, 0x00000002,
    0x00050036, 0x00000002, 0x00000004, 0x00000000,
    0x00000003, 0x000200f8, 0x00000005, 0x000100fd,
    0x00010038,
};

// Resolve a global proc (instance==NULL is valid for the global commands:
// vkCreateInstance, vkEnumerateInstanceVersion, ...).
#define GIPA(inst, name) ((PFN_##name) vk_icdGetInstanceProcAddr((inst), #name))

// STAGE 5 — the in-PD lavapipe render (defined below dregg_render_pd_run).
int      dregg_render_pd_render(VkInstance inst, VkPhysicalDevice phys,
                                VkDevice dev, PFN_vkGetDeviceProcAddr pGDPA);
unsigned dregg_render_pd_rgba_checksum(void);

int dregg_render_pd_run(void) {
    // (0) Negotiate the loader<->ICD interface version (the loader-less protocol:
    //     we play the loader's role, asking the ICD for its version).
    uint32_t icd_ver = 0;
    if (vk_icdNegotiateLoaderICDInterfaceVersion(&icd_ver) != VK_SUCCESS) {
        puts("[driver] STAGE 0 FAIL: ICD interface negotiation");
        return 10;
    }
    printf("[driver] ICD interface version = %u (loader-less; lavapipe in-PD)\n", icd_ver);

    // (1) Resolve + call vkCreateInstance via the ICD proc-addr chain.
    PFN_vkCreateInstance pCreateInstance = GIPA(VK_NULL_HANDLE, vkCreateInstance);
    if (!pCreateInstance) {
        puts("[driver] STAGE 1 FAIL: vkCreateInstance not resolvable from the ICD");
        return 11;
    }
    VkApplicationInfo app = {
        .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
        .pApplicationName = "dregg-render-pd",
        .apiVersion = VK_API_VERSION_1_1,
    };
    VkInstanceCreateInfo ici = {
        .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
        .pApplicationInfo = &app,
    };
    VkInstance inst = VK_NULL_HANDLE;
    VkResult r = pCreateInstance(&ici, NULL, &inst);
    if (r != VK_SUCCESS || inst == VK_NULL_HANDLE) {
        printf("[driver] STAGE 1 FAIL: vkCreateInstance = %d\n", (int)r);
        return 12;
    }
    puts("[driver] vkCreateInstance OK — lavapipe VkInstance live in the PD");

    // (2) Enumerate the physical device(s): the llvmpipe VkPhysicalDevice.
    PFN_vkEnumeratePhysicalDevices pEnum = GIPA(inst, vkEnumeratePhysicalDevices);
    PFN_vkGetPhysicalDeviceProperties pProps = GIPA(inst, vkGetPhysicalDeviceProperties);
    if (!pEnum || !pProps) {
        puts("[driver] STAGE 2 FAIL: device-enumeration procs not resolvable");
        return 13;
    }
    uint32_t n = 0;
    pEnum(inst, &n, NULL);
    if (n == 0) {
        puts("[driver] STAGE 2 FAIL: zero physical devices (lavapipe should expose one)");
        return 14;
    }
    VkPhysicalDevice phys[4];
    if (n > 4) n = 4;
    pEnum(inst, &n, phys);
    VkPhysicalDeviceProperties pd = {0};
    pProps(phys[0], &pd);
    printf("[driver] VkPhysicalDevice[0] = \"%s\" (apiVersion %u.%u.%u)\n",
           pd.deviceName,
           VK_VERSION_MAJOR(pd.apiVersion),
           VK_VERSION_MINOR(pd.apiVersion),
           VK_VERSION_PATCH(pd.apiVersion));

    // (3) Create a logical device with one compute-capable queue.
    PFN_vkGetPhysicalDeviceQueueFamilyProperties pQF =
        GIPA(inst, vkGetPhysicalDeviceQueueFamilyProperties);
    PFN_vkCreateDevice pCreateDevice = GIPA(inst, vkCreateDevice);
    PFN_vkGetDeviceProcAddr pGDPA = GIPA(inst, vkGetDeviceProcAddr);
    if (!pQF || !pCreateDevice || !pGDPA) {
        puts("[driver] STAGE 3 FAIL: device-creation procs not resolvable");
        return 15;
    }
    uint32_t qn = 0;
    pQF(phys[0], &qn, NULL);
    if (qn == 0) { puts("[driver] STAGE 3 FAIL: no queue families"); return 16; }

    // THE JIT TARGET LEVER: register the AArch64 target explicitly + measure the
    // registry state BEFORE vkCreateDevice triggers the JIT init
    // (lp_build_create_jit_compiler_for_module -> EngineBuilder::selectTarget).
    // The wall was selectTarget() returning NULL (a NULL-vtable virtual call); this
    // tells us whether the process triple now resolves to a registered target.
    (void) dregg_llvm_target_diag();
    float prio = 1.0f;
    VkDeviceQueueCreateInfo qci = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
        .queueFamilyIndex = 0,
        .queueCount = 1,
        .pQueuePriorities = &prio,
    };
    VkDeviceCreateInfo dci = {
        .sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
        .queueCreateInfoCount = 1,
        .pQueueCreateInfos = &qci,
    };
    VkDevice dev = VK_NULL_HANDLE;
    r = pCreateDevice(phys[0], &dci, NULL, &dev);
    // Report the W→X JIT activity that instance + physical-device + screen
    // creation ALREADY provoked, even if device creation then fails — this is the
    // measured proof the in-PD JIT executable-mapping path fired.
    printf("[driver] W->X so far: %lu executable mmap(s), %lu PROT_EXEC mprotect flip(s)\n",
           (unsigned long) dregg_render_pd_jit_exec_maps(),
           (unsigned long) dregg_render_pd_jit_wx_flips());
    if (r != VK_SUCCESS || dev == VK_NULL_HANDLE) {
        printf("[driver] STAGE 3: vkCreateDevice = %d (VK_ERROR_UNKNOWN=-13).\n", (int)r);
        printf("[driver]   lavapipe's lvp_queue_init unconditionally calls\n");
        printf("[driver]   vk_queue_enable_submit_thread -> thrd_create: this single-thread\n");
        printf("[driver]   seL4 root task cannot spawn a 2nd TCB. The NEXT OS demand =\n");
        printf("[driver]   real thread creation (sel4-musl pthread -> a scheduled seL4 TCB).\n");
        return 17;
    }
    puts("[driver] vkCreateDevice OK — logical device live");

    // (4) THE JIT EXERCISE: build a compute pipeline from the empty SPIR-V. This
    //     drives lavapipe's NIR->LLVM->machine-code path, which mmaps a W region,
    //     writes the shader's machine code, and makes it executable (the W→X the
    //     handler services). vkCreateComputePipelines forces the JIT eagerly.
    PFN_vkCreateShaderModule pCSM =
        (PFN_vkCreateShaderModule) pGDPA(dev, "vkCreateShaderModule");
    PFN_vkCreatePipelineLayout pCPL =
        (PFN_vkCreatePipelineLayout) pGDPA(dev, "vkCreatePipelineLayout");
    PFN_vkCreateComputePipelines pCCP =
        (PFN_vkCreateComputePipelines) pGDPA(dev, "vkCreateComputePipelines");
    if (!pCSM || !pCPL || !pCCP) {
        puts("[driver] STAGE 4 FAIL: pipeline procs not resolvable");
        return 18;
    }
    VkShaderModuleCreateInfo smci = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = sizeof(empty_comp_spv),
        .pCode = empty_comp_spv,
    };
    VkShaderModule sm = VK_NULL_HANDLE;
    r = pCSM(dev, &smci, NULL, &sm);
    if (r != VK_SUCCESS) { printf("[driver] STAGE 4 FAIL: vkCreateShaderModule = %d\n", (int)r); return 19; }

    VkPipelineLayoutCreateInfo plci = { .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO };
    VkPipelineLayout pl = VK_NULL_HANDLE;
    r = pCPL(dev, &plci, NULL, &pl);
    if (r != VK_SUCCESS) { printf("[driver] STAGE 4 FAIL: vkCreatePipelineLayout = %d\n", (int)r); return 20; }

    VkComputePipelineCreateInfo cpci = {
        .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .stage = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .stage = VK_SHADER_STAGE_COMPUTE_BIT,
            .module = sm,
            .pName = "main",
        },
        .layout = pl,
    };
    VkPipeline pipe = VK_NULL_HANDLE;
    r = pCCP(dev, VK_NULL_HANDLE, 1, &cpci, NULL, &pipe);
    if (r != VK_SUCCESS || pipe == VK_NULL_HANDLE) {
        printf("[driver] STAGE 4 FAIL: vkCreateComputePipelines = %d (the JIT path)\n", (int)r);
        return 21;
    }
    puts("[driver] vkCreateComputePipelines OK — lavapipe JIT'd a shader IN-PD");

    // Report the W→X activity the JIT provoked (the seL4-musl handler counted it).
    printf("[driver] W->X observed: %lu executable mmap(s), %lu PROT_EXEC mprotect flip(s)\n",
           (unsigned long) dregg_render_pd_jit_exec_maps(),
           (unsigned long) dregg_render_pd_jit_wx_flips());

    puts("[driver] === lavapipe software-Vulkan RAN inside the seL4 PD ===");

    // (5) THE RENDER WELD: rasterize one real 800×600 RGBA frame IN-PD and stage
    //     it for the Rust render_blit → ramfb path. This drives lavapipe's actual
    //     image-writeback rasterizer (not just the shader JIT) into a linear
    //     host-visible VkImage, then maps it and copies the bytes into
    //     g_render_rgba. The Rust boot path (main.rs) blits those bytes
    //     RGBA→XRGB8888 into the PD framebuffer and byte-checks them.
    {
        int rr = dregg_render_pd_render(inst, phys[0], dev, pGDPA);
        if (rr != 0) {
            printf("[driver] STAGE 5: in-PD render produced no frame (rc=%d)\n", rr);
            // Not fatal to the smoke: the JIT/W→X proof above stands. The render
            // weld reports its own precise rung; the Rust side falls back to a
            // backdrop on an empty/short buffer (render_blit returns 0).
        } else {
            printf("[driver] STAGE 5: in-PD lavapipe render OK — %u×%u RGBA staged "
                   "(checksum 0x%08x)\n",
                   RENDER_W, RENDER_H, dregg_render_pd_rgba_checksum());
        }
    }

    return 0;
}

// A 32-bit additive-rotate checksum over the staged RGBA — printed by both the C
// driver and the Rust blit so the serial proves the SAME bytes flowed end to end
// (a cheap in-VM byte-compare witness, no host bake needed at boot).
unsigned dregg_render_pd_rgba_checksum(void) {
    unsigned h = 2166136261u; // FNV-1a offset basis
    for (size_t i = 0; i < sizeof(g_render_rgba); i++) {
        h ^= g_render_rgba[i];
        h *= 16777619u; // FNV-1a prime
    }
    return h;
}

// STAGE 5 — render one frame with lavapipe into a linear, host-visible VkImage
// and copy it into g_render_rgba. We use vkCmdClearColorImage on a deterministic
// cockpit-backdrop color over the whole 800×600 surface: it drives lavapipe's
// real rasterizer image-write path into mappable VK_IMAGE_TILING_LINEAR memory —
// genuine in-PD pixels, deterministic so the Rust blit can byte-verify them. (A
// full element-tree gpui render is the wgpu-link rung on top; this proves the
// lavapipe→RGBA→map readback substrate the blit consumes.)
static int find_mem_type(VkPhysicalDevice phys,
                         PFN_vkGetPhysicalDeviceMemoryProperties pGMP,
                         uint32_t type_bits, VkMemoryPropertyFlags want) {
    VkPhysicalDeviceMemoryProperties mp = {0};
    pGMP(phys, &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; i++) {
        if ((type_bits & (1u << i)) &&
            (mp.memoryTypes[i].propertyFlags & want) == want) {
            return (int)i;
        }
    }
    return -1;
}

int dregg_render_pd_render(VkInstance inst, VkPhysicalDevice phys, VkDevice dev,
                           PFN_vkGetDeviceProcAddr pGDPA) {
    // The deterministic cockpit-backdrop fill (the deos cockpit's dark slate
    // `rgb(11,15,26)`), as a normalized RGBA clear color. Every pixel becomes
    // this, so the staged buffer is exactly WIDTH*HEIGHT of (11,15,26,255).
    const float CR = 11.0f / 255.0f, CG = 15.0f / 255.0f, CB = 26.0f / 255.0f;

    PFN_vkGetPhysicalDeviceMemoryProperties pGMP =
        (PFN_vkGetPhysicalDeviceMemoryProperties)
        vk_icdGetInstanceProcAddr(inst, "vkGetPhysicalDeviceMemoryProperties");
    PFN_vkCreateImage         pCI  = (PFN_vkCreateImage)         pGDPA(dev, "vkCreateImage");
    PFN_vkGetImageMemoryRequirements pIMR =
        (PFN_vkGetImageMemoryRequirements) pGDPA(dev, "vkGetImageMemoryRequirements");
    PFN_vkAllocateMemory      pAM  = (PFN_vkAllocateMemory)      pGDPA(dev, "vkAllocateMemory");
    PFN_vkBindImageMemory     pBIM = (PFN_vkBindImageMemory)     pGDPA(dev, "vkBindImageMemory");
    PFN_vkMapMemory           pMM  = (PFN_vkMapMemory)           pGDPA(dev, "vkMapMemory");
    PFN_vkGetImageSubresourceLayout pISL =
        (PFN_vkGetImageSubresourceLayout) pGDPA(dev, "vkGetImageSubresourceLayout");
    PFN_vkCreateCommandPool   pCCP = (PFN_vkCreateCommandPool)   pGDPA(dev, "vkCreateCommandPool");
    PFN_vkAllocateCommandBuffers pACB =
        (PFN_vkAllocateCommandBuffers) pGDPA(dev, "vkAllocateCommandBuffers");
    PFN_vkBeginCommandBuffer  pBCB = (PFN_vkBeginCommandBuffer)  pGDPA(dev, "vkBeginCommandBuffer");
    PFN_vkCmdClearColorImage  pCCI = (PFN_vkCmdClearColorImage)  pGDPA(dev, "vkCmdClearColorImage");
    PFN_vkCmdPipelineBarrier  pCPB = (PFN_vkCmdPipelineBarrier)  pGDPA(dev, "vkCmdPipelineBarrier");
    PFN_vkEndCommandBuffer    pECB = (PFN_vkEndCommandBuffer)    pGDPA(dev, "vkEndCommandBuffer");
    PFN_vkGetDeviceQueue      pGDQ = (PFN_vkGetDeviceQueue)      pGDPA(dev, "vkGetDeviceQueue");
    PFN_vkQueueSubmit         pQS  = (PFN_vkQueueSubmit)         pGDPA(dev, "vkQueueSubmit");
    PFN_vkQueueWaitIdle       pQWI = (PFN_vkQueueWaitIdle)       pGDPA(dev, "vkQueueWaitIdle");
    if (!pGMP || !pCI || !pIMR || !pAM || !pBIM || !pMM || !pISL || !pCCP ||
        !pACB || !pBCB || !pCCI || !pCPB || !pECB || !pGDQ || !pQS || !pQWI) {
        puts("[driver]   STAGE 5: render procs not resolvable");
        return 50;
    }

    // A linear, host-visible RGBA8 image — directly mappable (no staging copy).
    VkImageCreateInfo ici = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
        .imageType = VK_IMAGE_TYPE_2D,
        .format = VK_FORMAT_R8G8B8A8_UNORM,
        .extent = { RENDER_W, RENDER_H, 1 },
        .mipLevels = 1, .arrayLayers = 1,
        .samples = VK_SAMPLE_COUNT_1_BIT,
        .tiling = VK_IMAGE_TILING_LINEAR,
        .usage = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
        .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
    };
    VkImage img = VK_NULL_HANDLE;
    if (pCI(dev, &ici, NULL, &img) != VK_SUCCESS) { puts("[driver]   STAGE 5: vkCreateImage failed"); return 51; }

    VkMemoryRequirements mr = {0};
    pIMR(dev, img, &mr);
    int mt = find_mem_type(phys, pGMP, mr.memoryTypeBits,
                           VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                           VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (mt < 0) { puts("[driver]   STAGE 5: no host-visible memory type"); return 52; }
    VkMemoryAllocateInfo mai = {
        .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
        .allocationSize = mr.size,
        .memoryTypeIndex = (uint32_t)mt,
    };
    VkDeviceMemory mem = VK_NULL_HANDLE;
    if (pAM(dev, &mai, NULL, &mem) != VK_SUCCESS) { puts("[driver]   STAGE 5: vkAllocateMemory failed"); return 53; }
    if (pBIM(dev, img, mem, 0) != VK_SUCCESS) { puts("[driver]   STAGE 5: vkBindImageMemory failed"); return 54; }

    VkCommandPoolCreateInfo cpci = { .sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO, .queueFamilyIndex = 0 };
    VkCommandPool pool = VK_NULL_HANDLE;
    if (pCCP(dev, &cpci, NULL, &pool) != VK_SUCCESS) { puts("[driver]   STAGE 5: vkCreateCommandPool failed"); return 55; }
    VkCommandBufferAllocateInfo cbai = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool = pool, .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY, .commandBufferCount = 1,
    };
    VkCommandBuffer cb = VK_NULL_HANDLE;
    if (pACB(dev, &cbai, &cb) != VK_SUCCESS) { puts("[driver]   STAGE 5: vkAllocateCommandBuffers failed"); return 56; }

    VkCommandBufferBeginInfo bi = { .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
                                    .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT };
    pBCB(cb, &bi);

    // UNDEFINED → TRANSFER_DST so the clear is well-defined.
    VkImageMemoryBarrier toDst = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
        .srcAccessMask = 0, .dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_UNDEFINED, .newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
        .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED, .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .image = img,
        .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
    };
    pCPB(cb, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
         0, 0, NULL, 0, NULL, 1, &toDst);

    VkClearColorValue clr = { .float32 = { CR, CG, CB, 1.0f } };
    VkImageSubresourceRange range = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 };
    pCCI(cb, img, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, &clr, 1, &range);

    // TRANSFER_DST → GENERAL so the host map sees the written bytes.
    VkImageMemoryBarrier toHost = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
        .srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT, .dstAccessMask = VK_ACCESS_HOST_READ_BIT,
        .oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, .newLayout = VK_IMAGE_LAYOUT_GENERAL,
        .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED, .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .image = img,
        .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
    };
    pCPB(cb, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_HOST_BIT,
         0, 0, NULL, 0, NULL, 1, &toHost);

    pECB(cb);

    VkQueue q = VK_NULL_HANDLE;
    pGDQ(dev, 0, 0, &q);
    VkSubmitInfo si = { .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO, .commandBufferCount = 1, .pCommandBuffers = &cb };
    if (pQS(q, 1, &si, VK_NULL_HANDLE) != VK_SUCCESS) { puts("[driver]   STAGE 5: vkQueueSubmit failed"); return 57; }
    if (pQWI(q) != VK_SUCCESS) { puts("[driver]   STAGE 5: vkQueueWaitIdle failed"); return 58; }

    // Map the linear image + copy into g_render_rgba, honoring the row pitch.
    VkImageSubresource sub = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0 };
    VkSubresourceLayout lay = {0};
    pISL(dev, img, &sub, &lay);
    void *mapped = NULL;
    if (pMM(dev, mem, 0, VK_WHOLE_SIZE, 0, &mapped) != VK_SUCCESS || !mapped) {
        puts("[driver]   STAGE 5: vkMapMemory failed");
        return 59;
    }
    const unsigned char *base = (const unsigned char *)mapped + lay.offset;
    for (unsigned y = 0; y < RENDER_H; y++) {
        const unsigned char *src = base + (size_t)y * lay.rowPitch;
        unsigned char *dst = g_render_rgba + (size_t)y * RENDER_W * 4;
        for (unsigned x = 0; x < RENDER_W * 4; x++) dst[x] = src[x];
    }
    g_render_ready = 1;
    return 0;
}
