// @generated by `cargo run -p dregg-cell --example gen_image_snapshot`.
// DO NOT EDIT BY HAND. A frozen LIVE IMAGE of REAL dregg-cell cells:
// every id / commitment / cap below is this crate's genuine output
// (real CellId::derive_raw, real state_commitment, real CapabilitySet).
//
// Regenerate from the repo root (and redirect into this file):
//   cargo run -p dregg-cell --example gen_image_snapshot \
//     > sel4/dregg-pd/deos-image/src/image_data.rs

#![allow(dead_code)]

/// One inspectable substance value: a (label, value) pair, pre-rendered.
pub struct Kv {
    pub k: &'static str,
    pub v: &'static str,
}

/// One capability in a cell's c-list (the AUTHORITY substance), rendered.
pub struct CapRow {
    pub target: &'static str, // target cell id (short hex)
    pub slot: u32,
    pub auth: &'static str, // AuthRequired
    pub note: &'static str, // human note (which named cell / caveat)
}

/// One state field (the STATE substance), rendered.
pub struct FieldRow {
    pub slot: u32,
    pub note: &'static str,  // human meaning, or ""
    pub kind: &'static str,  // public | committed | disclosable
    pub value: &'static str, // decoded value or commitment hash
}

/// One cell in the image — everything the viewer inspects.
pub struct ImageCell {
    pub key: &'static str,
    pub title: &'static str,
    pub blurb: &'static str,
    pub id_hex: &'static str, // content-addressed id (short)
    pub pk_hex: &'static str,
    pub token_hex: &'static str,
    pub mode: &'static str,
    pub life_tag: &'static str,
    pub life_desc: &'static str,
    // VALUE substance
    pub balance: i64,
    pub is_well: bool,
    // STATE substance
    pub nonce: u64,
    pub fields_used: u32, // how many of the 16 fields are nonzero
    pub fields: &'static [FieldRow],
    // AUTHORITY substance
    pub caps: &'static [CapRow],
    pub perms: &'static [Kv], // the 8 permission gates
    // EVIDENCE substance
    pub proved_state: bool,
    pub vk_hash: &'static str, // "none" if no VK
    pub vk_program: &'static str,
    pub commitment: &'static str, // state_commitment() (short hex)
}

pub const IMAGE: &[ImageCell] = &[
    ImageCell {
        key: "about",
        title: "about deos",
        blurb: "the welcome, as a live object you can inspect",
        id_hex: "8e1890b6 24127c32 720ac85d d35e4e3f",
        pk_hex: "a0000000 00000020 00000000 00000021",
        token_hex: "64656f73 2e676172 64656e2e 746f6b65",
        mode: "SOVEREIGN",
        life_tag: "LIVE",
        life_desc: "accepts effects; the ordinary running state",
        balance: 0,
        is_well: false,
        nonce: 2,
        fields_used: 5,
        fields: &[
            FieldRow {
                slot: 0,
                note: "greeting",
                kind: "public",
                value: "\"welcome to deos\"",
            },
            FieldRow {
                slot: 1,
                note: "thesis",
                kind: "public",
                value: "\"a computer you hold\"",
            },
            FieldRow {
                slot: 2,
                note: "law of authority",
                kind: "public",
                value: "\"authority is proof\"",
            },
            FieldRow {
                slot: 3,
                note: "law of persistence",
                kind: "public",
                value: "\"persistence is default\"",
            },
            FieldRow {
                slot: 4,
                note: "law of sovereignty",
                kind: "public",
                value: "\"the keys are yours\"",
            },
        ],
        caps: &[],
        perms: &[
            Kv {
                k: "send",
                v: "signature",
            },
            Kv {
                k: "receive",
                v: "none",
            },
            Kv {
                k: "set_state",
                v: "signature",
            },
            Kv {
                k: "set_permissions",
                v: "signature",
            },
            Kv {
                k: "set_vk",
                v: "proof",
            },
            Kv {
                k: "increment_nonce",
                v: "signature",
            },
            Kv {
                k: "delegate",
                v: "signature",
            },
            Kv {
                k: "access",
                v: "none",
            },
        ],
        proved_state: false,
        vk_hash: "none",
        vk_program: "",
        commitment: "8bdf3ea5 b9d13631 08f30bd5 ..",
    },
    ImageCell {
        key: "garden",
        title: "the garden",
        blurb: "a sovereign content cell — transclude its quote",
        id_hex: "ffa3cb29 27cb1bc2 8bb7ccc1 6099a654",
        pk_hex: "9a000000 000000d2 00000000 00000073",
        token_hex: "64656f73 2e676172 64656e2e 746f6b65",
        mode: "SOVEREIGN",
        life_tag: "LIVE",
        life_desc: "accepts effects; the ordinary running state",
        balance: 0,
        is_well: false,
        nonce: 1,
        fields_used: 6,
        fields: &[
            FieldRow {
                slot: 0,
                note: "motto line 1",
                kind: "public",
                value: "\"I object to doing\"",
            },
            FieldRow {
                slot: 1,
                note: "motto line 2",
                kind: "public",
                value: "\"things computers\"",
            },
            FieldRow {
                slot: 2,
                note: "motto line 3",
                kind: "public",
                value: "\"can do.\"",
            },
            FieldRow {
                slot: 3,
                note: "attribution",
                kind: "public",
                value: "\"- Guild of Houyhnhnm\"",
            },
            FieldRow {
                slot: 7,
                note: "year (u64)",
                kind: "public",
                value: "1999",
            },
            FieldRow {
                slot: 10,
                note: "private (committed)",
                kind: "committed",
                value: "f0731163 79a5cd05 85e0e326 ..",
            },
        ],
        caps: &[],
        perms: &[
            Kv {
                k: "send",
                v: "signature",
            },
            Kv {
                k: "receive",
                v: "none",
            },
            Kv {
                k: "set_state",
                v: "signature",
            },
            Kv {
                k: "set_permissions",
                v: "signature",
            },
            Kv {
                k: "set_vk",
                v: "signature",
            },
            Kv {
                k: "increment_nonce",
                v: "signature",
            },
            Kv {
                k: "delegate",
                v: "signature",
            },
            Kv {
                k: "access",
                v: "none",
            },
        ],
        proved_state: false,
        vk_hash: "none",
        vk_program: "",
        commitment: "e5236455 7fd96a85 0c4de1be ..",
    },
    ImageCell {
        key: "wallet",
        title: "your wallet",
        blurb: "value + the c-list — spend caps over the web",
        id_hex: "ab11dff1 22f7aec9 d62fb9bb 0cc92e7a",
        pk_hex: "01000000 0000000d 00000000 0000001e",
        token_hex: "64656f73 2e76616c 75652e63 6f6d7075",
        mode: "SOVEREIGN",
        life_tag: "LIVE",
        life_desc: "accepts effects; the ordinary running state",
        balance: 1000,
        is_well: false,
        nonce: 3,
        fields_used: 2,
        fields: &[
            FieldRow {
                slot: 0,
                note: "last recipient",
                kind: "public",
                value: "\"last->peer\"",
            },
            FieldRow {
                slot: 1,
                note: "last amount",
                kind: "public",
                value: "250",
            },
        ],
        caps: &[
            CapRow {
                target: "ffa3cb29 27cb1bc2 8bb7ccc1 6099a654",
                slot: 0,
                auth: "either",
                note: "-> the garden",
            },
            CapRow {
                target: "6ba3b626 21db85f0 ff68edbd 70d6da2e",
                slot: 1,
                auth: "signature",
                note: "-> a peer",
            },
        ],
        perms: &[
            Kv {
                k: "send",
                v: "signature",
            },
            Kv {
                k: "receive",
                v: "none",
            },
            Kv {
                k: "set_state",
                v: "signature",
            },
            Kv {
                k: "set_permissions",
                v: "signature",
            },
            Kv {
                k: "set_vk",
                v: "signature",
            },
            Kv {
                k: "increment_nonce",
                v: "signature",
            },
            Kv {
                k: "delegate",
                v: "signature",
            },
            Kv {
                k: "access",
                v: "none",
            },
        ],
        proved_state: false,
        vk_hash: "none",
        vk_program: "",
        commitment: "ce4e220d 35785daa 6b290a92 ..",
    },
    ImageCell {
        key: "mint",
        title: "the mint",
        blurb: "an issuer well: -supply, so the image conserves to zero",
        id_hex: "4683648a 144d34e4 9890be34 66326fbe",
        pk_hex: "f0000000 00000030 00000000 00000031",
        token_hex: "64656f73 2e76616c 75652e63 6f6d7075",
        mode: "SOVEREIGN",
        life_tag: "LIVE",
        life_desc: "accepts effects; the ordinary running state",
        balance: -1200,
        is_well: true,
        nonce: 1,
        fields_used: 2,
        fields: &[
            FieldRow {
                slot: 0,
                note: "role",
                kind: "public",
                value: "\"computrons issuer\"",
            },
            FieldRow {
                slot: 1,
                note: "supply minted (u64)",
                kind: "public",
                value: "1200",
            },
        ],
        caps: &[],
        perms: &[
            Kv {
                k: "send",
                v: "signature",
            },
            Kv {
                k: "receive",
                v: "none",
            },
            Kv {
                k: "set_state",
                v: "signature",
            },
            Kv {
                k: "set_permissions",
                v: "signature",
            },
            Kv {
                k: "set_vk",
                v: "proof",
            },
            Kv {
                k: "increment_nonce",
                v: "signature",
            },
            Kv {
                k: "delegate",
                v: "signature",
            },
            Kv {
                k: "access",
                v: "none",
            },
        ],
        proved_state: false,
        vk_hash: "0455373c b015dc24 099836be ..",
        vk_program: "dregg.mint.v1",
        commitment: "a885431e 1a2450d6 d73ba431 ..",
    },
    ImageCell {
        key: "record",
        title: "the chronicle",
        blurb: "a sealed, proof-backed record — read its evidence",
        id_hex: "ffd155cf 7230b151 b712baaa 40036664",
        pk_hex: "c0000000 000000c0 00000000 000000c1",
        token_hex: "64656f73 2e676172 64656e2e 746f6b65",
        mode: "SOVEREIGN",
        life_tag: "SEALED",
        life_desc: "reversible quiescence; sealed at height 42000",
        balance: 0,
        is_well: false,
        nonce: 2,
        fields_used: 16,
        fields: &[
            FieldRow {
                slot: 0,
                note: "entry 1",
                kind: "public",
                value: "111",
            },
            FieldRow {
                slot: 1,
                note: "entry 2",
                kind: "public",
                value: "222",
            },
            FieldRow {
                slot: 2,
                note: "",
                kind: "public",
                value: "333",
            },
            FieldRow {
                slot: 3,
                note: "",
                kind: "public",
                value: "444",
            },
            FieldRow {
                slot: 4,
                note: "",
                kind: "public",
                value: "555",
            },
            FieldRow {
                slot: 5,
                note: "",
                kind: "public",
                value: "666",
            },
            FieldRow {
                slot: 6,
                note: "",
                kind: "public",
                value: "777",
            },
            FieldRow {
                slot: 7,
                note: "",
                kind: "public",
                value: "888",
            },
            FieldRow {
                slot: 8,
                note: "",
                kind: "public",
                value: "999",
            },
            FieldRow {
                slot: 9,
                note: "",
                kind: "public",
                value: "1110",
            },
            FieldRow {
                slot: 10,
                note: "",
                kind: "public",
                value: "1221",
            },
            FieldRow {
                slot: 11,
                note: "",
                kind: "public",
                value: "1332",
            },
            FieldRow {
                slot: 12,
                note: "",
                kind: "public",
                value: "1443",
            },
            FieldRow {
                slot: 13,
                note: "",
                kind: "public",
                value: "1554",
            },
            FieldRow {
                slot: 14,
                note: "",
                kind: "public",
                value: "1665",
            },
            FieldRow {
                slot: 15,
                note: "entry 16",
                kind: "public",
                value: "1776",
            },
        ],
        caps: &[],
        perms: &[
            Kv {
                k: "send",
                v: "signature",
            },
            Kv {
                k: "receive",
                v: "none",
            },
            Kv {
                k: "set_state",
                v: "signature",
            },
            Kv {
                k: "set_permissions",
                v: "signature",
            },
            Kv {
                k: "set_vk",
                v: "signature",
            },
            Kv {
                k: "increment_nonce",
                v: "signature",
            },
            Kv {
                k: "delegate",
                v: "signature",
            },
            Kv {
                k: "access",
                v: "none",
            },
        ],
        proved_state: true,
        vk_hash: "39265531 df941549 d230c277 ..",
        vk_program: "dregg.chronicle.v2",
        commitment: "bd1551df 454991f8 624591d2 ..",
    },
    ImageCell {
        key: "peer",
        title: "a peer",
        blurb: "the far end of a cap — retired, but provably so",
        id_hex: "6ba3b626 21db85f0 ff68edbd 70d6da2e",
        pk_hex: "42000000 0000005a 00000000 0000007b",
        token_hex: "64656f73 2e76616c 75652e63 6f6d7075",
        mode: "SOVEREIGN",
        life_tag: "DESTROYED",
        life_desc: "permanently retired at height 41700",
        balance: 200,
        is_well: false,
        nonce: 1,
        fields_used: 1,
        fields: &[FieldRow {
            slot: 0,
            note: "label",
            kind: "public",
            value: "\"a friend's cell\"",
        }],
        caps: &[],
        perms: &[
            Kv {
                k: "send",
                v: "signature",
            },
            Kv {
                k: "receive",
                v: "none",
            },
            Kv {
                k: "set_state",
                v: "signature",
            },
            Kv {
                k: "set_permissions",
                v: "signature",
            },
            Kv {
                k: "set_vk",
                v: "signature",
            },
            Kv {
                k: "increment_nonce",
                v: "signature",
            },
            Kv {
                k: "delegate",
                v: "signature",
            },
            Kv {
                k: "access",
                v: "none",
            },
        ],
        proved_state: false,
        vk_hash: "none",
        vk_program: "",
        commitment: "58231725 d0d9662d 03dab65f ..",
    },
];

/// The real sum of all balances across the image (the conservation
/// shadow: issuer wells carry -supply, so a closed image sums to zero).
pub const BALANCE_SUM: i64 = 0;
/// How many cells are in the image.
pub const N_CELLS: usize = 6;
