//! THE deos LIVE IMAGE VIEWER — the thing you boot INTO is a Smalltalk/Pharo-
//! style object browser of REAL deos cells, on seL4, in a QEMU window. NOT a
//! welcome slideshow: the left rail lists the ACTUAL cells in the image (an
//! "image" of real `dregg_cell::CellState`s — real content-addressed ids, real
//! signed balances, real c-lists, real fields, real proofs), and the main pane
//! inspects the FOCUSED cell. "cell 3/6" means cell 3 of 6 LIVE in the image.
//!
//! ## What this PD is
//!
//! It GROWS the deos-tutorial PD (`sel4/dregg-pd/deos-tutorial`): the SAME
//! bytes->glass machinery (fw_cfg + ramfb scanout, `fb.rs`) and the SAME real
//! virtio-keyboard (`keyboard.rs`, the net-PD device-cap discipline), but the
//! fixed six-screen arc is replaced by a navigable cell inspector (`view.rs`):
//!
//!   - UP/DOWN move focus BETWEEN cells in the rail (the footer's "cell N/M"
//!     reflects WHICH live cell is focused);
//!   - ENTER drills INTO the focused cell and pages its four substances —
//!     VALUE (the signed ledger), STATE (16 fields + nonce), AUTHORITY (the
//!     c-list ∧ permission gates), EVIDENCE (vk + proved_state + commitment);
//!   - ESC backs OUT to the image;
//!   - TAB switches to the **starbridge-v2 COCKPIT** mode — a REAL gpui render
//!     (lavapipe / no GPU / no window) of a cockpit-SHAPED Scene (the live
//!     `cockpit::Cockpit` element tree is the one named frontier — see
//!     `cockpit_frame` + GPUI-OFFSCREEN-FORK.md), baked in and blitted onto this
//!     same framebuffer (`cockpit_frame`). Two live faces of one boot.
//!
//! The cell DATA is REAL: `image_data.rs` is @generated by the host example
//! `cargo run -p dregg-cell --example gen_image_snapshot` against the genuine
//! `dregg-cell` crate — every id is a real `CellId::derive_raw`, every
//! commitment a real `state_commitment()`, every cap a real `CapabilitySet`
//! grant (the wallet's caps point at the garden's and peer's REAL ids — the web
//! of cells, wired). The PD is `#![no_std]` and cannot link std `dregg-cell`, so
//! the real cells are computed at build time and baked in.
//!
//! ## The cap partition IS the boundary
//!
//! This PD holds the display (fw_cfg) cap, its framebuffer, and the keyboard's
//! mmio/DMA/IRQ — and NOTHING else. seL4 faults any stray access.
//!
//! ## Fidelity (honestly labeled)
//!
//! The pixels are real (genuine ramfb scanout), the keyboard is a real
//! (emulated) virtio device, the navigation is real, and the cell internals are
//! a real `dregg-cell` snapshot. The cells do NOT yet CHANGE while you watch:
//! the LIVE in-VM executor running real turns to MUTATE these cells as you
//! navigate is the named frontier (Rung 3, the executor-PD Lean runtime —
//! `.docs-history-noclaude/SEL4-EMBEDDING.md §2`). This viewer makes real cells NAVIGABLE;
//! live-mutation is the next rung.

#![no_std]
#![no_main]

extern crate alloc;

use sel4_microkit::{
    debug_println, memory_region_symbol, protection_domain, Channel, ChannelSet, Handler,
    Infallible,
};

mod cockpit_frame;
mod fb;
mod font;
mod image_data;
mod keyboard;
mod view;

use fb::Canvas;
use keyboard::{Keyboard, Nav};
use view::{LiveTurn, ViewState, N_SUBSTANCES};

/// The keyboard IRQ channel (matches `<irq id="0">` in deos-image.system).
const KBD: Channel = Channel::new(0);

/// The executor PD signals a COMMITTED turn here: "a verified turn landed, its
/// receipt is in `commit_out` — repaint." Bound in `deos-live.system` to the
/// executor's `commit ready` channel (executor id 2 ⇄ deos_image id 1). In the
/// plain `deos-image.system` (no executor) this channel is simply never signalled.
const REPAINT: Channel = Channel::new(1);

/// The shared `commit_out` region (RW for the executor, R here): the executor
/// writes the verified turn's JSON receipt here; on a REPAINT signal we read the
/// genuine receipt and surface it on glass. Mapped in `deos-live.system`; in
/// `deos-image.system` the symbol stays unmapped and `commit_out()` is unused.
const COMMIT_OUT_SIZE: usize = 0x400000; // 4 MiB (matches dregg.system <memory_region commit_out>)

fn commit_out() -> *const u8 {
    memory_region_symbol!(commit_out_vaddr: *mut [u8], n = COMMIT_OUT_SIZE).as_ptr() as *const u8
}

/// Read the verified turn's receipt the executor PD wrote to `commit_out` and
/// extract its load-bearing facts (`"status":`, `"ok":`, and the advanced nonce).
/// The receipt is JSON the verified `dregg_exec_full_forest_auth` emitted; we scan
/// it byte-for-byte (no alloc), bounded to the first NUL (the region is zero-init)
/// or a 4 KiB cap (the receipt is ~313 bytes). A turn with `status:2 ok:1` is
/// `committed` — the repaint fires; anything else is fail-closed (no banner).
fn parse_receipt(seq: u32) -> LiveTurn {
    let p = commit_out();
    let read = |i: usize| -> u8 { unsafe { core::ptr::read_volatile(p.add(i)) } };

    // receipt length: up to the first 0 byte within a generous cap.
    let cap = 4096usize;
    let mut n = 0usize;
    while n < cap && read(n) != 0 {
        n += 1;
    }

    let find = |pat: &[u8], from: usize| -> Option<usize> {
        if pat.is_empty() || pat.len() > n {
            return None;
        }
        let mut i = from;
        while i + pat.len() <= n {
            let mut hit = true;
            for (k, &c) in pat.iter().enumerate() {
                if read(i + k) != c {
                    hit = false;
                    break;
                }
            }
            if hit {
                return Some(i);
            }
            i += 1;
        }
        None
    };
    // the first unsigned integer at or after `i` (skipping non-digits up to it).
    let uint_at = |mut i: usize| -> u64 {
        while i < n && !read(i).is_ascii_digit() {
            i += 1;
        }
        let mut v: u64 = 0;
        while i < n {
            let c = read(i);
            if !c.is_ascii_digit() {
                break;
            }
            v = v.saturating_mul(10).saturating_add((c - b'0') as u64);
            i += 1;
        }
        v
    };

    let status = find(b"\"status\":", 0)
        .map(|i| uint_at(i + 8) as u8)
        .unwrap_or(0);
    let ok = find(b"\"ok\":", 0)
        .map(|i| uint_at(i + 4) as u8)
        .unwrap_or(0);
    // nonce: the first `"int":N` following the `nonce` key in the receipt.
    let nonce = find(b"nonce", 0)
        .and_then(|i| find(b"int", i))
        .map(|j| uint_at(j + 3))
        .unwrap_or(0);

    LiveTurn {
        committed: status == 2 && ok == 1,
        status,
        ok,
        nonce,
        bytes: n,
        seq,
    }
}

/// Which top-level MODE the viewer is in. TAB switches between them — two live
/// faces of the same boot:
///   * `Image`   — the Smalltalk/Pharo object browser of REAL deos cells.
///   * `Cockpit` — a REAL gpui render (lavapipe, no GPU, no window) of a
///     starbridge-v2-cockpit-SHAPED Scene, blitted onto this framebuffer
///     (`cockpit_frame`). The live `cockpit::Cockpit` element tree is the one
///     named frontier (see `cockpit_frame`).
#[derive(Clone, Copy, PartialEq, Eq)]
enum Mode {
    Image,
    Cockpit,
}

/// The running viewer: the current mode + view state + the optional keyboard.
struct Viewer {
    mode: Mode,
    state: ViewState,
    kbd: Option<Keyboard>,
    /// Cockpit-mode focus: which top workspace tab the keyboard is hovering
    /// (index into `cockpit_frame::TABS`) and which was last chosen with ENTER.
    /// This is the state cockpit mode navigates instead of discarding nav.
    cockpit_focus: usize,
    cockpit_selected: Option<usize>,
    /// How many verified turns the executor PD has signalled a repaint for.
    turns: u32,
}

impl Viewer {
    /// Repaint the current mode into the framebuffer (which QEMU scans out).
    fn paint(&self) {
        let mut canvas = unsafe { Canvas::map() };
        match self.mode {
            Mode::Image => view::draw(&mut canvas, &self.state),
            Mode::Cockpit => {
                cockpit_frame::blit(&mut canvas, self.cockpit_focus, self.cockpit_selected)
            }
        }
    }

    /// Apply a navigation intent to the view state. Returns true if anything
    /// changed (so we only repaint on a real transition).
    fn apply(&mut self, nav: Nav) -> bool {
        // TAB switches MODE from anywhere — the one key that crosses the two
        // faces of the boot (the live image <-> the gpui cockpit).
        if nav == Nav::Toggle {
            self.mode = match self.mode {
                Mode::Image => Mode::Cockpit,
                Mode::Cockpit => Mode::Image,
            };
            match self.mode {
                Mode::Image => debug_println!("[deos-image]   -> MODE: the live image"),
                Mode::Cockpit => {
                    debug_println!(
                        "[deos-image]   -> MODE: the starbridge-v2 COCKPIT (real gpui render; LEFT/RIGHT focus a tab, ENTER selects)"
                    )
                }
            }
            self.paint();
            return true;
        }

        // In the cockpit mode, navigation now drives a REAL focus cursor over the
        // baked frame: LEFT/UP and RIGHT/DOWN walk the top workspace tabs
        // (HOME/SHELL/AGENT), ENTER selects the focused tab, ESC clears the
        // selection. The baked gpui frame is a static surface (no wgpu in-PD to
        // re-flow it), so the consumption is an overlay the repaint path draws —
        // but it IS the same IRQ→drain→apply→repaint loop the image mode uses,
        // now closed for the cockpit. (Re-flowing the workspace pane on select is
        // the next rung; it needs the off-VM live re-render.)
        if self.mode == Mode::Cockpit {
            let n = cockpit_frame::TABS.len();
            let before_focus = self.cockpit_focus;
            let before_selected = self.cockpit_selected;
            match nav {
                // RIGHT/DOWN walk the tabs forward; LEFT/UP walk backward.
                Nav::Down => {
                    self.cockpit_focus = (self.cockpit_focus + 1) % n;
                }
                Nav::Up => {
                    self.cockpit_focus = (self.cockpit_focus + n - 1) % n;
                }
                Nav::Enter => {
                    self.cockpit_selected = Some(self.cockpit_focus);
                }
                Nav::Back => {
                    self.cockpit_selected = None;
                }
                Nav::None | Nav::Toggle => {}
            }
            let changed =
                self.cockpit_focus != before_focus || self.cockpit_selected != before_selected;
            if changed {
                match self.cockpit_selected {
                    Some(s) => debug_println!(
                        "[deos-image]   -> cockpit tab focus {} (selected {})",
                        cockpit_frame::TABS[self.cockpit_focus],
                        cockpit_frame::TABS[s]
                    ),
                    None => debug_println!(
                        "[deos-image]   -> cockpit tab focus {}",
                        cockpit_frame::TABS[self.cockpit_focus]
                    ),
                }
                self.paint();
            }
            return changed;
        }

        let n = self.state.n_cells();
        let before_focus = self.state.focus;
        let before_drill = self.state.drill;

        match (self.state.drill, nav) {
            // ── browsing the rail ──────────────────────────────────────────
            (None, Nav::Down) => {
                self.state.focus = (self.state.focus + 1) % n;
            }
            (None, Nav::Up) => {
                self.state.focus = (self.state.focus + n - 1) % n;
            }
            (None, Nav::Enter) => {
                // drill INTO the focused cell, starting at the first substance.
                self.state.drill = Some(0);
            }
            (None, Nav::Back) => {
                // already at the top — no-op (stay in the image).
            }
            // ── drilled into a substance ───────────────────────────────────
            (Some(i), Nav::Enter) => {
                // page to the next substance; wrap back to the overview after
                // the last one (so ENTER repeatedly tours the whole cell then
                // returns to the rail — one-key delight).
                if i + 1 < N_SUBSTANCES {
                    self.state.drill = Some(i + 1);
                } else {
                    self.state.drill = None;
                }
            }
            (Some(i), Nav::Down) => {
                // a convenience: DOWN also pages substances forward.
                self.state.drill = Some((i + 1) % N_SUBSTANCES);
            }
            (Some(i), Nav::Up) => {
                self.state.drill = Some((i + N_SUBSTANCES - 1) % N_SUBSTANCES);
            }
            (Some(_), Nav::Back) => {
                // back OUT to the image (the rail).
                self.state.drill = None;
            }
            // `None` (no navigable key) and `Toggle` (handled by the early
            // return above) are no-ops in the rail/drill state machine.
            (_, Nav::None) | (_, Nav::Toggle) => {}
        }

        let changed = self.state.focus != before_focus || self.state.drill != before_drill;
        if changed {
            match self.state.drill {
                None => debug_println!(
                    "[deos-image]   -> cell {}/{} ({})",
                    self.state.focus + 1,
                    n,
                    image_data::IMAGE[self.state.focus].key
                ),
                Some(i) => debug_println!(
                    "[deos-image]   -> {} :: substance {}/{}",
                    image_data::IMAGE[self.state.focus].key,
                    i + 1,
                    N_SUBSTANCES
                ),
            }
            self.paint();
        }
        changed
    }
}

impl Handler for Viewer {
    type Error = Infallible;

    /// A notification. Two sources, distinguished by channel:
    ///   * `KBD` (id 0, the keyboard IRQ): drain events, navigate + repaint, then
    ///     re-arm the IRQ so the next keypress notifies us again.
    ///   * `REPAINT` (id 1, the executor PD's "commit ready" signal): a genuine
    ///     verified turn landed — read its receipt from the shared `commit_out`
    ///     region and repaint the framebuffer with the live-turn banner. This is
    ///     LIVE-REPAINT-ON-TURN on real seL4: a real `dregg_exec_full_forest_auth`
    ///     turn in its own PD drives a frame change in this PD, over a real
    ///     cross-PD notification channel.
    fn notified(&mut self, channels: ChannelSet) -> Result<(), Self::Error> {
        for ch in channels.iter() {
            if ch == KBD {
                if let Some(dev) = self.kbd.as_mut() {
                    let nav = keyboard::drain(dev);
                    let _ = self.apply(nav);
                }
                let _ = KBD.irq_ack();
            } else if ch == REPAINT {
                self.turns += 1;
                let lt = parse_receipt(self.turns);
                if lt.committed {
                    debug_println!(
                        "[deos-image]   <== LIVE TURN #{}: the executor PD committed a VERIFIED turn (status:{} ok:{}, nonce->{}, receipt {}B) — repainting on glass ( ◕‿◕ )",
                        lt.seq,
                        lt.status,
                        lt.ok,
                        lt.nonce,
                        lt.bytes
                    );
                } else {
                    debug_println!(
                        "[deos-image]   <== executor signalled, but the turn did NOT commit (status:{} ok:{}) — fail-closed, banner shows REJECTED",
                        lt.status,
                        lt.ok
                    );
                }
                self.state.live_turn = Some(lt);
                self.paint();
            } else {
                // The executor also signals a one-way verifier edge (id 3 ⇄ our
                // id 2 in deos-live.system); it carries no repaint payload here.
                debug_println!(
                    "[deos-image]   notified on channel {} (ignored)",
                    ch.index()
                );
            }
        }
        Ok(())
    }
}

#[protection_domain(heap_size = 0x40000)]
fn init() -> Viewer {
    debug_println!("");
    debug_println!("    +-----------------------------------------------+");
    debug_println!("    |   deos . robigalia v0  --  THE LIVE IMAGE     |");
    debug_println!("    |   deos-image PD : a live object browser of    |");
    debug_println!("    |   REAL deos cells (ramfb + virtio-keyboard)   |");
    debug_println!("    +-----------------------------------------------+");
    debug_println!(
        "[deos-image] booted -- {} REAL cells in the image (sum of balances = {} computrons)",
        image_data::N_CELLS,
        image_data::BALANCE_SUM
    );
    debug_println!("[deos-image] SOLE holder of the fw_cfg display cap + the virtio-keyboard cap.");

    let mut viewer = Viewer {
        mode: Mode::Image,
        state: ViewState::new(),
        kbd: None,
        cockpit_focus: 0,
        cockpit_selected: None,
        turns: 0,
    };

    // (A) DRAW the first cell's overview FIRST, so the bytes are present the
    // instant ramfb starts scanning out.
    viewer.paint();
    debug_println!(
        "[deos-image]   painted cell 1/{} ({}x{} XRGB8888)",
        image_data::N_CELLS,
        fb::WIDTH,
        fb::HEIGHT
    );

    // (B) configure ramfb so QEMU scans out this PD's framebuffer.
    if !fb::configure_ramfb() {
        debug_println!(
            "[deos-image]   (boot with `make run-image`; the window needs -device ramfb)"
        );
        return viewer;
    }

    // (C) bring up the keyboard. Real navigation is the headline; if the slot is
    // empty the viewer still shows cell 1 and names virtio-input as the rung.
    viewer.kbd = keyboard::init();
    if viewer.kbd.is_some() {
        let _ = KBD.irq_ack();
        debug_println!(
            "[deos-image]   INTERACTIVE: UP/DOWN walk the cells, ENTER drills in, ESC backs out."
        );
        debug_println!(
            "[deos-image]   TAB switches to the starbridge-v2 COCKPIT (real gpui render of a cockpit-shaped Scene, on glass)."
        );
    } else {
        debug_println!("[deos-image]   NON-INTERACTIVE this boot (no keyboard device).");
        debug_println!(
            "[deos-image]   next rung: wire -device virtio-keyboard-device on mmio slot 30."
        );
    }

    debug_println!("[deos-image]   the image is on glass, and it is alive to walk. ( o_o )");
    viewer
}
