(* ===========================================================================
   C16 — DEMONSTRATION 2: the branch-only machine step (N=2 reads c,b, +24w result
   slot) whole-program wrapper, generated by the SAME panWrapperLib.mk_mainRefine
   from ⟨reads=[c,b], bufOff=32w, koff=24w, spec=n2w(mstep c b)⟩ — reproduces C14's
   stepMainBody_refines with ZERO template edit (only the parameters differ).
   =========================================================================== *)
open HolKernel boolLib bossLib Parse;
open arithmeticTheory listTheory rich_listTheory wordsTheory wordsLib finite_mapTheory;
open panLangTheory panSemTheory panPropsTheory pairTheory;
open c14GenericTheory stepCoreTheory stepWrapperTheory stepLinkBInstTheory;
open panWrapperLib;

val _ = new_theory "stepGen";

val R = mk_wrapper
  { prefix       = "step",
    ffiName      = "stepFFI",        ffiDef        = stepFFI_def,
    ffiArgs      = "c b",
    ctrlName     = "stepCtrlStaged", ctrlStagedDef = stepCtrlStaged_def,
    relName      = "stepRel",        relDef        = stepRel_def,
    reads        = [("c","c"),("b","b")],
    bufOff       = "32w",            koff          = "24w",
    boundsStr    = "c <= 255 /\\ b < 256",
    specWord     = "n2w (mstep c b)",
    coreName     = "stepCore",       coreDef       = stepCore_def,
    coreFramed   = evaluate_stepCore_framed,
    coreNoFFI    = stepCore_noFFI,
    mainBodyName = "stepMainBody",   mainBodyDef   = stepMainBody_def,
    progName     = "stepGateProg",   progDef       = stepGateProg_def,
    linkB        = stepGateProg_linkB };

val _ = print "\n@@@ step mainRefine:\n";
val _ = print (thm_to_string (#mainRefine R));
val _ = print "\n@@@ step MACHINE CODE:\n";
val _ = print (thm_to_string (#machineCode R));
val _ = print ("\n@@@ stepGen axioms = " ^ Int.toString (length (axioms "stepGen")) ^ "\n");
val _ = print "\n@@@ stepGen DONE\n";

val _ = export_theory ();
